# DESIGNATION OF CLASS A, B, C, D, AND E AIRSPACE AREAS; AIR TRAFFIC SERVICE ROUTES; AND REPORTING POINTS
:toc:

## § 71.1 - Applicability.

A listing for Class A, B, C, D, and E airspace areas; air traffic service routes; and reporting points can be found in FAA Order 7400.11A, Airspace Designations and Reporting Points, dated August 3, 2016. This incorporation by reference was approved by the Director of the Federal Register in accordance with 5 U.S.C. 552 (a) and 1 CFR part 51. The approval to incorporate by reference FAA Order 7400.11A is effective September 15, 2016, through September 15, 2017. During the incorporation by reference period, proposed changes to the listings of Class A, B, C, D, and E airspace areas; air traffic service routes; and reporting points will be published in full text as proposed rule documents in the *Federal Register.* Amendments to the listings of Class A, B, C, D, and E airspace areas; air traffic service routes; and reporting points will be published in full text as final rules in the *Federal Register.* Periodically, the final rule amendments will be integrated into a revised edition of the Order and submitted to the Director of the Federal Register for approval for incorporation by reference in this section. Copies of FAA Order 7400.11A may be obtained from Airspace Policy Group, Federal Aviation Administration, 800 Independence Avenue SW., Washington, DC 20591, (202) 267-8783. An electronic version of the Order is available on the FAA Web site at *http://www.faa.gov/air_traffic/publications.* Copies of FAA Order 7400.11A may be inspected in Docket No. FAA-2016-XXXX; Amendment No. 71-48 on *http://www.regulations.gov.* A copy of FAA Order 7400.11A may be inspected at the National Archives and Records Administration (NARA). For information on the availability of this material at NARA, call (202) 741-6030, or go to: *http://www.archives.gov/federal-register/cfr/ibr-locations.html.*
            

## § 71.3 - Reserved


Reserved

## § 71.5 - Reporting points.

The reporting points listed in subpart H of FAA Order 7400.11A (incorporated by reference, see § 71.1) consist of geographic locations at which the position of an aircraft must be reported in accordance with part 91 of this chapter.

## § 71.7 - Bearings, radials, and mileages.

All bearings and radials in this part are true and are applied from point of origin and all mileages in this part are stated as nautical miles.

## § 71.9 - Overlapping airspace designations.

[loweralpha]
. When overlapping airspace designations apply to the same airspace, the operating rules associated with the more restrictive airspace designation apply.
. For the purpose of this section—
[arabic]
.. Class A airspace is more restrictive than Class B, Class C, Class D, Class E, or Class G airspace;
.. Class B airspace is more restrictive than Class C, Class D, Class E, or Class G airspace;
.. Class C airspace is more restrictive than Class D, Class E, or Class G airspace;
.. Class D airspace is more restrictive than Class E or Class G airspace; and
.. Class E is more restrictive than Class G airspace.

## § 71.11 - Air Traffic Service (ATS) routes.

Unless otherwise specified, the following apply:

[loweralpha]
. An Air Traffic Service (ATS) route is based on a centerline that extends from one navigation aid, fix, or intersection, to another navigation aid, fix, or intersection (or through several navigation aids, fixes, or intersections) specified for that route.
. An ATS route does not include the airspace of a prohibited area.

## § 71.13 - Classification of Air Traffic Service (ATS) routes.

Unless otherwise specified, ATS routes are classified as follows:

[loweralpha]
. In subpart A of this part:
[arabic]
.. Jet routes.
.. Area navigation (RNAV) routes.
. In subpart E of this part:
[arabic]
.. VOR Federal airways.
.. Colored Federal airways.
[lowerroman]
... Green Federal airways.
... Amber Federal airways.
... Red Federal airways.
... Blue Federal airways.
.. Area navigation (RNAV) routes.

## § 71.15 - Designation of jet routes and VOR Federal airways.

Unless otherwise specified, the place names appearing in the descriptions of airspace areas designated as jet routes in subpart A of FAA Order 7400.11A, and as VOR Federal airways in subpart E of FAA Order 7400.11A, are the names of VOR or VORTAC navigation aids. FAA Order 7400.11A is incorporated by reference in § 71.1.

