# Second-Class Airman Medical Certificate
:toc:

## § 67.201 - Eligibility.

To be eligible for a second-class airman medical certificate, and to remain eligible for a second-class airman medical certificate, a person must meet the requirements of this subpart.

## § 67.203 - Eye.

Eye standards for a second-class airman medical certificate are:

[loweralpha]
. Distant visual acuity of 20/20 or better in each eye separately, with or without corrective lenses. If corrective lenses (spectacles or contact lenses) are necessary for 20/20 vision, the person may be eligible only on the condition that corrective lenses are worn while exercising the privileges of an airman certificate.
. Near vision of 20/40 or better, Snellen equivalent, at 16 inches in each eye separately, with or without corrective lenses. If age 50 or older, near vision of 20/40 or better, Snellen equivalent, at both 16 inches and 32 inches in each eye separately, with or without corrective lenses.
. Ability to perceive those colors necessary for the safe performance of airman duties.
. Normal fields of vision.
. No acute or chronic pathological condition of either eye or adnexa that interferes with the proper function of an eye, that may reasonably be expected to progress to that degree, or that may reasonably be expected to be aggravated by flying.
. Bifoveal fixation and vergence-phoria relationship sufficient to prevent a break in fusion under conditions that may reasonably be expected to occur in performing airman duties. Tests for the factors named in this paragraph are not required except for persons found to have more than 1 prism diopter of hyperphoria, 6 prism diopters of esophoria, or 6 prism diopters of exophoria. If any of these values are exceeded, the Federal Air Surgeon may require the person to be examined by a qualified eye specialist to determine if there is bifoveal fixation and an adequate vergence-phoria relationship. However, if otherwise eligible, the person is issued a medical certificate pending the results of the examination.

## § 67.205 - Ear, nose, throat, and equilibrium.

Ear, nose, throat, and equilibrium standards for a second-class airman medical certificate are:

[loweralpha]
. The person shall demonstrate acceptable hearing by at least one of the following tests:
[arabic]
.. Demonstrate an ability to hear an average conversational voice in a quiet room, using both ears, at a distance of 6 feet from the examiner, with the back turned to the examiner.
.. Demonstrate an acceptable understanding of speech as determined by audiometric speech discrimination testing to a score of at least 70 percent obtained in one ear or in a sound field environment.
.. Provide acceptable results of pure tone audiometric testing of unaided hearing acuity according to the following table of worst acceptable thresholds, using the calibration standards of the American National Standards Institute, 1969:
. No disease or condition of the middle or internal ear, nose, oral cavity, pharynx, or larynx that—
[arabic]
.. Interferes with, or is aggravated by, flying or may reasonably be expected to do so; or
.. Interferes with, or may reasonably be expected to interfere with, clear and effective speech communication.
. No disease or condition manifested by, or that may reasonably be expected to be manifested by, vertigo or a disturbance of equilibrium.

## § 67.207 - Mental.

Mental standards for a second-class airman medical certificate are:

[loweralpha]
. No established medical history or clinical diagnosis of any of the following:
              
[arabic]
.. A personality disorder that is severe enough to have repeatedly manifested itself by overt acts.
.. A psychosis. As used in this section, “psychosis” refers to a mental disorder in which:
[lowerroman]
... The individual has manifested delusions, hallucinations, grossly bizarre or disorganized behavior, or other commonly accepted symptoms of this condition; or
... The individual may reasonably be expected to manifest delusions, hallucinations, grossly bizarre or disorganized behavior, or other commonly accepted symptoms of this condition.
.. A bipolar disorder.
.. Substance dependence, except where there is established clinical evidence, satisfactory to the Federal Air Surgeon, of recovery, including sustained total abstinence from the substance(s) for not less than the preceding 2 years. As used in this section—
[lowerroman]
... “Substance” includes: Alcohol; other sedatives and hypnotics; anxiolytics; opioids; central nervous system stimulants such as cocaine, amphetamines, and similarly acting sympathomimetics; hallucinogens; phencyclidine or similarly acting arylcyclohexylamines; cannabis; inhalants; and other psychoactive drugs and chemicals; and
... “Substance dependence” means a condition in which a person is dependent on a substance, other than tobacco or ordinary xanthine-containing (e.g., caffeine) beverages, as evidenced by—
[upperalpha]
.... Increased tolerance;
.... Manifestation of withdrawal symptoms;
.... Impaired control of use; or
.... Continued use despite damage to physical health or impairment of social, personal, or occupational functioning.
. No substance abuse within the preceding 2 years defined as:
[arabic]
.. Use of a substance in a situation in which that use was physically hazardous, if there has been at any other time an instance of the use of a substance also in a situation in which that use was physically hazardous;
.. A verified positive drug test result, an alcohol test result of 0.04 or greater alcohol concentration, or a refusal to submit to a drug or alcohol test required by the U.S. Department of Transportation or an agency of the U.S. Department of Transportation; or
.. Misuse of a substance that the Federal Air Surgeon, based on case history and appropriate, qualified medical judgment relating to the substance involved, finds—
[lowerroman]
... Makes the person unable to safely perform the duties or exercise the privileges of the airman certificate applied for or held; or
... May reasonably be expected, for the maximum duration of the airman medical certificate applied for or held, to make the person unable to perform those duties or exercise those privileges.
. No other personality disorder, neurosis, or other mental condition that the Federal Air Surgeon, based on the case history and appropriate, qualified medical judgment relating to the condition involved, finds—
[arabic]
.. Makes the person unable to safely perform the duties or exercise the privileges of the airman certificate applied for or held; or
.. May reasonably be expected, for the maximum duration of the airman medical certificate applied for or held, to make the person unable to perform those duties or exercise those privileges.

## § 67.209 - Neurologic.

Neurologic standards for a second-class airman medical certificate are:

[loweralpha]
. No established medical history or clinical diagnosis of any of the following:
[arabic]
.. Epilepsy;
.. A disturbance of consciousness without satisfactory medical explanation of the cause; or
.. A transient loss of control of nervous system function(s) without satisfactory medical explanation of the cause;
. No other seizure disorder, disturbance of consciousness, or neurologic condition that the Federal Air Surgeon, based on the case history and appropriate, qualified medical judgment relating to the condition involved, finds—
[arabic]
.. Makes the person unable to safely perform the duties or exercise the privileges of the airman certificate applied for or held; or
.. May reasonably be expected, for the maximum duration of the airman medical certificate applied for or held, to make the person unable to perform those duties or exercise those privileges.

## § 67.211 - Cardiovascular.

Cardiovascular standards for a second-class medical certificate are no established medical history or clinical diagnosis of any of the following:

[loweralpha]
. Myocardial infarction;
. Angina pectoris;
. Coronary heart disease that has required treatment or, if untreated, that has been symptomatic or clinically significant;
. Cardiac valve replacement;
. Permanent cardiac pacemaker implantation; or
. Heart replacement.

## § 67.213 - General medical condition.

The general medical standards for a second-class airman medical certificate are:

[loweralpha]
. No established medical history or clinical diagnosis of diabetes mellitus that requires insulin or any other hypoglycemic drug for control.
. No other organic, functional, or structural disease, defect, or limitation that the Federal Air Surgeon, based on the case history and appropriate, qualified medical judgment relating to the condition involved, finds—
[arabic]
.. Makes the person unable to safely perform the duties or exercise the privileges of the airman certificate applied for or held; or
.. May reasonably be expected, for the maximum duration of the airman medical certificate applied for or held, to make the person unable to perform those duties or exercise those privileges.
. No medication or other treatment that the Federal Air Surgeon, based on the case history and appropriate, qualified medical judgment relating to the medication or other treatment involved, finds—
[arabic]
.. Makes the person unable to safely perform the duties or exercise the privileges of the airman certificate applied for or held; or
.. May reasonably be expected, for the maximum duration of the airman medical certificate applied for or held, to make the person unable to perform those duties or exercise those privileges.

## § 67.215 - Discretionary issuance.

A person who does not meet the provisions of §§ 67.203 through 67.213 may apply for the discretionary issuance of a certificate under § 67.401.

