# Air Traffic Control Tower Operators
:toc:

## § 65.31 - Required credentials, certificates, and ratings or qualifications.

No person may act as an air traffic control tower operator at an air traffic control tower in connection with civil aircraft unless he or she—

[loweralpha]
. Holds an FAA Credential with a tower rating or an air traffic control tower operator certificate issued under this subpart;
. Holds a facility rating for that control tower issued under this subpart, or has qualified for the operating position at which he or she acts and is under the supervision of the holder of a facility rating for that control tower; and
. Except for a person employed by the FAA or employed by, or on active duty with, the Department of the Air Force, Army, or Navy or the Coast Guard, holds at least a second-class medical certificate issued under part 67 of this chapter.

## § 65.33 - Eligibility requirements: General.

To be eligible for an air traffic control tower operator certificate a person must—

[loweralpha]
. Be at least 18 years of age;
. Be of good moral character;
. Be able to read, write, and understand the English language and speak it without accent or impediment of speech that would interfere with two-way radio conversation;
. Except for a person employed by the FAA or employed by, or on active duty with, the Department of the Air Force, Army, or Navy or the Coast Guard, hold at least a second-class medical certificate issued under part 67 of this chapter within the 12 months before the date application is made; and
. Comply with § 65.35.

## § 65.35 - Knowledge requirements.

Each applicant for an air traffic control tower operator certificate must pass a written test on—

[loweralpha]
. The flight rules in part 91 of this chapter:
. Airport traffic control procedures, and this subpart:
. En route traffic control procedures;
. Communications operating procedures;
. Flight assistance service;
. Air navigation, and aids to air navigation; and
. Aviation weather.

## § 65.37 - Skill requirements: Operating positions.

No person may act as an air traffic control tower operator at any operating position unless he has passed a practical test on—

[loweralpha]
. Control tower equipment and its use;
. Weather reporting procedures and use of reports;
. Notices to Airmen, and use of the Airman's Information Manual;
. Use of operational forms;
. Performance of noncontrol operational duties; and
. Each of the following procedures that is applicable to that operating position and is required by the person performing the examination:
[arabic]
.. The airport, including rules, equipment, runways, taxiways, and obstructions.
.. The terrain features, visual checkpoints, and obstructions within the lateral boundaries of the surface areas of Class B, Class C, Class D, or Class E airspace designated for the airport.
.. Traffic patterns and associated procedures for use of preferential runways and noise abatement.
.. Operational agreements.
              
.. The center, alternate airports, and those airways, routes, reporting points, and air navigation aids used for terminal air traffic control.
.. Search and rescue procedures.
.. Terminal air traffic control procedures and phraseology.
.. Holding procedures, prescribed instrument approach, and departure procedures.
.. Radar alignment and technical operation.
.. The application of the prescribed radar and nonradar separation standard, as appropriate.

## § 65.39 - Practical experience requirements: Facility rating.

Each applicant for a facility rating at any air traffic control tower must have satisfactorily served—

[loweralpha]
. As an air traffic control tower operator at that control tower without a facility rating for at least 6 months; or
. As an air traffic control tower operator with a facility rating at a different control tower for at least 6 months before the date he applies for the rating.
              

## § 65.41 - Skill requirements: Facility ratings.

Each applicant for a facility rating at an air traffic control tower must have passed a practical test on each item listed in § 65.37 of this part that is applicable to each operating position at the control tower at which the rating is sought.

## § 65.43 - Reserved


Reserved

## § 65.45 - Performance of duties.

[loweralpha]
. An air traffic control tower operator shall perform his duties in accordance with the limitations on his certificate and the procedures and practices prescribed in air traffic control manuals of the FAA, to provide for the safe, orderly, and expeditious flow of air traffic.
. An operator with a facility rating may control traffic at any operating position at the control tower at which he holds a facility rating. However, he may not issue an air traffic clearance for IFR flight without authorization from the appropriate facility exercising IFR control at that location.
. An operator who does not hold a facility rating for a particular control tower may act at each operating position for which he has qualified, under the supervision of an operator holding a facility rating for that control tower.

## §§ 65.46-65.46b - Reserved


Reserved

## § 65.47 - Maximum hours.

Except in an emergency, a certificated air traffic control tower operator must be relieved of all duties for at least 24 consecutive hours at least once during each 7 consecutive days. Such an operator may not serve or be required to serve—

[loweralpha]
. For more than 10 consecutive hours; or
. For more than 10 hours during a period of 24 consecutive hours, unless he has had a rest period of at least 8 hours at or before the end of the 10 hours of duty.

## § 65.49 - General operating rules.

[loweralpha]
. Except for a person employed by the FAA or employed by, or on active duty with, the Department of the Air Force, Army, or Navy, or the Coast Guard, no person may act as an air traffic control tower operator under a certificate issued to him or her under this part unless he or she has in his or her personal possession an appropriate current medical certificate issued under part 67 of this chapter.
. Each person holding an air traffic control tower operator certificate shall keep it readily available when performing duties in an air traffic control tower, and shall present that certificate or his medical certificate or both for inspection upon the request of the Administrator or an authorized representative of the National Transportation Safety Board, or of any Federal, State, or local law enforcement officer.
. A certificated air traffic control tower operator who does not hold a facility rating for a particular control tower may not act at any operating position at the control tower concerned unless there is maintained at that control tower, readily available to persons named in paragraph (b) of this section, a current record of the operating positions at which he has qualified.
. An air traffic control tower operator may not perform duties under his certificate during any period of known physical deficiency that would make him unable to meet the physical requirements for his current medical certificate. However, if the deficiency is temporary, he may perform duties that are not affected by it whenever another certificated and qualified operator is present and on duty.
. A certificated air traffic control tower operator may not control air traffic with equipment that the Administrator has found to be inadequate.
. The holder of an air traffic control tower operator certificate, or an applicant for one, shall, upon the reasonable request of the Administrator, cooperate fully in any test that is made of him.

## § 65.50 - Currency requirements.

The holder of an air traffic control tower operator certificate may not perform any duties under that certificate unless—

[loweralpha]
. He has served for at least three of the preceding 6 months as an air traffic control tower operator at the control tower to which his facility rating applies, or at the operating positions for which he has qualified; or
. He has shown that he meets the requirements for his certificate and facility rating at the control tower concerned, or for operating at positions for which he has previously qualified.

