# Certification, Operations Specifications, and Certain Other Requirements for Operations Conducted Under Part 121 or Part 135 of This Chapter
:toc:

## § 119.31 - Applicability.

This subpart sets out certification requirements and prescribes the content of operations specifications and certain other requirements for operations conducted under part 121 or part 135 of this chapter.

## § 119.33 - General requirements.

[loweralpha]
. A person may not operate as a direct air carrier unless that person—
[arabic]
.. Is a citizen of the United States;
.. Obtains an Air Carrier Certificate; and
.. Obtains operations specifications that prescribe the authorizations, limitations, and procedures under which each kind of operation must be conducted.
. A person other than a direct air carrier may not conduct any commercial passenger or cargo aircraft operation for compensation or hire under part 121 or part 135 of this chapter unless that person—
[arabic]
.. Is a citizen of the United States;
.. Obtains an Operating Certificate; and
              
.. Obtains operations specifications that prescribe the authorizations, limitations, and procedures under which each kind of operation must be conducted.
. Each applicant for a certificate under this part and each applicant for operations specifications authorizing a new kind of operation that is subject to § 121.163 or § 135.145 of this chapter shall conduct proving tests as authorized by the Administrator during the application process for authority to conduct operations under part 121 or part 135 of this chapter. All proving tests must be conducted in a manner acceptable to the Administrator. All proving tests must be conducted under the appropriate operating and maintenance requirements of part 121 or 135 of this chapter that would apply if the applicant were fully certificated. The Administrator will issue a letter of authorization to each person stating the various authorities under which the proving tests shall be conducted.

## § 119.35 - Certificate application requirements for all operators.

[loweralpha]
. A person applying to the Administrator for an Air Carrier Certificate or Operating Certificate under this part (applicant) must submit an application—
[arabic]
.. In a form and manner prescribed by the Administrator; and
.. Containing any information the Administrator requires the applicant to submit.
. Each applicant must submit the application to the Administrator at least 90 days before the date of intended operation.

## § 119.36 - Additional certificate application requirements for commercial operators.

[loweralpha]
. Each applicant for the original issue of an operating certificate for the purpose of conducting intrastate common carriage operations under part 121 or part 135 of this chapter must submit an application in a form and manner prescribed by the Administrator to the Flight Standards District Office in whose area the applicant proposes to establish or has established his or her principal base of operations.
. Each application submitted under paragraph (a) of this section must contain a signed statement showing the following:
[arabic]
.. For corporate applicants:
[lowerroman]
... The name and address of each stockholder who owns 5 percent or more of the total voting stock of the corporation, and if that stockholder is not the sole beneficial owner of the stock, the name and address of each beneficial owner. An individual is considered to own the stock owned, directly or indirectly, by or for his or her spouse, children, grandchildren, or parents.
... The name and address of each director and each officer and each person employed or who will be employed in a management position described in §§ 119.65 and 119.69, as applicable.
... The name and address of each person directly or indirectly controlling or controlled by the applicant and each person under direct or indirect control with the applicant.
.. For non-corporate applicants:
[lowerroman]
... The name and address of each person having a financial interest therein and the nature and extent of that interest.
... The name and address of each person employed or who will be employed in a management position described in §§ 119.65 and 119.69, as applicable.
. In addition, each applicant for the original issue of an operating certificate under paragraph (a) of this section must submit with the application a signed statement showing—
[arabic]
.. The nature and scope of its intended operation, including the name and address of each person, if any, with whom the applicant has a contract to provide services as a commercial operator and the scope, nature, date, and duration of each of those contracts; and
.. For applicants intending to conduct operations under part 121 of this chapter, the financial information listed in paragraph (e) of this section.
. Each applicant for, or holder of, a certificate issued under paragraph (a) of this section, shall notify the Administrator within 10 days after—
[arabic]
.. A change in any of the persons, or the names and addresses of any of the persons, submitted to the Administrator under paragraph (b)(1) or (b)(2) of this section; or
.. For applicants intending to conduct operations under part 121 of this chapter, a change in the financial information submitted to the Administrator under paragraph (e) of this section that occurs while the application for the issue is pending before the FAA and that would make the applicant's financial situation substantially less favorable than originally reported.
. Each applicant for the original issue of an operating certificate under paragraph (a) of this section who intends to conduct operations under part 121 of this chapter must submit the following financial information:
[arabic]
.. A balance sheet that shows assets, liabilities, and net worth, as of a date not more than 60 days before the date of application.
.. An itemization of liabilities more than 60 days past due on the balance sheet date, if any, showing each creditor's name and address, a description of the liability, and the amount and due date of the liability.
.. An itemization of claims in litigation, if any, against the applicant as of the date of application showing each claimant's name and address and a description and the amount of the claim.
.. A detailed projection of the proposed operation covering 6 complete months after the month in which the certificate is expected to be issued including—
[lowerroman]
... Estimated amount and source of both operating and nonoperating revenue, including identification of its existing and anticipated income producing contracts and estimated revenue per mile or hour of operation by aircraft type;
... Estimated amount of operating and nonoperating expenses by expense objective classification; and
... Estimated net profit or loss for the period.
.. An estimate of the cash that will be needed for the proposed operations during the first 6 months after the month in which the certificate is expected to be issued, including—
[lowerroman]
... Acquisition of property and equipment (explain);
... Retirement of debt (explain);
... Additional working capital (explain);
... Operating losses other than depreciation and amortization (explain); and
... Other (explain).
.. An estimate of the cash that will be available during the first 6 months after the month in which the certificate is expected to be issued, from—
[lowerroman]
... Sale of property or flight equipment (explain);
... New debt (explain);
... New equity (explain);
... Working capital reduction (explain);
... Operations (profits) (explain);
... Depreciation and amortization (explain); and
... Other (explain).
.. A schedule of insurance coverage in effect on the balance sheet date showing insurance companies; policy numbers; types, amounts, and period of coverage; and special conditions, exclusions, and limitations.
.. Any other financial information that the Administrator requires to enable him or her to determine that the applicant has sufficient financial resources to conduct his or her operations with the degree of safety required in the public interest.
. Each financial statement containing financial information required by paragraph (e) of this section must be based on accounts prepared and maintained on an accrual basis in accordance with generally accepted accounting principles applied on a consistent basis, and must contain the name and address of the applicant's public accounting firm, if any. Information submitted must be signed by an officer, owner, or partner of the applicant or certificate holder.

## § 119.37 - Contents of an Air Carrier Certificate or Operating Certificate.

The Air Carrier Certificate or Operating Certificate includes—

[loweralpha]
. The certificate holder's name;
              
. The location of the certificate holder's principal base of operations;
. The certificate number;
. The certificate's effective date; and
. The name or the designator of the certificate-holding district office.

## § 119.39 - Issuing or denying a certificate.

[loweralpha]
. An applicant may be issued an Air Carrier Certificate or Operating Certificate if, after investigation, the Administrator finds that the applicant—
[arabic]
.. Meets the applicable requirements of this part;
.. Holds the economic authority applicable to the kinds of operations to be conducted, issued by the Department of Transportation, if required; and
.. Is properly and adequately equipped in accordance with the requirements of this chapter and is able to conduct a safe operation under appropriate provisions of part 121 or part 135 of this chapter and operations specifications issued under this part.
. An application for a certificate may be denied if the Administrator finds that—
[arabic]
.. The applicant is not properly or adequately equipped or is not able to conduct safe operations under this subchapter;
.. The applicant previously held an Air Carrier Certificate or Operating Certificate which was revoked;
.. The applicant intends to or fills a key management position listed in § 119.65(a) or § 119.69(a), as applicable, with an individual who exercised control over or who held the same or a similar position with a certificate holder whose certificate was revoked, or is in the process of being revoked, and that individual materially contributed to the circumstances causing revocation or causing the revocation process;
.. An individual who will have control over or have a substantial ownership interest in the applicant had the same or similar control or interest in a certificate holder whose certificate was revoked, or is in the process of being revoked, and that individual materially contributed to the circumstances causing revocation or causing the revocation process; or
.. In the case of an applicant for an Operating Certificate for intrastate common carriage, that for financial reasons the applicant is not able to conduct a safe operation.

## § 119.41 - Amending a certificate.

[loweralpha]
. The Administrator may amend any certificate issued under this part if—
[arabic]
.. The Administrator determines, under 49 U.S.C. 44709 and part 13 of this chapter, that safety in air commerce and the public interest requires the amendment; or
.. The certificate holder applies for the amendment and the certificate-holding district office determines that safety in air commerce and the public interest allows the amendment.
. When the Administrator proposes to issue an order amending, suspending, or revoking all or part of any certificate, the procedure in § 13.19 of this chapter applies.
. When the certificate holder applies for an amendment of its certificate, the following procedure applies:
[arabic]
.. The certificate holder must file an application to amend its certificate with the certificate-holding district office at least 15 days before the date proposed by the applicant for the amendment to become effective, unless the administrator approves filing within a shorter period; and
.. The application must be submitted to the certificate-holding district office in the form and manner prescribed by the Administrator.
. When a certificate holder seeks reconsideration of a decision from the certificate-holding district office concerning amendments of a certificate, the following procedure applies:
[arabic]
.. The petition for reconsideration must be made within 30 days after the certificate holder receives the notice of denial; and
.. The certificate holder must petition for reconsideration to the Director, Flight Standards Service.

## § 119.43 - Certificate holder's duty to maintain operations specifications.

[loweralpha]
. Each certificate holder shall maintain a complete and separate set of its operations specifications at its principal base of operations.
. Each certificate holder shall insert pertinent excerpts of its operations specifications, or references thereto, in its manual and shall—
[arabic]
.. Clearly identify each such excerpt as a part of its operations specifications; and
.. State that compliance with each operations specifications requirement is mandatory.
. Each certificate holder shall keep each of its employees and other persons used in its operations informed of the provisions of its operations specifications that apply to that employee's or person's duties and responsibilities.

## § 119.45 - Reserved


Reserved

## § 119.47 - Maintaining a principal base of operations, main operations base, and main maintenance base; change of address.

[loweralpha]
. Each certificate holder must maintain a principal base of operations. Each certificate holder may also establish a main operations base and a main maintenance base which may be located at either the same location as the principal base of operations or at separate locations.
. At least 30 days before it proposes to establish or change the location of its principal base of operations, its main operations base, or its main maintenance base, a certificate holder must provide written notification to its certificate-holding district office.

## § 119.49 - Contents of operations specifications.

[loweralpha]
. Each certificate holder conducting domestic, flag, or commuter operations must obtain operations specifications containing all of the following:
[arabic]
.. The specific location of the certificate holder's principal base of operations and, if different, the address that shall serve as the primary point of contact for correspondence between the FAA and the certificate holder and the name and mailing address of the certificate holder's agent for service.
.. Other business names under which the certificate holder may operate.
.. Reference to the economic authority issued by the Department of Transportation, if required.
.. Type of aircraft, registration markings, and serial numbers of each aircraft authorized for use, each regular and alternate airport to be used in scheduled operations, and, except for commuter operations, each provisional and refueling airport.
[lowerroman]
... Subject to the approval of the Administrator with regard to form and content, the certificate holder may incorporate by reference the items listed in paragraph (a)(4) of this section into the certificate holder's operations specifications by maintaining a current listing of those items and by referring to the specific list in the applicable paragraph of the operations specifications.
... The certificate holder may not conduct any operation using any aircraft or airport not listed.
.. Kinds of operations authorized.
.. Authorization and limitations for routes and areas of operations.
.. Airport limitations.
.. Time limitations, or standards for determining time limitations, for overhauling, inspecting, and checking airframes, engines, propellers, rotors, appliances, and emergency equipment.
.. Authorization for the method of controlling weight and balance of aircraft.
.. Interline equipment interchange requirements, if relevant.
.. Aircraft wet lease information required by § 119.53(c).
.. Any authorized deviation and exemption granted from any requirement of this chapter.
.. An authorization permitting, or a prohibition against, accepting, handling, and transporting materials regulated as hazardous materials in transport under 49 CFR parts 171 through 180.
.. Any other item the Administrator determines is necessary.
. Each certificate holder conducting supplemental operations must obtain operations specifications containing all of the following:
[arabic]
.. The specific location of the certificate holder's principal base of operations, and, if different, the address that shall serve as the primary point of contact for correspondence between the FAA and the certificate holder and the name and mailing address of the certificate holder's agent for service.
.. Other business names under which the certificate holder may operate.
.. Reference to the economic authority issued by the Department of Transportation, if required.
.. Type of aircraft, registration markings, and serial number of each aircraft authorized for use.
[lowerroman]
... Subject to the approval of the Administrator with regard to form and content, the certificate holder may incorporate by reference the items listed in paragraph (b)(4) of this section into the certificate holder's operations specifications by maintaining a current listing of those items and by referring to the specific list in the applicable paragraph of the operations specifications.
... The certificate holder may not conduct any operation using any aircraft not listed.
.. Kinds of operations authorized.
.. Authorization and limitations for routes and areas of operations.
.. Special airport authorizations and limitations.
.. Time limitations, or standards for determining time limitations, for overhauling, inspecting, and checking airframes, engines, propellers, appliances, and emergency equipment.
.. Authorization for the method of controlling weight and balance of aircraft.
.. Aircraft wet lease information required by § 119.53(c).
.. Any authorization or requirement to conduct supplemental operations as provided by § 119.21(a)(3).
.. Any authorized deviation or exemption from any requirement of this chapter.
.. An authorization permitting, or a prohibition against, accepting, handling, and transporting materials regulated as hazardous materials in transport under 49 CFR parts 171 through 180.
.. Any other item the Administrator determines is necessary.
. Each certificate holder conducting on-demand operations must obtain operations specifications containing all of the following:
[arabic]
.. The specific location of the certificate holder's principal base of operations, and if different, the address that shall serve as the primary point of contact for correspondence between the FAA and the name and mailing address of the certificate holder's agent for service.
.. Other business names under which the certificate holder may operate.
.. Reference to the economic authority issued by the Department of Transportation, if required.
.. Kind and area of operations authorized.
.. Category and class of aircraft that may be used in those operations.
.. Type of aircraft, registration markings, and serial number of each aircraft that is subject to an airworthiness maintenance program required by § 135.411(a)(2) of this chapter.
[lowerroman]
... Subject to the approval of the Administrator with regard to form and content, the certificate holder may incorporate by reference the items listed in paragraph (c)(6) of this section into the certificate holder's operations specifications by maintaining a current listing of those items and by referring to the specific list in the applicable paragraph of the operations specifications.
... The certificate holder may not conduct any operation using any aircraft not listed.
.. Registration markings of each aircraft that is to be inspected under an approved aircraft inspection program under § 135.419 of this chapter.
.. Time limitations or standards for determining time limitations, for overhauls, inspections, and checks for airframes, engines, propellers, rotors, appliances, and emergency equipment of aircraft that are subject to an airworthiness maintenance program required by § 135.411(a)(2) of this chapter.
.. Additional maintenance items required by the Administrator under § 135.421 of this chapter.
.. Aircraft wet lease information required by § 119.53(c).
.. Any authorized deviation or exemption from any requirement of this chapter.
              
.. An authorization permitting, or a prohibition against, accepting, handling, and transporting materials regulated as hazardous materials in transport under 49 CFR parts 171 through 180.
.. Any other item the Administrator determines is necessary.

## § 119.51 - Amending operations specifications.

[loweralpha]
. The Administrator may amend any operations specifications issued under this part if—
[arabic]
.. The Administrator determines that safety in air commerce and the public interest require the amendment; or
.. The certificate holder applies for the amendment, and the Administrator determines that safety in air commerce and the public interest allows the amendment.
. Except as provided in paragraph (e) of this section, when the Administrator initiates an amendment to a certificate holder's operations specifications, the following procedure applies:
[arabic]
.. The certificate-holding district office notifies the certificate holder in writing of the proposed amendment.
.. The certificate-holding district office sets a reasonable period (but not less than 7 days) within which the certificate holder may submit written information, views, and arguments on the amendment.
.. After considering all material presented, the certificate-holding district office notifies the certificate holder of—
[lowerroman]
... The adoption of the proposed amendment;
... The partial adoption of the proposed amendment; or
... The withdrawal of the proposed amendment.
.. If the certificate-holding district office issues an amendment to the operations specifications, it becomes effective not less than 30 days after the certificate holder receives notice of it unless—
[lowerroman]
... The certificate-holding district office finds under paragraph (e) of this section that there is an emergency requiring immediate action with respect to safety in air commerce; or
... The certificate holder petitions for reconsideration of the amendment under paragraph (d) of this section.
. When the certificate holder applies for an amendment to its operations specifications, the following procedure applies:
[arabic]
.. The certificate holder must file an application to amend its operations specifications—
[lowerroman]
... At least 90 days before the date proposed by the applicant for the amendment to become effective, unless a shorter time is approved, in cases of mergers; acquisitions of airline operational assets that require an additional showing of safety (e.g., proving tests); changes in the kind of operation as defined in § 110.2; resumption of operations following a suspension of operations as a result of bankruptcy actions; or the initial introduction of aircraft not before proven for use in air carrier or commercial operator operations.
... At least 15 days before the date proposed by the applicant for the amendment to become effective in all other cases.
.. The application must be submitted to the certificate-holding district office in a form and manner prescribed by the Administrator.
.. After considering all material presented, the certificate-holding district office notifies the certificate holder of—
[lowerroman]
... The adoption of the applied for amendment;
... The partial adoption of the applied for amendment; or
... The denial of the applied for amendment. The certificate holder may petition for reconsideration of a denial under paragraph (d) of this section.
.. If the certificate-holding district office approves the amendment, following coordination with the certificate holder regarding its implementation, the amendment is effective on the date the Administrator approves it.
. When a certificate holder seeks reconsideration of a decision from the certificate-holding district office concerning the amendment of operations specifications, the following procedure applies:
[arabic]
.. The certificate holder must petition for reconsideration of that decision within 30 days of the date that the certificate holder receives a notice of denial of the amendment to its operations specifications, or of the date it receives notice of an FAA-initiated amendment to its operations specifications, whichever circumstance applies.
.. The certificate holder must address its petition to the Director, Flight Standards Service.
.. A petition for reconsideration, if filed within the 30-day period, suspends the effectiveness of any amendment issued by the certificate-holding district office unless the certificate-holding district office has found, under paragraph (e) of this section, that an emergency exists requiring immediate action with respect to safety in air transportation or air commerce.
.. If a petition for reconsideration is not filed within 30 days, the procedures of paragraph (c) of this section apply.
. If the certificate-holding district office finds that an emergency exists requiring immediate action with respect to safety in air commerce or air transportation that makes the procedures set out in this section impracticable or contrary to the public interest:
[arabic]
.. The certificate-holding district office amends the operations specifications and makes the amendment effective on the day the certificate holder receives notice of it.
.. In the notice to the certificate holder, the certificate-holding district office articulates the reasons for its finding that an emergency exists requiring immediate action with respect to safety in air transportation or air commerce or that makes it impracticable or contrary to the public interest to stay the effectiveness of the amendment.

## § 119.53 - Wet leasing of aircraft and other arrangements for transportation by air.

[loweralpha]
. Unless otherwise authorized by the Administrator, prior to conducting operations involving a wet lease, each certificate holder under this part authorized to conduct common carriage operations under this subchapter shall provide the Administrator with a copy of the wet lease to be executed which would lease the aircraft to any other person engaged in common carriage operations under this subchapter, including foreign air carriers, or to any other foreign person engaged in common carriage wholly outside the United States.
. No certificate holder under this part may wet lease from a foreign air carrier or any other foreign person or any person not authorized to engage in common carriage.
. Upon receiving a copy of a wet lease, the Administrator determines which party to the agreement has operational control of the aircraft and issues amendments to the operations specifications of each party to the agreement, as needed. The lessor must provide the following information to be incorporated into the operations specifications of both parties, as needed.
[arabic]
.. The names of the parties to the agreement and the duration thereof.
.. The nationality and registration markings of each aircraft involved in the agreement.
.. The kind of operation (e.g., domestic, flag, supplemental, commuter, or on-demand).
.. The airports or areas of operation.
.. A statement specifying the party deemed to have operational control and the times, airports, or areas under which such operational control is exercised.
. In making the determination of paragraph (c) of this section, the Administrator will consider the following:
[arabic]
.. Crewmembers and training.
.. Airworthiness and performance of maintenance.
.. Dispatch.
.. Servicing the aircraft.
.. Scheduling.
.. Any other factor the Administrator considers relevant.
. Other arrangements for transportation by air: Except as provided in paragraph (f) of this section, a certificate holder under this part operating under part 121 or 135 of this chapter may not conduct any operation for another certificate holder under this part or a foreign air carrier under part 129 of this chapter or a foreign person engaged in common carriage wholly outside the United States unless it holds applicable Department of Transportation economic authority, if required, and is authorized under its operations specifications to conduct the same kinds of operations (as defined in § 110.2). The certificate holder conducting the substitute operation must conduct that operation in accordance with the same operations authority held by the certificate holder arranging for the substitute operation. These substitute operations must be conducted between airports for which the substitute certificate holder holds authority for scheduled operations or within areas of operations for which the substitute certificate holder has authority for supplemental or on-demand operations.
. A certificate holder under this part may, if authorized by the Department of Transportation under § 380.3 of this title and the Administrator in the case of interstate commuter, interstate domestic, and flag operations, or the Administrator in the case of scheduled intrastate common carriage operations, conduct one or more flights for passengers who are stranded because of the cancellation of their scheduled flights. These flights must be conducted under the rules of part 121 or part 135 of this chapter applicable to supplemental or on-demand operations.

## § 119.55 - Obtaining deviation authority to perform operations under a U.S. military contract.

[loweralpha]
. The Administrator may authorize a certificate holder that is authorized to conduct supplemental or on-demand operations to deviate from the applicable requirements of this part, part 117, part 121, or part 135 of this chapter in order to perform operations under a U.S. military contract.
. A certificate holder that has a contract with the U.S. Department of Defense's Air Mobility Command (AMC) must submit a request for deviation authority to AMC. AMC will review the requests, then forward the carriers' consolidated requests, along with AMC's recommendations, to the FAA for review and action.
. The Administrator may authorize a deviation to perform operations under a U.S. military contract under the following conditions—
[arabic]
.. The Department of Defense certifies to the Administrator that the operation is essential to the national defense;
.. The Department of Defense further certifies that the certificate holder cannot perform the operation without deviation authority;
.. The certificate holder will perform the operation under a contract or subcontract for the benefit of a U.S. armed service; and
.. The Administrator finds that the deviation is based on grounds other than economic advantage either to the certificate holder or to the United States.
. In the case where the Administrator authorizes a deviation under this section, the Administrator will issue an appropriate amendment to the certificate holder's operations specifications.
. The Administrator may, at any time, terminate any grant of deviation authority issued under this section.

## § 119.57 - Obtaining deviation authority to perform an emergency operation.

[loweralpha]
. In emergency conditions, the Administrator may authorize deviations if—
[arabic]
.. Those conditions necessitate the transportation of persons or supplies for the protection of life or property; and
.. The Administrator finds that a deviation is necessary for the expeditious conduct of the operations.
. When the Administrator authorizes deviations for operations under emergency conditions—
[arabic]
.. The Administrator will issue an appropriate amendment to the certificate holder's operations specifications; or
.. If the nature of the emergency does not permit timely amendment of the operations specifications—
              
[lowerroman]
... The Administrator may authorize the deviation orally; and
... The certificate holder shall provide documentation describing the nature of the emergency to the certificate-holding district office within 24 hours after completing the operation.

## § 119.59 - Conducting tests and inspections.

[loweralpha]
. At any time or place, the Administrator may conduct an inspection or test to determine whether a certificate holder under this part is complying with title 49 of the United States Code, applicable regulations, the certificate, or the certificate holder's operations specifications.
. The certificate holder must—
[arabic]
.. Make available to the Administrator at the certificate holder's principal base of operations—
[lowerroman]
... The certificate holder's Air Carrier Certificate or the certificate holder's Operating Certificate and the certificate holder's operations specifications; and
... A current listing that will include the location and persons responsible for each record, document, and report required to be kept by the certificate holder under title 49 of the United States Code applicable to the operation of the certificate holder.
.. Allow the Administrator to make any test or inspection to determine compliance respecting any matter stated in paragraph (a) of this section.
. Each employee of, or person used by, the certificate holder who is responsible for maintaining the certificate holder's records must make those records available to the Administrator.
. The Administrator may determine a certificate holder's continued eligibility to hold its certificate and/or operations specifications on any grounds listed in paragraph (a) of this section, or any other appropriate grounds.
. Failure by any certificate holder to make available to the Administrator upon request, the certificate, operations specifications, or any required record, document, or report is grounds for suspension of all or any part of the certificate holder's certificate and operations specifications.
. In the case of operators conducting intrastate common carriage operations, these inspections and tests include inspections and tests of financial books and records.

## § 119.61 - Duration and surrender of certificate and operations specifications.

[loweralpha]
. An Air Carrier Certificate or Operating Certificate issued under this part is effective until—
[arabic]
.. The certificate holder surrenders it to the Administrator; or
.. The Administrator suspends, revokes, or otherwise terminates the certificate.
. Operations specifications issued under this part, part 121, or part 135 of this chapter are effective unless—
[arabic]
.. The Administrator suspends, revokes, or otherwise terminates the certificate;
.. The operations specifications are amended as provided in § 119.51;
.. The certificate holder does not conduct a kind of operation for more than the time specified in § 119.63 and fails to follow the procedures of § 119.63 upon resuming that kind of operation; or
.. The Administrator suspends or revokes the operations specifications for a kind of operation.
. Within 30 days after a certificate holder terminates operations under part 135 of this chapter, the operating certificate and operations specifications must be surrendered by the certificate holder to the certificate-holding district office.

## § 119.63 - Recency of operation.

[loweralpha]
. Except as provided in paragraph (b) of this section, no certificate holder may conduct a kind of operation for which it holds authority in its operations specifications unless the certificate holder has conducted that kind of operation within the preceding number of consecutive calendar days specified in this paragraph:
[arabic]
.. For domestic, flag, or commuter operations—30 days.
.. For supplemental or on-demand operations—90 days, except that if the certificate holder has authority to conduct domestic, flag, or commuter operations, and has conducted domestic, flag or commuter operations within the previous 30 days, this paragraph does not apply.
. If a certificate holder does not conduct a kind of operation for which it is authorized in its operations specifications within the number of calendar days specified in paragraph (a) of this section, it shall not conduct such kind of operation unless—
[arabic]
.. It advises the Administrator at least 5 consecutive calendar days before resumption of that kind of operation; and
.. It makes itself available and accessible during the 5 consecutive calendar day period in the event that the FAA decides to conduct a full inspection reexamination to determine whether the certificate holder remains properly and adequately equipped and able to conduct a safe operation.

## § 119.65 - Management personnel required for operations conducted under part 121 of this chapter.

[loweralpha]
. Each certificate holder must have sufficient qualified management and technical personnel to ensure the highest degree of safety in its operations. The certificate holder must have qualified personnel serving full-time in the following or equivalent positions:
[arabic]
.. Director of Safety.
.. Director of Operations.
.. Chief Pilot.
.. Director of Maintenance.
.. Chief Inspector.
. The Administrator may approve positions or numbers of positions other than those listed in paragraph (a) of this section for a particular operation if the certificate holder shows that it can perform the operation with the highest degree of safety under the direction of fewer or different categories of management personnel due to—
[arabic]
.. The kind of operation involved;
.. The number and type of airplanes used; and
.. The area of operations.
. The title of the positions required under paragraph (a) of this section or the title and number of equivalent positions approved under paragraph (b) of this section shall be set forth in the certificate holder's operations specifications.
. The individuals who serve in the positions required or approved under paragraph (a) or (b) of this section and anyone in a position to exercise control over operations conducted under the operating certificate must—
[arabic]
.. Be qualified through training, experience, and expertise;
.. To the extent of their responsibilities, have a full understanding of the following materials with respect to the certificate holder's operation—
[lowerroman]
... Aviation safety standards and safe operating practices;
... 14 CFR Chapter I (Federal Aviation Regulations);
... The certificate holder's operations specifications;
... All appropriate maintenance and airworthiness requirements of this chapter (e.g., parts 1, 21, 23, 25, 43, 45, 47, 65, 91, and 121 of this chapter); and
... The manual required by § 121.133 of this chapter; and
.. Discharge their duties to meet applicable legal requirements and to maintain safe operations.
. Each certificate holder must:
[arabic]
.. State in the general policy provisions of the manual required by § 121.133 of this chapter, the duties, responsibilities, and authority of personnel required under paragraph (a) of this section;
.. List in the manual the names and business addresses of the individuals assigned to those positions; and
.. Notify the certificate-holding district office within 10 days of any change in personnel or any vacancy in any position listed.

## § 119.67 - Management personnel: Qualifications for operations conducted under part 121 of this chapter.

[loweralpha]
. To serve as Director of Operations under § 119.65(a) a person must—
[arabic]
.. Hold an airline transport pilot certificate;
.. Have at least 3 years supervisory or managerial experience within the last 6 years in a position that exercised operational control over any operations conducted with large airplanes under part 121 or part 135 of this chapter, or if the certificate holder uses only small airplanes in its operations, the experience may be obtained in large or small airplanes; and
.. In the case of a person becoming a Director of Operations—
[lowerroman]
... For the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of a large airplane operated under part 121 or part 135 of this chapter, if the certificate holder operates large airplanes. If the certificate holder uses only small airplanes in its operation, the experience may be obtained in either large or small airplanes.
... In the case of a person with previous experience as a Director of Operations, have at least 3 years experience as pilot in command of a large airplane operated under part 121 or part 135 of this chapter, if the certificate holder operates large airplanes. If the certificate holder uses only small airplanes in its operation, the experience may be obtained in either large or small airplanes.
. To serve as Chief Pilot under § 119.65(a) a person must hold an airline transport pilot certificate with appropriate ratings for at least one of the airplanes used in the certificate holder's operation and:
[arabic]
.. In the case of a person becoming a Chief Pilot for the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of a large airplane operated under part 121 or part 135 of this chapter, if the certificate holder operates large airplanes. If the certificate holder uses only small airplanes in its operation, the experience may be obtained in either large or small airplanes.
.. In the case of a person with previous experience as a Chief Pilot, have at least 3 years experience, as pilot in command of a large airplane operated under part 121 or part 135 of this chapter, if the certificate holder operates large airplanes. If the certificate holder uses only small airplanes in its operation, the experience may be obtained in either large or small airplanes.
. To serve as Director of Maintenance under § 119.65(a) a person must—
[arabic]
.. Hold a mechanic certificate with airframe and powerplant ratings;
.. Have 1 year of experience in a position responsible for returning airplanes to service;
.. Have at least 1 year of experience in a supervisory capacity under either paragraph (c)(4)(i) or (c)(4)(ii) of this section maintaining the same category and class of airplane as the certificate holder uses; and
.. Have 3 years experience within the past 6 years in one or a combination of the following—
[lowerroman]
... Maintaining large airplanes with 10 or more passenger seats, including at the time of appointment as Director of Maintenance, experience in maintaining the same category and class of airplane as the certificate holder uses; or
... Repairing airplanes in a certificated airframe repair station that is rated to maintain airplanes in the same category and class of airplane as the certificate holder uses.
. To serve as Chief Inspector under § 119.65(a) a person must—
[arabic]
.. Hold a mechanic certificate with both airframe and powerplant ratings, and have held these ratings for at least 3 years;
.. Have at least 3 years of maintenance experience on different types of large airplanes with 10 or more passenger seats with an air carrier or certificated repair station, 1 year of which must have been as maintenance inspector; and
.. Have at least 1 year of experience in a supervisory capacity maintaining the same category and class of aircraft as the certificate holder uses.
. A certificate holder may request a deviation to employ a person who does not meet the appropriate airman experience, managerial experience, or supervisory experience requirements of this section if the Manager of the Air Transportation Division, AFS-200, or the Manager of the Aircraft Maintenance Division, AFS-300, as appropriate, finds that the person has comparable experience, and can effectively perform the functions associated with the position in accordance with the requirements of this chapter and the procedures outlined in the certificate holder's manual. Grants of deviation under this paragraph may be granted after consideration of the size and scope of the operation and the qualifications of the intended personnel. The Administrator may, at any time, terminate any grant of deviation authority issued under this paragraph.

## § 119.69 - Management personnel required for operations conducted under part 135 of this chapter.

[loweralpha]
. Each certificate holder must have sufficient qualified management and technical personnel to ensure the safety of its operations. Except for a certificate holder using only one pilot in its operations, the certificate holder must have qualified personnel serving in the following or equivalent positions:
[arabic]
.. Director of Operations.
.. Chief Pilot.
.. Director of Maintenance.
. The Administrator may approve positions or numbers of positions other than those listed in paragraph (a) of this section for a particular operation if the certificate holder shows that it can perform the operation with the highest degree of safety under the direction of fewer or different categories of management personnel due to—
[arabic]
.. The kind of operation involved;
.. The number and type of aircraft used; and
.. The area of operations.
. The title of the positions required under paragraph (a) of this section or the title and number of equivalent positions approved under paragraph (b) of this section shall be set forth in the certificate holder's operations specifications.
. The individuals who serve in the positions required or approved under paragraph (a) or (b) of this section and anyone in a position to exercise control over operations conducted under the operating certificate must—
[arabic]
.. Be qualified through training, experience, and expertise;
.. To the extent of their responsibilities, have a full understanding of the following material with respect to the certificate holder's operation—
[lowerroman]
... Aviation safety standards and safe operating practices;
... 14 CFR Chapter I (Federal Aviation Regulations);
... The certificate holder's operations specifications;
... All appropriate maintenance and airworthiness requirements of this chapter (e.g., parts 1, 21, 23, 25, 43, 45, 47, 65, 91, and 135 of this chapter); and
... The manual required by § 135.21 of this chapter; and
.. Discharge their duties to meet applicable legal requirements and to maintain safe operations.
. Each certificate holder must—
[arabic]
.. State in the general policy provisions of the manual required by § 135.21 of this chapter, the duties, responsibilities, and authority of personnel required or approved under paragraph (a) or (b), respectively, of this section;
.. List in the manual the names and business addresses of the individuals assigned to those positions; and
.. Notify the certificate-holding district office within 10 days of any change in personnel or any vacancy in any position listed.

## § 119.71 - Management personnel: Qualifications for operations conducted under part 135 of this chapter.

[loweralpha]
. To serve as Director of Operations under § 119.69(a) for a certificate holder conducting any operations for which the pilot in command is required to hold an airline transport pilot certificate a person must hold an airline transport pilot certificate and either:
[arabic]
.. Have at least 3 years supervisory or managerial experience within the last 6 years in a position that exercised operational control over any operations conducted under part 121 or part 135 of this chapter; or
.. In the case of a person becoming Director of Operations—
[lowerroman]
... For the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
... In the case of a person with previous experience as a Director of Operations, have at least 3 years experience, as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
. To serve as Director of Operations under § 119.69(a) for a certificate holder that only conducts operations for which the pilot in command is required to hold a commercial pilot certificate, a person must hold at least a commercial pilot certificate. If an instrument rating is required for any pilot in command for that certificate holder, the Director of Operations must also hold an instrument rating. In addition, the Director of Operations must either—
[arabic]
.. Have at least 3 years supervisory or managerial experience within the last 6 years in a position that exercised operational control over any operations conducted under part 121 or part 135 of this chapter; or
.. In the case of a person becoming Director of Operations—
[lowerroman]
... For the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
... In the case of a person with previous experience as a Director of Operations, have at least 3 years experience as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
. To serve as Chief Pilot under § 119.69(a) for a certificate holder conducting any operation for which the pilot in command is required to hold an airline transport pilot certificate a person must hold an airline transport pilot certificate with appropriate ratings and be qualified to serve as pilot in command in at least one aircraft used in the certificate holder's operation and:
[arabic]
.. In the case of a person becoming a Chief Pilot for the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
.. In the case of a person with previous experience as a Chief Pilot, have at least 3 years experience as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
. To serve as Chief Pilot under § 119.69(a) for a certificate holder that only conducts operations for which the pilot in command is required to hold a commercial pilot certificate, a person must hold at least a commercial pilot certificate. If an instrument rating is required for any pilot in command for that certificate holder, the Chief Pilot must also hold an instrument rating. The Chief Pilot must be qualified to serve as pilot in command in at least one aircraft used in the certificate holder's operation. In addition, the Chief Pilot must:
[arabic]
.. In the case of a person becoming a Chief Pilot for the first time ever, have at least 3 years experience, within the past 6 years, as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
.. In the case of a person with previous experience as a Chief Pilot, have at least 3 years experience as pilot in command of an aircraft operated under part 121 or part 135 of this chapter.
. To serve as Director of Maintenance under § 119.69(a) a person must hold a mechanic certificate with airframe and powerplant ratings and either:
[arabic]
.. Have 3 years of experience within the past 6 years maintaining aircraft as a certificated mechanic, including, at the time of appointment as Director of Maintenance, experience in maintaining the same category and class of aircraft as the certificate holder uses; or
.. Have 3 years of experience within the past 6 years repairing aircraft in a certificated airframe repair station, including 1 year in the capacity of approving aircraft for return to service.
. A certificate holder may request a deviation to employ a person who does not meet the appropriate airmen experience requirements, managerial experience requirements, or supervisory experience requirements of this section if the Manager of the Air Transportation Division, AFS-200, or the Manager of the Aircraft Maintenance Division, AFS-300, as appropriate, find that the person has comparable experience, and can effectively perform the functions associated with the position in accordance with the requirements of this chapter and the procedures outlined in the certificate holder's manual. The Administrator may, at any time, terminate any grant of deviation authority issued under this paragraph.

## § 119.73 - Employment of former FAA employees.

[loweralpha]
. Except as specified in paragraph (c) of this section, no certificate holder conducting operations under part 121 or 135 of this chapter may knowingly employ or make a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual, in the preceding 2 years—
[arabic]
.. Served as, or was directly responsible for the oversight of, a Flight Standards Service aviation safety inspector; and
.. Had direct responsibility to inspect, or oversee the inspection of, the operations of the certificate holder.
. For the purpose of this section, an individual shall be considered to be acting as an agent or representative of a certificate holder in a matter before the agency if the individual makes any written or oral communication on behalf of the certificate holder to the agency (or any of its officers or employees) in connection with a particular matter, whether or not involving a specific party and without regard to whether the individual has participated in, or had responsibility for, the particular matter while serving as a Flight Standards Service aviation safety inspector.
. The provisions of this section do not prohibit a certificate holder from knowingly employing or making a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual was employed by the certificate holder before October 21, 2011.

