# Special Flight Operations
:toc:

## § 91.301

### Reserved

## § 91.303

### Aerobatic flight.

No person may operate an aircraft in aerobatic flight—

. Over any congested area of a city, town, or settlement;
. Over an open air assembly of persons;
. Within the lateral boundaries of the surface areas of Class B, Class C, Class D, or Class E airspace designated for an airport;
. Within 4 nautical miles of the center line of any Federal airway;
. Below an altitude of 1,500 feet above the surface; or
. When flight visibility is less than 3 statute miles.
              

## § 91.305

### Flight test areas.

No person may flight test an aircraft except over open water, or sparsely populated areas, having light air traffic.

## § 91.307

### Parachutes and parachuting.

. No pilot of a civil aircraft may allow a parachute that is available for emergency use to be carried in that aircraft unless it is an approved type and has been packed by a certificated and appropriately rated parachute rigger—
.. Within the preceding 180 days, if its canopy, shrouds, and harness are composed exclusively of nylon, rayon, or other similar synthetic fiber or materials that are substantially resistant to damage from mold, mildew, or other fungi and other rotting agents propagated in a moist environment; or
.. Within the preceding 60 days, if any part of the parachute is composed of silk, pongee, or other natural fiber or materials not specified in paragraph (a)(1) of this section.
. Except in an emergency, no pilot in command may allow, and no person may conduct, a parachute operation from an aircraft within the United States except in accordance with part 105 of this chapter.
. Unless each occupant of the aircraft is wearing an approved parachute, no pilot of a civil aircraft carrying any person (other than a crewmember) may execute any intentional maneuver that exceeds—
.. A bank of 60 degrees relative to the horizon; or
.. A nose-up or nose-down attitude of 30 degrees relative to the horizon.
. Paragraph (c) of this section does not apply to—
.. Flight tests for pilot certification or rating; or
.. Spins and other flight maneuvers required by the regulations for any certificate or rating when given by—
... A certificated flight instructor; or
              
... An airline transport pilot instructing in accordance with § 61.67 of this chapter.
. For the purposes of this section, *approved parachute* means—
.. A parachute manufactured under a type certificate or a technical standard order (C-23 series); or
.. A personnel-carrying military parachute identified by an NAF, AAF, or AN drawing number, an AAF order number, or any other military designation or specification number.

## § 91.309

### Towing: Gliders and unpowered ultralight vehicles.

. No person may operate a civil aircraft towing a glider or unpowered ultralight vehicle unless—
.. The pilot in command of the towing aircraft is qualified under § 61.69 of this chapter;
.. The towing aircraft is equipped with a tow-hitch of a kind, and installed in a manner, that is approved by the Administrator;
.. The towline used has breaking strength not less than 80 percent of the maximum certificated operating weight of the glider or unpowered ultralight vehicle and not more than twice this operating weight. However, the towline used may have a breaking strength more than twice the maximum certificated operating weight of the glider or unpowered ultralight vehicle if—
... A safety link is installed at the point of attachment of the towline to the glider or unpowered ultralight vehicle with a breaking strength not less than 80 percent of the maximum certificated operating weight of the glider or unpowered ultralight vehicle and not greater than twice this operating weight;
... A safety link is installed at the point of attachment of the towline to the towing aircraft with a breaking strength greater, but not more than 25 percent greater, than that of the safety link at the towed glider or unpowered ultralight vehicle end of the towline and not greater than twice the maximum certificated operating weight of the glider or unpowered ultralight vehicle;
.. Before conducting any towing operation within the lateral boundaries of the surface areas of Class B, Class C, Class D, or Class E airspace designated for an airport, or before making each towing flight within such controlled airspace if required by ATC, the pilot in command notifies the control tower. If a control tower does not exist or is not in operation, the pilot in command must notify the FAA flight service station serving that controlled airspace before conducting any towing operations in that airspace; and
.. The pilots of the towing aircraft and the glider or unpowered ultralight vehicle have agreed upon a general course of action, including takeoff and release signals, airspeeds, and emergency procedures for each pilot.
. No pilot of a civil aircraft may intentionally release a towline, after release of a glider or unpowered ultralight vehicle, in a manner that endangers the life or property of another.

## § 91.311

### Towing: Other than under § 91.309.

No pilot of a civil aircraft may tow anything with that aircraft (other than under § 91.309) except in accordance with the terms of a certificate of waiver issued by the Administrator.

## § 91.313

### Restricted category civil aircraft: Operating limitations.

. No person may operate a restricted category civil aircraft—
.. For other than the special purpose for which it is certificated; or
.. In an operation other than one necessary to accomplish the work activity directly associated with that special purpose.
. For the purpose of paragraph (a) of this section, operating a restricted category civil aircraft to provide flight crewmember training in a special purpose operation for which the aircraft is certificated is considered to be an operation for that special purpose.
              
. No person may operate a restricted category civil aircraft carrying persons or property for compensation or hire. For the purposes of this paragraph, a special purpose operation involving the carriage of persons or material necessary to accomplish that operation, such as crop dusting, seeding, spraying, and banner towing (including the carrying of required persons or material to the location of that operation), and operation for the purpose of providing flight crewmember training in a special purpose operation, are not considered to be the carriage of persons or property for compensation or hire.
. No person may be carried on a restricted category civil aircraft unless that person—
.. Is a flight crewmember;
.. Is a flight crewmember trainee;
.. Performs an essential function in connection with a special purpose operation for which the aircraft is certificated; or
.. Is necessary to accomplish the work activity directly associated with that special purpose.
. Except when operating in accordance with the terms and conditions of a certificate of waiver or special operating limitations issued by the Administrator, no person may operate a restricted category civil aircraft within the United States—
.. Over a densely populated area;
.. In a congested airway; or
.. Near a busy airport where passenger transport operations are conducted.
. This section does not apply to nonpassenger-carrying civil rotorcraft external-load operations conducted under part 133 of this chapter.
. No person may operate a small restricted-category civil airplane manufactured after July 18, 1978, unless an approved shoulder harness is installed for each front seat. The shoulder harness must be designed to protect each occupant from serious head injury when the occupant experiences the ultimate inertia forces specified in § 23.561(b)(2) of this chapter. The shoulder harness installation at each flight crewmember station must permit the crewmember, when seated and with the safety belt and shoulder harness fastened, to perform all functions necessary for flight operation. For purposes of this paragraph—
.. The date of manufacture of an airplane is the date the inspection acceptance records reflect that the airplane is complete and meets the FAA-approved type design data; and
.. A front seat is a seat located at a flight crewmember station or any seat located alongside such a seat.

## § 91.315

### Limited category civil aircraft: Operating limitations.

No person may operate a limited category civil aircraft carrying persons or property for compensation or hire.

## § 91.317

### Provisionally certificated civil aircraft: Operating limitations.

. No person may operate a provisionally certificated civil aircraft unless that person is eligible for a provisional airworthiness certificate under § 21.213 of this chapter.
. No person may operate a provisionally certificated civil aircraft outside the United States unless that person has specific authority to do so from the Administrator and each foreign country involved.
. Unless otherwise authorized by the Director, Flight Standards Service, no person may operate a provisionally certificated civil aircraft in air transportation.
. Unless otherwise authorized by the Administrator, no person may operate a provisionally certificated civil aircraft except—
.. In direct conjunction with the type or supplemental type certification of that aircraft;
.. For training flight crews, including simulated air carrier operations;
.. Demonstration flight by the manufacturer for prospective purchasers;
.. Market surveys by the manufacturer;
.. Flight checking of instruments, accessories, and equipment that do not affect the basic airworthiness of the aircraft; or
.. Service testing of the aircraft.
. Each person operating a provisionally certificated civil aircraft shall operate within the prescribed limitations displayed in the aircraft or set forth in the provisional aircraft flight manual or other appropriate document. However, when operating in direct conjunction with the type or supplemental type certification of the aircraft, that person shall operate under the experimental aircraft limitations of § 21.191 of this chapter and when flight testing, shall operate under the requirements of § 91.305 of this part.
. Each person operating a provisionally certificated civil aircraft shall establish approved procedures for—
.. The use and guidance of flight and ground personnel in operating under this section; and
.. Operating in and out of airports where takeoffs or approaches over populated areas are necessary. No person may operate that aircraft except in compliance with the approved procedures.
. Each person operating a provisionally certificated civil aircraft shall ensure that each flight crewmember is properly certificated and has adequate knowledge of, and familiarity with, the aircraft and procedures to be used by that crewmember.
. Each person operating a provisionally certificated civil aircraft shall maintain it as required by applicable regulations and as may be specially prescribed by the Administrator.
. Whenever the manufacturer, or the Administrator, determines that a change in design, construction, or operation is necessary to ensure safe operation, no person may operate a provisionally certificated civil aircraft until that change has been made and approved. Section 21.99 of this chapter applies to operations under this section.
. Each person operating a provisionally certificated civil aircraft—
.. May carry in that aircraft only persons who have a proper interest in the operations allowed by this section or who are specifically authorized by both the manufacturer and the Administrator; and
.. Shall advise each person carried that the aircraft is provisionally certificated.
. The Administrator may prescribe additional limitations or procedures that the Administrator considers necessary, including limitations on the number of persons who may be carried in the aircraft.

## § 91.319

### Aircraft having experimental certificates: Operating limitations.

. No person may operate an aircraft that has an experimental certificate—
.. For other than the purpose for which the certificate was issued; or
.. Carrying persons or property for compensation or hire.
. No person may operate an aircraft that has an experimental certificate outside of an area assigned by the Administrator until it is shown that—
.. The aircraft is controllable throughout its normal range of speeds and throughout all the maneuvers to be executed; and
.. The aircraft has no hazardous operating characteristics or design features.
. Unless otherwise authorized by the Administrator in special operating limitations, no person may operate an aircraft that has an experimental certificate over a densely populated area or in a congested airway. The Administrator may issue special operating limitations for particular aircraft to permit takeoffs and landings to be conducted over a densely populated area or in a congested airway, in accordance with terms and conditions specified in the authorization in the interest of safety in air commerce.
. Each person operating an aircraft that has an experimental certificate shall—
.. Advise each person carried of the experimental nature of the aircraft;
.. Operate under VFR, day only, unless otherwise specifically authorized by the Administrator; and
.. Notify the control tower of the experimental nature of the aircraft when operating the aircraft into or out of airports with operating control towers.
. No person may operate an aircraft that is issued an experimental certificate under § 21.191(i) of this chapter for compensation or hire, except a person may operate an aircraft issued an experimental certificate under § 21.191(i)(1) for compensation or hire to—
.. Tow a glider that is a light-sport aircraft or unpowered ultralight vehicle in accordance with § 91.309; or
.. Conduct flight training in an aircraft which that person provides prior to January 31, 2010.
. No person may lease an aircraft that is issued an experimental certificate under § 21.191(i) of this chapter, except in accordance with paragraph (e)(1) of this section.
. No person may operate an aircraft issued an experimental certificate under § 21.191(i)(1) of this chapter to tow a glider that is a light-sport aircraft or unpowered ultralight vehicle for compensation or hire or to conduct flight training for compensation or hire in an aircraft which that persons provides unless within the preceding 100 hours of time in service the aircraft has—
.. Been inspected by a certificated repairman (light-sport aircraft) with a maintenance rating, an appropriately rated mechanic, or an appropriately rated repair station in accordance with inspection procedures developed by the aircraft manufacturer or a person acceptable to the FAA; or
.. Received an inspection for the issuance of an airworthiness certificate in accordance with part 21 of this chapter.
. The FAA may issue deviation authority providing relief from the provisions of paragraph (a) of this section for the purpose of conducting flight training. The FAA will issue this deviation authority as a letter of deviation authority.
.. The FAA may cancel or amend a letter of deviation authority at any time.
.. An applicant must submit a request for deviation authority to the FAA at least 60 days before the date of intended operations. A request for deviation authority must contain a complete description of the proposed operation and justification that establishes a level of safety equivalent to that provided under the regulations for the deviation requested.
... The Administrator may prescribe additional limitations that the Administrator considers necessary, including limitations on the persons that may be carried in the aircraft.

## § 91.321

### Carriage of candidates in elections.

. As an aircraft operator, you may receive payment for carrying a candidate, agent of a candidate, or person traveling on behalf of a candidate, running for Federal, State, or local election, without having to comply with the rules in parts 121, 125 or 135 of this chapter, under the following conditions:
.. Your primary business is not as an air carrier or commercial operator;
.. You carry the candidate, agent, or person traveling on behalf of a candidate, under the rules of part 91; and
.. By Federal, state or local law, you are required to receive payment for carrying the candidate, agent, or person traveling on behalf of a candidate. For federal elections, the payment may not exceed the amount required by the Federal Election Commission. For a state or local election, the payment may not exceed the amount required under the applicable state or local law.
. For the purposes of this section, for Federal elections, the terms *candidate* and *election* have the same meaning as set forth in the regulations of the Federal Election Commission. For State or local elections, the terms *candidate* and *election* have the same meaning as provided by the applicable State or local law and those terms relate to candidates for election to public office in State and local government elections.

## § 91.323

### Increased maximum certificated weights for certain airplanes operated in Alaska.

. Notwithstanding any other provision of the Federal Aviation Regulations, the Administrator will approve, as provided in this section, an increase in the maximum certificated weight of an airplane type certificated under Aeronautics Bulletin No. 7-A of the U.S. Department of Commerce dated January 1, 1931, as amended, or under the normal category of part 4a of the former Civil Air Regulations (14 CFR part 4a, 1964 ed.) if that airplane is operated in the State of Alaska by—
.. A certificate holder conducting operations under part 121 or part 135 of this chapter; or
.. The U.S. Department of Interior in conducting its game and fish law enforcement activities or its management, fire detection, and fire suppression activities concerning public lands.
. The maximum certificated weight approved under this section may not exceed—
.. 12,500 pounds;
.. 115 percent of the maximum weight listed in the FAA aircraft specifications;
.. The weight at which the airplane meets the positive maneuvering load factor requirement for the normal category specified in § 23.337 of this chapter; or
.. The weight at which the airplane meets the climb performance requirements under which it was type certificated.
. In determining the maximum certificated weight, the Administrator considers the structural soundness of the airplane and the terrain to be traversed.
. The maximum certificated weight determined under this section is added to the airplane's operation limitations and is identified as the maximum weight authorized for operations within the State of Alaska.

## § 91.325

### Primary category aircraft: Operating limitations.

. No person may operate a primary category aircraft carrying persons or property for compensation or hire.
. No person may operate a primary category aircraft that is maintained by the pilot-owner under an approved special inspection and maintenance program except—
.. The pilot-owner; or
.. A designee of the pilot-owner, provided that the pilot-owner does not receive compensation for the use of the aircraft.

## § 91.327

### Aircraft having a special airworthiness certificate in the light-sport category: Operating limitations.

. No person may operate an aircraft that has a special airworthiness certificate in the light-sport category for compensation or hire except—
              
.. To tow a glider or an unpowered ultralight vehicle in accordance with § 91.309 of this chapter; or
.. To conduct flight training.
. No person may operate an aircraft that has a special airworthiness certificate in the light-sport category unless—
.. The aircraft is maintained by a certificated repairman with a light-sport aircraft maintenance rating, an appropriately rated mechanic, or an appropriately rated repair station in accordance with the applicable provisions of part 43 of this chapter and maintenance and inspection procedures developed by the aircraft manufacturer or a person acceptable to the FAA;
.. A condition inspection is performed once every 12 calendar months by a certificated repairman (light-sport aircraft) with a maintenance rating, an appropriately rated mechanic, or an appropriately rated repair station in accordance with inspection procedures developed by the aircraft manufacturer or a person acceptable to the FAA;
.. The owner or operator complies with all applicable airworthiness directives;
.. The owner or operator complies with each safety directive applicable to the aircraft that corrects an existing unsafe condition. In lieu of complying with a safety directive an owner or operator may—
... Correct the unsafe condition in a manner different from that specified in the safety directive provided the person issuing the directive concurs with the action; or
... Obtain an FAA waiver from the provisions of the safety directive based on a conclusion that the safety directive was issued without adhering to the applicable consensus standard;
.. Each alteration accomplished after the aircraft's date of manufacture meets the applicable and current consensus standard and has been authorized by either the manufacturer or a person acceptable to the FAA;
.. Each major alteration to an aircraft product produced under a consensus standard is authorized, performed and inspected in accordance with maintenance and inspection procedures developed by the manufacturer or a person acceptable to the FAA; and
.. The owner or operator complies with the requirements for the recording of major repairs and major alterations performed on type-certificated products in accordance with § 43.9(d) of this chapter, and with the retention requirements in § 91.417.
. No person may operate an aircraft issued a special airworthiness certificate in the light-sport category to tow a glider or unpowered ultralight vehicle for compensation or hire or conduct flight training for compensation or hire in an aircraft which that persons provides unless within the preceding 100 hours of time in service the aircraft has—
.. Been inspected by a certificated repairman with a light-sport aircraft maintenance rating, an appropriately rated mechanic, or an appropriately rated repair station in accordance with inspection procedures developed by the aircraft manufacturer or a person acceptable to the FAA and been approved for return to service in accordance with part 43 of this chapter; or
.. Received an inspection for the issuance of an airworthiness certificate in accordance with part 21 of this chapter.
. Each person operating an aircraft issued a special airworthiness certificate in the light-sport category must operate the aircraft in accordance with the aircraft's operating instructions, including any provisions for necessary operating equipment specified in the aircraft's equipment list.
. Each person operating an aircraft issued a special airworthiness certificate in the light-sport category must advise each person carried of the special nature of the aircraft and that the aircraft does not meet the airworthiness requirements for an aircraft issued a standard airworthiness certificate.
. The FAA may prescribe additional limitations that it considers necessary.

## §§ 91.328-91.399

### Reserved

