# Nondirectional Radio Beacon Facilities
:toc:

## § 171.21

### Scope.

. This subpart sets forth minimum requirements for the approval and operation of non-Federal, nondirectional radio beacon facilities that are to be involved in the approval of instrument flight rules and air traffic control procedures related to those facilities.
. A nondirectional radio beacon (“H” facilities domestically—NDB facilities internationally) radiates a continuous carrier of approximately equal intensity at all azimuths. The carrier is modulated at 1020 cycles per second for station identification purposes.

## § 171.23

### Requests for IFR procedure.

. Each person who requests an IFR procedure based on a nondirectional radio beacon facility that he owns must submit the following information with that request:
.. A description of the facility and evidence that the equipment meets the performance requirements of § 171.27 and is installed in accordance with § 171.29.
.. A proposed procedure for operating the facility.
.. A proposed maintenance arrangement and a maintenance manual that meets the requirements of § 171.31.
.. A statement of intention to meet the requirements of this subpart.
.. A showing that the facility has an acceptable level of operational reliability and an acceptable standard of performance. Previous equivalent operational experience with a facility with identical design and operational characteristics will be considered in showing compliance with this subparagraph.
. After the FAA inspects and evaluates the facility, it advises the owner of the results and of any required changes in the facility or the maintenance manual or maintenance organization. The owner must then correct the deficiencies, if any, and operate the facility for an in-service evaluation by the FAA.

## § 171.25

### Minimum requirements for approval.

. The following are the minimum requirements that must be met before the FAA will approve an IFR procedure for a non-Federal, nondirectional radio beacon facility under this subpart:
.. The facility's performances, as determined by air and ground inspection, must meet the requirements of § 171.27.
.. The installation of the equipment must meet the requirements of § 171.29.
.. The owner must agree to operate and maintain the facility in accord- ance with § 171.31.
.. The owner must agree to furnish periodic reports, as set forth in § 171.33, and agree to allow the FAA to inspect the facility and its operation whenever necessary.
.. The owner must assure the FAA that he will not withdraw the facility from service without the permission of the FAA.
.. The owner must bear all costs of meeting the requirements of this section and of any flight or ground inspections made before the facility is commissioned, except that the Federal Aviation Administration may bear certain of these costs subject to budgetary limitations and policy established by the Administrator.
              
. If the applicant for approval meets the requirements of paragraph (a) of this section, the FAA commissions the facility as a prerequisite to its approval for use in an IFR procedure. The approval is withdrawn at any time the facility does not continue to meet those requirements. In addition, the facility may be de-commissioned whenever the frequency channel is needed for higher priority common system service.

## § 171.27

### Performance requirements.

. The facility must meet the performance requirements set forth in the “International Standards and Recommended Practices, Aeronautical Telecommunications, Part I, paragraph 3.4” (Annex 10 to the Convention on International Civil Aviation), except that identification by on-off keying of a second carrier frequency, separated from the main carrier by 1020 Hz plus or minus 50 Hz, is also acceptable.
. The facility must perform in accordance with recognized and accepted good electronic engineering practices for the desired service.
. Ground inspection consists of an examination of the design features of the equipment to determine (based on recognized and accepted good engineering practices) that there will not be conditions that will allow unsafe operations because of component failure or deterioration.
. Flight tests to determine the facility's adequacy for operational requirements and compliance with applicable “Standards and Recommended Practices” are conducted in accord- ance with the “U.S. Standard Flight Inspection Manual”, particularly section 207. The original test is made by the FAA and later tests shall be made under arrangements, satisfactory to the FAA, that are made by the owner.

## § 171.29

### Installation requirements.

. The facility must be installed according to accepted good engineering practices, applicable electric and safety codes, and FCC licensing requirements.
. The facility must have a reliable source of suitable primary power.
. Dual transmitting equipment may be required to support some IFR procedures.
. A facility intended for use as an instrument approach aid for an airport must have or be supplemented by (depending on the circumstances) the following ground-air or landline communications services:
.. At facilities outside of and not immediately adjacent to controlled airspace, there must be ground-air communications from the airport served by the facility. Voice on the aid controlled from the airport is acceptable.
.. At facilities within or immediately adjacent to controlled airspace, there must be the ground-air communications required by paragraph (d)(1) of this section and reliable communications (at least a landline telephone) from the airport to the nearest FAA air traffic control or communication facility.
              

## § 171.31

### Maintenance and operations requirements.

. The owner of the facility must establish an adequate maintenance system and provide qualified maintenance personnel to maintain the facility at the level attained at the time it was commissioned. Each person who maintains a facility must meet at least the Federal Communications Commission's licensing requirements and show that he has the special knowledge and skills needed to maintain the facility including proficiency in maintenance procedures and the use of specialized test equipment.
. The owner must prepare, and obtain approval of, an operations and maintenance manual that sets forth mandatory procedures for operations, preventive maintenance, and emergency maintenance, including instructions on each of the following:
.. Physical security of the facility.
.. Maintenance and operations by authorized persons only.
.. FCC licensing requirements for operating and maintenance personnel.
.. Posting of licenses and signs.
.. Relations between the facility and FAA air traffic control facilities, with a description of the boundaries of controlled airspace over or near the facility, instructions for relaying air traffic control instructions and information (if applicable), and instructions for the operation of an air traffic advisory service if the facility is located outside of controlled airspace.
.. Notice to the Administrator of any suspension of service.
.. Detailed arrangements for maintenance flight inspection and servicing stating the frequency of servicing.
.. Air-ground communications, if provided, expressly written or incorporating appropriate sections of FAA manuals by reference.
.. Keeping of station logs and other technical reports, and the submission of reports required by § 171.33.
.. Monitoring of the facility, at least once each half hour, to assure continuous operation.
.. Inspections by United States personnel.
.. Names, addresses, and telephone numbers of persons to be notified in an emergency.
.. Shutdowns for routine maintenance and issue of “Notices to Airmen” for routine or emergency shutdowns (private use facilities may omit the “Notices to Airmen”).
.. Commissioning of the facility.
.. An acceptable procedure for amending or revising the manual.
.. The following information concerning the facility:
... Location by latitude and longitude to the nearest second, and its position with respect to airport layouts.
... The type, make, and model of the basic radio equipment that will provide the service.
... The station power emission and frequency.
... The hours of operation.
... Station identification call letters and method of station identification, whether by Morse code or recorded voice announcement, and the time spacing of the identification.
. If the owner desires to modify the facility, he must submit the proposal to the FAA and meet applicable requirements of the FCC.
. The owner's maintenance personnel must participate in initial inspections made by the FAA. In the case of subsequent inspections, the owner or his representative shall participate.
. The owner shall provide a stock of spare parts, including vacuum tubes, of such a quantity to make possible the prompt replacement of components that fail or deteriorate in service.
. The owner shall close the facility upon receiving two successive pilot reports of its malfunctioning.

## § 171.33

### Reports.

The owner of each facility to which this subpart applies shall make the following reports, at the times indicated, to the FAA Regional office for the area in which the facility is located:

. *Record of meter readings and adjustments* (*Form FAA-198*). To be filled out by the owner or his maintenance representative with the equipment adjustments and meter readings as of the time of commissioning, with one copy to be kept in the permanent records of the facility and two copies to the appropriate Regional Office of the FAA. The owner shall revise the form after any major repair, modernization, or returning, to reflect an accurate record of facility operation and adjustment.
. *Facility maintenance log* (*FAA Form 6030-1*). This form is a permanent record of all equipment malfunctioning met in maintaining the facility, including information on the kind of work and adjustments made, equipment failures, causes (if determined), and corrective action taken. The owner shall keep the original of each report at the facility and send a copy to the appropriate Regional Office of the FAA at the end of the month in which it is prepared.
. *Radio equipment operation record* (*Form FAA-418*). To contain a complete record of meter readings, recorded on each scheduled visit to the facility. The owner shall keep the original of each month's record at the facility and send a copy of it to the appropriate Regional Office of the FAA.

