# Operating Noise Limits
:toc:

## § 91.801

### Applicability: Relation to part 36.

. This subpart prescribes operating noise limits and related requirements that apply, as follows, to the operation of civil aircraft in the United States.
.. Sections 91.803, 91.805, 91.807, 91.809, and 91.811 apply to civil subsonic jet (turbojet) airplanes with maximum weights of more than 75,000 pounds and—
... If U.S. registered, that have standard airworthiness certificates; or
... If foreign registered, that would be required by this chapter to have a U.S. standard airworthiness certificate in order to conduct the operations intended for the airplane were it registered in the United States. Those sections apply to operations to or from airports in the United States under this part and parts 121, 125, 129, and 135 of this chapter.
.. Section 91.813 applies to U.S. operators of civil subsonic jet (turbojet) airplanes covered by this subpart. This section applies to operators operating to or from airports in the United States under this part and parts 121, 125, and 135, but not to those operating under part 129 of this chapter.
.. Sections 91.803, 91.819, and 91.821 apply to U.S.-registered civil supersonic airplanes having standard airworthiness certificates and to foreign-registered civil supersonic airplanes that, if registered in the United States, would be required by this chapter to have U.S. standard airworthiness certificates in order to conduct the operations intended for the airplane. Those sections apply to operations under this part and under parts 121, 125, 129, and 135 of this chapter.
. Unless otherwise specified, as used in this subpart “part 36” refers to 14 CFR part 36, including the noise levels under appendix C of that part, notwithstanding the provisions of that part excepting certain airplanes from the specified noise requirements. For purposes of this subpart, the various stages of noise levels, the terms used to describe airplanes with respect to those levels, and the terms “subsonic airplane” and “supersonic airplane” have the meanings specified under part 36 of this chapter. For purposes of this subpart, for subsonic airplanes operated in foreign air commerce in the United States, the Administrator may accept compliance with the noise requirements under annex 16 of the International Civil Aviation Organization when those requirements have been shown to be substantially compatible with, and achieve results equivalent to those achievable under, part 36 for that airplane. Determinations made under these provisions are subject to the limitations of § 36.5 of this chapter as if those noise levels were part 36 noise levels.
. Sections 91.851 through 91.877 of this subpart prescribe operating noise limits and related requirements that apply to any civil subsonic jet (turbojet) airplane (for which an airworthiness certificate other than an experimental certificate has been issued by the Administrator) with a maximum certificated takeoff weight of more than 75,000 pounds operating to or from an airport in the 48 contiguous United States and the District of Columbia under this part, parts 121, 125, 129, or 135 of this chapter on and after September 25, 1991.
. Section 91.877 prescribes reporting requirements that apply to any civil subsonic jet (turbojet) airplane with a maximum weight of more than 75,000 pounds operated by an air carrier or foreign air carrier between the contiguous United States and the State of Hawaii, between the State of Hawaii and any point outside of the 48 contiguous United States, or between the islands of Hawaii in turnaround service, under part 121 or 129 of this chapter on or after November 5, 1990.
. Sections 91.881 through 91.883 of this subpart prescribe operating noise limits and related requirements that apply to any civil subsonic jet airplane with a maximum takeoff weight of 75,000 pounds or less and for which an airworthiness certificate (other than an experimental certificate) has been issued, operating to or from an airport in the contiguous United States under this part, part 121, 125, 129, or 135 of this chapter on and after December 31, 2015.

## § 91.803

### Part 125 operators: Designation of applicable regulations.

For airplanes covered by this subpart and operated under part 125 of this chapter, the following regulations apply as specified:

. For each airplane operation to which requirements prescribed under this subpart applied before November 29, 1980, those requirements of this subpart continue to apply.
. For each subsonic airplane operation to which requirements prescribed under this subpart did not apply before November 29, 1980, because the airplane was not operated in the United States under this part or part 121, 129, or 135 of this chapter, the requirements prescribed under § 91.805 of this subpart apply.
. For each supersonic airplane operation to which requirements prescribed under this subpart did not apply before November 29, 1980, because the airplane was not operated in the United States under this part or part 121, 129, or 135 of this chapter, the requirements of §§ 91.819 and 91.821 of this subpart apply.
. For each airplane required to operate under part 125 for which a deviation under that part is approved to operate, in whole or in part, under this part or part 121, 129, or 135 of this chapter, notwithstanding the approval, the requirements prescribed under paragraphs (a), (b), and (c) of this section continue to apply.

## § 91.805

### Final compliance: Subsonic airplanes.

Except as provided in §§ 91.809 and 91.811, on and after January 1, 1985, no person may operate to or from an airport in the United States any subsonic airplane covered by this subpart unless that airplane has been shown to comply with Stage 2 or Stage 3 noise levels under part 36 of this chapter.

## §§ 91.807-91.813

### Reserved

## § 91.815

### Agricultural and fire fighting airplanes: Noise operating limitations.

. This section applies to propeller-driven, small airplanes having standard airworthiness certificates that are designed for “agricultural aircraft operations” (as defined in § 137.3 of this chapter, as effective on January 1, 1966) or for dispensing fire fighting materials.
. If the Airplane Flight Manual, or other approved manual material information, markings, or placards for the airplane indicate that the airplane has not been shown to comply with the noise limits under part 36 of this chapter, no person may operate that airplane, except—
.. To the extent necessary to accomplish the work activity directly associated with the purpose for which it is designed;
.. To provide flight crewmember training in the special purpose operation for which the airplane is designed; and
              
.. To conduct “nondispensing aerial work operations” in accordance with the requirements under § 137.29(c) of this chapter.

## § 91.817

### Civil aircraft sonic boom.

. No person may operate a civil aircraft in the United States at a true flight Mach number greater than 1 except in compliance with conditions and limitations in an authorization to exceed Mach 1 issued to the operator under appendix B of this part.
. In addition, no person may operate a civil aircraft for which the maximum operating limit speed M*M0* exceeds a Mach number of 1, to or from an airport in the United States, unless—
.. Information available to the flight crew includes flight limitations that ensure that flights entering or leaving the United States will not cause a sonic boom to reach the surface within the United States; and
.. The operator complies with the flight limitations prescribed in paragraph (b)(1) of this section or complies with conditions and limitations in an authorization to exceed Mach 1 issued under appendix B of this part.

## § 91.819

### Civil supersonic airplanes that do not comply with part 36.

. *Applicability.* This section applies to civil supersonic airplanes that have not been shown to comply with the Stage 2 noise limits of part 36 in effect on October 13, 1977, using applicable trade-off provisions, and that are operated in the United States, after July 31, 1978.
. *Airport use.* Except in an emergency, the following apply to each person who operates a civil supersonic airplane to or from an airport in the United States:
.. Regardless of whether a type design change approval is applied for under part 21 of this chapter, no person may land or take off an airplane covered by this section for which the type design is changed, after July 31, 1978, in a manner constituting an “acoustical change” under § 21.93 unless the acoustical change requirements of part 36 are complied with.
.. No flight may be scheduled, or otherwise planned, for takeoff or landing after 10 p.m. and before 7 a.m. local time.

## § 91.821

### Civil supersonic airplanes: Noise limits.

Except for Concorde airplanes having flight time before January 1, 1980, no person may operate in the United States, a civil supersonic airplane that does not comply with Stage 2 noise limits of part 36 in effect on October 13, 1977, using applicable trade-off provisions.

## §§ 91.823-91.849

### Reserved

## § 91.851

### Definitions.

For the purposes of §§ 91.851 through 91.877 of this subpart:

*Chapter 4 noise level* means a noise level at or below the maximum noise level prescribed in Chapter 4, Paragraph 4.4, Maximum Noise Levels, of the International Civil Aviation Organization (ICAO) Annex 16, Volume I, Amendment 7, effective March 21, 2002. The Director of the Federal Register in accordance with 5 U.S.C. 552(a) and 1 CFR part 51 approved the incorporation by reference of this document, which can be obtained from the International Civil Aviation Organization (ICAO), Document Sales Unit, 999 University Street, Montreal, Quebec H3C 5H7, Canada. Also, you may obtain documents on the Internet at *http://www.ICAO.int/eshop/index.cfm.* Copies may be reviewed at the U.S. Department of Transportation, Docket Operations, West Building Ground Floor, Room W12-140, 1200 New Jersey Avenue, SE., Washington, DC 20590 or at the National Archives and Records Administration (NARA). For information on the availability of this material at NARA, call 202-741-6030, or go to: *http://www.archives.gov/federal_register/code_of_federal_regulations/ibr_locations.html.*
              

*Contiguous United States* means the area encompassed by the 48 contiguous United States and the District of Columbia.

*Fleet* means those civil subsonic jet (turbojet) airplanes with a maximum certificated weight of more than 75,000 pounds that are listed on an operator's operations specifications as eligible for operation in the contiguous United States.

*Import* means a change in ownership of an airplane from a non-U.S. person to a U.S. person when the airplane is brought into the United States for operation.

*Operations specifications* means an enumeration of airplanes by type, model, series, and serial number operated by the operator or foreign air carrier on a given day, regardless of how or whether such airplanes are formally listed or designated by the operator.

*Owner* means any person that has indicia of ownership sufficient to register the airplane in the United States pursuant to part 47 of this chapter.

*New entrant* means an air carrier or foreign air carrier that, on or before November 5, 1990, did not conduct operations under part 121 or 129 of this chapter using an airplane covered by this subpart to or from any airport in the contiguous United States, but that initiates such operation after that date.

*Stage 2 noise levels* mean the requirements for Stage 2 noise levels as defined in part 36 of this chapter in effect on November 5, 1990.

*Stage 3 noise levels* mean the requirements for Stage 3 noise levels as defined in part 36 of this chapter in effect on November 5, 1990.

*Stage 4 noise level* means a noise level at or below the Stage 4 noise limit prescribed in part 36 of this chapter.

*Stage 2 airplane* means a civil subsonic jet (turbojet) airplane with a maximum certificated weight of 75,000 pounds or more that complies with Stage 2 noise levels as defined in part 36 of this chapter.

*Stage 3 airplane* means a civil subsonic jet (turbojet) airplane with a maximum certificated weight of 75,000 pounds or more that complies with Stage 3 noise levels as defined in part 36 of this chapter.

*Stage 4 airplane* means an airplane that has been shown not to exceed the Stage 4 noise limit prescribed in part 36 of this chapter. A Stage 4 airplane complies with all of the noise operating rules of this part.

## § 91.853

### Final compliance: Civil subsonic airplanes.

Except as provided in § 91.873, after December 31, 1999, no person shall operate to or from any airport in the contiguous United States any airplane subject to § 91.801(c) of this subpart, unless that airplane has been shown to comply with Stage 3 or Stage 4 noise levels.

## § 91.855

### Entry and nonaddition rule.

No person may operate any airplane subject to § 91.801(c) of this subpart to or from an airport in the contiguous United States unless one or more of the following apply:

. The airplane complies with Stage 3 or Stage 4 noise levels.
. The airplane complies with Stage 2 noise levels and was owned by a U.S. person on and since November 5, 1990. Stage 2 airplanes that meet these criteria and are leased to foreign airlines are also subject to the return provisions of paragraph (e) of this section.
. The airplane complies with Stage 2 noise levels, is owned by a non-U.S. person, and is the subject of a binding lease to a U.S. person effective before and on September 25, 1991. Any such airplane may be operated for the term of the lease in effect on that date, and any extensions thereof provided for in that lease.
. The airplane complies with Stage 2 noise levels and is operated by a foreign air carrier.
. The airplane complies with Stage 2 noise levels and is operated by a foreign operator other than for the purpose of foreign air commerce.
. The airplane complies with Stage 2 noise levels and—
.. On November 5, 1990, was owned by:
... A corporation, trust, or partnership organized under the laws of the United States or any State (including individual States, territories, possessions, and the District of Columbia);
... An individual who is a citizen of the United States; or
... An entity owned or controlled by a corporation, trust, partnership, or individual described in paragraph (f)(1) (i) or (ii) of this section; and
.. Enters into the United States not later than 6 months after the expiration of a lease agreement (including any extensions thereof) between an owner described in paragraph (f)(1) of this section and a foreign airline.
. The airplane complies with Stage 2 noise levels and was purchased by the importer under a written contract executed before November 5, 1990.
. Any Stage 2 airplane described in this section is eligible for operation in the contiguous United States only as provided under § 91.865 or 91.867.

## § 91.857

### Stage 2 operations outside of the 48 contiguous United States.

An operator of a Stage 2 airplane that is operating only between points outside the contiguous United States on or after November 5, 1990, must include in its operations specifications a statement that such airplane may not be used to provide air transportation to or from any airport in the contiguous United States.

## § 91.858

### Special flight authorizations for non-revenue Stage 2 operations.

. After December 31, 1999, any operator of a Stage 2 airplane over 75,000 pounds may operate that airplane in nonrevenue service in the contiguous United States only for the following purposes:
.. Sell, lease, or scrap the airplane;
.. Obtain modifications to meet Stage 3 noise levels;
.. Obtain scheduled heavy maintenance or significant modifications;
.. Deliver the airplane to a lessee or return it to a lessor;
.. Park or store the airplane; and
.. Prepare the airplane for any of the purposes listed in paragraph (a)(1) thru (a)(5) of this section.
. An operator of a Stage 2 airplane that needs to operate in the contiguous United States for any of the purposes listed above may apply to FAA's Office of Environment and Energy for a special flight authorization. The applicant must file in advance. Applications are due 30 days in advance of the planned flight and must provide the information necessary for the FAA to determine that the planned flight is within the limits prescribed in the law.

## § 91.859

### Modification to meet Stage 3 or Stage 4 noise levels.

For an airplane subject to § 91.801(c) of this subpart and otherwise prohibited from operation to or from an airport in the contiguous United States by § 91.855, any person may apply for a special flight authorization for that airplane to operate in the contiguous United States for the purpose of obtaining modifications to meet Stage 3 or Stage 4 noise levels.

## § 91.861

### Base level.

. *U.S. Operators.* The base level of a U.S. operator is equal to the number of owned or leased Stage 2 airplanes subject to § 91.801(c) of this subpart that were listed on that operator's operations specifications for operations to or from airports in the contiguous United States on any one day selected by the operator during the period January 1, 1990, through July 1, 1991, plus or minus adjustments made pursuant to paragraphs (a) (1) and (2).
.. The base level of a U.S. operator shall be increased by a number equal to the total of the following—
... The number of Stage 2 airplanes returned to service in the United States pursuant to § 91.855(f);
... The number of Stage 2 airplanes purchased pursuant to § 91.855(g); and
... Any U.S. operator base level acquired with a Stage 2 airplane transferred from another person under § 91.863.
.. The base level of a U.S. operator shall be decreased by the amount of U.S. operator base level transferred with the corresponding number of Stage 2 airplanes to another person under § 91.863.
. Foreign air carriers. The base level of a foreign air carrier is equal to the number of owned or leased Stage 2 airplanes that were listed on that carrier's U.S. operations specifications on any one day during the period January 1, 1990, through July 1, 1991, plus or minus any adjustments to the base levels made pursuant to paragraphs (b) (1) and (2).
.. The base level of a foreign air carrier shall be increased by the amount of foreign air carrier base level acquired with a Stage 2 airplane from another person under § 91.863.
.. The base level of a foreign air carrier shall be decreased by the amount of foreign air carrier base level transferred with a Stage 2 airplane to another person under § 91.863.
. New entrants do not have a base level.

## § 91.863

### Transfers of Stage 2 airplanes with base level.

. Stage 2 airplanes may be transferred with or without the corresponding amount of base level. Base level may not be transferred without the corresponding number of Stage 2 airplanes.
. No portion of a U.S. operator's base level established under § 91.861(a) may be used for operations by a foreign air carrier. No portion of a foreign air carrier's base level established under § 91.861(b) may be used for operations by a U.S. operator.
. Whenever a transfer of Stage 2 airplanes with base level occurs, the transferring and acquiring parties shall, within 10 days, jointly submit written notification of the transfer to the FAA, Office of Environment and Energy. Such notification shall state:
.. The names of the transferring and acquiring parties;
.. The name, address, and telephone number of the individual responsible for submitting the notification on behalf of the transferring and acquiring parties;
.. The total number of Stage 2 airplanes transferred, listed by airplane type, model, series, and serial number;
.. The corresponding amount of base level transferred and whether it is U.S. operator or foreign air carrier base level; and
.. The effective date of the transaction.
. If, taken as a whole, a transaction or series of transactions made pursuant to this section does not produce an increase or decrease in the number of Stage 2 airplanes for either the acquiring or transferring operator, such transaction or series of transactions may not be used to establish compliance with the requirements of § 91.865.

## § 91.865

### Phased compliance for operators with base level.

Except as provided in paragraph (a) of this section, each operator that operates an airplane under part 91, 121, 125, 129, or 135 of this chapter, regardless of the national registry of the airplane, shall comply with paragraph (b) or (d) of this section at each interim compliance date with regard to its subsonic airplane fleet covered by § 91.801(c) of this subpart.

. This section does not apply to new entrants covered by § 91.867 or to foreign operators not engaged in foreign air commerce.
. Each operator that chooses to comply with this paragraph pursuant to any interim compliance requirement shall reduce the number of Stage 2 airplanes it operates that are eligible for operation in the contiguous United States to a maximum of:
.. After December 31, 1994, 75 percent of the base level held by the operator;
.. After December 31, 1996, 50 percent of the base level held by the operator;
.. After December 31, 1998, 25 percent of the base level held by the operator.
. Except as provided under § 91.871, the number of Stage 2 airplanes that must be reduced at each compliance date contained in paragraph (b) of this section shall be determined by reference to the amount of base level held by the operator on that compliance date, as calculated under § 91.861.
. Each operator that chooses to comply with this paragraph pursuant to any interim compliance requirement shall operate a fleet that consists of:
.. After December 31, 1994, not less than 55 percent Stage 3 airplanes;
.. After December 31, 1996, not less than 65 percent Stage 3 airplanes;
.. After December 31, 1998, not less than 75 percent Stage 3 airplanes.
. Calculations resulting in fractions may be rounded to permit the continued operation of the next whole number of Stage 2 airplanes.

## § 91.867

### Phased compliance for new entrants.

. New entrant U.S. air carriers.
.. A new entrant initiating operations under part 121 of this chapter on or before December 31, 1994, may initiate service without regard to the percentage of its fleet composed of Stage 3 airplanes.
.. After December 31, 1994, at least 25 percent of the fleet of a new entrant must comply with Stage 3 noise levels.
.. After December 31, 1996, at least 50 percent of the fleet of a new entrant must comply with Stage 3 noise levels.
.. After December 31, 1998, at least 75 percent of the fleet of a new entrant must comply with Stage 3 noise levels.
. New entrant foreign air carriers.
.. A new entrant foreign air carrier initiating part 129 operations on or before December 31, 1994, may initiate service without regard to the percentage of its fleet composed of Stage 3 airplanes.
.. After December 31, 1994, at least 25 percent of the fleet on U.S. operations specifications of a new entrant foreign air carrier must comply with Stage 3 noise levels.
.. After December 31, 1996, at least 50 percent of the fleet on U.S. operations specifications of a new entrant foreign air carrier must comply with Stage 3 noise levels.
.. After December 31, 1998, at least 75 percent of the fleet on U.S. operations specifications of a new entrant foreign air carrier must comply with Stage 3 noise levels.
. Calculations resulting in fractions may be rounded to permit the continued operation of the next whole number of Stage 2 airplanes.

## § 91.869

### Carry-forward compliance.

. Any operator that exceeds the requirements of paragraph (b) of § 91.865 of this part on or before December 31, 1994, or on or before December 31, 1996, may claim a credit that may be applied at a subsequent interim compliance date.
. Any operator that eliminates or modifies more Stage 2 airplanes pursuant to § 91.865(b) than required as of December 31, 1994, or December 31, 1996, may count the number of additional Stage 2 airplanes reduced as a credit toward—
.. The number of Stage 2 airplanes it would otherwise be required to reduce following a subsequent interim compliance date specified in § 91.865(b); or
.. The number of Stage 3 airplanes it would otherwise be required to operate in its fleet following a subsequent interim compliance date to meet the percentage requirements specified in § 91.865(d).

## § 91.871

### Waivers from interim compliance requirements.

. Any U.S. operator or foreign air carrier subject to the requirements of § 91.865 or 91.867 of this subpart may request a waiver from any individual compliance requirement.
. Applications must be filed with the Secretary of Transportation at least 120 days prior to the compliance date from which the waiver is requested.
. Applicants must show that a grant of waiver would be in the public interest, and must include in its application its plans and activities for modifying its fleet, including evidence of good faith efforts to comply with the requirements of § 91.865 or § 91.867. The application should contain all information the applicant considers relevant, including, as appropriate, the following:
.. The applicant's balance sheet and cash flow positions;
              
.. The composition of the applicant's current fleet; and
.. The applicant's delivery position with respect to new airplanes or noise-abatement equipment.
. Waivers will be granted only upon a showing by the applicant that compliance with the requirements of § 91.865 or 91.867 at a particular interim compliance date is financially onerous, physically impossible, or technologically infeasible, or that it would have an adverse effect on competition or on service to small communities.
. The conditions of any waiver granted under this section shall be determined by the circumstances presented in the application, but in no case may the term extend beyond the next interim compliance date.
. A summary of any request for a waiver under this section will be published in the *Federal Register,* and public comment will be invited. Unless the Secretary finds that circumstances require otherwise, the public comment period will be at least 14 days.

## § 91.873

### Waivers from final compliance.

. A U.S. air carrier or a foreign air carrier may apply for a waiver from the prohibition contained in § 91.853 of this part for its remaining Stage 2 airplanes, provided that, by July 1, 1999, at least 85 percent of the airplanes used by the carrier to provide service to or from an airport in the contiguous United States will comply with the Stage 3 noise levels.
. An application for the waiver described in paragraph (a) of this section must be filed with the Secretary of Transportation no later than January 1, 1999, or, in the case of a foreign air carrier, no later than April 20, 2000. Such application must include a plan with firm orders for replacing or modifying all airplanes to comply with Stage 3 noise levels at the earliest practicable time.
. To be eligible to apply for the waiver under this section, a new entrant U.S. air carrier must initiate service no later than January 1, 1999, and must comply fully with all provisions of this section.
. The Secretary may grant a waiver under this section if the Secretary finds that granting such waiver is in the public interest. In making such a finding, the Secretary shall include consideration of the effect of granting such waiver on competition in the air carrier industry and the effect on small community air service, and any other information submitted by the applicant that the Secretary considers relevant.
. The term of any waiver granted under this section shall be determined by the circumstances presented in the application, but in no case will the waiver permit the operation of any Stage 2 airplane covered by this subchapter in the contiguous United States after December 31, 2003.
. A summary of any request for a waiver under this section will be published in the *Federal Register,* and public comment will be invited. Unless the secretary finds that circumstances require otherwise, the public comment period will be at least 14 days.

## § 91.875

### Annual progress reports.

. Each operator subject to § 91.865 or § 91.867 of this chapter shall submit an annual report to the FAA, Office of Environment and Energy, on the progress it has made toward complying with the requirements of that section. Such reports shall be submitted no later than 45 days after the end of a calendar year. All progress reports must provide the information through the end of the calendar year, be certified by the operator as true and complete (under penalty of 18 U.S.C. 1001), and include the following information:
.. The name and address of the operator;
.. The name, title, and telephone number of the person designated by the operator to be responsible for ensuring the accuracy of the information in the report;
.. The operator's progress during the reporting period toward compliance with the requirements of § 91.853, § 91.865 or § 91.867. For airplanes on U.S. operations specifications, each operator shall identify the airplanes by type, model, series, and serial number.
... Each Stage 2 airplane added or removed from operation or U.S. operations specifications (grouped separately by those airplanes acquired with and without base level);
... Each Stage 2 airplane modified to Stage 3 noise levels (identifying the manufacturer and model of noise abatement retrofit equipment;
... Each Stage 3 airplane on U.S. operations specifications as of the last day of the reporting period; and
... For each Stage 2 airplane transferred or acquired, the name and address of the recipient or transferor; and, if base level was transferred, the person to or from whom base level was transferred or acquired pursuant to Section 91.863 along with the effective date of each base level transaction, and the type of base level transferred or acquired.
. Each operator subject to § 91.865 or § 91.867 of this chapter shall submit an initial progress report covering the period from January 1, 1990, through December 31, 1991, and provide:
.. For each operator subject to § 91.865:
... The date used to establish its base level pursuant to § 91.861(a); and
... A list of those Stage 2 airplanes (by type, model, series and serial number) in its base level, including adjustments made pursuant to § 91.861 after the date its base level was established.
.. For each U.S. operator:
... A plan to meet the compliance schedules in § 91.865 or § 91.867 and the final compliance date of § 91.853, including the schedule for delivery of replacement Stage 3 airplanes or the installation of noise abatement retrofit equipment; and
... A separate list (by type, model, series, and serial number) of those airplanes included in the operator's base level, pursuant to § 91.861(a)(1) (i) and (ii), under the categories “returned” or “purchased,” along with the date each was added to its operations specifications.
. Each operator subject to § 91.865 or § 91.867 of this chapter shall submit subsequent annual progress reports covering the calendar year preceding the report and including any changes in the information provided in paragraphs (a) and (b) of this section; including the use of any carry-forward credits pursuant to § 91.869.
. An operator may request, in any report, that specific planning data be considered proprietary.
. If an operator's actions during any reporting period cause it to achieve compliance with § 91.853, the report should include a statement to that effect. Further progress reports are not required unless there is any change in the information reported pursuant to paragraph (a) of this section.
. For each U.S. operator subject to § 91.865, progress reports submitted for calendar years 1994, 1996, and 1998, shall also state how the operator achieved compliance with the requirements of that section, i.e.—
.. By reducing the number of Stage 2 airplanes in its fleet to no more than the maximum permitted percentage of its base level under § 91.865(b), or
.. By operating a fleet that consists of at least the minimum required percentage of Stage 3 airplanes under § 91.865(d).

## § 91.877

### Annual reporting of Hawaiian operations.

. Each air carrier or foreign air carrier subject to § 91.865 or § 91.867 of this part that conducts operations between the contiguous United States and the State of Hawaii, between the State of Hawaii and any point outside of the contiguous United States, or between the islands of Hawaii in turnaround service, on or since November 5, 1990, shall include in its annual report the information described in paragraph (c) of this section.
. Each air carrier or foreign air carrier not subject to § 91.865 or § 91.867 of this part that conducts operations between the contiguous U.S. and the State of Hawaii, between the State of Hawaii and any point outside of the contiguous United States, or between the islands of Hawaii in turnaround service, on or since November 5, 1990, shall submit an annual report to the FAA, Office of Environment and Energy, on its compliance with the Hawaiian operations provisions of 49 U.S.C. 47528. Such reports shall be submitted no later than 45 days after the end of a calendar year. All progress reports must provide the information through the end of the calendar year, be certified by the operator as true and complete (under penalty of 18 U.S.C. 1001), and include the following information—
.. The name and address of the air carrier or foreign air carrier;
.. The name, title, and telephone number of the person designated by the air carrier or foreign air carrier to be responsible for ensuring the accuracy of the information in the report; and
.. The information specified in paragraph (c) of this section.
. The following information must be included in reports filed pursuant to this section—
.. For operations conducted between the contiguous United States and the State of Hawaii—
... The number of Stage 2 airplanes used to conduct such operations as of November 5, 1990;
... Any change to that number during the calendar year being reported, including the date of such change;
.. For air carriers that conduct inter-island turnaround service in the State of Hawaii—
... The number of Stage 2 airplanes used to conduct such operations as of November 5, 1990;
... Any change to that number during the calendar year being reported, including the date of such change;
... For an air carrier that provided inter-island trunaround service within the state of Hawaii on November 5, 1990, the number reported under paragraph (c)(2)(i) of this section may include all Stage 2 airplanes with a maximum certificated takeoff weight of more than 75,000 pounds that were owned or leased by the air carrier on November 5, 1990, regardless of whether such airplanes were operated by that air carrier or foreign air carrier on that date.
.. For operations conducted between the State of Hawaii and a point outside the contiguous United States—
... The number of Stage 2 airplanes used to conduct such operations as of November 5, 1990; and
... Any change to that number during the calendar year being reported, including the date of such change.
. Reports or amended reports for years predating this regulation are required to be filed concurrently with the next annual report.

## §§ 91.879-91.880

### Reserved

## § 91.881

### Final compliance: Civil subsonic jet airplanes weighing 75,000 pounds or less.

Except as provided in § 91.883, after December 31, 2015, a person may not operate to or from an airport in the contiguous United States a civil subsonic jet airplane subject to § 91.801(e) of this subpart unless that airplane has been shown to comply with Stage 3 noise levels.

## § 91.883

### Special flight authorizations for jet airplanes weighing 75,000 pounds or less.

. After December 31, 2015, an operator of a jet airplane weighing 75,000 pounds or less that does not comply with Stage 3 noise levels may, when granted a special flight authorization by the FAA, operate that airplane in the contiguous United States only for one of the following purposes:
.. To sell, lease, or use the airplane outside the 48 contiguous States;
.. To scrap the airplane;
.. To obtain modifications to the airplane to meet Stage 3 noise levels;
.. To perform scheduled heavy maintenance or significant modifications on the airplane at a maintenance facility located in the contiguous 48 States;
.. To deliver the airplane to an operator leasing the airplane from the owner or return the airplane to the lessor;
.. To prepare, park, or store the airplane in anticipation of any of the activities described in paragraphs (a)(1) through (a)(5) of this section;
.. To provide transport of persons and goods in the relief of an emergency situation; or
              
.. To divert the airplane to an alternative airport in the 48 contiguous States on account of weather, mechanical, fuel, air traffic control, or other safety reasons while conducting a flight in order to perform any of the activities described in paragraphs (a)(1) through (a)(7) of this section.
. An operator of an affected airplane may apply for a special flight authorization for one of the purposes listed in paragraph (a) of this section by filing an application with the FAA's Office of Environment and Energy. Except for emergency relief authorizations sought under paragraph (a)(7) of this section, applications must be filed at least 30 days in advance of the planned flight. All applications must provide the information necessary for the FAA to determine that the planned flight is within the limits prescribed in the law.

## §§ 91.884-91.899

### Reserved

