# EXPENDITURE OF FEDERAL FUNDS FOR NONMILITARY AIRPORTS OR AIR NAVIGATION FACILITIES THEREON
:toc:

## § 169.1 - Applicability.

[loweralpha]
. This part prescribes the requirements for issuing a written recommendation and certification that a proposed project is reasonably necessary for use in air commerce or in the interests of national defense. The first two sentences of section 308(a) of the Federal Aviation Act of 1958 (49 U.S.C. 1349(a)): (1) Require such a recommendation and certification where Federal funds are to be expended for nonmilitary purposes for airports or air navigation facilities thereon; and (2) provide that any interested person may apply to the Administrator, under regulations prescribed by him, for a recommendation and certification.
. This part does not apply to projects for the expenditure of Federal funds for military purposes or for airports, or air navigation facilities thereon, operated by the Federal Aviation Administration.

## § 169.3 - Application for recommendation and certification.

[loweralpha]
. Any interested person may apply to the Administrator for a recommendation and certification with respect to a proposed project for the acquisition, establishment, construction, alteration, repair, maintenance, or operation of an airport or an air navigation facility thereon by or in his interests, on which Federal funds are proposed to be expended for nonmilitary purposes. The application shall be filed with the Regional Airports Division or Airports District Office, whichever is appropriate, in whose geographical area the airport is located. The application must state—
[arabic]
.. The name and address of the applicant, the owner of the airport, and the individual responsible for its operation and maintenance, and the interest of the applicant in the matter;
.. The location of the airport, and of any air navigation facilities thereon;
.. A technical description of the project;
.. The information contained in the notice required by § 157.3 of this chapter; and
.. All available pertinent data relating to the necessity of the airport or air navigation facility for use in air commerce including where applicable—
[lowerroman]
... The number and type of aircraft that use or would use the airport or facility;
... The present and expected level of activity;
... Any special use of the airport or facility such as its providing access to places of recreation as national forests or parks or to isolated communities where access by other means is not available or is curtailed by climatic condition; and
... In the case of an airport or air navigation facility owned, operated, or maintained by a Federal agency other than the FAA, the relationship of the airport or facility to the performance of that agency's functions.
. Each of the following has the effect of a recommendation and certification, and a separate application under this part with respect thereto is not required:
[arabic]
.. Approval of a project under section 16 of the Airport and Airway Development Act of 1970 (49 U.S.C. 1701).
.. Inclusion of an airport in the National Airport System Plan, if—
[lowerroman]
... Notice of construction or alteration required by § 157.3 of this chapter has been given; and
... The Administrator has determined that there is no objection to the proposed construction or alteration.

## § 169.5 - FAA determination.

[loweralpha]
. The Administrator issues a recommendation and certification if he finds that the airport or facility is reasonably necessary for use in air commerce or in the interests of national defense; that it conforms to all applicable plans and policies for, and allocations of, airspace; and that it otherwise complies with requirements of Federal law properly considered by the Administrator. The Administrator may grant the recommendation and certification subject to conditions that ensure conformity of the airport or facility with these standards.
. A recommendation and certification under this part, express or implied, does not extend to a modified version of an airport or facility to which it applies, or to an additional area or facility at the same airport.
. If the application is denied the Administrator notifies the applicant of the grounds for the denial. The Administrator may revoke a recommendation and certification for proper cause.
. The authority of the Administrator under this part is exercised by Regional Airports Division Managers as to airports or facilities within their respective regions.

