# Part 119 Certificate Holders Authorized To Conduct Operations under Part 121 or Part 135 or Operators Under § 91.147 of This Chapter and Safety-Sensitive Employees
:toc:

## § 120.31 - Prohibited drugs.

[loweralpha]
. Each certificate holder or operator shall provide each employee performing a function listed in subpart E of this part, and his or her supervisor, with the training specified in that subpart.
. No certificate holder or operator may use any contractor to perform a function listed in subpart E of this part unless that contractor provides each of its employees performing that function for the certificate holder or operator, and his or her supervisor, with the training specified in that subpart.

## § 120.33 - Use of prohibited drugs.

[loweralpha]
. This section applies to individuals who perform a function listed in subpart E of this part for a certificate holder or operator. For the purpose of this section, an individual who performs such a function pursuant to a contract with the certificate holder or the operator is considered to be performing that function for the certificate holder or the operator.
. No certificate holder or operator may knowingly use any individual to perform, nor may any individual perform for a certificate holder or an operator, either directly or by contract, any function listed in subpart E of this part while that individual has a prohibited drug, as defined in this part, in his or her system.
. No certificate holder or operator shall knowingly use any individual to perform, nor shall any individual perform for a certificate holder or operator, either directly or by contract, any safety-sensitive function if that individual has a verified positive drug test result on, or has refused to submit to, a drug test required by subpart E of this part and the individual has not met the requirements of that subpart for returning to the performance of safety-sensitive duties.

## § 120.35 - Testing for prohibited drugs.

[loweralpha]
. Each certificate holder or operator shall test each of its employees who perform a function listed in subpart E of this part in accordance with that subpart.
. Except as provided in paragraph (c) of this section, no certificate holder or operator may use any contractor to perform a function listed in subpart E of this part unless that contractor tests each employee performing such a function for the certificate holder or operator in accordance with that subpart.
. If a certificate holder conducts an on-demand operation into an airport at which no maintenance providers are available that are subject to the requirements of subpart E of this part and emergency maintenance is required, the certificate holder may use individuals not meeting the requirements of paragraph (b) of this section to provide such emergency maintenance under both of the following conditions:
[arabic]
.. The certificate holder must give written notification of the emergency maintenance to the Drug Abatement Program Division, AAM-800, 800 Independence Avenue, SW., Washington, DC 20591, within 10 days after being provided same in accordance with this paragraph. A certificate holder must retain copies of all such written notifications for two years.
.. The aircraft must be reinspected by maintenance personnel who meet the requirements of paragraph (b) of this section when the aircraft is next at an airport where such maintenance personnel are available.
. For purposes of this section, emergency maintenance means maintenance that—
[arabic]
.. Is not scheduled and
.. Is made necessary by an aircraft condition not discovered prior to the departure for that location.

## § 120.37 - Misuse of alcohol.

[loweralpha]
. *General.* This section applies to covered employees who perform a function listed in subpart F of this part for a certificate holder. For the purpose of this section, an individual who meets the definition of covered employee in subpart F of this part is considered to be performing the function for the certificate holder.
. *Alcohol concentration.* No covered employee shall report for duty or remain on duty requiring the performance of safety-sensitive functions while having an alcohol concentration of 0.04 or greater. No certificate holder having actual knowledge that an employee has an alcohol concentration of 0.04 or greater shall permit the employee to perform or continue to perform safety-sensitive functions.
. *On-duty use.* No covered employee shall use alcohol while performing safety-sensitive functions. No certificate holder having actual knowledge that a covered employee is using alcohol while performing safety-sensitive functions shall permit the employee to perform or continue to perform safety-sensitive functions.
. *Pre-duty use.*
[arabic]
.. No covered employee shall perform flight crewmember or flight attendant duties within 8 hours after using alcohol. No certificate holder having actual knowledge that such an employee has used alcohol within 8 hours shall permit the employee to perform or continue to perform the specified duties.
.. No covered employee shall perform safety-sensitive duties other than those specified in paragraph (d)(1) of this section within 4 hours after using alcohol. No certificate holder having actual knowledge that such an employee has used alcohol within 4 hours shall permit the employee to perform or to continue to perform safety-sensitive functions.
. *Use following an accident.* No covered employee who has actual knowledge of an accident involving an aircraft for which he or she performed a safety-sensitive function at or near the time of the accident shall use alcohol for 8 hours following the accident, unless he or she has been given a post-accident test under subpart F of this part, or the employer has determined that the employee's performance could not have contributed to the accident.
. *Refusal to submit to a required alcohol test.* A covered employee must not refuse to submit to any alcohol test required under subpart F of this part. A certificate holder must not permit an employee who refuses to submit to such a test to perform or continue to perform safety-sensitive functions.

## § 120.39 - Testing for alcohol.

[loweralpha]
. Each certificate holder must establish an alcohol testing program in accordance with the provisions of subpart F of this part.
. Except as provided in paragraph (c) of this section, no certificate holder or operator may use any individual who meets the definition of covered employee in subpart A of this part to perform a safety-sensitive function listed in that subpart F of this part unless that individual is subject to testing for alcohol misuse in accordance with the provisions of that subpart.
              
. If a certificate holder conducts an on-demand operation into an airport at which no maintenance providers are available that are subject to the requirements of subpart F of this part and emergency maintenance is required, the certificate holder may use individuals not meeting the requirements of paragraph (b) of this section to provide such emergency maintenance under both of the following conditions:
[arabic]
.. The certificate holder must give written notification of the emergency maintenance to the Drug Abatement Program Division, AAM-800, 800 Independence Avenue, SW., Washington, DC 20591, within 10 days after being provided same in accordance with this paragraph. A certificate holder must retain copies of all such written notifications for two years.
.. The aircraft must be reinspected by maintenance personnel who meet the requirements of paragraph (b) of this section when the aircraft is next at an airport where such maintenance personnel are available.
. For purposes of this section, emergency maintenance means maintenance that—
[arabic]
.. Is not scheduled and
.. Is made necessary by an aircraft condition not discovered prior to the departure for that location.

