# General
:toc:

## § 158.1

### Applicability.

This part applies to passenger facility charges (PFC's) as may be approved by the Administrator of the Federal Aviation Administration (FAA) and imposed by a public agency that controls a commercial service airport. This part also describes the procedures for reducing funds to a large or medium hub airport that imposes a PFC.

## § 158.3

### Definitions.

The following definitions apply in this part:

*Airport* means any area of land or water, including any heliport, that is used or intended to be used for the landing and takeoff of aircraft, and any appurtenant areas that are used or intended to be used for airport buildings or other airport facilities or rights-of-way, together with all airport buildings and facilities located thereon.

*Airport capital plan* means a capital improvement program that lists airport-related planning, development or noise compatibility projects expected to be accomplished with anticipated available funds.

*Airport layout plan (ALP)* means a plan showing the existing and proposed airport facilities and boundaries in a form prescribed by the Administrator.

*Airport revenue* means revenue generated by a public airport (1) through any lease, rent, fee, PFC or other charge collected, directly or indirectly, in connection with any aeronautical activity conducted on an airport that it controls; or (2) In connection with any activity conducted on airport land acquired with Federal financial assistance, or with PFC revenue under this part, or conveyed to such public agency under the provisions of any Federal surplus property program or any provision enacted to authorize the conveyance of Federal property to a public agency for airport purposes.

*Air travel ticket* includes all documents, electronic records, boarding passes, and any other ticketing medium about a passenger's itinerary necessary to transport a passenger by air, including passenger manifests.

*Allowable cost* means the reasonable and necessary costs of carrying out an approved project including costs incurred prior to and subsequent to the approval to impose a PFC, and making payments for debt service on bonds and other indebtedness incurred to carry out such projects. Allowable costs include only those costs incurred on or after November 5, 1990. Costs of terminal development incurred after August 1, 1986, at an airport that did not have more than .25 percent of the total annual passenger boardings in the U.S. in the most recent calendar year for which data is available and at which total passenger boardings declined by at least 16 percent between calendar year 1989 and calendar year 1997 are allowable.

*Approved project* means a project for which the FAA has approved using PFC revenue under this part. The FAA may also approve specific projects contained in a single or multi-phased project or development described in an airport capital plan separately. This includes projects acknowledged by the FAA under § 158.30 of this part.

*Bond financing costs* means the costs of financing a bond and includes such costs as those associated with issuance, underwriting discount, original issue discount, capitalized interest, debt service reserve funds, initial credit enhancement costs, and initial trustee and paying agent fees.

*Charge effective date* means the date on which carriers are obliged to collect a PFC.

*Charge expiration date* means the date on which carriers are to cease to collect a PFC.

*Collecting carrier* means an issuing carrier or other carrier collecting a PFC, whether or not such carrier issues the air travel ticket.

*Collection* means the acceptance of payment of a PFC from a passenger.

*Commercial service airport* means a public airport that annually enplanes 2,500 or more passengers and receives scheduled passenger service of aircraft.

*Covered air carrier* means an air carrier that files for bankruptcy protection or has an involuntary bankruptcy proceeding started against it after December 12, 2003. An air carrier that is currently in compliance with PFC remittance requirements and has an involuntary bankruptcy proceeding commenced against it has 90 days from the date such proceeding was filed to obtain dismissal of the involuntary petition before becoming a covered air carrier. An air carrier ceases to be a covered air carrier when it emerges from bankruptcy protection.

*Covered airport* means a medium or large hub airport at which one or two air carriers control more than 50 percent of passenger boardings.

*Debt service* means payments for such items as principal and interest, sinking funds, call premiums, periodic credit enhancement fees, trustee and paying agent fees, coverage, and remarketing fees.

*Exclusive long-term lease or use agreement* means an exclusive lease or use agreement between a public agency and an air carrier or foreign air carrier with a term of 5 years or more.

*FAA Airports office* means a regional, district or field office of the Federal Aviation Administration that administers Federal airport-related matters.

*Financial need* means that a public agency cannot meet its operational or debt service obligations and does not have at least a 2-month capital reserve fund.

*Frequent flier award coupon* means a zero-fare award of air transportation that an air carrier or foreign air carrier provides to a passenger in exchange for accumulated travel mileage credits in a customer loyalty program, whether or not the term “frequent flier” is used in the definition of that program. The definition of “frequent flier award coupon” does not extend to redemption of accumulated credits for awards of additional or upgraded service on trips for which the passenger has paid a published fare, “two-for-the-price-of-one” and similar marketing programs, or to air transportation purchased for a passenger by other parties.

*Ground support equipment* means service and maintenance equipment used at an airport to support aeronautical operations and related activities. Baggage tugs, belt loaders, cargo loaders, forklifts, fuel trucks, lavatory trucks, and pushback tractors are among the types of vehicles that fit this definition.

*Implementation of an approved project* means: (1) With respect to construction, issuance to a contractor of notice to proceed or the start of physical construction; (2) with respect to nonconstruction projects other than property acquisition, commencement of work by a contractor or public agency to carry out the statement of work; or (3) with respect to property acquisition projects, commencement of title search, surveying, or appraisal for a significant portion of the property to be acquired.

*Issuing carrier* means any air carrier or foreign air carrier that issues an air travel ticket or whose imprinted ticket stock is used in issuing such ticket by an agent.

*Medium or large hub airport* means a commercial service airport that has more than 0.25 percent of the total number of passenger boardings at all such airports in the U.S. for the prior calendar year, as determined by the Administrator.

*Non-hub airport* means a commercial service airport (as defined in 49 U.S.C. 47102) that has less than 0.05 percent of the passenger boardings in the U.S. in the prior calendar year on an aircraft in service in air commerce.

*Nonrevenue passenger* means a passenger receiving air transportation from an air carrier or foreign air carrier for which remuneration is not received by the air carrier or foreign air carrier as defined under Department of Transportation Regulations or as otherwise determined by the Administrator. Air carrier employees or others receiving air transportation against whom token service charges are levied are considered nonrevenue passengers. Infants for whom a token fare is charged are also considered nonrevenue passengers.

*Notice of intent (to impose or use PFC revenue)* means a notice under § 158.30 from a public agency controlling a non-hub airport that it intends to impose a PFC and/or use PFC revenue. Except for §§ 158.25 through 30, “notice of intent” can be used interchangeably with “application.”

*One-way trip* means any trip that is not a round trip.

*Passenger enplaned* means a domestic, territorial or international revenue passenger enplaned in the States in scheduled or nonscheduled service on aircraft in intrastate, interstate, or foreign commerce.

*PFC* means a passenger facility charge covered by this part imposed by a public agency on passengers enplaned at a commercial service airport it controls.

*PFC administrative support costs* means the reasonable and necessary costs of developing a PFC application or amendment, issuing and maintaining the required PFC records, and performing the required audit of the public agency's PFC account. These costs may include reasonable monthly financial account charges and transaction fees.

*Project* means airport planning, airport land acquisition or development of a single project, a multi-phased development program, (including but not limited to development described in an airport capital plan) or a new airport for which PFC financing is sought or approved under this part.

*Public agency* means a State or any agency of one or more States; a municipality or other political subdivision of a State; an authority created by Federal, State or local law; a tax-supported organization; an Indian tribe or pueblo that controls a commercial service airport; or for the purposes of this part, a private sponsor of an airport approved to participate in the Pilot Program on Private Ownership of Airports.

*Round trip* means a trip on a complete air travel itinerary which terminates at the origin point.

*Significant business interest* means an air carrier or foreign air carrier that:

(1) Had no less than 1.0 percent of passenger boardings at that airport in the prior calendar year,

(2) Had at least 25,000 passenger boardings at the airport in that prior calendar year, or

(3) Provides scheduled service at that airport.

*State* means a State of the United States, the District of Columbia, the Commonwealth of Puerto Rico, the Virgin Islands, American Samoa, the Commonwealth of the Northern Mariana Islands, and Guam.

*Unliquidated PFC revenue* means revenue received by a public agency from collecting carriers but not yet used on approved projects.

## § 158.5

### Authority to impose PFC's.

Subject to the provisions of this part, the Administrator may grant authority to a public agency that controls a commercial service airport to impose a PFC of $1, $2, $3, $4, or $4.50 on passengers enplaned at such an airport. No public agency may impose a PFC under this part unless authorized by the Administrator. No State or political subdivision or agency thereof that is not a public agency may impose a PFC covered by this part.

## § 158.7

### Exclusivity of authority.

. A State, political subdivision of a State, or authority of a State or political subdivision that is not the eligible public agency may not tax, regulate, prohibit, or otherwise attempt to control in any manner the imposition or collection of a PFC or the use of PFC revenue.
. No contract or agreement between an air carrier or foreign air carrier and a public agency may impair the authority of such public agency to impose a PFC or use the PFC revenue in accordance with this part.

## § 158.9

### Limitations.

. No public agency may impose a PFC on any passenger—
.. For more than 2 boardings on a one-way trip or in each direction of a round trip;
.. On any flight to an eligible point on an air carrier that receives essential air service compensation on that route. The Administrator makes available a list of carriers and eligible routes determined by the Department of Transportation for which PFC's may not be imposed under this section;
              
.. Who is a nonrevenue passenger or obtained the ticket for air transportation with a frequent flier award coupon;
.. On flights, including flight segments, between 2 or more points in Hawaii;
.. In Alaska aboard an aircraft having a certificated seating capacity of fewer than 60 passengers; or
.. Enplaning at an airport if the passenger did not pay for the air transportation that resulted in the enplanement due to Department of Defense charter arrangements and payments.
. No public agency may require a foreign airline that does not serve a point or points in the U.S. to collect a PFC from a passenger.

## § 158.11

### Public agency request not to require collection of PFC's by a class of air carriers or foreign air carriers or for service to isolated communities.

. Subject to the requirements of this part, a public agency may request that collection of PFC's not be required for—
.. Passengers enplaned by any class of air carrier or foreign air carrier if the number of passengers enplaned by the carriers in the class constitutes not more than one percent of the total number of passengers enplaned annually at the airport at which the fee is imposed; or
.. Passengers enplaned on a flight to an airport—
... That has fewer than 2,500 passenger boardings each year and receives scheduled passenger service; or
... In a community that has a population of less than 10,000 and is not connected by a land highway or vehicular way to the land-connected National Highway System within a State.
. The public agency may request this exclusion authority under paragraph (a)(1) or (a)(2) of this section or both.

## § 158.13

### Use of PFC revenue.

PFC revenue, including any interest earned after such revenue has been remitted to a public agency, may be used only to finance the allowable costs of approved projects at any airport the public agency controls.

. *Total cost.* PFC revenue may be used to pay all or part of the allowable cost of an approved project.
. *PFC administrative support costs.* Public agencies may use PFC revenue to pay for allowable administrative support costs. Public agencies must submit these costs as a separate project in each PFC application.
. *Maximum cost for certain low-emission technology projects.* If a project involves a vehicle or ground support equipment using low emission technology eligible under § 158.15(b), the FAA will determine the maximum cost that may be financed by PFC revenue. The maximum cost for a new vehicle is the incremental amount between the purchase price of a new low emission vehicle and the purchase price of a standard emission vehicle, or the cost of converting a standard emission vehicle to a low emission vehicle.
. *Bond-associated debt service and financing costs.* (1) Public agencies may use PFC revenue to pay debt service and financing costs incurred for a bond issued to carry out approved projects.
. *Exception providing for the use of PFC revenue to pay for debt service for non-eligible projects.* The FAA may authorize a public agency under § 158.18 to impose a PFC for payments for debt service on indebtedness incurred to carry out an airport project that is not eligible if the FAA determines that such use is necessary because of the financial need of the airport.
. *Combination of PFC revenue and Federal grant funds.* A public agency may combine PFC revenue and airport grant funds to carry out an approved project. These projects are subject to the record keeping and auditing requirements of this part, as well as the reporting, record keeping and auditing requirements imposed by the Airport and Airway Improvement Act of 1982 (AAIA).
. *Non-Federal share.* Public agencies may use PFC revenue to meet the non-Federal share of the cost of projects funded under the Federal airport grant program or the FAA “Program to Permit Cost-Sharing of Air Traffic Modernization Projects” under 49 U.S.C. 44517.
. *Approval of project following approval to impose a PFC.* The public agency may not use PFC revenue or interest earned thereon except on an approved project.

(2) If the public agency's bond documents require that PFC revenue be commingled in the general revenue stream of the airport and pledged for the benefit of holders of obligations, the FAA considers PFC revenue to have paid the costs covered in § 158.13(d)(1) if—

(i) An amount equal to the part of the proceeds of the bond issued to carry out approved projects is used to pay allowable costs of such projects; and

(ii) To the extent the PFC revenue collected in any year exceeds the debt service and financing costs on such bonds during that year, an amount equal to the excess is applied as required by § 158.39.

## § 158.15

### Project eligibility at PFC levels of $1, $2, or $3.

. To be eligible, a project must—
.. Preserve or enhance safety, security, or capacity of the national air transportation system;
.. Reduce noise or mitigate noise impacts resulting from an airport; or
.. Furnish opportunities for enhanced competition between or among air carriers.
. Eligible projects are any of the following projects—
.. Airport development eligible under subchapter I of chapter 471 of 49 U.S.C.;
.. Airport planning eligible under subchapter I of chapter 471 of 49 U.S.C.;
.. Terminal development as described in 49 U.S.C. 47110(d);
.. Airport noise compatibility planning as described in 49 U.S.C. 47505;
.. Noise compatibility measures eligible for Federal assistance under 49 U.S.C. 47504, without regard to whether the measures are approved under 49 U.S.C. 47504;
.. Construction of gates and related areas at which passengers are enplaned or deplaned and other areas directly related to the movement of passengers and baggage in air commerce within the boundaries of the airport. These areas do not include restaurants, car rental and automobile parking facilities, or other concessions. Projects required to enable added air service by an air carrier with less than 50 percent of the annual passenger boardings at an airport have added eligibility. Such projects may include structural foundations and floor systems, exterior building walls and load-bearing interior columns or walls, windows, door and roof systems, building utilities (including heating, air conditioning, ventilation, plumbing, and electrical service), and aircraft fueling facilities next to the gate;
.. A project approved under the FAA's “Program to Permit Cost-Sharing of Air Traffic Modernization Projects” under 49 U.S.C. 44517; or
.. If the airport is in an air quality nonattainment area (as defined by section 171(2) of the Clean Air Act (42 U.S.C. 7501(2)) or a maintenance area referred to in section 175A of such Act (42 U.S.C. 7505a), and the project will result in the airport receiving appropriate emission credits as described in 49 U.S.C. 47139, a project for:
... Converting vehicles eligible under § 158.15(b)(1) and ground support equipment powered by a diesel or gasoline engine used at a commercial service airport to low-emission technology certified or verified by the Environmental Protection Agency to reduce emissions or to use cleaner burning conventional fuels; or
... Acquiring for use at a commercial service airport vehicles eligible under § 158.15(b)(1) and, subject to § 158.13(c), ground support equipment that include low-emission technology or use cleaner burning fuels.
. An eligible project must be adequately justified to qualify for PFC funding.

## § 158.17

### Project eligibility at PFC levels of $4 or $4.50.

. A project for any airport is eligible for PFC funding at levels of $4 or $4.50 if—
.. The project meets the eligibility requirements of § 158.15;
.. The project costs requested for collection at $4 or $4.50 cannot be paid for from funds reasonably expected to be available for the programs referred to in 49 U.S.C. 48103; and
.. In the case of a surface transportation or terminal project, the public agency has made adequate provision for financing the airside needs of the airport, including runways, taxiways, aprons, and aircraft gates.
. In addition, a project for a medium or large airport is only eligible for PFC funding at levels of $4 or $4.50 if the project will make a significant contribution to improving air safety and security, increasing competition among air carriers, reducing current or anticipated congestion, or reducing the impact of aviation noise on people living near the airport.

## § 158.18

### Use of PFC revenue to pay for debt service for non-eligible projects.

. The FAA may authorize a public agency to impose a PFC to make payments for debt service on indebtedness incurred to carry out at the airport a project that is not eligible if the FAA determines it is necessary because of the financial need of the airport. The FAA defines financial need in § 158.3.
. A public agency may request authority to impose a PFC and use PFC revenue under this section using the PFC application procedures in § 158.25. The public agency must document its financial position and explain its financial recovery plan that uses all available resources.
. The FAA reviews the application using the procedures in § 158.27. The FAA will issue its decision on the public agency's request under § 158.29.

## § 158.19

### Requirement for competition plans.

. Beginning in fiscal year 2001, no public agency may impose a PFC with respect to a covered airport unless the public agency has submitted a written competition plan. This requirement does not apply to PFC authority approved prior to April 5, 2000.
. The Administrator will review any plan submitted under paragraph (a) of this section to ensure that it meets the requirements of 49 U.S.C. 47106(f) and periodically will review its implementation to ensure that each covered airport successfully implements its plan.

