# PROTECTION OF VOLUNTARILY SUBMITTED INFORMATION
:toc:

## § 193.1 - What does this part cover?

This part describes when and how the FAA protects from disclosure safety and security information that you submit voluntarily to the FAA. This part carries out 49 U.S.C. 40123, protection of voluntarily submitted information.

## § 193.3 - Definitions.

*Agency* means each authority of the Government of the United States, whether or not the agency is within or subject to review by another agency, but does not include—

[arabic]
. The Congress;
. The courts of the United States;
. The governments of the territories or possessions of the United States;
. The government of the District of Columbia;
. Court martial and military commissions.

*De-identified* means that the identity of the source of the information, and the names of persons have been removed from the information.

*Disclose* means to release information to a person other than another agency. Examples are disclosures under the Freedom of Information Act (5 U.S.C. 552), in rulemaking proceedings, in a press release, or to a party to a legal action.

*Information* includes data, reports, source, and other information. “Information” may be used to describe the whole or a portion of a submission of information.

*Summarized* means that individual incidents are not specifically described, but are presented in statistical or other general form.

*Voluntary* means that the information was not required to be submitted as part of a mandatory program, and was not submitted as a condition of doing business with the government. “Voluntarily-provided information” does not include information submitted as part of complying with statutory, regulatory, or contractual requirements, except that information submitted as part of complying with a voluntary program under this part is considered to be voluntarily provided.

## § 193.5 - How may I submit safety or security information and have it protected from disclosure?

[loweralpha]
. You may do so under a program under this part. The program may be developed based on your proposal, a proposal from another person, or a proposal developed by the FAA.
. You may be any person, including an individual, a company, or an organization.
. You may propose to develop a program under this part using either the notice procedure in § 193.11 or the no-notice procedure in § 193.13.
. If the FAA decides to protect the information that you propose to submit it issues an order designating the information as protected under this part.
. The FAA only issues an order designating information as protected if the FAA makes the findings in § 193.7.
. The designation may be for a program in which all similar persons may participate, or for a program in which only you submit information.
. Even if you receive protection from disclosure under this part, this part does not establish the extent to which the FAA may or may not use the information to take enforcement action. Limits on enforcement action applicable to a program under this part will be in another policy or rule.

## § 193.7 - What does it mean for the FAA to designate information as protected?

[loweralpha]
. *General.* When the FAA issues an order designating information as protected under this part, the FAA does not disclose the information except as provided in this part.
. *What findings does the FAA make before designating information as protected?* The FAA designates information as protected under this part when the FAA finds that—
[arabic]
.. The information is provided voluntarily;
.. The information is safety or security related;
.. The disclosure of the information would inhibit the voluntary provision of that type of information;
.. The receipt of that type of information aids in fulfilling the FAA's safety and security responsibilities; and
.. Withholding such information from disclosure, under the circumstances provided in this part, will be consistent with the FAA's safety and security responsibilities.
. *How will the FAA handle requests for information under the Freedom of Information Act (FOIA)?* The FAA does not disclose information that is designated as protected under this part in response to a FOIA request.
. *What if the FAA obtains from another source the same information I submit?* Only information received under a program under this part is protected from disclosure under this part. Information obtained by the FAA through another means is not protected under this part.
. *Sharing information with other agencies.* The FAA may provide information that you have submitted under this part to other agencies with safety or security responsibilities. The agencies are subject to the requirements of 49 U.S.C. 40123 regarding nondisclosure of information. The FAA will give the information to another agency only if, for each such request, the other agency provides the FAA with adequate assurance, in writing, that—
            
[arabic]
.. The agency has a safety or security need for the information, including the general nature of the need.
.. The agency will protect the information from disclosure as required in 49 U.S.C. 40123, this part, and the designation. This includes a commitment that the agency will mark the information as provided in the designation.
.. The agency will limit access to those with a need to know to carry out safety or security responsibilities.
. *What if the FAA receives a subpoena for the information I submit?* When the FAA receives a subpoena for information you have submitted under this part, the FAA contacts you to determine whether you object to disclosure of the information or you wish to participate in responding to the subpoena. If both you and the FAA determine that release of the information is appropriate, the information is released. Otherwise, the FAA will not release information designated as protected under this part unless ordered to do so by a court of competent jurisdiction.

## § 193.9 - Will the FAA ever disclose information that is designated as protected under this part?

The FAA discloses information that is designated as protected under this part when withholding it would not be consistent with the FAA's safety and security responsibilities, as follows:

[loweralpha]
. *Disclosure in all programs.*
[arabic]
.. The FAA may disclose de-identified, summarized information submitted under this part to explain the need for changes in policies and regulations. An example is the FAA publishing a notice of proposed rulemaking based on your information, and including a de-identified, summarized version of your information (and the information from other persons, if applicable) to explain the need for the notice of proposed rulemaking.
.. The FAA may disclose information provided under this part to correct a condition that compromises safety or security, if that condition continues uncorrected.
.. The FAA may disclose information provided under this part to carry out a criminal investigation or prosecution.
.. The FAA may disclose information provided under this part to comply with 49 U.S.C. 44905, regarding information about threats to civil aviation.
. *Additional disclosures.* For each program, the FAA may find that there are additional circumstances under which withholding information provided under this part would not be consistent with the FAA's safety and security responsibilities. Those circumstances are described in the designation for that program.

## § 193.11 - What is the notice procedure?

This section states the notice procedure for the FAA to designate information as protected under this part. This procedure is used when there is not an immediate safety or security need for the information. This procedure generally is used to specify a type of information that you and others like you will provide on an on-going basis.

[loweralpha]
. *Application.* You may apply to have information designated as protected under this part by submitting an application addressed to the U.S. Department of Transportation, Docket Operations, West Building Ground Floor, Room W12-140, 1200 New Jersey Avenue, SE., Washington, DC 20590 for paper submissions, and the Federal Docket Management System (FDMS) Web page at *http://www.regulations.gov* for electronic submissions. Your application must include the designation described in paragraph (c) of this section that you want the FAA to issue. You should not include in your application any information that you do not want available to the public. The FAA may issue a proposed designation based on the application or may deny your application.
. *Proposed designation.* Before issuing a designation under this section, based either on your application or the FAA's own initiative, the FAA publishes a proposed designation in the *Federal Register* and requests comment.
. *Designation.* The FAA designates information as protected under this part if, after review of the comments, the FAA makes the findings in § 193.7. The FAA publishes in the *Federal Register* an order designating the information provided under the program as protected under this part. The designation includes the following:
[arabic]
.. A summary of why the FAA finds that you and others, if applicable, will provide the information voluntarily.
.. A description of the type of information that you and others, if applicable, may voluntarily provide under the program and a summary of why the FAA finds that the information is safety or security related.
.. A summary of why the FAA finds that the disclosure of the information would inhibit you and others, if applicable, from voluntarily providing of that type of information.
.. A summary of why the receipt of that type of information aids in fulfilling the FAA's safety and security responsibilities.
.. A summary of why withholding such information from disclosure would be consistent with the FAA's safety and security responsibilities, including a statement as to the circumstances under which, and a summary of why, withholding such information from disclosure would not be consistent with the FAA's safety and security responsibilities, as described in § 193.9.
.. A summary of how the FAA will distinguish information protected under this part from information the FAA receives from other sources.
.. A summary of the significant comments received and the FAA's responses.
. *Amendment of designation.* The FAA may amend a designation using the procedures in paragraphs (a), (b), and (c) of this section.
. *Withdrawal of designation.* The FAA may withdraw a designation under this section at any time the FAA finds that continuation of the designation does not meet the elements of § 193.7, or if the requirements of the designation are not met. The FAA withdraws the designation by publishing a notice in the *Federal Register.* The withdrawal is effective on the date of publication or such later date as the notice may state. Information provided during the time the program was designated remains protected under this part and the program. Information provided after the withdrawal of the designation is effective is not protected under this part or the program.

## § 193.13 - What is the no-notice procedure?

This section states the no-notice procedure for the FAA to designate information as protected under this part. This procedure is used when there is an immediate safety or security need for the information. This procedure generally is used for specific information that you will provide on a short-term basis.

[loweralpha]
. *Application.* You may request that the FAA designate information you are offering as protected under this part. You must state your name, at least the general nature of information, and whether you will provide the information without the protection of this part. Your request may be verbal or writing.
. *Designation.* The FAA issues a written order designating information provided under this section as protected under this part. The FAA designates the information as protected under this part if the FAA—
[arabic]
.. Makes the findings as § 193.7; and
.. Finds that there is an immediate safety or security need to obtain the information without carrying out the procedures in § 193.11 of this part.
. *Time limit.* Except as provided in paragraphs (c)(1) and (c)(2) of this section, no designation under this section continues in effect for more than 60 days after the date of designation. Information provided during the time the designation was in effect remains protected under this part. Information provided that the designation ceases to be in effect is not protected under this part. The designation remains in effect for more than 60 days if—
[arabic]
.. The procedures to designate such information under § 193.11(a) have been initiated, or
.. There is an ongoing enforcement or criminal investigation, in which case the designation may continue until the investigation is completed.
. *Amendment of designation.* The FAA may amend a designation under this section using the procedures in paragraphs (a) and (b) of this section.
            
. *Withdrawal of designation.* The FAA may withdraw a designation under this section at any time the FAA finds that continuation does not meet the elements of § 193.7, or if the requirements of the designation are not met. The FAA withdraws the designation by notifying the person in writing that the designation is withdrawn. The withdrawal is effective on the date of receipt of the notice or such later date as the notice may state. Information provided during the time the designation was in effect remains protected under this part. Information provided after the withdrawal is effective is not protected under this part.

## § 193.15 - What FAA officials exercise the authority of the Administrator under this part?

[loweralpha]
. The authority to issue proposed and final designations, to issue proposed and final amendments of designations, and to withdraw designations under this part, and to disclose information that has been designated as protected under this part, is delegated by the Administrator to Associate Administrators and Assistant Administrators and to the Chief Counsel, their Deputies, and any individual formally designated as Acting Associate or Assistant Administrator, Acting Chief Counsel, or Acting Deputy of such offices.
. The officials identified in paragraph (a) of this section may further delegate the authority to issue proposed designations and proposed amendments to designations.

## § 193.17 - How must design and production approval holders handle information they receive from the FAA under this part?

[loweralpha]
. If the FAA discloses information under § 193.9(a)(2) to the holders of design approvals of production approvals issued by the FAA, the approval holder must disclose that information only to persons who need to know the information to address the safety or security condition.
. Unless an emergency exists, before disclosing information to approval holders the FAA will contact the submitter of the information.

