# Special Federal Aviation Regulations
:toc:

## § 121.1500

### SFAR No. 111—Lavatory Oxygen Systems.

. *Applicability.* This SFAR applies to the following persons:
.. All operators of transport category airplanes that are required to comply with AD 2012-11-09, but only for airplanes on which the actions required by that AD have not been accomplished.
.. Applicants for airworthiness certificates.
.. Holders of production certificates.
.. Applicants for type certificates, including changes to type certificates.
. *Regulatory relief.* Except as noted in paragraph (d) of this section and contrary provisions of 14 CFR part 21, and 14 CFR 25.1447, 119.51, 121.329, 121.333 and 129.13, notwithstanding, for the duration of this SFAR:
.. A person described in paragraph (a) of this section may conduct flight operations and add airplanes to operations specifications with disabled lavatory oxygen systems, modified in accordance with FAA Airworthiness Directive 2011-04-09, subject to the following limitations:
... This relief is limited to regulatory compliance of lavatory oxygen systems.
... Within 30 days of March 29, 2013, all oxygen masks must be removed from affected lavatories, and the mask stowage location must be reclosed.
... Within 60 days of March 29, 2013 each affected operator must verify that crew emergency procedures specifically include a visual check of the lavatory as a priority when checking the cabin following any event where oxygen masks were deployed in the cabin.
.. An applicant for an airworthiness certificate may obtain an airworthiness certificate for airplanes to be operated by a person described in paragraph (a) of this section, although the airplane lavatory oxygen system is disabled.
.. A holder of a production certificate may apply for an airworthiness certificate or approval for airplanes to be operated by a person described in paragraph (a) of this section.
.. An applicant for a type certificate or change to a type certificate may obtain a design approval without showing compliance with § 25.1447(c)(1) of this chapter for lavatory oxygen systems, in accordance with this SFAR.
.. Each person covered by paragraph (a) of this section may inform passengers that the lavatories are not equipped with supplemental oxygen.
. *Return to service documentation.* When a person described in paragraph (a) of this section has modified airplanes as required by Airworthiness Directive 2011-04-09, the affected airplanes must be returned to service with a note in the airplane maintenance records that the modification was done under the provisions of this SFAR.
. *Expiration.* This SFAR expires on September 10, 2015, except this SFAR will continue to apply to any airplane for which the FAA approves an extension of the AD compliance time for the duration of the extension.

