# Valparaiso, Florida, Terminal Area
:toc:

## § 93.80

### Applicability.

This subpart prescribes special air traffic rules for aircraft operating in the Valparaiso, Florida, Terminal Area.

## § 93.81

### Applicability and description of area.

The Valparaiso, Florida Terminal Area is designated as follows:

. North-South Corridor. The North-South Corridor includes the airspace extending upward from the surface up to, but not including, 18,000 feet MSL, bounded by a line beginning at:
              
. East-West Corridor—The East-West Corridor is divided into three sections to accommodate the different altitudes as portions of the corridor underlie restricted areas R-2915C, R-2919B, and R-2914B.
.. The west section would include that airspace extending upward from the surface to but not including 8,500 feet MSL, bounded by a line beginning at: Latitude 30°22′47″ N., Longitude 86°51′30″ W.: then along the shoreline to Latitude 30°23′46″ N., Longitude 86°38′15″ W.; to Latitude 30°20′51″ N., Longitude 86°38′50″ W.; then 3 NM from and parallel to the shoreline to Latitude 30°19′31″ N., Longitude 86°51′30″ W.; to the beginning.
.. The center section would include that airspace extending upward from the surface to but not including 18,000 feet MSL, bounded by a line beginning at:
              
.. The east section would include that airspace extending upward from the surface to but not including 8,500 feet MSL, bounded by a line beginning at:
              

## § 93.83

### Aircraft operations.

. *North-South Corridor.* Unless otherwise authorized by ATC (including the Eglin Radar Control Facility), no person may operate an aircraft in flight within the North-South Corridor designated in § 93.81(b)(1) unless—
.. Before operating within the corridor, that person obtains a clearance from the Eglin Radar Control Facility or an appropriate FAA ATC facility; and
.. That person maintains two-way radio communication with the Eglin Radar Control Facility or an appropriate FAA ATC facility while within the corridor.
. *East-West Corridor.* Unless otherwise authorized by ATC (including the Eglin Radar Control Facility), no person may operate an aircraft in flight within the East-West Corridor designated in § 93.81(b)(2) unless—
.. Before operating within the corridor, that person establishes two-way radio communications with Eglin Radar Control Facility or an appropriate FAA ATC facility and receives an ATC advisory concerning operations being conducted therein; and
.. That person maintains two-way radio communications with the Eglin Radar Control Facility or an appropriate FAA ATC facility while within the corridor.

