# Continued Airworthiness and Safety Improvements
:toc:

## § 91.1501 - Purpose and definition.

[loweralpha]
. This subpart requires operators to support the continued airworthiness of each airplane. These requirements may include, but are not limited to, revising the inspection program, incorporating design changes, and incorporating revisions to Instructions for Continued Airworthiness.
. For purposes of this subpart, the “FAA Oversight Office” is the aircraft certification office or office of the Transport Airplane Directorate with oversight responsibility for the relevant type certificate or supplemental type certificate, as determined by the Administrator.

## § 91.1503 - Reserved


Reserved

## § 91.1505 - Repairs assessment for pressurized fuselages.

[loweralpha]
. No person may operate an Airbus Model A300 (excluding the -600 series), British Aerospace Model BAC 1-11, Boeing Model, 707, 720, 727, 737 or 747, McDonnell Douglas Model DC-8, DC-9/MD-80 or DC-10, Fokker Model F28, or Lockheed Model L-1011 airplane beyond applicable flight cycle implementation time specified below, or May 25, 2001, whichever occurs later, unless repair assessment guidelines applicable to the fuselage pressure boundary (fuselage skin, door skin, and bulkhead webs) that have been approved by the FAA Aircraft Certification Office (ACO), or office of the Transport Airplane Directorate, having cognizance over the type certificate for the affected airplane are incorporated within its inspection program:
[arabic]
.. For the Airbus Model A300 (excluding the -600 series), the flight cycle implementation time is:
[lowerroman]
... Model B2: 36,000 flights.
... Model B4-100 (including Model B4-2C): 30,000 flights above the window line, and 36,000 flights below the window line.
... Model B4-200: 25,500 flights above the window line, and 34,000 flights below the window line.
.. For all models of the British Aerospace BAC 1-11, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 707, the flight cycle implementation time is 15,000 flights.
.. For all models of the Boeing 720, the flight cycle implementation time is 23,000 flights.
.. For all models of the Boeing 727, the flight cycle implementation time is 45,000 flights.
.. For all models of the Boeing 737, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 747, the flight cycle implementation time is 15,000 flights.
.. For all models of the McDonnell Douglas DC-8, the flight cycle implementation time is 30,000 flights.
.. For all models of the McDonnell Douglas DC-9/MD-80, the flight cycle implementation time is 60,000 flights.
.. For all models of the McDonnell Douglas DC-10, the flight cycle implementation time is 30,000 flights.
.. For all models of the Lockheed L-1011, the flight cycle implementation time is 27,000 flights.
.. For the Fokker F-28 Mark 1000, 2000, 3000, and 4000, the flight cycle implementation time is 60,000 flights.
. [Reserved]

## § 91.1507 - Fuel tank system inspection program.

[loweralpha]
. Except as provided in paragraph (g) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity, have—
[arabic]
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7,500 pounds or more.
. For each airplane on which an auxiliary fuel tank is installed under a field approval, before June 16, 2008, the operator must submit to the FAA Oversight Office proposed maintenance instructions for the tank that meet the requirements of Special Federal Aviation Regulation No. 88 (SFAR 88) of this chapter.
. After December 16, 2008, no operator may operate an airplane identified in paragraph (a) of this section unless the inspection program for that airplane has been revised to include applicable inspections, procedures, and limitations for fuel tank systems.
. The proposed fuel tank system inspection program revisions specified in paragraph (c) of this section must be based on fuel tank system Instructions for Continued Airworthiness (ICA) that have been developed in accordance with the applicable provisions of SFAR 88 of this chapter or § 25.1529 and part 25, Appendix H, of this chapter, in effect on June 6, 2001 (including those developed for auxiliary fuel tanks, if any, installed under supplemental type certificates or other design approval) and that have been approved by the FAA Oversight Office.
. After December 16, 2008, before returning an airplane to service after any alterations for which fuel tank ICA are developed under SFAR 88, or under § 25.1529 in effect on June 6, 2001, the operator must include in the inspection program for the airplane inspections and procedures for the fuel tank system based on those ICA.
. The fuel tank system inspection program changes identified in paragraphs (d) and (e) of this section and any later fuel tank system revisions must be submitted to the Flight Standards District Office (FSDO) responsible for review and approval.
. This section does not apply to the following airplane models:
[arabic]
.. Bombardier CL-44
.. Concorde
.. deHavilland D.H. 106 Comet 4C
.. VFW-Vereinigte Flugtechnische Werk VFW-614
.. Illyushin Aviation IL 96T
.. Bristol Aircraft Britannia 305
.. Handley Page Herald Type 300
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C
.. Airbus Caravelle
.. Lockheed L-300

