# Crewmember Testing Requirements
:toc:

## § 135.291 - Applicability.

Except as provided in § 135.3, this subpart—

[loweralpha]
. Prescribes the tests and checks required for pilot and flight attendant crewmembers and for the approval of check pilots in operations under this part; and
. Permits training center personnel authorized under part 142 of this chapter who meet the requirements of §§ 135.337 and 135.339 to conduct training, testing, and checking under contract or other arrangement to those persons subject to the requirements of this subpart.

## § 135.293 - Initial and recurrent pilot testing requirements.

[loweralpha]
. No certificate holder may use a pilot, nor may any person serve as a pilot, unless, since the beginning of the 12th calendar month before that service, that pilot has passed a written or oral test, given by the Administrator or an authorized check pilot, on that pilot's knowledge in the following areas—
[arabic]
.. The appropriate provisions of parts 61, 91, and 135 of this chapter and the operations specifications and the manual of the certificate holder;
.. For each type of aircraft to be flown by the pilot, the aircraft powerplant, major components and systems, major appliances, performance and operating limitations, standard and emergency operating procedures, and the contents of the approved Aircraft Flight Manual or equivalent, as applicable;
.. For each type of aircraft to be flown by the pilot, the method of determining compliance with weight and balance limitations for takeoff, landing and en route operations;
.. Navigation and use of air navigation aids appropriate to the operation or pilot authorization, including, when applicable, instrument approach facilities and procedures;
.. Air traffic control procedures, including IFR procedures when applicable;
.. Meteorology in general, including the principles of frontal systems, icing, fog, thunderstorms, and windshear, and, if appropriate for the operation of the certificate holder, high altitude weather;
.. Procedures for—
[lowerroman]
... Recognizing and avoiding severe weather situations;
... Escaping from severe weather situations, in case of inadvertent encounters, including low-altitude windshear (except that rotorcraft pilots are not required to be tested on escaping from low-altitude windshear);
              
... Operating in or near thunderstorms (including best penetrating altitudes), turbulent air (including clear air turbulence), icing, hail, and other potentially hazardous meteorological conditions; and
.. New equipment, procedures, or techniques, as appropriate; and
.. For rotorcraft pilots, procedures for aircraft handling in flat-light, whiteout, and brownout conditions, including methods for recognizing and avoiding those conditions.
. No certificate holder may use a pilot, nor may any person serve as a pilot, in any aircraft unless, since the beginning of the 12th calendar month before that service, that pilot has passed a competency check given by the Administrator or an authorized check pilot in that class of aircraft, if single-engine airplane other than turbojet, or that type of aircraft, if helicopter, multiengine airplane, or turbojet airplane, to determine the pilot's competence in practical skills and techniques in that aircraft or class of aircraft. The extent of the competency check shall be determined by the Administrator or authorized check pilot conducting the competency check. The competency check may include any of the maneuvers and procedures currently required for the original issuance of the particular pilot certificate required for the operations authorized and appropriate to the category, class and type of aircraft involved. For the purposes of this paragraph, type, as to an airplane, means any one of a group of airplanes determined by the Administrator to have a similar means of propulsion, the same manufacturer, and no significantly different handling or flight characteristics. For the purposes of this paragraph, type, as to a helicopter, means a basic make and model.
. Each competency check given in a rotorcraft must include a demonstration of the pilot's ability to maneuver the rotorcraft solely by reference to instruments. The check must determine the pilot's ability to safely maneuver the rotorcraft into visual meteorological conditions following an inadvertent encounter with instrument meteorological conditions. For competency checks in non-IFR-certified rotorcraft, the pilot must perform such maneuvers as are appropriate to the rotorcraft's installed equipment, the certificate holder's operations specifications, and the operating environment.
. The instrument proficiency check required by § 135.297 may be substituted for the competency check required by this section for the type of aircraft used in the check.
. For the purpose of this part, competent performance of a procedure or maneuver by a person to be used as a pilot requires that the pilot be the obvious master of the aircraft, with the successful outcome of the maneuver never in doubt.
. The Administrator or authorized check pilot certifies the competency of each pilot who passes the knowledge or flight check in the certificate holder's pilot records.
. Portions of a required competency check may be given in an aircraft simulator or other appropriate training device, if approved by the Administrator.
. Rotorcraft pilots must be tested on the subjects in paragraph (a)(9) of this section when taking a written or oral knowledge test after April 22, 2015. Rotorcraft pilots must be checked on the maneuvers and procedures in paragraph (c) of this section when taking a competency check after April 22, 2015.

## § 135.295 - Initial and recurrent flight attendant crewmember testing requirements.

No certificate holder may use a flight attendant crewmember, nor may any person serve as a flight attendant crewmember unless, since the beginning of the 12th calendar month before that service, the certificate holder has determined by appropriate initial and recurrent testing that the person is knowledgeable and competent in the following areas as appropriate to assigned duties and responsibilities—

[loweralpha]
. Authority of the pilot in command;
. Passenger handling, including procedures to be followed in handling deranged persons or other persons whose conduct might jeopardize safety;
. Crewmember assignments, functions, and responsibilities during ditching and evacuation of persons who may need the assistance of another person to move expeditiously to an exit in an emergency;
. Briefing of passengers;
. Location and operation of portable fire extinguishers and other items of emergency equipment;
. Proper use of cabin equipment and controls;
. Location and operation of passenger oxygen equipment;
. Location and operation of all normal and emergency exits, including evacuation chutes and escape ropes; and
[lowerroman]
.. Seating of persons who may need assistance of another person to move rapidly to an exit in an emergency as prescribed by the certificate holder's operations manual.

## § 135.297 - Pilot in command: Instrument proficiency check requirements.

[loweralpha]
. No certificate holder may use a pilot, nor may any person serve, as a pilot in command of an aircraft under IFR unless, since the beginning of the 6th calendar month before that service, that pilot has passed an instrument proficiency check under this section administered by the Administrator or an authorized check pilot.
. No pilot may use any type of precision instrument approach procedure under IFR unless, since the beginning of the 6th calendar month before that use, the pilot satisfactorily demonstrated that type of approach procedure. No pilot may use any type of nonprecision approach procedure under IFR unless, since the beginning of the 6th calendar month before that use, the pilot has satisfactorily demonstrated either that type of approach procedure or any other two different types of nonprecision approach procedures. The instrument approach procedure or procedures must include at least one straight-in approach, one circling approach, and one missed approach. Each type of approach procedure demonstrated must be conducted to published minimums for that procedure.
. The instrument proficiency check required by paragraph (a) of this section consists of an oral or written equipment test and a flight check under simulated or actual IFR conditions. The equipment test includes questions on emergency procedures, engine operation, fuel and lubrication systems, power settings, stall speeds, best engine-out speed, propeller and supercharger operations, and hydraulic, mechanical, and electrical systems, as appropriate. The flight check includes navigation by instruments, recovery from simulated emergencies, and standard instrument approaches involving navigational facilities which that pilot is to be authorized to use. Each pilot taking the instrument proficiency check must show that standard of competence required by § 135.293(e).
[arabic]
.. The instrument proficiency check must—
[lowerroman]
... For a pilot in command of an airplane under § 135.243(a), include the procedures and maneuvers for an airline transport pilot certificate in the particular type of airplane, if appropriate; and
... For a pilot in command of an airplane or helicopter under § 135.243(c), include the procedures and maneuvers for a commercial pilot certificate with an instrument rating and, if required, for the appropriate type rating.
.. The instrument proficiency check must be given by an authorized check airman or by the Administrator.
              
. If the pilot in command is assigned to pilot only one type of aircraft, that pilot must take the instrument proficiency check required by paragraph (a) of this section in that type of aircraft.
. If the pilot in command is assigned to pilot more than one type of aircraft, that pilot must take the instrument proficiency check required by paragraph (a) of this section in each type of aircraft to which that pilot is assigned, in rotation, but not more than one flight check during each period described in paragraph (a) of this section.
. If the pilot in command is assigned to pilot both single-engine and multiengine aircraft, that pilot must initially take the instrument proficiency check required by paragraph (a) of this section in a multiengine aircraft, and each succeeding check alternately in single-engine and multiengine aircraft, but not more than one flight check during each period described in paragraph (a) of this section. Portions of a required flight check may be given in an aircraft simulator or other appropriate training device, if approved by the Administrator.
. If the pilot in command is authorized to use an autopilot system in place of a second in command, that pilot must show, during the required instrument proficiency check, that the pilot is able (without a second in command) both with and without using the autopilot to—
[arabic]
.. Conduct instrument operations competently; and
.. Properly conduct air-ground communications and comply with complex air traffic control instructions.
.. Each pilot taking the autopilot check must show that, while using the autopilot, the airplane can be operated as proficiently as it would be if a second in command were present to handle air-ground communications and air traffic control instructions. The autopilot check need only be demonstrated once every 12 calendar months during the instrument proficiency check required under paragraph (a) of this section.

## § 135.299 - Pilot in command: Line checks: Routes and airports.

[loweralpha]
. No certificate holder may use a pilot, nor may any person serve, as a pilot in command of a flight unless, since the beginning of the 12th calendar month before that service, that pilot has passed a flight check in one of the types of aircraft which that pilot is to fly. The flight check shall—
[arabic]
.. Be given by an approved check pilot or by the Administrator;
.. Consist of at least one flight over one route segment; and
.. Include takeoffs and landings at one or more representative airports. In addition to the requirements of this paragraph, for a pilot authorized to conduct IFR operations, at least one flight shall be flown over a civil airway, an approved off-airway route, or a portion of either of them.
. The pilot who conducts the check shall determine whether the pilot being checked satisfactorily performs the duties and responsibilities of a pilot in command in operations under this part, and shall so certify in the pilot training record.
. Each certificate holder shall establish in the manual required by § 135.21 a procedure which will ensure that each pilot who has not flown over a route and into an airport within the preceding 90 days will, before beginning the flight, become familiar with all available information required for the safe operation of that flight.

## § 135.301 - Crewmember: Tests and checks, grace provisions, training to accepted standards.

[loweralpha]
. If a crewmember who is required to take a test or a flight check under this part, completes the test or flight check in the calendar month before or after the calendar month in which it is required, that crewmember is considered to have completed the test or check in the calendar month in which it is required.
              
. If a pilot being checked under this subpart fails any of the required maneuvers, the person giving the check may give additional training to the pilot during the course of the check. In addition to repeating the maneuvers failed, the person giving the check may require the pilot being checked to repeat any other maneuvers that are necessary to determine the pilot's proficiency. If the pilot being checked is unable to demonstrate satisfactory performance to the person conducting the check, the certificate holder may not use the pilot, nor may the pilot serve, as a flight crewmember in operations under this part until the pilot has satisfactorily completed the check.

