# Approval of Routes: Domestic and Flag Operations
:toc:

## § 121.91

### Applicability.

This subpart prescribes rules for obtaining approval of routes by certificate holders conducting domestic or flag operations.

## § 121.93

### Route requirements: General.

. Each certificate holder conducting domestic or flag operations seeking a route approval must show—
.. That it is able to conduct satisfactorily scheduled operations between each regular, provisional, and refueling airport over that route or route segment; and
.. That the facilities and services required by §§ 121.97 through 121.107 are available and adequate for the proposed operation.
              
. Paragraph (a) of this section does not require actual flight over a route or route segment if the certificate holder shows that the flight is not essential to safety, considering the availability and adequacy of airports, lighting, maintenance, communication, navigation, fueling, ground, and airplane radio facilities, and the ability of the personnel to be used in the proposed operation.

## § 121.95

### Route width.

. Approved routes and route segments over U.S. Federal airways or foreign airways (and advisory routes in the case of certificate holders conducting flag operations) have a width equal to the designated width of those airways or routes. Whenever the Administrator finds it necessary to determine the width of other approved routes, he considers the following:
.. Terrain clearance.
.. Minimum en route altitudes.
.. Ground and airborne navigation aids.
.. Air traffic density.
.. ATC procedures.
. Any route widths of other approved routes determined by the Administrator are specified in the certificate holder's operations specifications.

## § 121.97

### Airports: Required data.

. Each certificate holder conducting domestic or flag operations must show that each route it submits for approval has enough airports that are properly equipped and adequate for the proposed operation, considering such items as size, surface, obstructions, facilities, public protection, lighting, navigational and communications aids, and ATC.
. Each certificate holder conducting domestic or flag operations must show that it has an approved system for obtaining, maintaining, and distributing to appropriate personnel current aeronautical data for each airport it uses to ensure a safe operation at that airport. The aeronautical data must include the following:
.. (1) Airports.
... (i) Facilities.
... Public protection. After February 15, 2008, for ETOPS beyond 180 minutes or operations in the North Polar area and South Polar area, this includes facilities at each airport or in the immediate area sufficient to protect the passengers from the elements and to see to their welfare.
... and communications aids.
... affecting takeoff, landing, or ground operations.
... traffic facilities.
.. clearways and stopways.
... (i) Dimensions.
... (ii) Surface.
... and lighting systems.
... and gradient.
.. thresholds.
... (i) Location.
... (ii) Dimensions.
... or landing or both.
.. (4) Obstacles.
... affecting takeoff and landing performance computations in accordance with Subpart I of this part.
... obstacles.
.. flight procedures.
... procedure.
... procedure.
... approach procedure.
.. information.
... visual range measurement equipment.
... winds under low visibility conditions.
. If the certificate-holding district office charged with the overall inspection of the certificate holder's operations finds that revisions are necessary for the continued adequacy of the certificate holder's system for collection, dissemination, and usage of aeronautical data that has been granted approval, the certificate holder shall, after notification by the certificate-holding district office, make those revisions in the system. Within 30 days after the certificate holder receives such notice, the certificate holder may file a petition to reconsider the notice with the Director, Flight Standards Service. This filing of a petition to reconsider stays the notice pending a decision by the Director, Flight Standards Service. However, if the certificate-holding district office finds that there is an emergency that requires immediate action in the interest of safety in air transportation, the Director, Flight Standards Service may, upon statement of the reasons, require a change effective without stay.

## § 121.99

### Communications facilities—domestic and flag operations.

. Each certificate holder conducting domestic or flag operations must show that a two-way communication system, or other means of communication approved by the FAA certificate holding district office, is available over the entire route. The communications may be direct links or via an approved communication link that will provide reliable and rapid communications under normal operating conditions between each airplane and the appropriate dispatch office, and between each airplane and the appropriate air traffic control unit.
. Except in an emergency, for all flag and domestic kinds of operations, the communications systems between each airplane and the dispatch office must be independent of any system operated by the United States.
. Each certificate holder conducting flag operations must provide voice communications for ETOPS where voice communication facilities are available. In determining whether facilities are available, the certificate holder must consider potential routes and altitudes needed for diversion to ETOPS Alternate Airports. Where facilities are not available or are of such poor quality that voice communication is not possible, another communication system must be substituted.
. Except as provided in paragraph (e) of this section, after February 15, 2008 for ETOPS beyond 180 minutes, each certificate holder conducting flag operations must have a second communication system in addition to that required by paragraph (c) of this section. That system must be able to provide immediate satellite-based voice communications of landline-telephone fidelity. The system must be able to communicate between the flight crew and air traffic services, and the flight crew and the certificate holder. In determining whether such communications are available, the certificate holder must consider potential routes and altitudes needed for diversion to ETOPS Alternate Airports. Where immediate, satellite-based voice communications are not available, or are of such poor quality that voice communication is not possible, another communication system must be substituted.
. Operators of two-engine turbine-powered airplanes with 207 minute ETOPS approval in the North Pacific Area of Operation must comply with the requirements of paragraph (d) of this section as of February 15, 2007.

## § 121.101

### Weather reporting facilities.

. Each certificate holder conducting domestic or flag operations must show that enough weather reporting services are available along each route to ensure weather reports and forecasts necessary for the operation.
. Except as provided in paragraph (d) of this section, no certificate holder conducting domestic or flag operations may use any weather report to control flight unless—
.. For operations within the 48 contiguous States and the District of Columbia, it was prepared by the U.S. National Weather Service or a source approved by the U.S. National Weather Service; or
.. For operations conducted outside the 48 contiguous States and the District of Columbia, it was prepared by a source approved by the Administrator.
. Each certificate holder conducting domestic or flag operations that uses forecasts to control flight movements shall use forecasts prepared from weather reports specified in paragraph (b) of this section and from any source approved under its system adopted pursuant to paragraph (d) of this section.
. Each certificate holder conducting domestic or flag operations shall adopt and put into use an approved system for obtaining forecasts and reports of adverse weather phenomena, such as clear air turbulence, thunderstorms, and low altitude wind shear, that may affect safety of flight on each route to be flown and at each airport to be used.

## § 121.103

### En route navigation facilities.

. Except as provided in paragraph (b) of this section, each certificate holder conducting domestic or flag operations must show, for each proposed route (including to any regular, provisional, refueling or alternate airports), that suitable navigation aids are available to navigate the airplane along the route within the degree of accuracy required for ATC. Navigation aids required for approval of routes outside of controlled airspace are listed in the certificate holder's operations specifications except for those aids required for routes to alternate airports.
. Navigation aids are not required for any of the following operations—
.. Day VFR operations that the certificate holder shows can be conducted safely by pilotage because of the characteristics of the terrain;
.. Night VFR operations on routes that the certificate holder shows have reliably lighted landmarks adequate for safe operation; and
.. Other operations approved by the certificate holding district office.

## § 121.105

### Servicing and maintenance facilities.

Each certificate holder conducting domestic or flag operations must show that competent personnel and adequate facilities and equipment (including spare parts, supplies, and materials) are available at such points along the certificate holder's route as are necessary for the proper servicing, maintenance, and preventive maintenance of airplanes and auxiliary equipment.

## § 121.106

### ETOPS Alternate Airport: Rescue and fire fighting service.

. Except as provided in paragraph (b) of this section, the following rescue and fire fighting service (RFFS) must be available at each airport listed as an ETOPS Alternate Airport in a dispatch or flight release.
.. For ETOPS up to 180 minutes, each designated ETOPS Alternate Airport must have RFFS equivalent to that specified by ICAO as Category 4, or higher.
.. For ETOPS beyond 180 minutes, each designated ETOPS Alternate Airport must have RFFS equivalent to that specified by ICAO Category 4, or higher. In addition, the aircraft must remain within the ETOPS authorized diversion time from an Adequate Airport that has RFFS equivalent to that specified by ICAO Category 7, or higher.
. If the equipment and personnel required in paragraph (a) of this section are not immediately available at an airport, the certificate holder may still list the airport on the dispatch or flight release if the airport's RFFS can be augmented to meet paragraph (a) of this section from local fire fighting assets. A 30-minute response time for augmentation is adequate if the local assets can be notified while the diverting airplane is en route. The augmenting equipment and personnel must be available on arrival of the diverting airplane and must remain as long as the diverting airplane needs RFFS.

## § 121.107

### Dispatch centers.

Each certificate holder conducting domestic or flag operations must show that it has enough dispatch centers, adequate for the operations to be conducted, that are located at points necessary to ensure proper operational control of each flight.

