# Development of Noise Exposure Maps and Noise Compatibility Programs
:toc:

## § 150.21 - Noise exposure maps and related descriptions.

[loweralpha]
. Each airport operator may after completion of the consultations and public procedure specified under paragraph (b) of this section submit to the Regional Airports Division Manager five copies of the noise exposure map (or revised map) which identifies each noncompatible land use in each area depicted on the map, as of the date of submission, and five copies of a map each with accompanying documentation setting forth—
[arabic]
.. The noise exposure based on forecast aircraft operations at the airport for a forecast period that is at least 5 years in the future, beginning after the date of submission (based on reasonable assumptions concerning future type and frequency of aircraft operations, number of nighttime operations, flight patterns, airport layout including any planned airport development, planned land use changes, and demographic changes in the surrounding areas); and
.. The nature and extent, if any, to which those forecast operations will affect the compatibility and land uses depicted on the map.
. Each map, and related documentation submitted under this section must be developed and prepared in accordance with appendix A of this part, or an FAA approved equivalent, and in consultation with states, and public agencies and planning agencies whose area, or any portion of whose area, of jurisdiction is within the L*dn* 65 dB contour depicted on the map, FAA regional officials, and other Federal officials having local responsibility for land uses depicted on the map. This consultation must include regular aeronautical users of the airport. The airport operator shall certify that it has afforded interested persons adequate opportunity to submit their views, data, and comments concerning the correctness and adequacy of the draft noise exposure map and descriptions of forecast aircraft operations. Each map and revised map must be accompanied by documentation describing the consultation accomplished under this paragraph and the opportunities afforded the public to review and comment during the development of the map. One copy of all written comments received during consultation shall also be filed with the Regional Airports Division Manager.
. The Regional Airports Division Manager acknowledges receipt of noise exposure maps and descriptions and indicates whether they are in compliance with the applicable requirements. The Regional Airports Division Manager publishes in the *Federal Register* a notice of compliance for each such noise exposure map and description, identifying the airport involved. Such notice includes information as to when and where the map and related documentation are available for public inspection.
. The airport operator shall, in accordance with this section, promptly prepare and submit a revised noise exposure map.
[arabic]
.. If, after submission of a noise exposure map under paragraph (a) of this section, any change in the operation of the airport would create any “substantial, new noncompatible use” in any area depicted on the map beyond that which is forecast for a period of at least five years after the date of submission, the airport operator shall, in accordance with this section, promptly prepare and submit a revised noise exposure map. A change in the operation of an airport creates a substantial new noncompatible use if that change results in an increase in the yearly day-night average sound level of 1.5 dB or greater in either a land area which was formerly compatible but is thereby made noncompatible under Appendix A (Table 1), or in a land area which was previously determined to be noncompatible under that Table and whose noncompatibility is now significantly increased.
.. If, after submission of a noise exposure map under paragraph (a) of this section, any change in the operation of the airport would significantly reduce noise over existing noncompatible uses that is not reflected in either the existing conditions or forecast noise exposure map on file with the FAA, the airport operator shall, in accordance with this section, promptly prepare and submit a revised noise exposure map. A change in the operation of the airport creates a significant reduction in noise over existing noncompatible uses if that change results in a decrease in the yearly day-night average sound level of 1.5 dB or greater in a land area which was formerly noncompatible but is thereby made compatible under Appendix A (Table 1).
.. Such updating of the map shall include a reassessment of those areas excluded under section A150.101(e)(5) of Appendix A because of high ambient noise levels.
.. If the forecast map is based on assumptions involving recommendations in a noise compatibility program which are subsequently disapproved by the FAA, a revised map must be submitted if revised assumptions would create a substantial, new noncompatible use not indicated on the forecast map. Revised noise exposure maps are subject to the same requirements and procedures as initial submissions of noise exposure maps under this part.
. Each map, or revised map, and description of consultation and opportunity for public comment, submitted to the FAA, must be certified as true and complete under penalty of 18 U.S.C. 1001.
. Title 49, section 47506 provides that no person who acquires property or an interest therein after the date of enactment of the Act in an area surrounding an airport with respect to which a noise exposure map has been submitted under section 47503 of the Act shall be entitled to recover damages with respect to the noise attributable to such airport if such person had actual or constructive knowledge of the existence of such noise exposure map unless, in addition to any other elements for recovery of damages, such person can show that—
              

(f)(2) Title 49 section 47506(b) further provides:
              

(g) For this purpose, the term *significant* in paragraph (f) of this section means that change or increase in one or more of the four factors which results in a “substantial new noncompatible use” as defined in § 150.21(d), affecting the property in issue. Responsibility for applying or interpreting this provision with respect to specific properties rests with local government.

## § 150.23 - Noise compatibility programs.

[loweralpha]
. Any airport operator who has submitted an acceptable noise exposure map under § 150.21 may, after FAA notice of acceptability and other consultation and public procedure specified under paragraphs (b) and (c) of this section, as applicable, submit to the Regional Airports Division Manager five copies of a noise compatibility program.
. An airport operator may submit the noise compatibility program at the same time as the noise exposure map. In this case, the Regional Airports Division Manager will not begin the statutory 180-day review period (for the program) until after FAA reviews the noise exposure map and finds that it and its supporting documentation are in compliance with the applicable requirements.
. Each noise compatibility program must be developed and prepared in accordance with appendix B of this part, or an FAA approved equivalent, and in consultation with FAA regional officials, the officials of the state and of any public agencies and planning agencies whose area, or any portion or whose area, of jurisdiction within the L*dn* 65 dB noise contours is depicted on the noise exposure map, and other Federal officials having local responsibility of land uses depicted on the map. Consultation with FAA regional officials shall include, to the extent practicable, informal agreement from FAA on proposed new or modified flight procedures. For air carrier airports, consultation must include any air carriers and, to the extent practicable, other aircraft operators using the airport. For other airports, consultation must include, to the extent practicable, aircraft operators using the airport.
. Prior to and during the development of a program, and prior to submission of the resulting draft program to the FAA, the airport operator shall afford adequate opportunity for the active and direct participation of the States, public agencies and planning agencies in the areas surrounding the airport, aeronautical users of the airport, the airport operator, and the general public to submit their views, data, and comments on the formulation and adequacy of that program. Prior to submitting the program to the FAA, the airport operator shall also provide notice and the opportunity for a public hearing.
. Each noise compatibility program submitted to the FAA must consist of at least the following:
[arabic]
.. A copy of the noise exposure map and its supporting documentation as found in compliance with the applicable requirements by the FAA, per § 150.21(c).
.. A description and analysis of the alternative measures considered by the airport operator in developing the program, together with a discussion of why each rejected measure was not included in the program.
.. Program measures proposed to reduce or eliminate present and future noncompatible land uses and a description of the relative contribution of each of the proposed measures to the overall effectiveness of the program.
.. A description of public participation and the consultation with officials of public agencies and planning agencies in areas surrounding the airport, FAA regional officials and other Federal officials having local responsibility for land uses depicted on the map, any air carriers and other users of the airport.
.. The actual or anticipated effect of the program on reducing noise exposure to individuals and noncompatible land uses and preventing the introduction of additional noncompatible uses within the area covered by the noise exposure map. The effects must be based on expressed assumptions concerning the type and frequency of aircraft operations, number of nighttime operations, flight patterns, airport layout including planned airport development, planned land use changes, and demographic changes within the L*dn* 65 dB noise contours.
.. A description of how the proposed future actions may change any noise control or compatibility plans or actions previously adopted by the airport proprietor.
.. A summary of the comments at any public hearing on the program and a copy of all written material submitted to the operator under paragraphs (c) and (d) of this section, together with the operator's response and disposition of those comments and materials to demonstrate the program is feasible and reasonably consistent with obtaining the objectives of airport noise compatibility planning under this part.
.. The period covered by the program, the schedule for implementation of the program, the persons responsible for implementation of each measure in the program, and, for each measure, documentation supporting the feasibility of implementation, including any essential governmental actions, costs, and anticipated sources of funding, that will demonstrate that the program is reasonably consistent with achieving the goals of airport noise compatibility planning under this part.
.. Provision for revising the program if made necessary by revision of the noise exposure map.

