# New York Class B Airspace Hudson River and East River Exclusion Special Flight Rules Area
:toc:

## § 93.350

### Definitions.

For the purposes of this subpart only the following definitions apply:

. *Local operation.* Any aircraft within the Hudson River Exclusion that is conducting an operation other than as described in paragraph (b) of this section. Local operations include but are not limited to operations for sightseeing, electronic news gathering, and law enforcement.
. *Transient operation.* Aircraft transiting the entire length of the Hudson River Class B Exclusion, as defined in paragraph (d) of this section, from one end to the other.
. *New York Class B airspace East River Exclusion* is that airspace below 1,500 feet MSL between the east and west banks of, and overlying, the East River beginning at lat. 40°38′39″ N., long. 74°02′03″ W., thence north along a line drawn direct to the southwestern tip of Governors Island, thence north along a line direct to the southwest tip of Manhattan Island, thence north along the west bank of the East River to the LGA VOR/DME 6-mile arc, thence counterclockwise along the 6-mile arc to the east bank of the East River, thence south along the east bank of the East River to the point of beginning at lat. 40°38′39″ N., long 74°02′03″ W.; and that airspace 1,100 feet MSL and below between the east and west banks of, and overlying the East River, from the LGA VOR/DME 6-mile arc to the north tip of Roosevelt Island.
. *New York Class B airspace Hudson River Exclusion* is that area from the surface up to but not including the overlying floor of the New York Class B airspace area, between the east and west banks of, and overlying, the Hudson River within the area beginning north of LaGuardia Airport on the west bank of the Hudson River at lat. 40°57′45″ N., long. 73°54′48″ W. (near Alpine Tower), thence south along the west bank of the Hudson River to intersect the Colts Neck VOR/DME 012° radial, thence southwest along the Colts Neck 012° radial to the Hudson River shoreline, thence south along the shoreline to the Verrazano-Narrows Bridge, thence east along the Bridge to the east bank of the Hudson River, thence north along the east bank of the Hudson River to lat. 40°38′39″ N., long. 74°02′03″ W., thence north along a line drawn direct to the southwesternmost point of Governors Island, thence north along a line drawn direct to the southwest tip of Manhattan Island, thence north along the east bank of the Hudson River to the LGA VOR/DME 11-mile arc, north of LaGuardia Airport, thence counterclockwise along the 11-mile arc to lat. 40°57′54″ N., long. 73°54′23″ W., thence to the point of beginning.

## § 93.351

### General requirements for operating in the East River and/or Hudson River Exclusions.

Pilots must adhere to the following requirements:

. Maintain an indicated airspeed not to exceed 140 knots.
. Anti-collision lights and aircraft position/navigation lights shall be on, if equipped. Use of landing lights is recommended.
. Self announce position on the appropriate radio frequency for the East River or Hudson River as depicted on the New York VFR Terminal Area Chart (TAC) and/or New York Helicopter Route Chart.
. Have a current New York TAC chart and/or New York Helicopter Route Chart in the aircraft and be familiar with the information contained therein.

## § 93.352

### Hudson River Exclusion specific operating procedures.

In addition to the requirements in § 93.351, the following procedures apply:

. Pilots must self announce, at the charted mandatory reporting points, the following information: aircraft type, current position, direction of flight, and altitude.
. Pilots must fly along the west shoreline of the Hudson River when southbound, and along the east shoreline of the Hudson River when northbound; while remaining within the boundaries of the Hudson River Exclusion as defined in § 93.350(d).
. Aircraft transiting the area within the Hudson River Exclusion in accordance with § 93.350(b) must transit the Hudson River Exclusion at or above an altitude of 1,000 feet MSL up to, but not including, the floor of the overlying Class B airspace.

## § 93.353

### East River Exclusion specific operating procedures.

No person may operate an airplane in the East River Exclusion extending from the southwestern tip of Governors Island to the north tip of Roosevelt Island except:

. Seaplanes landing on or taking off from the river; or
. Airplanes authorized by ATC. Pilots must contact LaGuardia Airport Traffic Control Tower prior to Governors Island for authorization.

