# General
:toc:

## § 63.1 - Applicability.

This part prescribes the requirements for issuing flight engineer and flight navigator certificates and the general operating rules for holders of those certificates.

## § 63.2 - Certification of foreign flight crewmembers other than pilots.

A person who is neither a United States citizen nor a resident alien is issued a certificate under this part (other than under § 63.23 or § 63.42) outside the United States only when the Administrator finds that the certificate is needed for the operation of a U.S.-registered civil aircraft.

## § 63.3 - Certificates and ratings required.

[loweralpha]
. No person may act as a flight engineer of a civil aircraft of U.S. registry unless he has in his personal possession a current flight engineer certificate with appropriate ratings issued to him under this part and a second-class (or higher) medical certificate issued to him under part 67 of this chapter within the preceding 12 months. However, when the aircraft is operated within a foreign country, a current flight engineer certificate issued by the country in which the aircraft is operated, with evidence of current medical qualification for that certificate, may be used. Also, in the case of a flight engineer certificate issued under § 63.42, evidence of current medical qualification accepted for the issue of that certificate is used in place of a medical certificate.
. No person may act as a flight navigator of a civil aircraft of U.S. registry unless he has in his personal possession a current flight navigator certificate issued to him under this part and a second-class (or higher) medical certificate issued to him under part 67 of this chapter within the preceding 12 months. However, when the aircraft is operated within a foreign country, a current flight navigator certificate issued by the country in which the aircraft is operated, with evidence of current medical qualification for that certificate, may be used.
. Each person who holds a flight engineer or flight navigator certificate, or medical certificate, shall present either or both for inspection upon the request of the Administrator or an authorized representative of the National Transportation Safety Board, or of any Federal, State, or local law enforcement officer.

## § 63.11 - Application and issue.

[loweralpha]
. An application for a certificate and appropriate class rating, or for an additional rating, under this part must be made on a form and in a manner prescribed by the Administrator. Each person who applies for airmen certification services to be administered outside the United States for any certificate or rating issued under this part must show evidence that the fee prescribed in appendix A of part 187 of this chapter has been paid.
. An applicant who meets the requirements of this part is entitled to an appropriate certificate and appropriate class ratings.
. Unless authorized by the Administrator, a person whose flight engineer certificate is suspended may not apply for any rating to be added to that certificate during the period of suspension.
. Unless the order of revocation provides otherwise, a person whose flight engineer or flight navigator certificate is revoked may not apply for the same kind of certificate for 1 year after the date of revocation.

## § 63.12 - Offenses involving alcohol or drugs.

[loweralpha]
. A conviction for the violation of any Federal or state statute relating to the growing, processing, manufacture, sale, disposition, possession, transportation, or importation of narcotic drugs, marihuana, or depressant or stimulant drugs or substances is grounds for—
[arabic]
.. Denial of an application for any certificate or rating issued under this part for a period of up to 1 year after the date of final conviction; or
.. Suspension or revocation of any certificate or rating issued under this part.
. The commission of an act prohibited by § 91.17(a) or § 91.19(a) of this chapter is grounds for—
[arabic]
.. Denial of an application for a certificate or rating issued under this part for a period of up to 1 year after the date of that act; or
              
.. Suspension or revocation of any certificate or rating issued under this part.

## § 63.12a - Refusal to submit to an alcohol test or to furnish test results.

A refusal to submit to a test to indicate the percentage by weight of alcohol in the blood, when requested by a law enforcement officer in accordance with § 91.11(c) of this chapter, or a refusal to furnish or authorize the release of the test results when requested by the Administrator in accordance with § 91.17 (c) or (d) of this chapter, is grounds for—

[loweralpha]
. Denial of an application for any certificate or rating issued under this part for a period of up to 1 year after the date of that refusal; or
. Suspension or revocation of any certificate or rating issued under this part.

## § 63.12b  - Reserved


Reserved

## § 63.13 - Temporary certificate.

A certificate effective for a period of not more than 120 days may be issued to a qualified applicant, pending review of his application and supplementary documents and the issue of the certificate for which he applied.

## § 63.14 - Security disqualification.

[loweralpha]
. *Eligibility standard.* No person is eligible to hold a certificate, rating, or authorization issued under this part when the Transportation Security Administration (TSA) has notified the FAA in writing that the person poses a security threat.
. *Effect of the issuance by the TSA of an Initial Notification of Threat Assessment.*
[arabic]
.. The FAA will hold in abeyance pending the outcome of the TSA's final threat assessment review an application for any certificate, rating, or authorization under this part by any person who has been issued an Initial Notification of Threat Assessment by the TSA.
.. The FAA will suspend any certificate, rating, or authorization issued under this part after the TSA issues to the holder an Initial Notification of Threat Assessment.
. *Effect of the issuance by the TSA of a Final Notification of Threat Assessment.*
[arabic]
.. The FAA will deny an application for any certificate, rating, or authorization under this part to any person who has been issued a Final Notification of Threat Assessment.
.. The FAA will revoke any certificate, rating, or authorization issued under this part after the TSA has issued to the holder a Final Notification of Threat Assessment.

## § 63.15 - Duration of certificates.

[loweralpha]
. Except as provided in § 63.23 and paragraph (b) of this section, a certificate or rating issued under this part is effective until it is surrendered, suspended, or revoked.
. A flight engineer certificate (with any amendment thereto) issued under § 63.42 expires at the end of the 24th month after the month in which the certificate was issued or renewed. However, the holder may exercise the privileges of that certificate only while the foreign flight engineer license on which that certificate is based is effective.
. Any certificate issued under this part ceases to be effective if it is surrendered, suspended, or revoked. The holder of any certificate issued under this part that is suspended or revoked shall, upon the Administrator's request, return it to the Administrator.
. Except for temporary certificate issued under § 63.13, the holder of a paper certificate issued under this part may not exercise the privileges of that certificate after March 31, 2013.

## § 63.15a - Reserved


Reserved

## § 63.16 - Change of name; replacement of lost or destroyed certificate.

[loweralpha]
. An application for a change of name on a certificate issued under this part must be accompanied by the applicant's current certificate and the marriage license, court order, or other document verifying the change. The documents are returned to the applicant after inspection.
. An application for a replacement of a lost or destroyed certificate is made by letter to the Department of Transportation, Federal Aviation Administration, Airman Certification Branch, Post Office Box 25082, Oklahoma City, OK 73125. The letter must—
[arabic]
.. Contain the name in which the certificate was issued, the permanent mailing address (including zip code), social security number (if any), and date and place of birth of the certificate holder, and any available information regarding the grade, number, and date of issue of the certificate, and the ratings on it; and
.. Be accompanied by a check or money order for $2, payable to the Federal Aviation Administration.
. An application for a replacement of a lost or destroyed medical certificate is made by letter to the Department of Transportation, Federal Aviation Administration, Civil Aeromedical Institute, Aeromedical Certification Branch, Post Office Box 25082, Oklahoma City, OK 73125, accompanied by a check or money order for $2.00.
. A person whose certificate issued under this part or medical certificate, or both, has been lost may obtain a telegram from the Federal Aviation Administration confirming that it was issued. The telegram may be carried as a certificate for a period not to exceed 60 days pending his receiving a duplicate under paragraph (b) or (c) of this section, unless he has been notified that the certificate has been suspended or revoked. The request for such a telegram may be made by prepaid telegram, stating the date upon which a duplicate certificate was requested, or including the request for a duplicate and a money order for the necessary amount. The request for a telegraphic certificate should be sent to the office prescribed in paragraph (b) or (c) of this section, as appropriate. However, a request for both at the same time should be sent to the office prescribed in paragraph (b) of this section.

## § 63.17 - Tests: General procedure.

[loweralpha]
. Tests prescribed by or under this part are given at times and places, and by persons, designated by the Administrator.
. The minimum passing grade for each test is 70 percent.

## § 63.18 - Written tests: Cheating or other unauthorized conduct.

[loweralpha]
. Except as authorized by the Administrator, no person may—
[arabic]
.. Copy, or intentionally remove, a written test under this part;
.. Give to another, or receive from another, any part or copy of that test;
.. Give help on that test to, or receive help on that test from, any person during the period that test is being given.
.. Take any part of that test in behalf of another person;
.. Use any material or aid during the period that test is being given; or
.. Intentionally cause, assist, or participate in any act prohibited by this paragraph.
. No person who commits an act prohibited by paragraph (a) of this section is eligible for any airman or ground instructor certificate or rating under this chapter for a period of 1 year after the date of that act. In addition, the commission of that act is a basis for suspending or revoking any airman or ground instructor certificate or rating held by that person.

## § 63.19 - Operations during physical deficiency.

No person may serve as a flight engineer or flight navigator during a period of known physical deficiency, or increase in physical deficiency, that would make him unable to meet the physical requirements for his current medical certificate.

## § 63.20 - Applications, certificates, logbooks, reports, and records; falsification, reproduction, or alteration.

[loweralpha]
. No person may make or cause to be made—
[arabic]
.. Any fraudulent or intentionally false statement on any application for a certificate or rating under this part;
.. Any fraudulent or intentionally false entry in any logbook, record, or report that is required to be kept, made, or used, to show compliance with any requirement for any certificate or rating under this part;
.. Any reproduction, for fraudulent purpose, of any certificate or rating under this part; or
.. Any alteration of any certificate or rating under this part.
. The commission by any person of an act prohibited under paragraph (a) of this section is a basis for suspending or revoking any airman or ground instructor certificate or rating held by that person.

## § 63.21 - Change of address.

Within 30 days after any change in his permanent mailing address, the holder of a certificate issued under this part shall notify the Department of Transportation, Federal Aviation Administration, Airman Certification Branch, Post Office Box 25082, Oklahoma City, OK 73125, in writing, of his new address.

## § 63.23 - Special purpose flight engineer and flight navigator certificates: Operation of U.S.-registered civil airplanes leased by a person not a U.S. citizen.

[loweralpha]
. *General.* The holder of a current foreign flight engineer or flight navigator certificate, license, or authorization issued by a foreign contracting State to the Convention on International Civil Aviation, who meets the requirements of this section, may hold a special purpose flight engineer or flight navigator certificate, as appropriate, authorizing the holder to perform flight engineer or flight navigator duties on a civil airplane of U.S. registry, leased to a person not a citizen of the United States, carrying persons or property for compensation or hire. Special purpose flight engineer and flight navigator certificates are issued under this section only for airplane types that can have a maximum passenger seating configuration, excluding any flight crewmember seat, of more than 30 seats or a maximum payload capacity (as defined in § 135.2(e) of this chapter) of more than 7,500 pounds.
. *Eligibility.* To be eligible for the issuance, or renewal, of a certificate under this section, an applicant must present the following to the Administrator:
[arabic]
.. A current foreign flight engineer or flight navigator certificate, license, or authorization issued by the aeronautical authority of a foreign contracting State to the Convention on International Civil Aviation or a facsimile acceptable to the Administrator. The certificate or license must authorize the applicant to perform the flight engineer or flight navigator duties to be authorized by a certificate issued under this section on the same airplane type as the leased airplane.
.. A current certification by the lessee of the airplane—
[lowerroman]
... Stating that the applicant is employed by the lessee;
... Specifying the airplane type on which the applicant will perform flight engineer or flight navigator duties; and
... Stating that the applicant has received ground and flight instruction which qualifies the applicant to perform the duties to be assigned on the airplane.
              
.. Documentation showing that the applicant currently meets the medical standards for the foreign flight engineer or flight navigator certificate, license, or authorization required by paragraph (b)(1) of this section, except that a U.S. medical certificate issued under part 67 of this chapter is not evidence that the applicant meets those standards unless the State which issued the applicant's foreign flight engineer or flight navigator certificate, license, or authorization accepts a U.S. medical certificate as evidence of medical fitness for a flight engineer or flight navigator certificate, license, or authorization.
. *Privileges.* The holder of a special purpose flight engineer or flight navigator certificate issued under this section may exercise the same privileges as those shown on the certificate, license, or authorization specified in paragraph (b)(1) of this section, subject to the limitations specified in this section.
. *Limitations.* Each certificate issued under this section is subject to the following limitations:
[arabic]
.. It is valid only—
[lowerroman]
... For flights between foreign countries and for flights in foreign air commerce;
... While it and the certificate, license, or authorization required by paragraph (b)(1) of this section are in the certificate holder's personal possession and are current;
... While the certificate holder is employed by the person to whom the airplane described in the certification required by paragraph (b)(2) of this section is leased;
... While the certificate holder is performing flight engineer or flight navigator duties on the U.S.-registered civil airplane described in the certification required by paragraph (b)(2) of this section; and
... While the medical documentation required by paragraph (b)(3) of this section is in the certificate holder's personal possession and is currently valid.
.. Each certificate issued under this section contains the following:
[lowerroman]
... The name of the person to whom the U.S.-registered civil airplane is leased.
... The type of airplane.
... The limitation: “Issued under, and subject to, § 63.23 of the Federal Aviation Regulations.”
... The limitation: “Subject to the privileges and limitations shown on the holder's foreign flight (engineer or navigator) certificate, license, or authorization.”
.. Any additional limitations placed on the certificate which the Administrator considers necessary.
. *Termination.* Each special purpose flight engineer or flight navigator certificate issued under this section terminates—
[arabic]
.. When the lease agreement for the airplane described in the certification required by paragraph (b)(2) of this section terminates;
.. When the foreign flight engineer or flight navigator certificate, license, or authorization, or the medical documentation required by paragraph (b) of this section is suspended, revoked, or no longer valid; or
.. After 24 months after the month in which the special purpose flight engineer or flight navigator certificate was issued.
. *Surrender of certificate.* The certificate holder shall surrender the special purpose flight engineer or flight navigator certificate to the Administrator within 7 days after the date it terminates.
. *Renewal.* The certificate holder may have the certificate renewed by complying with the requirements of paragraph (b) of this section at the time of application for renewal.

