# Airplane Performance Operating Limitations
:toc:

## § 135.361 - Applicability.

[loweralpha]
. This subpart prescribes airplane performance operating limitations applicable to the operation of the categories of airplanes listed in § 135.363 when operated under this part.
. For the purpose of this subpart, *effective length of the runway,* for landing means the distance from the point at which the obstruction clearance plane associated with the approach end of the runway intersects the centerline of the runway to the far end of the runway.
. For the purpose of this subpart, *obstruction clearance plane* means a plane sloping upward from the runway at a slope of 1:20 to the horizontal, and tangent to or clearing all obstructions within a specified area surrounding the runway as shown in a profile view of that area. In the plan view, the centerline of the specified area coincides with the centerline of the runway, beginning at the point where the obstruction clearance plane intersects the centerline of the runway and proceeding to a point at least 1,500 feet from the beginning point. After that the centerline coincides with the takeoff path over the ground for the runway (in the case of takeoffs) or with the instrument approach counterpart (for landings), or, where the applicable one of these paths has not been established, it proceeds consistent with turns of at least 4,000-foot radius until a point is reached beyond which the obstruction clearance plane clears all obstructions. This area extends laterally 200 feet on each side of the centerline at the point where the obstruction clearance plane intersects the runway and continues at this width to the end of the runway; then it increases uniformly to 500 feet on each side of the centerline at a point 1,500 feet from the intersection of the obstruction clearance plane with the runway; after that it extends laterally 500 feet on each side of the centerline.

## § 135.363 - General.

[loweralpha]
. Each certificate holder operating a reciprocating engine powered large transport category airplane shall comply with §§ 135.365 through 135.377.
. Each certificate holder operating a turbine engine powered large transport category airplane shall comply with §§ 135.379 through 135.387, except that when it operates a turbopropeller-powered large transport category airplane certificated after August 29, 1959, but previously type certificated with the same number of reciprocating engines, it may comply with §§ 135.365 through 135.377.
. Each certificate holder operating a large nontransport category airplane shall comply with §§ 135.389 through 135.395 and any determination of compliance must be based only on approved performance data. For the purpose of this subpart, a large nontrans- port category airplane is an airplane that was type certificated before July 1, 1942.
. Each certificate holder operating a small transport category airplane shall comply with § 135.397.
. Each certificate holder operating a small nontransport category airplane shall comply with § 135.399.
. The performance data in the Airplane Flight Manual applies in determining compliance with §§ 135.365 through 135.387. Where conditions are different from those on which the performance data is based, compliance is determined by interpolation or by computing the effects of change in the specific variables, if the results of the interpolation or computations are substantially as accurate as the results of direct tests.
. No person may take off a reciprocating engine powered large transport category airplane at a weight that is more than the allowable weight for the runway being used (determined under the runway takeoff limitations of the transport category operating rules of this subpart) after taking into account the temperature operating correction factors in section 4a.749a-T or section 4b.117 of the Civil Air Regulations in effect on January 31, 1965, and in the applicable Airplane Flight Manual.
. The Administrator may author- ize in the operations specifications deviations from this subpart if special circumstances make a literal observ- ance of a requirement unnecessary for safety.
[lowerroman]
.. The 10-mile width specified in §§ 135.369 through 135.373 may be reduced to 5 miles, for not more than 20 miles, when operating under VFR or where navigation facilities furnish reliable and accurate identification of high ground and obstructions located outside of 5 miles, but within 10 miles, on each side of the intended track.

(j) Each certificate holder operating a commuter category airplane shall comply with § 135.398.

## § 135.364 - Maximum flying time outside the United States.

After August 13, 2008, no certificate holder may operate an airplane, other than an all-cargo airplane with more than two engines, on a planned route that exceeds 180 minutes flying time (at the one-engine-inoperative cruise speed under standard conditions in still air) from an Adequate Airport outside the continental United States unless the operation is approved by the FAA in accordance with Appendix G of this part, Extended Operations (ETOPS).

## § 135.365 - Large transport category airplanes: Reciprocating engine powered: Weight limitations.

[loweralpha]
. No person may take off a reciprocating engine powered large transport category airplane from an airport located at an elevation outside of the range for which maximum takeoff weights have been determined for that airplane.
. No person may take off a reciprocating engine powered large transport category airplane for an airport of intended destination that is located at an elevation outside of the range for which maximum landing weights have been determined for that airplane.
. No person may specify, or have specified, an alternate airport that is located at an elevation outside of the range for which maximum landing weights have been determined for the reciprocating engine powered large transport category airplane concerned.
              
. No person may take off a reciprocating engine powered large transport category airplane at a weight more than the maximum authorized takeoff weight for the elevation of the airport.
. No person may take off a reciprocating engine powered large transport category airplane if its weight on arrival at the airport of destination will be more than the maximum authorized landing weight for the elevation of that airport, allowing for normal consumption of fuel and oil en route.

## § 135.367 - Large transport category airplanes: Reciprocating engine powered: Takeoff limitations.

[loweralpha]
. No person operating a reciprocating engine powered large transport category airplane may take off that airplane unless it is possible—
[arabic]
.. To stop the airplane safely on the runway, as shown by the accelerate-stop distance data, at any time during takeoff until reaching critical-engine failure speed;
.. If the critical engine fails at any time after the airplane reaches critical-engine failure speed V*1*, to continue the takeoff and reach a height of 50 feet, as indicated by the takeoff path data, before passing over the end of the runway; and
.. To clear all obstacles either by at least 50 feet vertically (as shown by the takeoff path data) or 200 feet horizontally within the airport boundaries and 300 feet horizontally beyond the boundaries, without banking before reaching a height of 50 feet (as shown by the takeoff path data) and after that without banking more than 15 degrees.
. In applying this section, corrections must be made for any runway gradient. To allow for wind effect, takeoff data based on still air may be corrected by taking into account not more than 50 percent of any reported headwind component and not less than 150 percent of any reported tailwind component.

## § 135.369 - Large transport category airplanes: Reciprocating engine powered: En route limitations: All engines operating.

[loweralpha]
. No person operating a reciprocating engine powered large transport category airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that does not allow a rate of climb (in feet per minute), with all engines operating, of at least 6.90 Vs*o* (that is, the number of feet per minute obtained by multiplying the number of knots by 6.90) at an altitude of a least 1,000 feet above the highest ground or obstruction within ten miles of each side of the intended track.
. This section does not apply to large transport category airplanes certificated under part 4a of the Civil Air Regulations.

## § 135.371 - Large transport category airplanes: Reciprocating engine powered: En route limitations: One engine inoperative.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person operating a reciprocating engine powered large transport category airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that does not allow a rate of climb (in feet per minute), with one engine inoperative, of at least (0.079−0.106/N) Vs*o*2 (where N is the number of engines installed and Vs*o* is expressed in knots) at an altitude of least 1,000 feet above the highest ground or obstruction within 10 miles of each side of the intended track. However, for the purposes of this paragraph the rate of climb for transport category airplanes certificated under part 4a of the Civil Air Regulations is 0.026 Vs*o*2.
. In place of the requirements of paragraph (a) of this section, a person may, under an approved procedure, operate a reciprocating engine powered large transport category airplane at an all-engines-operating altitude that allows the airplane to continue, after an engine failure, to an alternate airport where a landing can be made under § 135.377, allowing for normal consumption of fuel and oil. After the assumed failure, the flight path must clear the ground and any obstruction within five miles on each side of the intended track by at least 2,000 feet.
. If an approved procedure under paragraph (b) of this section is used, the certificate holder shall comply with the following:
              
[arabic]
.. The rate of climb (as prescribed in the Airplane Flight Manual for the appropriate weight and altitude) used in calculating the airplane's flight path shall be diminished by an amount in feet per minute, equal to (0.079−0.106/N) Vs*o*2 (when N is the number of engines installed and Vs*o* is expressed in knots) for airplanes certificated under part 25 of this chapter and by 0.026 Vs*o*2 for airplanes certificated under part 4a of the Civil Air Regulations.
.. The all-engines-operating altitude shall be sufficient so that in the event the critical engine becomes inoperative at any point along the route, the flight will be able to proceed to a predetermined alternate airport by use of this procedure. In determining the takeoff weight, the airplane is assumed to pass over the critical obstruction following engine failure at a point no closer to the critical obstruction than the nearest approved navigational fix, unless the Administrator approves a procedure established on a different basis upon finding that adequate operational safeguards exist.
.. The airplane must meet the provisions of paragraph (a) of this section at 1,000 feet above the airport used as an alternate in this procedure.
.. The procedure must include an approved method of accounting for winds and temperatures that would otherwise adversely affect the flight path.
.. In complying with this procedure, fuel jettisoning is allowed if the certificate holder shows that it has an adequate training program, that proper instructions are given to the flight crew, and all other precautions are taken to ensure a safe procedure.
.. The certificate holder and the pilot in command shall jointly elect an alternate airport for which the appropriate weather reports or forecasts, or any combination of them, indicate that weather conditions will be at or above the alternate weather minimum specified in the certificate holder's operations specifications for that airport when the flight arrives.

## § 135.373 - Part 25 transport category airplanes with four or more engines: Reciprocating engine powered: En route limitations: Two engines inoperative.

[loweralpha]
. No person may operate an airplane certificated under part 25 and having four or more engines unless—
[arabic]
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets § 135.377; or
.. It is operated at a weight allowing the airplane, with the two critical engines inoperative, to climb at 0.013 Vs*o*2 feet per minute (that is, the number of feet per minute obtained by multiplying the number of knots squared by 0.013) at an altitude of 1,000 feet above the highest ground or obstruction within 10 miles on each side of the intended track, or at an altitude of 5,000 feet, whichever is higher.
. For the purposes of paragraph (a)(2) of this section, it is assumed that—
[arabic]
.. The two engines fail at the point that is most critical with respect to the takeoff weight;
.. Consumption of fuel and oil is normal with all engines operating up to the point where the two engines fail with two engines operating beyond that point;
.. Where the engines are assumed to fail at an altitude above the prescribed minimum altitude, compliance with the prescribed rate of climb at the prescribed minimum altitude need not be shown during the descent from the cruising altitude to the prescribed minimum altitude, if those requirements can be met once the prescribed minimum altitude is reached, and assuming descent to be along a net flight path and the rate of descent to be 0.013 Vs*o*2 greater than the rate in the approved performance data; and
.. If fuel jettisoning is provided, the airplane's weight at the point where the two engines fail is considered to be not less than that which would include enough fuel to proceed to an airport meeting § 135.377 and to arrive at an altitude of at least 1,000 feet directly over that airport.

## § 135.375 - Large transport category airplanes: Reciprocating engine powered: Landing limitations: Destination airports.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person operating a reciprocating engine powered large transport category airplane may take off that airplane, unless its weight on arrival, allowing for normal consumption of fuel and oil in flight, would allow a full stop landing at the intended destination within 60 percent of the effective length of each runway described below from a point 50 feet directly above the intersection of the obstruction clearance plane and the runway. For the purposes of determining the allowable landing weight at the destination airport the following is assumed:
[arabic]
.. The airplane is landed on the most favorable runway and in the most favorable direction in still air.
.. The airplane is landed on the most suitable runway considering the probable wind velocity and direction (forecast for the expected time of arrival), the ground handling characteristics of the type of airplane, and other conditions such as landing aids and terrain, and allowing for the effect of the landing path and roll of not more than 50 percent of the headwind component or not less than 150 percent of the tailwind component.
. An airplane that would be prohibited from being taken off because it could not meet paragraph (a)(2) of this section may be taken off if an alternate airport is selected that meets all of this section except that the airplane can accomplish a full stop landing within 70 percent of the effective length of the runway.

## § 135.377 - Large transport category airplanes: Reciprocating engine powered: Landing limitations: Alternate airports.

No person may list an airport as an alternate airport in a flight plan unless the airplane (at the weight anticipated at the time of arrival at the airport), based on the assumptions in § 135.375(a) (1) and (2), can be brought to a full stop landing within 70 percent of the effective length of the runway.

## § 135.379 - Large transport category airplanes: Turbine engine powered: Takeoff limitations.

[loweralpha]
. No person operating a turbine engine powered large transport category airplane may take off that airplane at a weight greater than that listed in the Airplane Flight Manual for the elevation of the airport and for the ambient temperature existing at take- off.
. No person operating a turbine engine powered large transport category airplane certificated after August 26, 1957, but before August 30, 1959 (SR422, 422A), may take off that airplane at a weight greater than that listed in the Airplane Flight Manual for the minimum distance required for takeoff. In the case of an airplane certificated after September 30, 1958 (SR422A, 422B), the takeoff distance may include a clearway distance but the clearway distance included may not be greater than one-half of the takeoff run.
. No person operating a turbine engine powered large transport category airplane certificated after August 29, 1959 (SR422B), may take off that airplane at a weight greater than that listed in the Airplane Flight Manual at which compliance with the following may be shown:
[arabic]
.. The accelerate-stop distance, as defined in § 25.109 of this chapter, must not exceed the length of the runway plus the length of any stopway.
.. The takeoff distance must not exceed the length of the runway plus the length of any clearway except that the length of any clearway included must not be greater than one-half the length of the runway.
.. The takeoff run must not be greater than the length of the runway.
. No person operating a turbine engine powered large transport category airplane may take off that airplane at a weight greater than that listed in the Airplane Flight Manual—
[arabic]
.. For an airplane certificated after August 26, 1957, but before October 1, 1958 (SR422), that allows a takeoff path that clears all obstacles either by at least (35 + 0.01 D) feet vertically (D is the distance along the intended flight path from the end of the runway in feet), or by at least 200 feet horizontally within the airport boundaries and by at least 300 feet horizontally after passing the boundaries; or
.. For an airplane certificated after September 30, 1958 (SR422A, 422B), that allows a net takeoff flight path that clears all obstacles either by a height of at least 35 feet vertically, or by at least 200 feet horizontally within the airport boundaries and by at least 300 feet horizontally after passing the boundaries.
. In determining maximum weights, minimum distances, and flight paths under paragraphs (a) through (d) of this section, correction must be made for the runway to be used, the elevation of the airport, the effective runway gradient, the ambient temperature and wind component at the time of takeoff, and, if operating limitations exist for the minimum distances required for takeoff from wet runways, the runway surface condition (dry or wet). Wet runway distances associated with grooved or porous friction course runways, if provided in the Airplane Flight Manual, may be used only for runways that are grooved or treated with a porous friction course (PFC) overlay, and that the operator determines are designed, constructed, and maintained in a manner acceptable to the Administrator.
. For the purposes of this section, it is assumed that the airplane is not banked before reaching a height of 50 feet, as shown by the takeoff path or net takeoff flight path data (as appropriate) in the Airplane Flight Manual, and after that the maximum bank is not more than 15 degrees.
. For the purposes of this section, the terms, *takeoff distance, takeoff run, net takeoff flight path,* have the same meanings as set forth in the rules under which the airplane was certificated.

## § 135.381 - Large transport category airplanes: Turbine engine powered: En route limitations: One engine inoperative.

[loweralpha]
. No person operating a turbine engine powered large transport category airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that is greater than that which (under the approved, one engine inoperative, en route net flight path data in the Airplane Flight Manual for that airplane) will allow compliance with paragraph (a) (1) or (2) of this section, based on the ambient temperatures expected en route.
[arabic]
.. There is a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within five statute miles on each side of the intended track, and, in addition, if that airplane was certificated after August 29, 1958 (SR422B), there is a positive slope at 1,500 feet above the airport where the airplane is assumed to land after an engine fails.
.. The net flight path allows the airplane to continue flight from the cruising altitude to an airport where a landing can be made under § 135.387 clearing all terrain and obstructions within five statute miles of the intended track by at least 2,000 feet vertically and with a positive slope at 1,000 feet above the airport where the airplane lands after an engine fails, or, if that airplane was certificated after September 30, 1958 (SR422A, 422B), with a positive slope at 1,500 feet above the airport where the airplane lands after an engine fails.
. For the purpose of paragraph (a)(2) of this section, it is assumed that—
[arabic]
.. The engine fails at the most critical point en route;
.. The airplane passes over the critical obstruction, after engine failure at a point that is no closer to the obstruction than the approved navigation fix, unless the Administrator authorizes a different procedure based on adequate operational safeguards;
.. An approved method is used to allow for adverse winds;
.. Fuel jettisoning will be allowed if the certificate holder shows that the crew is properly instructed, that the training program is adequate, and that all other precautions are taken to ensure a safe procedure;
.. The alternate airport is selected and meets the prescribed weather minimums; and
.. The consumption of fuel and oil after engine failure is the same as the consumption that is allowed for in the approved net flight path data in the Airplane Flight Manual.

## § 135.383 - Large transport category airplanes: Turbine engine powered: En route limitations: Two engines inoperative.

[loweralpha]
. Airplanes certificated after August 26, 1957, but before October 1, 1958 (SR422). No person may operate a turbine engine powered large transport category airplane along an intended route unless that person complies with either of the following:
[arabic]
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets § 135.387.
.. Its weight, according to the two-engine-inoperative, en route, net flight path data in the Airplane Flight Manual, allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets § 135.387, with a net flight path (considering the ambient temperature anticipated along the track) having a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within five statute miles on each side of the intended track, or at an altitude of 5,000 feet, whichever is higher.
              
. Airplanes certificated after September 30, 1958, but before August 30, 1959 (SR422A). No person may operate a turbine engine powered large transport category airplane along an intended route unless that person complies with either of the following:
[arabic]
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets § 135.387.
.. Its weight, according to the two-engine-inoperative, en route, net flight path data in the Airplane Flight Manual allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets § 135.387 with a net flight path (considering the ambient temperatures anticipated along the track) having a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within five statute miles on each side of the intended track, or at an altitude of 2,000 feet, whichever is higher.
              
. Aircraft certificated after August 29, 1959 (SR422B). No person may operate a turbine engine powered large transport category airplane along an intended route unless that person complies with either of the following:
[arabic]
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets § 135.387.
.. Its weight, according to the two-engine-inoperative, en route, net flight path data in the Airplane Flight Manual, allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets § 135.387, with the net flight path (considering the ambient temperatures anticipated along the track) clearing vertically by at least 2,000 feet all terrain and obstructions within five statute miles on each side of the intended track. For the purposes of this paragraph, it is assumed that—
[lowerroman]
... The two engines fail at the most critical point en route;
... The net flight path has a positive slope at 1,500 feet above the airport where the landing is assumed to be made after the engines fail;
... Fuel jettisoning will be approved if the certificate holder shows that the crew is properly instructed, that the training program is adequate, and that all other precautions are taken to ensure a safe procedure;
... The airplane's weight at the point where the two engines are assumed to fail provides enough fuel to continue to the airport, to arrive at an altitude of at least 1,500 feet directly over the airport, and after that to fly for 15 minutes at cruise power or thrust, or both; and
... The consumption of fuel and oil after the engines fail is the same as the consumption that is allowed for in the net flight path data in the Airplane Flight Manual.

## § 135.385 - Large transport category airplanes: Turbine engine powered: Landing limitations: Destination airports.

[loweralpha]
. No person operating a turbine engine powered large transport category airplane may take off that airplane at a weight that (allowing for normal consumption of fuel and oil in flight to the destination or alternate airport) the weight of the airplane on arrival would exceed the landing weight in the Airplane Flight Manual for the elevation of the destination or alternate airport and the ambient temperature anticipated at the time of landing.
. Except as provided in paragraph (c), (d), (e), or (f) of this section, no person operating a turbine engine powered large transport category airplane may take off that airplane unless its weight on arrival, allowing for normal consumption of fuel and oil in flight (in accordance with the landing distance in the Airplane Flight Manual for the elevation of the destination airport and the wind conditions expected there at the time of landing), would allow a full stop landing at the intended destination airport within 60 percent of the effective length of each runway described below from a point 50 feet above the intersection of the obstruction clearance plane and the runway. For the purpose of determining the allowable landing weight at the destination airport the following is assumed:
[arabic]
.. The airplane is landed on the most favorable runway and in the most favorable direction, in still air.
.. The airplane is landed on the most suitable runway considering the probable wind velocity and direction and the ground handling characteristics of the airplane, and considering other conditions such as landing aids and terrain.
. A turbopropeller powered airplane that would be prohibited from being taken off because it could not meet paragraph (b)(2) of this section, may be taken off if an alternate airport is selected that meets all of this section except that the airplane can accomplish a full stop landing within 70 percent of the effective length of the runway.
. Unless, based on a showing of actual operating landing techniques on wet runways, a shorter landing distance (but never less than that required by paragraph (b) of this section) has been approved for a specific type and model airplane and included in the Airplane Flight Manual, no person may take off a turbojet airplane when the appropriate weather reports or forecasts, or any combination of them, indicate that the runways at the destination airport may be wet or slippery at the estimated time of arrival unless the effective runway length at the destination airport is at least 115 percent of the runway length required under paragraph (b) of this section.
. A turbojet airplane that would be prohibited from being taken off because it could not meet paragraph (b)(2) of this section may be taken off if an alternate airport is selected that meets all of paragraph (b) of this section.
. An eligible on-demand operator may take off a turbine engine powered large transport category airplane on an on-demand flight if all of the following conditions exist:
[arabic]
.. The operation is permitted by an approved Destination Airport Analysis in that person's operations manual.
              
.. The airplane's weight on arrival, allowing for normal consumption of fuel and oil in flight (in accordance with the landing distance in the Airplane Flight Manual for the elevation of the destination airport and the wind conditions expected there at the time of landing), would allow a full stop landing at the intended destination airport within 80 percent of the effective length of each runway described below from a point 50 feet above the intersection of the obstruction clearance plane and the runway. For the purpose of determining the allowable landing weight at the destination airport, the following is assumed:
[lowerroman]
... The airplane is landed on the most favorable runway and in the most favorable direction, in still air.
... The airplane is landed on the most suitable runway considering the probable wind velocity and direction and the ground handling characteristics of the airplane, and considering other conditions such as landing aids and terrain.
.. The operation is authorized by operations specifications.

## § 135.387 - Large transport category airplanes: Turbine engine powered: Landing limitations: Alternate airports.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person may select an airport as an alternate airport for a turbine engine powered large transport category airplane unless (based on the assumptions in § 135.385(b)) that airplane, at the weight expected at the time of arrival, can be brought to a full stop landing within 70 percent of the effective length of the runway for turbo-propeller-powered airplanes and 60 percent of the effective length of the runway for turbojet airplanes, from a point 50 feet above the intersection of the obstruction clearance plane and the runway.
. Eligible on-demand operators may select an airport as an alternate airport for a turbine engine powered large transport category airplane if (based on the assumptions in § 135.385(f)) that airplane, at the weight expected at the time of arrival, can be brought to a full stop landing within 80 percent of the effective length of the runway from a point 50 feet above the intersection of the obstruction clearance plane and the runway.

## § 135.389 - Large nontransport category airplanes: Takeoff limitations.

[loweralpha]
. No person operating a large nontransport category airplane may take off that airplane at a weight greater than the weight that would allow the airplane to be brought to a safe stop within the effective length of the runway, from any point during the takeoff before reaching 105 percent of minimum control speed (the minimum speed at which an airplane can be safely controlled in flight after an engine becomes inoperative) or 115 percent of the power off stalling speed in the takeoff configuration, whichever is greater.
. For the purposes of this section—
[arabic]
.. It may be assumed that takeoff power is used on all engines during the acceleration;
.. Not more than 50 percent of the reported headwind component, or not less than 150 percent of the reported tailwind component, may be taken into account;
.. The average runway gradient (the difference between the elevations of the endpoints of the runway divided by the total length) must be considered if it is more than one-half of one percent;
.. It is assumed that the airplane is operating in standard atmosphere; and
.. For takeoff, *effective length of the runway* means the distance from the end of the runway at which the takeoff is started to a point at which the obstruction clearance plane associated with the other end of the runway intersects the runway centerline.

## § 135.391 - Large nontransport category airplanes: En route limitations: One engine inoperative.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person operating a large nontransport category airplane may take off that airplane at a weight that does not allow a rate of climb of at least 50 feet a minute, with the critical engine inoperative, at an altitude of at least 1,000 feet above the highest obstruction within five miles on each side of the intended track, or 5,000 feet, whichever is higher.
. Without regard to paragraph (a) of this section, if the Administrator finds that safe operations are not impaired, a person may operate the airplane at an altitude that allows the airplane, in case of engine failure, to clear all obstructions within five miles on each side of the intended track by 1,000 feet. If this procedure is used, the rate of descent for the appropriate weight and altitude is assumed to be 50 feet a minute greater than the rate in the approved performance data. Before approving such a procedure, the Administrator considers the following for the route, route segement, or area concerned:
[arabic]
.. The reliability of wind and weather forecasting.
.. The location and kinds of navigation aids.
.. The prevailing weather conditions, particularly the frequency and amount of turbulence normally encountered.
.. Terrain features.
.. Air traffic problems.
.. Any other operational factors that affect the operations.
. For the purposes of this section, it is assumed that—
[arabic]
.. The critical engine is inoperative;
.. The propeller of the inoperative engine is in the minimum drag position;
.. The wing flaps and landing gear are in the most favorable position;
.. The operating engines are operating at the maximum continuous power available;
.. The airplane is operating in standard atmosphere; and
.. The weight of the airplane is progressively reduced by the anticipated consumption of fuel and oil.

## § 135.393 - Large nontransport category airplanes: Landing limitations: Destination airports.

[loweralpha]
. No person operating a large nontransport category airplane may take off that airplane at a weight that—
[arabic]
.. Allowing for anticipated consumption of fuel and oil, is greater than the weight that would allow a full stop landing within 60 percent of the effective length of the most suitable runway at the destination airport; and
.. Is greater than the weight allowable if the landing is to be made on the runway—
[lowerroman]
... With the greatest effective length in still air; and
... Required by the probable wind, taking into account not more than 50 percent of the headwind component or not less than 150 percent of the tailwind component.
. For the purpose of this section, it is assumed that—
[arabic]
.. The airplane passes directly over the intersection of the obstruction clearance plane and the runway at a height of 50 feet in a steady gliding approach at a true indicated airspeed of at least 1.3 V*so*;
.. The landing does not require exceptional pilot skill; and
.. The airplane is operating in standard atmosphere.

## § 135.395 - Large nontransport category airplanes: Landing limitations: Alternate airports.

No person may select an airport as an alternate airport for a large nontransport category airplane unless that airplane (at the weight anticipated at the time of arrival), based on the assumptions in § 135.393(b), can be brought to a full stop landing within 70 percent of the effective length of the runway.

## § 135.397 - Small transport category airplane performance operating limitations.

[loweralpha]
. No person may operate a reciprocating engine powered small transport category airplane unless that person complies with the weight limitations in § 135.365, the takeoff limitations in § 135.367 (except paragraph (a)(3)), and the landing limitations in §§ 135.375 and 135.377.
. No person may operate a turbine engine powered small transport category airplane unless that person complies with the takeoff limitations in § 135.379 (except paragraphs (d) and (f)) and the landing limitations in §§ 135.385 and 135.387.

## § 135.398 - Commuter category airplanes performance operating limitations.

[loweralpha]
. No person may operate a commuter category airplane unless that person complies with the takeoff weight limitations in the approved Airplane Flight Manual.
. No person may take off an airplane type certificated in the commuter category at a weight greater than that listed in the Airplane Flight Manual that allows a net takeoff flight path that clears all obstacles either by a height of at least 35 feet vertically, or at least 200 feet horizontally within the airport boundaries and by at least 300 feet horizontally after passing the boundaries.
. No person may operate a commuter category airplane unless that person complies with the landing limitations prescribed in §§ 135.385 and 135.387 of this part. For purposes of this paragraph, §§ 135.385 and 135.387 are applicable to all commuter category airplanes notwithstanding their stated applicability to turbine-engine-powered large transport category airplanes.
. In determining maximum weights, minimum distances and flight paths under paragraphs (a) through (c) of this section, correction must be made for the runway to be used, the elevation of the airport, the effective runway gradient, and ambient temperature, and wind component at the time of takeoff.
. For the purposes of this section, the assumption is that the airplane is not banked before reaching a height of 50 feet as shown by the net takeoff flight path data in the Airplane Flight Manual and thereafter the maximum bank is not more than 15 degrees.

## § 135.399 - Small nontransport category airplane performance operating limitations.

[loweralpha]
. No person may operate a reciprocating engine or turbopropeller-powered small airplane that is certificated under § 135.169(b) (2), (3), (4), (5), or (6) unless that person complies with the takeoff weight limitations in the approved Airplane Flight Manual or equivalent for operations under this part, and, if the airplane is certificated under § 135.169(b) (4) or (5) with the landing weight limitations in the Approved Airplane Flight Manual or equivalent for operations under this part.
. No person may operate an airplane that is certificated under § 135.169(b)(6) unless that person complies with the landing limitations prescribed in §§ 135.385 and 135.387 of this part. For purposes of this paragraph, §§ 135.385 and 135.387 are applicable to reciprocating and turbopropeller-powered small airplanes notwithstanding their stated applicability to turbine engine powered large transport category airplanes.

