# Equipment, Instrument, and Certificate Requirements
:toc:

## § 91.201 - Reserved


Reserved

## § 91.203 - Civil aircraft: Certifications required.

[loweralpha]
. Except as provided in § 91.715, no person may operate a civil aircraft unless it has within it the following:
[arabic]
.. An appropriate and current airworthiness certificate. Each U.S. airworthiness certificate used to comply with this subparagraph (except a special flight permit, a copy of the applicable operations specifications issued under § 21.197(c) of this chapter, appropriate sections of the air carrier manual required by parts 121 and 135 of this chapter containing that portion of the operations specifications issued under § 21.197(c), or an authorization under § 91.611) must have on it the registration number assigned to the aircraft under part 47 of this chapter. However, the airworthiness certificate need not have on it an assigned special identification number before 10 days after that number is first affixed to the aircraft. A revised airworthiness certificate having on it an assigned special identification number, that has been affixed to an aircraft, may only be obtained upon application to an FAA Flight Standards district office.
.. An effective U.S. registration certificate issued to its owner or, for operation within the United States, the second copy of the Aircraft registration Application as provided for in § 47.31(c), a Certificate of Aircraft registration as provided in part 48, or a registration certification issued under the laws of a foreign country.
. No person may operate a civil aircraft unless the airworthiness certificate required by paragraph (a) of this section or a special flight authorization issued under § 91.715 is displayed at the cabin or cockpit entrance so that it is legible to passengers or crew.
. No person may operate an aircraft with a fuel tank installed within the passenger compartment or a baggage compartment unless the installation was accomplished pursuant to part 43 of this chapter, and a copy of FAA Form 337 authorizing that installation is on board the aircraft.
. No person may operate a civil airplane (domestic or foreign) into or out of an airport in the United States unless it complies with the fuel venting and exhaust emissions requirements of part 34 of this chapter.

## § 91.205 - Powered civil aircraft with standard category U.S. airworthiness certificates: Instrument and equipment requirements.

[loweralpha]
. *General.* Except as provided in paragraphs (c)(3) and (e) of this section, no person may operate a powered civil aircraft with a standard category U.S. airworthiness certificate in any operation described in paragraphs (b) through (f) of this section unless that aircraft contains the instruments and equipment specified in those paragraphs (or FAA-approved equivalents) for that type of operation, and those instruments and items of equipment are in operable condition.
. *Visual-flight rules (day).* For VFR flight during the day, the following instruments and equipment are required:
[arabic]
.. Airspeed indicator.
.. Altimeter.
.. Magnetic direction indicator.
.. Tachometer for each engine.
.. Oil pressure gauge for each engine using pressure system.
.. Temperature gauge for each liquid-cooled engine.
.. Oil temperature gauge for each air-cooled engine.
.. Manifold pressure gauge for each altitude engine.
.. Fuel gauge indicating the quantity of fuel in each tank.
.. Landing gear position indicator, if the aircraft has a retractable landing gear.
.. For small civil airplanes certificated after March 11, 1996, in accordance with part 23 of this chapter, an approved aviation red or aviation white anticollision light system. In the event of failure of any light of the anticollision light system, operation of the aircraft may continue to a location where repairs or replacement can be made.
.. If the aircraft is operated for hire over water and beyond power-off gliding distance from shore, approved flotation gear readily available to each occupant and, unless the aircraft is operating under part 121 of this subchapter, at least one pyrotechnic signaling device. As used in this section, “shore” means that area of the land adjacent to the water which is above the high water mark and excludes land areas which are intermittently under water.
.. An approved safety belt with an approved metal-to-metal latching device for each occupant 2 years of age or older.
.. For small civil airplanes manufactured after July 18, 1978, an approved shoulder harness for each front seat. The shoulder harness must be designed to protect the occupant from serious head injury when the occupant experiences the ultimate inertia forces specified in § 23.561(b)(2) of this chapter. Each shoulder harness installed at a flight crewmember station must permit the crewmember, when seated and with the safety belt and shoulder harness fastened, to perform all functions necessary for flight operations. For purposes of this paragraph—
[lowerroman]
... The date of manufacture of an airplane is the date the inspection acceptance records reflect that the airplane is complete and meets the FAA-approved type design data; and
... A front seat is a seat located at a flight crewmember station or any seat located alongside such a seat.
.. An emergency locator transmitter, if required by § 91.207.
.. For normal, utility, and acrobatic category airplanes with a seating configuration, excluding pilot seats, of 9 or less, manufactured after December 12, 1986, a shoulder harness for—
[lowerroman]
... Each front seat that meets the requirements of § 23.785 (g) and (h) of this chapter in effect on December 12, 1985;
... Each additional seat that meets the requirements of § 23.785(g) of this chapter in effect on December 12, 1985.
.. For rotorcraft manufactured after September 16, 1992, a shoulder harness for each seat that meets the requirements of § 27.2 or § 29.2 of this chapter in effect on September 16, 1991.
. *Visual flight rules (night).* For VFR flight at night, the following instruments and equipment are required:
[arabic]
.. Instruments and equipment specified in paragraph (b) of this section.
.. Approved position lights.
.. An approved aviation red or aviation white anticollision light system on all U.S.-registered civil aircraft. Anticollision light systems initially installed after August 11, 1971, on aircraft for which a type certificate was issued or applied for before August 11, 1971, must at least meet the anticollision light standards of part 23, 25, 27, or 29 of this chapter, as applicable, that were in effect on August 10, 1971, except that the color may be either aviation red or aviation white. In the event of failure of any light of the anticollision light system, operations with the aircraft may be continued to a stop where repairs or replacement can be made.
.. If the aircraft is operated for hire, one electric landing light.
.. An adequate source of electrical energy for all installed electrical and radio equipment.
.. One spare set of fuses, or three spare fuses of each kind required, that are accessible to the pilot in flight.
. *Instrument flight rules.* For IFR flight, the following instruments and equipment are required:
[arabic]
.. Instruments and equipment specified in paragraph (b) of this section, and, for night flight, instruments and equipment specified in paragraph (c) of this section.
.. Two-way radio communication and navigation equipment suitable for the route to be flown.
.. Gyroscopic rate-of-turn indicator, except on the following aircraft:
[lowerroman]
... Airplanes with a third attitude instrument system usable through flight attitudes of 360 degrees of pitch and roll and installed in accordance with the instrument requirements prescribed in § 121.305(j) of this chapter; and
... Rotorcraft with a third attitude instrument system usable through flight attitudes of ±80 degrees of pitch and ±120 degrees of roll and installed in accordance with § 29.1303(g) of this chapter.
.. Slip-skid indicator.
.. Sensitive altimeter adjustable for barometric pressure.
.. A clock displaying hours, minutes, and seconds with a sweep-second pointer or digital presentation.
.. Generator or alternator of adequate capacity.
.. Gyroscopic pitch and bank indicator (artificial horizon).
.. Gyroscopic direction indicator (directional gyro or equivalent).
. *Flight at and above 24,000 feet MSL (FL 240).* If VOR navigation equipment is required under paragraph (d)(2) of this section, no person may operate a U.S.-registered civil aircraft within the 50 states and the District of Columbia at or above FL 240 unless that aircraft is equipped with approved DME or a suitable RNAV system. When the DME or RNAV system required by this paragraph fails at and above FL 240, the pilot in command of the aircraft must notify ATC immediately, and then may continue operations at and above FL 240 to the next airport of intended landing where repairs or replacement of the equipment can be made.
. *Category II operations.* The requirements for Category II operations are the instruments and equipment specified in—
[arabic]
.. Paragraph (d) of this section; and
.. Appendix A to this part.
. *Category III operations.* The instruments and equipment required for Category III operations are specified in paragraph (d) of this section.
. *Night vision goggle operations.* For night vision goggle operations, the following instruments and equipment must be installed in the aircraft, functioning in a normal manner, and approved for use by the FAA:
[arabic]
.. Instruments and equipment specified in paragraph (b) of this section, instruments and equipment specified in paragraph (c) of this section;
.. Night vision goggles;
.. Interior and exterior aircraft lighting system required for night vision goggle operations;
.. Two-way radio communications system;
.. Gyroscopic pitch and bank indicator (artificial horizon);
.. Generator or alternator of adequate capacity for the required instruments and equipment; and
.. Radar altimeter.
              
[lowerroman]
... *Exclusions.* Paragraphs (f) and (g) of this section do not apply to operations conducted by a holder of a certificate issued under part 121 or part 135 of this chapter.

## § 91.207 - Emergency locator transmitters.

[loweralpha]
. Except as provided in paragraphs (e) and (f) of this section, no person may operate a U.S.-registered civil airplane unless—
[arabic]
.. There is attached to the airplane an approved automatic type emergency locator transmitter that is in operable condition for the following operations, except that after June 21, 1995, an emergency locator transmitter that meets the requirements of TSO-C91 may not be used for new installations:
[lowerroman]
... Those operations governed by the supplemental air carrier and commercial operator rules of parts 121 and 125;
... Charter flights governed by the domestic and flag air carrier rules of part 121 of this chapter; and
... Operations governed by part 135 of this chapter; or
.. For operations other than those specified in paragraph (a)(1) of this section, there must be attached to the airplane an approved personal type or an approved automatic type emergency locator transmitter that is in operable condition, except that after June 21, 1995, an emergency locator transmitter that meets the requirements of TSO-C91 may not be used for new installations.
. Each emergency locator transmitter required by paragraph (a) of this section must be attached to the airplane in such a manner that the probability of damage to the transmitter in the event of crash impact is minimized. Fixed and deployable automatic type transmitters must be attached to the airplane as far aft as practicable.
. Batteries used in the emergency locator transmitters required by paragraphs (a) and (b) of this section must be replaced (or recharged, if the batteries are rechargeable)—
[arabic]
.. When the transmitter has been in use for more than 1 cumulative hour; or
.. When 50 percent of their useful life (or, for rechargeable batteries, 50 percent of their useful life of charge) has expired, as established by the transmitter manufacturer under its approval.
              
. Each emergency locator transmitter required by paragraph (a) of this section must be inspected within 12 calendar months after the last inspection for—
[arabic]
.. Proper installation;
.. Battery corrosion;
.. Operation of the controls and crash sensor; and
.. The presence of a sufficient signal radiated from its antenna.
. Notwithstanding paragraph (a) of this section, a person may—
[arabic]
.. Ferry a newly acquired airplane from the place where possession of it was taken to a place where the emergency locator transmitter is to be installed; and
.. Ferry an airplane with an inoperative emergency locator transmitter from a place where repairs or replacements cannot be made to a place where they can be made.
              
. Paragraph (a) of this section does not apply to—
[arabic]
.. Before January 1, 2004, turbojet-powered aircraft;
.. Aircraft while engaged in scheduled flights by scheduled air carriers;
.. Aircraft while engaged in training operations conducted entirely within a 50-nautical mile radius of the airport from which such local flight operations began;
.. Aircraft while engaged in flight operations incident to design and testing;
.. New aircraft while engaged in flight operations incident to their manufacture, preparation, and delivery;
.. Aircraft while engaged in flight operations incident to the aerial application of chemicals and other substances for agricultural purposes;
.. Aircraft certificated by the Administrator for research and development purposes;
.. Aircraft while used for showing compliance with regulations, crew training, exhibition, air racing, or market surveys;
.. Aircraft equipped to carry not more than one person.
.. An aircraft during any period for which the transmitter has been temporarily removed for inspection, repair, modification, or replacement, subject to the following:
[lowerroman]
... No person may operate the aircraft unless the aircraft records contain an entry which includes the date of initial removal, the make, model, serial number, and reason for removing the transmitter, and a placard located in view of the pilot to show “ELT not installed.”
... No person may operate the aircraft more than 90 days after the ELT is initially removed from the aircraft; and
.. On and after January 1, 2004, aircraft with a maximum payload capacity of more than 18,000 pounds when used in air transportation.

## § 91.209 - Aircraft lights.

No person may:

[loweralpha]
. During the period from sunset to sunrise (or, in Alaska, during the period a prominent unlighted object cannot be seen from a distance of 3 statute miles or the sun is more than 6 degrees below the horizon)—
[arabic]
.. Operate an aircraft unless it has lighted position lights;
.. Park or move an aircraft in, or in dangerous proximity to, a night flight operations area of an airport unless the aircraft—
[lowerroman]
... Is clearly illuminated;
... Has lighted position lights; or
... is in an area that is marked by obstruction lights;
.. Anchor an aircraft unless the aircraft—
[lowerroman]
... Has lighted anchor lights; or
... Is in an area where anchor lights are not required on vessels; or
. Operate an aircraft that is equipped with an anticollision light system, unless it has lighted anticollision lights. However, the anticollision lights need not be lighted when the pilot-in-command determines that, because of operating conditions, it would be in the interest of safety to turn the lights off.

## § 91.211 - Supplemental oxygen.

[loweralpha]
. *General.* No person may operate a civil aircraft of U.S. registry—
[arabic]
.. At cabin pressure altitudes above 12,500 feet (MSL) up to and including 14,000 feet (MSL) unless the required minimum flight crew is provided with and uses supplemental oxygen for that part of the flight at those altitudes that is of more than 30 minutes duration;
.. At cabin pressure altitudes above 14,000 feet (MSL) unless the required minimum flight crew is provided with and uses supplemental oxygen during the entire flight time at those altitudes; and
.. At cabin pressure altitudes above 15,000 feet (MSL) unless each occupant of the aircraft is provided with supplemental oxygen.
. *Pressurized cabin aircraft.*
[arabic]
.. No person may operate a civil aircraft of U.S. registry with a pressurized cabin—
[lowerroman]
... At flight altitudes above flight level 250 unless at least a 10-minute supply of supplemental oxygen, in addition to any oxygen required to satisfy paragraph (a) of this section, is available for each occupant of the aircraft for use in the event that a descent is necessitated by loss of cabin pressurization; and
... At flight altitudes above flight level 350 unless one pilot at the controls of the airplane is wearing and using an oxygen mask that is secured and sealed and that either supplies oxygen at all times or automatically supplies oxygen whenever the cabin pressure altitude of the airplane exceeds 14,000 feet (MSL), except that the one pilot need not wear and use an oxygen mask while at or below flight level 410 if there are two pilots at the controls and each pilot has a quick-donning type of oxygen mask that can be placed on the face with one hand from the ready position within 5 seconds, supplying oxygen and properly secured and sealed.
.. Notwithstanding paragraph (b)(1)(ii) of this section, if for any reason at any time it is necessary for one pilot to leave the controls of the aircraft when operating at flight altitudes above flight level 350, the remaining pilot at the controls shall put on and use an oxygen mask until the other pilot has returned to that crewmember's station.

## § 91.213 - Inoperative instruments and equipment.

[loweralpha]
. Except as provided in paragraph (d) of this section, no person may take off an aircraft with inoperative instruments or equipment installed unless the following conditions are met:
[arabic]
.. An approved Minimum Equipment List exists for that aircraft.
.. The aircraft has within it a letter of authorization, issued by the FAA Flight Standards district office having jurisdiction over the area in which the operator is located, authorizing operation of the aircraft under the Minimum Equipment List. The letter of authorization may be obtained by written request of the airworthiness certificate holder. The Minimum Equipment List and the letter of authorization constitute a supplemental type certificate for the aircraft.
.. The approved Minimum Equipment List must—
[lowerroman]
... Be prepared in accordance with the limitations specified in paragraph (b) of this section; and
... Provide for the operation of the aircraft with the instruments and equipment in an inoperable condition.
.. The aircraft records available to the pilot must include an entry describing the inoperable instruments and equipment.
.. The aircraft is operated under all applicable conditions and limitations contained in the Minimum Equipment List and the letter authorizing the use of the list.
. The following instruments and equipment may not be included in a Minimum Equipment List:
[arabic]
.. Instruments and equipment that are either specifically or otherwise required by the airworthiness requirements under which the aircraft is type certificated and which are essential for safe operations under all operating conditions.
.. Instruments and equipment required by an airworthiness directive to be in operable condition unless the airworthiness directive provides otherwise.
.. Instruments and equipment required for specific operations by this part.
. A person authorized to use an approved Minimum Equipment List issued for a specific aircraft under subpart K of this part, part 121, 125, or 135 of this chapter must use that Minimum Equipment List to comply with the requirements in this section.
. Except for operations conducted in accordance with paragraph (a) or (c) of this section, a person may takeoff an aircraft in operations conducted under this part with inoperative instruments and equipment without an approved Minimum Equipment List provided—
[arabic]
.. The flight operation is conducted in a—
[lowerroman]
... Rotorcraft, non-turbine-powered airplane, glider, lighter-than-air aircraft, powered parachute, or weight-shift-control aircraft, for which a master minimum equipment list has not been developed; or
... Small rotorcraft, nonturbine-powered small airplane, glider, or lighter-than-air aircraft for which a Master Minimum Equipment List has been developed; and
.. The inoperative instruments and equipment are not—
[lowerroman]
... Part of the VFR-day type certification instruments and equipment prescribed in the applicable airworthiness regulations under which the aircraft was type certificated;
... Indicated as required on the aircraft's equipment list, or on the Kinds of Operations Equipment List for the kind of flight operation being conducted;
... Required by § 91.205 or any other rule of this part for the specific kind of flight operation being conducted; or
... Required to be operational by an airworthiness directive; and
.. The inoperative instruments and equipment are—
[lowerroman]
... Removed from the aircraft, the cockpit control placarded, and the maintenance recorded in accordance with § 43.9 of this chapter; or
... Deactivated and placarded “Inoperative.” If deactivation of the inoperative instrument or equipment involves maintenance, it must be accomplished and recorded in accordance with part 43 of this chapter; and
.. A determination is made by a pilot, who is certificated and appropriately rated under part 61 of this chapter, or by a person, who is certificated and appropriately rated to perform maintenance on the aircraft, that the inoperative instrument or equipment does not constitute a hazard to the aircraft.

An aircraft with inoperative instruments or equipment as provided in paragraph (d) of this section is considered to be in a properly altered condition acceptable to the Administrator.

(e) Notwithstanding any other provision of this section, an aircraft with inoperable instruments or equipment may be operated under a special flight permit issued in accordance with §§ 21.197 and 21.199 of this chapter.

## § 91.215 - ATC transponder and altitude reporting equipment and use.

[loweralpha]
. *All airspace: U.S.-registered civil aircraft.* For operations not conducted under part 121 or 135 of this chapter, ATC transponder equipment installed must meet the performance and environmental requirements of any class of TSO-C74b (Mode A) or any class of TSO-C74c (Mode A with altitude reporting capability) as appropriate, or the appropriate class of TSO-C112 (Mode S).
. *All airspace.* Unless otherwise authorized or directed by ATC, no person may operate an aircraft in the airspace described in paragraphs (b)(1) through (b)(5) of this section, unless that aircraft is equipped with an operable coded radar beacon transponder having either Mode 3/A 4096 code capability, replying to Mode 3/A interrogations with the code specified by ATC, or a Mode S capability, replying to Mode 3/A interrogations with the code specified by ATC and intermode and Mode S interrogations in accordance with the applicable provisions specified in TSO C-112, and that aircraft is equipped with automatic pressure altitude reporting equipment having a Mode C capability that automatically replies to Mode C interrogations by transmitting pressure altitude information in 100-foot increments. This requirement applies—
[arabic]
.. *All aircraft.* In Class A, Class B, and Class C airspace areas;
.. *All aircraft.* In all airspace within 30 nautical miles of an airport listed in appendix D, section 1 of this part from the surface upward to 10,000 feet MSL;
.. Notwithstanding paragraph (b)(2) of this section, any aircraft which was not originally certificated with an engine-driven electrical system or which has not subsequently been certified with such a system installed, balloon or glider may conduct operations in the airspace within 30 nautical miles of an airport listed in appendix D, section 1 of this part provided such operations are conducted—
[lowerroman]
... Outside any Class A, Class B, or Class C airspace area; and
... Below the altitude of the ceiling of a Class B or Class C airspace area designated for an airport or 10,000 feet MSL, whichever is lower; and
.. All aircraft in all airspace above the ceiling and within the lateral boundaries of a Class B or Class C airspace area designated for an airport upward to 10,000 feet MSL; and
.. All aircraft except any aircraft which was not originally certificated with an engine-driven electrical system or which has not subsequently been certified with such a system installed, balloon, or glider—
[lowerroman]
... In all airspace of the 48 contiguous states and the District of Columbia at and above 10,000 feet MSL, excluding the airspace at and below 2,500 feet above the surface; and
... In the airspace from the surface to 10,000 feet MSL within a 10-nautical-mile radius of any airport listed in appendix D, section 2 of this part, excluding the airspace below 1,200 feet outside of the lateral boundaries of the surface area of the airspace designated for that airport.
. *Transponder-on operation.* While in the airspace as specified in paragraph (b) of this section or in all controlled airspace, each person operating an aircraft equipped with an operable ATC transponder maintained in accordance with § 91.413 of this part shall operate the transponder, including Mode C equipment if installed, and shall reply on the appropriate code or as assigned by ATC.
. *ATC authorized deviations.* Requests for ATC authorized deviations must be made to the ATC facility having jurisdiction over the concerned airspace within the time periods specified as follows:
[arabic]
.. For operation of an aircraft with an operating transponder but without operating automatic pressure altitude reporting equipment having a Mode C capability, the request may be made at any time.
.. For operation of an aircraft with an inoperative transponder to the airport of ultimate destination, including any intermediate stops, or to proceed to a place where suitable repairs can be made or both, the request may be made at any time.
.. For operation of an aircraft that is not equipped with a transponder, the request must be made at least one hour before the proposed operation.

## § 91.217 - Data correspondence between automatically reported pressure altitude data and the pilot's altitude reference.

[loweralpha]
. No person may operate any automatic pressure altitude reporting equipment associated with a radar beacon transponder—
[arabic]
.. When deactivation of that equipment is directed by ATC;
.. Unless, as installed, that equipment was tested and calibrated to transmit altitude data corresponding within 125 feet (on a 95 percent probability basis) of the indicated or calibrated datum of the altimeter normally used to maintain flight altitude, with that altimeter referenced to 29.92 inches of mercury for altitudes from sea level to the maximum operating altitude of the aircraft; or
.. Unless the altimeters and digitizers in that equipment meet the standards of TSO-C10b and TSO-C88, respectively.
. No person may operate any automatic pressure altitude reporting equipment associated with a radar beacon transponder or with ADS-B Out equipment unless the pressure altitude reported for ADS-B Out and Mode C/S is derived from the same source for aircraft equipped with both a transponder and ADS-B Out.

## § 91.219 - Altitude alerting system or device: Turbojet-powered civil airplanes.

[loweralpha]
. Except as provided in paragraph (d) of this section, no person may operate a turbojet-powered U.S.-registered civil airplane unless that airplane is equipped with an approved altitude alerting system or device that is in operable condition and meets the requirements of paragraph (b) of this section.
. Each altitude alerting system or device required by paragraph (a) of this section must be able to—
[arabic]
.. Alert the pilot—
[lowerroman]
... Upon approaching a preselected altitude in either ascent or descent, by a sequence of both aural and visual signals in sufficient time to establish level flight at that preselected altitude; or
... Upon approaching a preselected altitude in either ascent or descent, by a sequence of visual signals in sufficient time to establish level flight at that preselected altitude, and when deviating above and below that preselected altitude, by an aural signal;
.. Provide the required signals from sea level to the highest operating altitude approved for the airplane in which it is installed;
.. Preselect altitudes in increments that are commensurate with the altitudes at which the aircraft is operated;
.. Be tested without special equipment to determine proper operation of the alerting signals; and
.. Accept necessary barometric pressure settings if the system or device operates on barometric pressure. However, for operation below 3,000 feet AGL, the system or device need only provide one signal, either visual or aural, to comply with this paragraph. A radio altimeter may be included to provide the signal if the operator has an approved procedure for its use to determine DA/DH or MDA, as appropriate.
. Each operator to which this section applies must establish and assign procedures for the use of the altitude alerting system or device and each flight crewmember must comply with those procedures assigned to him.
. Paragraph (a) of this section does not apply to any operation of an airplane that has an experimental certificate or to the operation of any airplane for the following purposes:
[arabic]
.. Ferrying a newly acquired airplane from the place where possession of it was taken to a place where the altitude alerting system or device is to be installed.
.. Continuing a flight as originally planned, if the altitude alerting system or device becomes inoperative after the airplane has taken off; however, the flight may not depart from a place where repair or replacement can be made.
.. Ferrying an airplane with any inoperative altitude alerting system or device from a place where repairs or replacements cannot be made to a place where it can be made.
.. Conducting an airworthiness flight test of the airplane.
.. Ferrying an airplane to a place outside the United States for the purpose of registering it in a foreign country.
.. Conducting a sales demonstration of the operation of the airplane.
.. Training foreign flight crews in the operation of the airplane before ferrying it to a place outside the United States for the purpose of registering it in a foreign country.

## § 91.221 - Traffic alert and collision avoidance system equipment and use.

[loweralpha]
. *All airspace: U.S.-registered civil aircraft.* Any traffic alert and collision avoidance system installed in a U.S.-registered civil aircraft must be approved by the Administrator.
. *Traffic alert and collision avoidance system, operation required.* Each person operating an aircraft equipped with an operable traffic alert and collision avoidance system shall have that system on and operating.

## § 91.223 - Terrain awareness and warning system.

[loweralpha]
. *Airplanes manufactured after March 29, 2002.* Except as provided in paragraph (d) of this section, no person may operate a turbine-powered U.S.-registered airplane configured with six or more passenger seats, excluding any pilot seat, unless that airplane is equipped with an approved terrain awareness and warning system that as a minimum meets the requirements for Class B equipment in Technical Standard Order (TSO)-C151.
. *Airplanes manufactured on or before March 29, 2002.* Except as provided in paragraph (d) of this section, no person may operate a turbine-powered U.S.-registered airplane configured with six or more passenger seats, excluding any pilot seat, after March 29, 2005, unless that airplane is equipped with an approved terrain awareness and warning system that as a minimum meets the requirements for Class B equipment in Technical Standard Order (TSO)-C151.
. *Airplane Flight Manual.* The Airplane Flight Manual shall contain appropriate procedures for—
[arabic]
.. The use of the terrain awareness and warning system; and
.. Proper flight crew reaction in response to the terrain awareness and warning system audio and visual warnings.
. *Exceptions.* Paragraphs (a) and (b) of this section do not apply to—
[arabic]
.. Parachuting operations when conducted entirely within a 50 nautical mile radius of the airport from which such local flight operations began.
.. Firefighting operations.
.. Flight operations when incident to the aerial application of chemicals and other substances.

## § 91.225 - Automatic Dependent Surveillance-Broadcast (ADS-B) Out equipment and use.

[loweralpha]
. After January 1, 2020, and unless otherwise authorized by ATC, no person may operate an aircraft in Class A airspace unless the aircraft has equipment installed that—
[arabic]
.. Meets the performance requirements in TSO-C166b, Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Service-Broadcast (TIS-B) Equipment Operating on the Radio Frequency of 1090 Megahertz (MHz); and
.. Meets the requirements of § 91.227.
. After January 1, 2020, and unless otherwise authorized by ATC, no person may operate an aircraft below 18,000 feet MSL and in airspace described in paragraph (d) of this section unless the aircraft has equipment installed that—
[arabic]
.. Meets the performance requirements in—
[lowerroman]
... TSO-C166b; or
... TSO-C154c, Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B) Equipment Operating on the Frequency of 978 MHz;
.. Meets the requirements of § 91.227.
. Operators with equipment installed with an approved deviation under § 21.618 of this chapter also are in compliance with this section.
. After January 1, 2020, and unless otherwise authorized by ATC, no person may operate an aircraft in the following airspace unless the aircraft has equipment installed that meets the requirements in paragraph (b) of this section:
[arabic]
.. Class B and Class C airspace areas;
.. Except as provided for in paragraph (e) of this section, within 30 nautical miles of an airport listed in appendix D, section 1 to this part from the surface upward to 10,000 feet MSL;
.. Above the ceiling and within the lateral boundaries of a Class B or Class C airspace area designated for an airport upward to 10,000 feet MSL;
.. Except as provided in paragraph (e) of this section, Class E airspace within the 48 contiguous states and the District of Columbia at and above 10,000 feet MSL, excluding the airspace at and below 2,500 feet above the surface; and
.. Class E airspace at and above 3,000 feet MSL over the Gulf of Mexico from the coastline of the United States out to 12 nautical miles.
. The requirements of paragraph (b) of this section do not apply to any aircraft that was not originally certificated with an electrical system, or that has not subsequently been certified with such a system installed, including balloons and gliders. These aircraft may conduct operations without ADS-B Out in the airspace specified in paragraphs (d)(2) and (d)(4) of this section. Operations authorized by this section must be conducted—
[arabic]
.. Outside any Class B or Class C airspace area; and
.. Below the altitude of the ceiling of a Class B or Class C airspace area designated for an airport, or 10,000 feet MSL, whichever is lower.
. Each person operating an aircraft equipped with ADS-B Out must operate this equipment in the transmit mode at all times.
. Requests for ATC authorized deviations from the requirements of this section must be made to the ATC facility having jurisdiction over the concerned airspace within the time periods specified as follows:
[arabic]
.. For operation of an aircraft with an inoperative ADS-B Out, to the airport of ultimate destination, including any intermediate stops, or to proceed to a place where suitable repairs can be made or both, the request may be made at any time.
.. For operation of an aircraft that is not equipped with ADS-B Out, the request must be made at least 1 hour before the proposed operation.
. The standards required in this section are incorporated by reference with the approval of the Director of the Office of the Federal Register under 5 U.S.C. 552(a) and 1 CFR part 51. All approved materials are available for inspection at the FAA's Office of Rulemaking (ARM-1), 800 Independence Avenue, SW., Washington, DC 20590 (telephone 202-267-9677), or at the National Archives and Records Administration (NARA). For information on the availability of this material at NARA, call 202-741-6030, or go to *http://www.archives.gov/federal_register/code_of_federal_regulations/ibr_locations.html.* This material is also available from the sources indicated in paragraphs (h)(1) and (h)(2) of this section.
[arabic]
.. Copies of Technical Standard Order (TSO)-C166b, Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Service-Broadcast (TIS-B) Equipment Operating on the Radio Frequency of 1090 Megahertz (MHz) (December 2, 2009) and TSO-C154c, Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B) Equipment Operating on the Frequency of 978 MHz (December 2, 2009) may be obtained from the U.S. Department of Transportation, Subsequent Distribution Office, DOT Warehouse M30, Ardmore East Business Center, 3341 Q 75th Avenue, Landover, MD 20785; telephone (301) 322-5377. Copies of TSO -C166B and TSO-C154c are also available on the FAA's Web site, at *http://www.faa.gov/aircraft/air_cert/design_approvals/tso/.* Select the link “Search Technical Standard Orders.”
.. Copies of Section 2, Equipment Performance Requirements and Test Procedures, of RTCA DO-260B, Minimum Operational Performance Standards for 1090 MHz Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Services-Broadcast (TIS-B), December 2, 2009 (referenced in TSO-C166b) and Section 2, Equipment Performance Requirements and Test Procedures, of RTCA DO-282B, Minimum Operational Performance Standards for Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B), December 2, 2009 (referenced in TSO C-154c) may be obtained from RTCA, Inc., 1828 L Street, NW., Suite 805, Washington, DC 20036-5133, telephone 202-833-9339. Copies of RTCA DO-260B and RTCA DO-282B are also available on RTCA Inc.'s Web site, at*http://www.rtca.org/onlinecart/allproducts.cfm.*
              

## § 91.227 - Automatic Dependent Surveillance-Broadcast (ADS-B) Out equipment performance requirements.

[loweralpha]
. *Definitions.* For the purposes of this section:

*ADS-B Out* is a function of an aircraft's onboard avionics that periodically broadcasts the aircraft's state vector (3-dimensional position and 3-dimensional velocity) and other required information as described in this section.

*Navigation Accuracy Category for Position* (*NAC*
                *P*) specifies the accuracy of a reported aircraft's position, as defined in TSO-C166b and TSO-C154c.

*Navigation Accuracy Category for Velocity* (*NAC*
                *V*) specifies the accuracy of a reported aircraft's velocity, as defined in TSO-C166b and TSO-C154c.

*Navigation Integrity Category (NIC)* specifies an integrity containment radius around an aircraft's reported position, as defined in TSO-C166b and TSO-C154c.

*Position Source* refers to the equipment installed onboard an aircraft used to process and provide aircraft position (for example, latitude, longitude, and velocity) information.

*Source Integrity Level (SIL)* indicates the probability of the reported horizontal position exceeding the containment radius defined by the NIC on a per sample or per hour basis, as defined in TSO-C166b and TSO-C154c.

*System Design Assurance (SDA)* indicates the probability of an aircraft malfunction causing false or misleading information to be transmitted, as defined in TSO-C166b and TSO-C154c.

*Total latency* is the total time between when the position is measured and when the position is transmitted by the aircraft.

*Uncompensated latency* is the time for which the aircraft does not compensate for latency.

(b) *1090 MHz ES and UAT Broadcast Links and Power Requirements*—

[arabic]
. Aircraft operating in Class A airspace must have equipment installed that meets the antenna and power output requirements of Class A1, A1S, A2, A3, B1S, or B1 equipment as defined in TSO-C166b, Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Service-Broadcast (TIS-B) Equipment Operating on the Radio Frequency of 1090 Megahertz (MHz).
. Aircraft operating in airspace designated for ADS-B Out, but outside of Class A airspace, must have equipment installed that meets the antenna and output power requirements of either:
[lowerroman]
.. Class A1, A1S, A2, A3, B1S, or B1 as defined in TSO-C166b; or
.. Class A1H, A1S, A2, A3, B1S, or B1 equipment as defined in TSO-C154c, Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B) Equipment Operating on the Frequency of 978 MHz.

(c) *ADS-B Out Performance Requirements for NAC*
                *P,*
                *NAC*
                *V*
                *, NIC, SDA*, *and SIL*—

[arabic]
. For aircraft broadcasting ADS-B Out as required under § 91.225 (a) and (b)—
[lowerroman]
.. The aircraft's NAC*P* must be less than 0.05 nautical miles;
.. The aircraft's NAC*V* must be less than 10 meters per second;
.. The aircraft's NIC must be less than 0.2 nautical miles;
.. The aircraft's SDA must be 2; and
.. The aircraft's SIL must be 3.
. Changes in NAC*P*, NAC*V*, SDA, and SIL must be broadcast within 10 seconds.
. Changes in NIC must be broadcast within 12 seconds.

(d) *Minimum Broadcast Message Element Set for ADS-B Out.* Each aircraft must broadcast the following information, as defined in TSO-C166b or TSO-C154c. The pilot must enter information for message elements listed in paragraphs (d)(7) through (d)(10) of this section during the appropriate phase of flight.

[arabic]
. The length and width of the aircraft;
. An indication of the aircraft's latitude and longitude;
. An indication of the aircraft's barometric pressure altitude;
. An indication of the aircraft's velocity;
. An indication if TCAS II or ACAS is installed and operating in a mode that can generate resolution advisory alerts;
              
. If an operable TCAS II or ACAS is installed, an indication if a resolution advisory is in effect;
. An indication of the Mode 3/A transponder code specified by ATC;
. An indication of the aircraft's call sign that is submitted on the flight plan, or the aircraft's registration number, except when the pilot has not filed a flight plan, has not requested ATC services, and is using a TSO-C154c self-assigned temporary 24-bit address;
. An indication if the flightcrew has identified an emergency, radio communication failure, or unlawful interference;
. An indication of the aircraft's “IDENT” to ATC;
. An indication of the aircraft assigned ICAO 24-bit address, except when the pilot has not filed a flight plan, has not requested ATC services, and is using a TSO-C154c self-assigned temporary 24-bit address;
. An indication of the aircraft's emitter category;
. An indication of whether an ADS-B In capability is installed;
. An indication of the aircraft's geometric altitude;
. An indication of the Navigation Accuracy Category for Position (NAC*P*);
. An indication of the Navigation Accuracy Category for Velocity (NAC*V*);
. An indication of the Navigation Integrity Category (NIC);
. An indication of the System Design Assurance (SDA); and
. An indication of the Source Integrity Level (SIL).

(e) *ADS-B Latency Requirements*—

[arabic]
. The aircraft must transmit its geometric position no later than 2.0 seconds from the time of measurement of the position to the time of transmission.
. Within the 2.0 total latency allocation, a maximum of 0.6 seconds can be uncompensated latency. The aircraft must compensate for any latency above 0.6 seconds up to the maximum 2.0 seconds total by extrapolating the geometric position to the time of message transmission.
. The aircraft must transmit its position and velocity at least once per second while airborne or while moving on the airport surface.
. The aircraft must transmit its position at least once every 5 seconds while stationary on the airport surface.

(f) *Equipment with an approved deviation.* Operators with equipment installed with an approved deviation under § 21.618 of this chapter also are in compliance with this section.

(g) *Incorporation by Reference.* The standards required in this section are incorporated by reference with the approval of the Director of the Office of the Federal Register under 5 U.S.C. 552(a) and 1 CFR part 51. All approved materials are available for inspection at the FAA's Office of Rulemaking (ARM-1), 800 Independence Avenue, SW., Washington, DC 20590 (telephone 202-267-9677), or at the National Archives and Records Administration (NARA). For information on the availability of this material at NARA, call 202-741-6030, or go to *http://www.archives.gov/federal_register/code_of_federal_regulations/ibr_locations.html.* This material is also available from the sources indicated in paragraphs (g)(1) and (g)(2) of this section.

[arabic]
. Copies of Technical Standard Order (TSO)-C166b, Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Service-Broadcast (TIS-B) Equipment Operating on the Radio Frequency of 1090 Megahertz (MHz) (December 2, 2009) and TSO-C154c, Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B) Equipment Operating on the Frequency of 978 MHz (December 2, 2009) may be obtained from the U.S. Department of Transportation, Subsequent Distribution Office, DOT Warehouse M30, Ardmore East Business Center, 3341 Q 75th Avenue, Landover, MD 20785; telephone (301) 322-5377. Copies of TSO -C166B and TSO-C154c are also available on the FAA's Web site, at *http://www.faa.gov/aircraft/air_cert/design_approvals/tso/.* Select the link “Search Technical Standard Orders.”
. Copies of Section 2, Equipment Performance Requirements and Test Procedures, of RTCA DO-260B, Minimum Operational Performance Standards for 1090 MHz Extended Squitter Automatic Dependent Surveillance-Broadcast (ADS-B) and Traffic Information Services-Broadcast (TIS-B), December 2, 2009 (referenced in TSO-C166b) and Section 2, Equipment Performance Requirements and Test Procedures, of RTCA DO-282B, Minimum Operational Performance Standards for Universal Access Transceiver (UAT) Automatic Dependent Surveillance-Broadcast (ADS-B), December 2, 2009 (referenced in TSO C-154c) may be obtained from RTCA, Inc., 1828 L Street, NW., Suite 805, Washington, DC 20036-5133, telephone 202-833-9339. Copies of RTCA DO-260B and RTCA DO-282B are also available on RTCA Inc.'s Web site, at*http://www.rtca.org/onlinecart/allproducts.cfm.*
              

## §§ 91.228-91.299 - Reserved


Reserved

