# Maintenance, Preventive Maintenance, and Alterations
:toc:

## § 91.401

### Applicability.

. This subpart prescribes rules governing the maintenance, preventive maintenance, and alterations of U.S.-registered civil aircraft operating within or outside of the United States.
. Sections 91.405, 91.409, 91.411, 91.417, and 91.419 of this subpart do not apply to an aircraft maintained in accordance with a continuous airworthiness maintenance program as provided in part 121, 129, or §§ 91.1411 or 135.411(a)(2) of this chapter.
. Sections 91.405 and 91.409 of this part do not apply to an airplane inspected in accordance with part 125 of this chapter.

## § 91.403

### General.

. The owner or operator of an aircraft is primarily responsible for maintaining that aircraft in an airworthy condition, including compliance with part 39 of this chapter.
. No person may perform maintenance, preventive maintenance, or alterations on an aircraft other than as prescribed in this subpart and other applicable regulations, including part 43 of this chapter.
. No person may operate an aircraft for which a manufacturer's maintenance manual or instructions for continued airworthiness has been issued that contains an airworthiness limitations section unless the mandatory replacement times, inspection intervals, and related procedures specified in that section or alternative inspection intervals and related procedures set forth in an operations specification approved by the Administrator under part 121 or 135 of this chapter or in accordance with an inspection program approved under § 91.409(e) have been complied with.
. A person must not alter an aircraft based on a supplemental type certificate unless the owner or operator of the aircraft is the holder of the supplemental type certificate, or has written permission from the holder.

## § 91.405

### Maintenance required.

Each owner or operator of an aircraft—

. Shall have that aircraft inspected as prescribed in subpart E of this part and shall between required inspections, except as provided in paragraph (c) of this section, have discrepancies repaired as prescribed in part 43 of this chapter;
. Shall ensure that maintenance personnel make appropriate entries in the aircraft maintenance records indicating the aircraft has been approved for return to service;
. Shall have any inoperative instrument or item of equipment, permitted to be inoperative by § 91.213(d)(2) of this part, repaired, replaced, removed, or inspected at the next required inspection; and
. When listed discrepancies include inoperative instruments or equipment, shall ensure that a placard has been installed as required by § 43.11 of this chapter.

## § 91.407

### Operation after maintenance, preventive maintenance, rebuilding, or alteration.

. No person may operate any aircraft that has undergone maintenance, preventive maintenance, rebuilding, or alteration unless—
.. It has been approved for return to service by a person authorized under § 43.7 of this chapter; and
.. The maintenance record entry required by § 43.9 or § 43.11, as applicable, of this chapter has been made.
. No person may carry any person (other than crewmembers) in an aircraft that has been maintained, rebuilt, or altered in a manner that may have appreciably changed its flight characteristics or substantially affected its operation in flight until an appropriately rated pilot with at least a private pilot certificate flies the aircraft, makes an operational check of the maintenance performed or alteration made, and logs the flight in the aircraft records.
. The aircraft does not have to be flown as required by paragraph (b) of this section if, prior to flight, ground tests, inspection, or both show conclusively that the maintenance, preventive maintenance, rebuilding, or alteration has not appreciably changed the flight characteristics or substantially affected the flight operation of the aircraft.

## § 91.409

### Inspections.

. Except as provided in paragraph (c) of this section, no person may operate an aircraft unless, within the preceding 12 calendar months, it has had—
.. An annual inspection in accordance with part 43 of this chapter and has been approved for return to service by a person authorized by § 43.7 of this chapter; or
.. An inspection for the issuance of an airworthiness certificate in accordance with part 21 of this chapter.
              
. Except as provided in paragraph (c) of this section, no person may operate an aircraft carrying any person (other than a crewmember) for hire, and no person may give flight instruction for hire in an aircraft which that person provides, unless within the preceding 100 hours of time in service the aircraft has received an annual or 100-hour inspection and been approved for return to service in accordance with part 43 of this chapter or has received an inspection for the issuance of an airworthiness certificate in accordance with part 21 of this chapter. The 100-hour limitation may be exceeded by not more than 10 hours while en route to reach a place where the inspection can be done. The excess time used to reach a place where the inspection can be done must be included in computing the next 100 hours of time in service.
. Paragraphs (a) and (b) of this section do not apply to—
.. An aircraft that carries a special flight permit, a current experimental certificate, or a light-sport or provisional airworthiness certificate;
.. An aircraft inspected in accordance with an approved aircraft inspection program under part 125 or 135 of this chapter and so identified by the registration number in the operations specifications of the certificate holder having the approved inspection program;
.. An aircraft subject to the requirements of paragraph (d) or (e) of this section; or
.. Turbine-powered rotorcraft when the operator elects to inspect that rotorcraft in accordance with paragraph (e) of this section.
. *Progressive inspection.* Each registered owner or operator of an aircraft desiring to use a progressive inspection program must submit a written request to the FAA Flight Standards district office having jurisdiction over the area in which the applicant is located, and shall provide—
.. A certificated mechanic holding an inspection authorization, a certificated airframe repair station, or the manufacturer of the aircraft to supervise or conduct the progressive inspection;
.. A current inspection procedures manual available and readily understandable to pilot and maintenance personnel containing, in detail—
... An explanation of the progressive inspection, including the continuity of inspection responsibility, the making of reports, and the keeping of records and technical reference material;
... An inspection schedule, specifying the intervals in hours or days when routine and detailed inspections will be performed and including instructions for exceeding an inspection interval by not more than 10 hours while en route and for changing an inspection interval because of service experience;
              
... Sample routine and detailed inspection forms and instructions for their use; and
... Sample reports and records and instructions for their use;
.. Enough housing and equipment for necessary disassembly and proper inspection of the aircraft; and
.. Appropriate current technical information for the aircraft.
              
. *Large airplanes (to which part 125 is not applicable), turbojet multiengine airplanes, turbopropeller-powered multiengine airplanes, and turbine-powered rotorcraft.* No person may operate a large airplane, turbojet multiengine airplane, turbopropeller-powered multiengine airplane, or turbine-powered rotorcraft unless the replacement times for life-limited parts specified in the aircraft specifications, type data sheets, or other documents approved by the Administrator are complied with and the airplane or turbine-powered rotorcraft, including the airframe, engines, propellers, rotors, appliances, survival equipment, and emergency equipment, is inspected in accordance with an inspection program selected under the provisions of paragraph (f) of this section, except that, the owner or operator of a turbine-powered rotorcraft may elect to use the inspection provisions of § 91.409(a), (b), (c), or (d) in lieu of an inspection option of § 91.409(f).
. *Selection of inspection program under paragraph (e) of this section.* The registered owner or operator of each airplane or turbine-powered rotorcraft described in paragraph (e) of this section must select, identify in the aircraft maintenance records, and use one of the following programs for the inspection of the aircraft:
.. A continuous airworthiness inspection program that is part of a continuous airworthiness maintenance program currently in use by a person holding an air carrier operating certificate or an operating certificate issued under part 121 or 135 of this chapter and operating that make and model aircraft under part 121 of this chapter or operating that make and model under part 135 of this chapter and maintaining it under § 135.411(a)(2) of this chapter.
.. An approved aircraft inspection program approved under § 135.419 of this chapter and currently in use by a person holding an operating certificate issued under part 135 of this chapter.
.. A current inspection program recommended by the manufacturer.
.. Any other inspection program established by the registered owner or operator of that airplane or turbine-powered rotorcraft and approved by the Administrator under paragraph (g) of this section. However, the Administrator may require revision of this inspection program in accordance with the provisions of § 91.415.
              
. *Inspection program approved under paragraph (e) of this section.* Each operator of an airplane or turbine-powered rotorcraft desiring to establish or change an approved inspection program under paragraph (f)(4) of this section must submit the program for approval to the local FAA Flight Standards district office having jurisdiction over the area in which the aircraft is based. The program must be in writing and include at least the following information:
.. Instructions and procedures for the conduct of inspections for the particular make and model airplane or turbine-powered rotorcraft, including necessary tests and checks. The instructions and procedures must set forth in detail the parts and areas of the airframe, engines, propellers, rotors, and appliances, including survival and emergency equipment required to be inspected.
.. A schedule for performing the inspections that must be performed under the program expressed in terms of the time in service, calendar time, number of system operations, or any combination of these.
. *Changes from one inspection program to another.* When an operator changes from one inspection program under paragraph (f) of this section to another, the time in service, calendar times, or cycles of operation accumulated under the previous program must be applied in determining inspection due times under the new program.

## § 91.410

### Reserved

## § 91.411

### Altimeter system and altitude reporting equipment tests and inspections.

. No person may operate an airplane, or helicopter, in controlled airspace under IFR unless—
.. Within the preceding 24 calendar months, each static pressure system, each altimeter instrument, and each automatic pressure altitude reporting system has been tested and inspected and found to comply with appendices E and F of part 43 of this chapter;
.. Except for the use of system drain and alternate static pressure valves, following any opening and closing of the static pressure system, that system has been tested and inspected and found to comply with paragraph (a), appendix E, of part 43 of this chapter; and
.. Following installation or maintenance on the automatic pressure altitude reporting system of the ATC transponder where data correspondence error could be introduced, the integrated system has been tested, inspected, and found to comply with paragraph (c), appendix E, of part 43 of this chapter.
. The tests required by paragraph (a) of this section must be conducted by—
.. The manufacturer of the airplane, or helicopter, on which the tests and inspections are to be performed;
.. A certificated repair station properly equipped to perform those functions and holding—
... An instrument rating, Class I;
... A limited instrument rating appropriate to the make and model of appliance to be tested;
... A limited rating appropriate to the test to be performed;
... An airframe rating appropriate to the airplane, or helicopter, to be tested; or
.. A certificated mechanic with an airframe rating (static pressure system tests and inspections only).
. Altimeter and altitude reporting equipment approved under Technical Standard Orders are considered to be tested and inspected as of the date of their manufacture.
. No person may operate an airplane, or helicopter, in controlled airspace under IFR at an altitude above the maximum altitude at which all altimeters and the automatic altitude reporting system of that airplane, or helicopter, have been tested.

## § 91.413

### ATC transponder tests and inspections.

. No persons may use an ATC transponder that is specified in 91.215(a), 121.345(c), or § 135.143(c) of this chapter unless, within the preceding 24 calendar months, the ATC transponder has been tested and inspected and found to comply with appendix F of part 43 of this chapter; and
. Following any installation or maintenance on an ATC transponder where data correspondence error could be introduced, the integrated system has been tested, inspected, and found to comply with paragraph (c), appendix E, of part 43 of this chapter.
. The tests and inspections specified in this section must be conducted by—
.. A certificated repair station properly equipped to perform those functions and holding—
... A radio rating, Class III;
... A limited radio rating appropriate to the make and model transponder to be tested;
... A limited rating appropriate to the test to be performed;
.. A holder of a continuous airworthiness maintenance program as provided in part 121 or § 135.411(a)(2) of this chapter; or
.. The manufacturer of the aircraft on which the transponder to be tested is installed, if the transponder was installed by that manufacturer.

## § 91.415

### Changes to aircraft inspection programs.

. Whenever the Administrator finds that revisions to an approved aircraft inspection program under § 91.409(f)(4) or § 91.1109 are necessary for the continued adequacy of the program, the owner or operator must, after notification by the Administrator, make any changes in the program found to be necessary by the Administrator.
. The owner or operator may petition the Administrator to reconsider the notice to make any changes in a program in accordance with paragraph (a) of this section.
. The petition must be filed with the Director, Flight Standards Service within 30 days after the certificate holder or fractional ownership program manager receives the notice.
. Except in the case of an emergency requiring immediate action in the interest of safety, the filing of the petition stays the notice pending a decision by the Administrator.

## § 91.417

### Maintenance records.

. Except for work performed in accordance with §§ 91.411 and 91.413, each registered owner or operator shall keep the following records for the periods specified in paragraph (b) of this section:
.. Records of the maintenance, preventive maintenance, and alteration and records of the 100-hour, annual, progressive, and other required or approved inspections, as appropriate, for each aircraft (including the airframe) and each engine, propeller, rotor, and appliance of an aircraft. The records must include—
... A description (or reference to data acceptable to the Administrator) of the work performed; and
... The date of completion of the work performed; and
... The signature, and certificate number of the person approving the aircraft for return to service.
.. Records containing the following information:
... The total time in service of the airframe, each engine, each propeller, and each rotor.
... The current status of life-limited parts of each airframe, engine, propeller, rotor, and appliance.
... The time since last overhaul of all items installed on the aircraft which are required to be overhauled on a specified time basis.
... The current inspection status of the aircraft, including the time since the last inspection required by the inspection program under which the aircraft and its appliances are maintained.
... The current status of applicable airworthiness directives (AD) and safety directives including, for each, the method of compliance, the AD or safety directive number and revision date. If the AD or safety directive involves recurring action, the time and date when the next action is required.
... Copies of the forms prescribed by § 43.9(d) of this chapter for each major alteration to the airframe and currently installed engines, rotors, propellers, and appliances.
. The owner or operator shall retain the following records for the periods prescribed:
.. The records specified in paragraph (a)(1) of this section shall be retained until the work is repeated or superseded by other work or for 1 year after the work is performed.
.. The records specified in paragraph (a)(2) of this section shall be retained and transferred with the aircraft at the time the aircraft is sold.
.. A list of defects furnished to a registered owner or operator under § 43.11 of this chapter shall be retained until the defects are repaired and the aircraft is approved for return to service.
. The owner or operator shall make all maintenance records required to be kept by this section available for inspection by the Administrator or any authorized representative of the National Transportation Safety Board (NTSB). In addition, the owner or operator shall present Form 337 described in paragraph (d) of this section for inspection upon request of any law enforcement officer.
. When a fuel tank is installed within the passenger compartment or a baggage compartment pursuant to part 43 of this chapter, a copy of FAA Form 337 shall be kept on board the modified aircraft by the owner or operator.

## § 91.419

### Transfer of maintenance records.

Any owner or operator who sells a U.S.-registered aircraft shall transfer to the purchaser, at the time of sale, the following records of that aircraft, in plain language form or in coded form at the election of the purchaser, if the coded form provides for the preservation and retrieval of information in a manner acceptable to the Administrator:

. The records specified in § 91.417(a)(2).
. The records specified in § 91.417(a)(1) which are not included in the records covered by paragraph (a) of this section, except that the purchaser may permit the seller to keep physical custody of such records. However, custody of records by the seller does not relieve the purchaser of the responsibility under § 91.417(c) to make the records available for inspection by the Administrator or any authorized representative of the National Transportation Safety Board (NTSB).

## § 91.421

### Rebuilt engine maintenance records.

. The owner or operator may use a new maintenance record, without previous operating history, for an aircraft engine rebuilt by the manufacturer or by an agency approved by the manufacturer.
. Each manufacturer or agency that grants zero time to an engine rebuilt by it shall enter in the new record—
.. A signed statement of the date the engine was rebuilt;
.. Each change made as required by airworthiness directives; and
.. Each change made in compliance with manufacturer's service bulletins, if the entry is specifically requested in that bulletin.
. For the purposes of this section, a rebuilt engine is a used engine that has been completely disassembled, inspected, repaired as necessary, reassembled, tested, and approved in the same manner and to the same tolerances and limits as a new engine with either new or used parts. However, all parts used in it must conform to the production drawing tolerances and limits for new parts or be of approved oversized or undersized dimensions for a new engine.

## §§ 91.423-91.499

### Reserved

