# Operating Rules
:toc:

## § 137.29

### General.

. Except as provided in paragraphs (d) and (e) of this section, this subpart prescribes rules that apply to persons and aircraft used in agricultural aircraft operations conducted under this part.
. [Reserved]
. The holder of an agricultural aircraft operator certificate may deviate from the provisions of part 91 of this chapter without a certificate of waiver, as authorized in this subpart for dispensing operations, when conducting nondispensing aerial work operations related to agriculture, horticulture, or forest preservation in accordance with the operating rules of this subpart.
. Sections 137.31 through 137.35, §§ 137.41, and 137.53 through 137.59 do not apply to persons and aircraft used in agricultural aircraft operations conducted with public aircraft.
. Sections 137.31 through 137.35, §§ 137.39, 137.41, 137.51 through 137.59, and subpart D do not apply to persons and rotorcraft used in agricultural aircraft operations conducted by a person holding a certificate under part 133 of this chapter and involving only the dispensing of water on forest fires by rotorcraft external-load means. However, the operation shall be conducted in accordance with—
.. The rules of part 133 of this chapter governing rotorcraft external-load operations; and
.. The operating rules of this subpart contained in §§ 137.29, 137.37, and §§ 137.43 through 137.49.

## § 137.31

### Aircraft requirements.

No person may operate an aircraft unless that aircraft—

. Meets the requirements of § 137.19(d); and
. Is equipped with a suitable and properly installed shoulder harness for use by each pilot.

## § 137.33

### Carrying of certificate.

. No person may operate an aircraft unless a facsimile of the agricultural aircraft operator certificate, under which the operation is conducted, is carried on that aircraft. The facsimile shall be presented for inspection upon the request of the Administrator or any Federal, State, or local law enforcement officer.
. Notwithstanding part 91 of this chapter, the registration and airworthiness certificates issued for the aircraft need not be carried in the aircraft. However, when those certificates are not carried in the aircraft they shall be kept available for inspection at the base from which the dispensing operation is conducted.

## § 137.35

### Limitations on private agricultural aircraft operator.

No person may conduct an agricultural aircraft operation under the authority of a private agricultural aircraft operator certificate—

. For compensation or hire;
. Over a congested area; or
. Over any property unless he is the owner or lessee of the property, or has ownership or other property interest in the crop located on that property.

## § 137.37

### Manner of dispensing.

No persons may dispense, or cause to be dispensed, from an aircraft, any material or substance in a manner that creates a hazard to persons or property on the surface.

## § 137.39

### Economic poison dispensing.

. Except as provided in paragraph (b) of this section, no person may dispense or cause to be dispensed from an aircraft, any economic poison that is registered with the U.S. Department of Agriculture under the Federal Insecticide, Fungicide, and Rodenticide Act (7 U.S.C. 135-135k)—
.. For a use other than that for which it is registered;
.. Contrary to any safety instructions or use limitations on its label; or
.. In violation of any law or regulation of the United States.
              
. This section does not apply to any person dispensing economic poisons for experimental purposes under—
.. The supervision of a Federal or State agency authorized by law to conduct research in the field of economic poisons; or
.. A permit from the U.S. Department of Agriculture issued pursuant to the Federal Insecticide, Fungicide, and Rodenticide Act (7 U.S.C. 135-135k).

## § 137.40

### Employment of former FAA employees.

. Except as specified in paragraph (c) of this section, no certificate holder may knowingly employ or make a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual, in the preceding 2 years—
.. Served as, or was directly responsible for the oversight of, a Flight Standards Service aviation safety inspector; and
.. Had direct responsibility to inspect, or oversee the inspection of, the operations of the certificate holder.
. For the purpose of this section, an individual shall be considered to be acting as an agent or representative of a certificate holder in a matter before the agency if the individual makes any written or oral communication on behalf of the certificate holder to the agency (or any of its officers or employees) in connection with a particular matter, whether or not involving a specific party and without regard to whether the individual has participated in, or had responsibility for, the particular matter while serving as a Flight Standards Service aviation safety inspector.
. The provisions of this section do not prohibit a certificate holder from knowingly employing or making a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual was employed by the certificate holder before October 21, 2011.

## § 137.41

### Personnel.

. *Information.* The holder of an agricultural aircraft operator certificate shall insure that each person used in the holder's agricultural aircraft operation is informed of that person's duties and responsibilities for the operation.
. *Supervisors.* No person may supervise an agricultural aircraft operation unless he has met the knowledge and skill requirements of § 137.19(e).
. *Pilot in command.* No person may act as pilot in command of an aircraft unless he holds a pilot certificate and rating prescribed by § 137.19 (b) or (c), as appropriate to the type of operation conducted. In addition, he must demonstrate to the holder of the Agricultural Aircraft Operator Certificate conducting the operation that he has met the knowledge and skill requirements of § 137.19(e). If the holder of that certificate has designated a person under § 137.19(e) to supervise his agricultural aircraft operations the demonstration must be made to the person so designated. However, a demonstration of the knowledge and skill requirement is not necessary for any pilot in command who—
.. Is, at the time of the filing of an application by an agricultural aircraft operator, working as a pilot in command for that operator; and
.. Has a record of operation under that applicant that does not disclose any question regarding the safety of his flight operations or his competence in dispensing agricultural materials or chemicals.

## § 137.42

### Fastening of safety belts and shoulder harnesses.

No person may operate an aircraft in operations required to be conducted under part 137 without a safety belt and shoulder harness properly secured about that person except that the shoulder harness need not be fastened if that person would be unable to perform required duties with the shoulder harness fastened.

## § 137.43

### Operations in controlled airspace designated for an airport.

. Except for flights to and from a dispensing area, no person may operate an aircraft within the lateral boundaries of the surface area of Class D airspace designated for an airport unless authorization for that operation has been obtained from the ATC facility having jurisdiction over that area.
. No person may operate an aircraft in weather conditions below VFR minimums within the lateral boundaries of a Class E airspace area that extends upward from the surface unless authorization for that operation has been obtained from the ATC facility having jurisdiction over that area.
. Notwithstanding § 91.157(b)(4) of this chapter, an aircraft may be operated under the special VFR weather minimums without meeting the requirements prescribed therein.

## § 137.45

### Nonobservance of airport traffic pattern.

Notwithstanding part 91 of this chapter, the pilot in command of an aircraft may deviate from an airport traffic pattern when authorized by the control tower concerned. At an airport without a functioning control tower, the pilot in command may deviate from the traffic pattern if—

. Prior coordination is made with the airport management concerned;
. Deviations are limited to the agricultural aircraft operation;
. Except in an emergency, landing and takeoffs are not made on ramps, taxiways, or other areas of the airport not intended for such use; and
. The aircraft at all times remains clear of, and gives way to, aircraft conforming to the traffic pattern for the airport.

## § 137.47

### Operation without position lights.

Notwithstanding part 91 of this chapter, an aircraft may be operated without position lights if prominent unlighted objects are visible for at least 1 mile and takeoffs and landings at—

. Airports with a functioning control tower are made only as authorized by the control tower operator; and
. Other airports are made only with the permission of the airport management and no other aircraft operations requiring position lights are in progress at that airport.

## § 137.49

### Operations over other than congested areas.

Notwithstanding part 91 of this chapter, during the actual dispensing operation, including approaches, departures, and turnarounds reasonably necessary for the operation, an aircraft may be operated over other than congested areas below 500 feet above the surface and closer than 500 feet to persons, vessels, vehicles, and structures, if the operations are conducted without creating a hazard to persons or property on the surface.

## § 137.51

### Operation over congested areas: General.

. Notwithstanding part 91 of this chapter, an aircraft may be operated over a congested area at altitudes required for the proper accomplishment of the agricultural aircraft operation if the operation is conducted—
.. With the maximum safety to persons and property on the surface, consistent with the operation; and
.. In accordance with the requirements of paragraph (b) of this section.
. No person may operate an aircraft over a congested area except in accordance with the requirements of this paragraph.
.. Prior written approval must be obtained from the appropriate official or governing body of the political subdivision over which the operations are conducted.
.. Notice of the intended operation must be given to the public by some effective means, such as daily newspapers, radio, television, or door-to-door notice.
.. A plan for each complete operation must be submitted to, and approved by appropriate personnel of the FAA Flight Standards District Office having jurisdiction over the area where the operation is to be conducted. The plan must include consideration of obstructions to flight; the emergency landing capabilities of the aircraft to be used; and any necessary coordination with air traffic control.
.. Single engine aircraft must be operated as follows:
... Except for helicopters, no person may take off a loaded aircraft, or make a turnaround over a congested area.
... No person may operate an aircraft over a congested area below the altitudes prescribed in part 91 of this chapter except during the actual dispensing operation, including the approaches and departures necessary for that operation.
... No person may operate an aircraft over a congested area during the actual dispensing operation, including the approaches and departures for that operation, unless it is operated in a pattern and at such an altitude that the aircraft can land, in an emergency, without endangering persons or property on the surface.
.. Multiengine aircraft must be operated as follows:
... No person may take off a multiengine airplane over a congested area except under conditions that will allow the airplane to be brought to a safe stop within the effective length of the runway from any point on takeoff up to the time of attaining, with all engines operating at normal takeoff power, 105 percent of the minimum control speed with the critical engine inoperative in the takeoff configuration or 115 percent of the power-off stall speed in the takeoff configuration, whichever is greater, as shown by the accelerate stop distance data. In applying this requirement, takeoff data is based upon still-air conditions, and no correction is made for any uphill gradient of 1 percent or less when the percentage is measured as the difference between elevation at the end points of the runway divided by the total length. For uphill gradients greater than 1 percent, the effective takeoff length of the runway is reduced 20 percent for each 1-percent grade.
... No person may operate a multiengine airplane at a weight greater than the weight that, with the critical engine inoperative, would permit a rate of climb of at least 50 feet per minute at an altitude of at least 1,000 feet above the elevation of the highest ground or obstruction within the area to be worked or at an altitude of 5,000 feet, whichever is higher. For the purposes of this subdivision, it is assumed that the propeller of the inoperative engine is in the minimum drag position; that the wing flaps and landing gear are in the most favorable positions; and that the remaining engine or engines are operating at the maximum continuous power available.
... No person may operate any multiengine aircraft over a congested area below the altitudes prescribed in part 91 of this chapter except during the actual dispensing operation, including the approaches, departures, and turnarounds necessary for that operation.

## § 137.53

### Operation over congested areas: Pilots and aircraft.

. *General.* No person may operate an aircraft over a congested area except in accordance with the pilot and aircraft rules of this section.
. *Pilots.* Each pilot in command must have at least—
.. 25 hours of pilot-in-command flight time in the make and basic model of the aircraft, at least 10 hours of which must have been acquired within the preceding 12 calendar months; and
.. 100 hours of flight experience as pilot in command in dispensing agricultural materials or chemicals.
. *Aircraft.* (1) Each aircraft must—(i) If it is an aircraft not specified in paragraph (c)(1)(ii) of this section, have had within the preceding 100 hours of time in service a 100-hour or annual inspection by a person authorized by part 65 or 145 of this chapter, or have been inspected under a progressive inspection system; and

(ii) If it is a large or turbine-powered multiengine civil airplane of U.S. registry, have been inspected in accordance with the applicable inspection program requirements of § 91.409 of this chapter.
              

(2) If other than a helicopter, it must be equipped with a device capable of jettisoning at least one-half of the aircraft's maximum authorized load of agricultural material within 45 seconds. If the aircraft is equipped with a device for releasing the tank or hopper as a unit, there must be a means to prevent inadvertent release by the pilot or other crewmember.

## § 137.55

### Business name: Commercial agricultural aircraft operator.

No person may operate under a business name that is not shown on his commercial agricultural aircraft operator certificate.

## § 137.57

### Availability of certificate.

Each holder of an agricultural aircraft operator certificate shall keep that certificate at his home base of operations and shall present it for inspection on the request of the Administrator or any Federal, State, or local law enforcement officer.

## § 137.59

### Inspection authority.

Each holder of an agricultural aircraft operator certificate shall allow the Administrator at any time and place to make inspections, including on-the-job inspections, to determine compliance with applicable regulations and his agricultural aircraft operator certificate.

