# Approval of Areas and Routes for Supplemental Operations
:toc:

## § 121.111

### Applicability.

This subpart prescribes rules for obtaining approval of areas and routes by certificate holders conducting supplemental operations.

## § 121.113

### Area and route requirements: General.

. Each certificate holder conducting supplemental operations seeking route and area approval must show—
              
.. That it is able to conduct operations within the United States in accordance with paragraphs (a) (3) and (4) of this section;
.. That it is able to conduct operations in accordance with the applicable requirements for each area outside the United States for which authorization is requested;
.. That it is equipped and able to conduct operations over, and use the navigational facilities associated with, the Federal airways, foreign airways, or advisory routes (ADR's) to be used; and
.. That it will conduct all IFR and night VFR operations over Federal airways, foreign airways, controlled airspace, or advisory routes (ADR's).
. Notwithstanding paragraph (a)(4) of this section, the Administrator may approve a route outside of controlled airspace if the certificate holder conducting supplemental operations shows the route is safe for operations and the Administrator finds that traffic density is such that an adequate level of safety can be assured. The certificate holder may not use such a route unless it is approved by the Administrator and is listed in the certificate holder's operations specifications.

## § 121.115

### Route width.

. Routes and route segments over Federal airways, foreign airways, or advisory routes have a width equal to the designated width of those airways or advisory routes. Whenever the Administrator finds it necessary to determine the width of other routes, he considers the following:
.. Terrain clearance.
.. Minimum en route altitudes.
.. Ground and airborne navigation aids.
.. Air traffic density.
.. ATC procedures.
. Any route widths of other routes determined by the Administrator are specified in the certificate holder's operations specifications.

## § 121.117

### Airports: Required data.

. No certificate holder conducting supplemental operations may use any airport unless it is properly equipped and adequate for the proposed operation, considering such items as size, surface, obstructions, facilities, public protection, lighting, navigational and communications aids, and ATC.
. Each certificate holder conducting supplemental operations must show that it has an approved system for obtaining, maintaining, and distributing to appropriate personnel current aeronautical data for each airport it uses to ensure a safe operation at that airport. The aeronautical data must include the following:
.. (1) Airports.
... (i) Facilities.
... protection.
... and communications aids.
... affecting takeoff, landing, or ground operations.
... traffic facilities.
.. clearways, and stopways.
... (i) Dimensions.
... (ii) Surface.
... and lighting systems.
... and gradient.
.. thresholds.
... (i) Location.
... (ii) Dimensions.
... or landing or both.
.. (4) Obstacles.
... affecting takeoff and landing performance computations in accordance with Subpart I of this part.
... obstacles.
.. flight procedures.
... procedure.
... procedure.
... approach procedure.
.. information.
... visual range measurement equipment.
... winds under low visibility conditions.
. If the certificate-holding district office charged with the overall inspection of the certificate holder's operations finds that revisions are necessary for the continued adequacy of the certificate holder's system for collection, dissemination, and usage of aeronautical data that has been granted approval, the certificate holder shall, after notification by the certificate-holding district office, make those revisions in the system. Within 30 days after the certificate holder receives such notice, the certificate holder may file a petition to reconsider the notice with the Director, Flight Standards Service. This filing of a petition to reconsider stays the notice pending a decision by the Director, Flight Standards Service. However, if the certificate-holding district office finds that there is an emergency that requires immediate action in the interest of safety in air transportation, the Director, Flight Standards Service may, upon a statement of the reasons, require a change effective without stay.

## § 121.119

### Weather reporting facilities.

. No certificate holder conducting supplemental operations may use any weather report to control flight unless it was prepared and released by the U.S. National Weather Service or a source approved by the Weather Bureau. For operations outside the U.S., or at U.S. Military airports, where those reports are not available, the certificate holder must show that its weather reports are prepared by a source found satisfactory by the Administrator.
. Each certificate holder conducting supplemental operations that uses forecasts to control flight movements shall use forecasts prepared from weather reports specified in paragraph (a) of this section.

## § 121.121

### En route navigation facilities.

. Except as provided in paragraph (b) of this section, no certificate holder conducting supplemental operations may conduct any operation over a route (including to any destination, refueling or alternate airports) unless suitable navigation aids are available to navigate the airplane along the route within the degree of accuracy required for ATC. Navigation aids required for routes outside of controlled airspace are listed in the certificate holder's operations specifications except for those aids required for routes to alternate airports.
. Navigation aids are not required for any of the following operations—
.. Day VFR operations that the certificate holder shows can be conducted safely by pilotage because of the characteristics of the terrain;
.. Night VFR operations on routes that the certificate holder shows have reliably lighted landmarks adequate for safe operation; and
.. Other operations approved by the certificate holding district office.

## § 121.122

### Communications facilities—supplemental operations.

. Each certificate holder conducting supplemental operations other than all-cargo operations in an airplane with more than two engines must show that a two-way radio communication system or other means of communication approved by the FAA is available. It must ensure reliable and rapid communications under normal operating conditions over the entire route (either direct or via approved point-to-point circuits) between each airplane and the certificate holder, and between each airplane and the appropriate air traffic services, except as specified in § 121.351(c).
. Except as provided in paragraph (d) of this section, each certificate holder conducting supplemental operations other than all-cargo operations in an airplane with more than two engines must provide voice communications for ETOPS where voice communication facilities are available. In determining whether facilities are available, the certificate holder must consider potential routes and altitudes needed for diversion to ETOPS Alternate Airports. Where facilities are not available or are of such poor quality that voice communication is not possible, another communication system must be substituted.
. Except as provided in paragraph (d) of this section, for ETOPS beyond 180 minutes each certificate holder conducting supplemental operations other than all-cargo operations in an airplane with more than two engines must have a second communication system in addition to that required by paragraph (b) of this section. That system must be able to provide immediate satellite-based voice communications of landline telephone-fidelity. The system must provide communication capabilities between the flight crew and air traffic services and the flight crew and the certificate holder. In determining whether such communications are available, the certificate holder must consider potential routes and altitudes needed for diversion to ETOPS Alternate Airports. Where immediate, satellite-based voice communications are not available, or are of such poor quality that voice communication is not possible, another communication system must be substituted.
. Operators of turbine engine powered airplanes do not need to meet the requirements of paragraphs (b) and (c) of this section until February 15, 2008.

## § 121.123

### Servicing maintenance facilities.

Each certificate holder conducting supplemental operations must show that competent personnel and adequate facilities and equipment (including spare parts, supplies, and materials) are available for the proper servicing, maintenance, and preventive maintenance of aircraft and auxiliary equipment.

## § 121.125

### Flight following system.

. Each certificate holder conducting supplemental operations must show that it has—
.. An approved flight following system established in accordance with subpart U of this part and adequate for the proper monitoring of each flight, considering the operations to be conducted; and
.. Flight following centers located at those points necessary—
... To ensure the proper monitoring of the progress of each flight with respect to its departure at the point of origin and arrival at its destination, including intermediate stops and diversions therefrom, and maintenance or mechanical delays encountered at those points or stops; and
... To ensure that the pilot in command is provided with all information necessary for the safety of the flight.
. A certificate holder conducting supplemental operations may arrange to have flight following facilities provided by persons other than its employees, but in such a case the certificate holder continues to be primarily responsible for operational control of each flight.
. A flight following system need not provide for in-flight monitoring by a flight following center.
. The certificate holder's operations specifications specify the flight following system it is authorized to use and the location of the centers.

## § 121.127

### Flight following system; requirements.

. Each certificate holder conducting supplemental operations using a flight following system must show that—
.. The system has adequate facilities and personnel to provide the information necessary for the initiation and safe conduct of each flight to—
... The flight crew of each aircraft; and
... The persons designated by the certificate holder to perform the function of operational control of the aircraft; and
.. The system has a means of communication by private or available public facilities (such as telephone, telegraph, or radio) to monitor the progress of each flight with respect to its departure at the point of origin and arrival at its destination, including intermediate stops and diversions therefrom, and maintenance or mechanical delays encountered at those points or stops.
. The certificate holder conducting supplemental operations must show that the personnel specified in paragraph (a) of this section, and those it designates to perform the function of operational control of the aircraft, are able to perform their required duties.

