# Flight Operations
:toc:

## § 121.531

### Applicability.

This subpart prescribes requirements for flight operations applicable to all certificate holders, except where otherwise specified.

## § 121.533

### Responsibility for operational control: Domestic operations.

. Each certificate holder conducting domestic operations is responsible for operational control.
. The pilot in command and the aircraft dispatcher are jointly responsible for the preflight planning, delay, and dispatch release of a flight in compliance with this chapter and operations specifications.
. The aircraft dispatcher is responsible for—
.. Monitoring the progress of each flight;
.. Issuing necessary information for the safety of the flight; and
.. Cancelling or redispatching a flight if, in his opinion or the opinion of the pilot in command, the flight cannot operate or continue to operate safely as planned or released.
. Each pilot in command of an aircraft is, during flight time, in command of the aircraft and crew and is responsible for the safety of the passengers, crewmembers, cargo, and airplane.
. Each pilot in command has full control and authority in the operation of the aircraft, without limitation, over other crewmembers and their duties during flight time, whether or not he holds valid certificates authorizing him to perform the duties of those crewmembers.

## § 121.535

### Responsibility for operational control: Flag operations.

. Each certificate holder conducting flag operations is responsible for operational control.
. The pilot in command and the aircraft dispatcher are jointly responsible for the preflight planning, delay, and dispatch release of a flight in compliance with this chapter and operations specifications.
. The aircraft dispatcher is responsible for—
.. Monitoring the progress of each flight;
.. Issuing necessary instructions and information for the safety of the flight; and
.. Cancelling or redispatching a flight if, in his opinion or the opinion of the pilot in command, the flight cannot operate or continue to operate safely as planned or released.
. Each pilot in command of an aircraft is, during flight time, in command of the aircraft and crew and is responsible for the safety of the passengers, crewmembers, cargo, and airplane.
. Each pilot in command has full control and authority in the operation of the aircraft, without limitation, over other crewmembers and their duties during flight time, whether or not he holds valid certificates authorizing him to perform the duties of those crewmembers.
. No pilot may operate an aircraft in a careless or reckless manner so as to endanger life or property.

## § 121.537

### Responsibility for operational control: Supplemental operations.

. Each certificate holder conducting supplemental operations—
.. Is responsible for operational control; and
.. Shall list each person authorized by it to exercise operational control in its operator's manual.
. The pilot in command and the director of operations are jointly responsible for the initiation, continuation, diversion, and termination of a flight in compliance with this chapter and the operations specifications. The director of operations may delegate the functions for the initiation, continuation, diversion, and termination of a flight but he may not delegate the responsibility for those functions.
. The director of operations is responsible for cancelling, diverting, or delaying a flight if in his opinion or the opinion of the pilot in command the flight cannot operate or continue to operate safely as planned or released. The director of operations is responsible for assuring that each flight is monitored with respect to at least the following:
.. Departure of the flight from the place of origin and arrival at the place of destination, including intermediate stops and any diversions therefrom.
.. Maintenance and mechanical delays encountered at places of origin and destination and intermediate stops.
.. Any known conditions that may adversely affect the safety of flight.
. Each pilot in command of an aircraft is, during flight time, in command of the aircraft and crew and is responsible for the safety of the passengers, crewmembers, cargo, and aircraft. The pilot in command has full control and authority in the operation of the aircraft, without limitation, over other crewmembers and their duties during flight time, whether or not he holds valid certificates authorizing him to perform the duties of those crewmembers.
. Each pilot in command of an aircraft is responsible for the preflight planning and the operation of the flight in compliance with this chapter and the operations specifications.
. No pilot may operate an aircraft, in a careless or reckless manner, so as to endanger life or property.

## § 121.538

### Aircraft security.

Certificate holders conducting operations under this part must comply with the applicable security requirements in 49 CFR chapter XII.

## § 121.539

### Operations notices.

Each certificate holder shall notify its appropriate operations personnel of each change in equipment and operating procedures, including each known change in the use of navigation aids, airports, air traffic control procedures and regulations, local airport traffic control rules, and known hazards to flight, including icing and other potentially hazardous meteorological conditions and irregularities in ground and navigation facilities.

## § 121.541

### Operations schedules: Domestic and flag operations.

In establishing flight operations schedules, each certificate holder conducting domestic or flag operations shall allow enough time for the proper servicing of aircraft at intermediate stops, and shall consider the prevailing winds en route and the cruising speed of the type of aircraft used. This cruising speed may not be more than that resulting from the specified cruising output of the engines.

## § 121.542

### Flight crewmember duties.

. No certificate holder shall require, nor may any flight crewmember perform, any duties during a critical phase of flight except those duties required for the safe operation of the aircraft. Duties such as company required calls made for such nonsafety related purposes as ordering galley supplies and confirming passenger connections, announcements made to passengers promoting the air carrier or pointing out sights of interest, and filling out company payroll and related records are not required for the safe operation of the aircraft.
. No flight crewmember may engage in, nor may any pilot in command permit, any activity during a critical phase of flight which could distract any flight crewmember from the performance of his or her duties or which could interfere in any way with the proper conduct of those duties. Activities such as eating meals, engaging in nonessential conversations within the cockpit and nonessential communications between the cabin and cockpit crews, and reading publications not related to the proper conduct of the flight are not required for the safe operation of the aircraft.
. For the purposes of this section, critical phases of flight includes all ground operations involving taxi, takeoff and landing, and all other flight operations conducted below 10,000 feet, except cruise flight.
. During all flight time as defined in 14 CFR 1.1, no flight crewmember may use, nor may any pilot in command permit the use of, a personal wireless communications device (as defined in 49 U.S.C. 44732(d)) or laptop computer while at a flight crewmember duty station unless the purpose is directly related to operation of the aircraft, or for emergency, safety-related, or employment-related communications, in accordance with air carrier procedures approved by the Administrator.

## § 121.543

### Flight crewmembers at controls.

. Except as provided in paragraph (b) of this section, each required flight crewmember on flight deck duty must remain at the assigned duty station with seat belt fastened while the aircraft is taking off or landing, and while it is en route.
. A required flight crewmember may leave the assigned duty station—
.. If the crewmember's absence is necessary for the performance of duties in connection with the operation of the aircraft;
.. If the crewmember's absence is in connection with physiological needs; or
.. If the crewmember is taking a rest period, and relief is provided—
... In the case of the assigned pilot in command during the en route cruise portion of the flight, by a pilot who holds an airline transport pilot certificate not subject to the limitations in § 61.167 of this chapter and an appropriate type rating, is currently qualified as pilot in command or second in command, and is qualified as pilot in command of that aircraft during the en route cruise portion of the flight. A second in command qualified to act as a pilot in command en route need not have completed the following pilot in command requirements: The 6-month recurrent flight training required by § 121.433(c)(1)(iii); the operating experience required by § 121.434; the takeoffs and landings required by § 121.439; the line check required by § 121.440; and the 6-month proficiency check or simulator training required by § 121.441(a)(1); and
... In the case of the assigned second in command, by a pilot qualified to act as second in command of that aircraft during en route operations. However, the relief pilot need not meet the recent experience requirements of § 121.439(b).

## § 121.544

### Pilot monitoring.

Each pilot who is seated at the pilot controls of the aircraft, while not flying the aircraft, must accomplish pilot monitoring duties as appropriate in accordance with the certificate holder's procedures contained in the manual required by § 121.133 of this part. Compliance with this section is required no later than March 12, 2019.

## § 121.545

### Manipulation of controls.

No pilot in command may allow any person to manipulate the controls of an aircraft during flight nor may any person manipulate the controls during flight unless that person is—

. A qualified pilot of the certificate holder operating that aircraft.
. An authorized pilot safety representative of the Administrator or of the National Transportation Safety Board who has the permission of the pilot in command, is qualified in the aircraft, and is checking flight operations; or
. A pilot of another certificate holder who has the permission of the pilot in command, is qualified in the aircraft, and is authorized by the certificate holder operating the aircraft.

## § 121.547

### Admission to flight deck.

. No person may admit any person to the flight deck of an aircraft unless the person being admitted is—
.. A crewmember;
.. An FAA air carrier inspector, a DOD commercial air carrier evaluator, or an authorized representative of the National Transportation Safety Board, who is performing official duties;
.. Any person who—
... Has permission of the pilot in command, an appropriate management official of the part 119 certificate holder, and the Administrator; and
... Is an employee of—
.. Any person who has the permission of the pilot in command, an appropriate management official of the part 119 certificate holder and the Administrator. Paragraph (a)(2) of this section does not limit the emergency authority of the pilot in command to exclude any person from the flightdeck in the interests of safety.
. For the purposes of paragraph (a)(3) of this section, employees of the United States who deal responsibly with matters relating to safety and employees of the certificate holder whose efficiency would be increased by familiarity with flight conditions, may be admitted by the certificate holder. However, the certificate holder may not admit employees of traffic, sales, or other departments that are not directly related to flight operations, unless they are eligible under paragraph (a)(4) of this section.
. No person may admit any person to the flight deck unless there is a seat available for his use in the passenger compartment, except—
.. An FAA air carrier inspector, a DOD commercial air carrier evaluator, or authorized representative of the Administrator or National Transportation Safety Board who is checking or observing flight operations;
.. An air traffic controller who is authorized by the Administrator to observe ATC procedures;
.. A certificated airman employed by the certificate holder whose duties require an airman certificate;
.. A certificated airman employed by another part 119 certificate holder whose duties with that part 119 certificate holder require an airman certificate and who is authorized by the part 119 certificate holder operating the aircraft to make specific trips over a route;
.. An employee of the part 119 certificate holder operating the aircraft whose duty is directly related to the conduct or planning of flight operations or the in-flight monitoring of aircraft equipment or operating procedures, if his presence on the flightdeck is necessary to perform his duties and he has been authorized in writing by a responsible supervisor, listed in the Operations Manual as having that authority; and
.. A technical representative of the manufacturer of the aircraft or its components whose duties are directly related to the in-flight monitoring of aircraft equipment or operating procedures, if his presence on the flightdeck is necessary to perform his duties and he has been authorized in writing by the Administrator and by a responsible supervisor of the operations department of the part 119 certificate holder, listed in the Operations Manual as having that authority.

(A) The United States, or

(B) A part 119 certificate holder and whose duties are such that admission to the flightdeck is necessary or advantageous for safe operation; or

(C) An aeronautical enterprise certificated by the Administrator and whose duties are such that admission to the flightdeck is necessary or advantageous for safe operation.

## § 121.548

### Aviation safety inspector's credentials: Admission to pilot's compartment.

Whenever, in performing the duties of conducting an inspection, an inspector of the Federal Aviation Administration presents form FAA 110A, “Aviation Safety Inspector's Credential,” to the pilot in command of an aircraft operated by a certificate holder, the inspector must be given free and uninterrupted access to the pilot's compartment of that aircraft.

## § 121.548a

### DOD Commercial Air Carrier Evaluator's Credential.

Whenever, in performing the duties of conducting an evaluation, a DOD commercial air carrier evaluator presents S&A Form 110B, “DOD Commercial Air Carrier Evaluator's Credential,” to the pilot in command of an airplane operated by the certificate holder, the evaluator must be given free and uninterrupted access to the pilot's compartment of that airplane.

## § 121.549

### Flying equipment.

. The pilot in command shall ensure that appropriate aeronautical charts containing adequate information concerning navigation aids and instrument approach procedures are aboard the aircraft for each flight.
. Each crewmember shall, on each flight, have readily available for his use a flashlight that is in good working order.

## § 121.550

### Secret Service Agents: Admission to flight deck.

Whenever an Agent of the Secret Service who is assigned the duty of protecting a person aboard an aircraft operated by a certificate holder considers it necessary in the performance of his duty to ride on the flight deck of the aircraft, he must, upon request and presentation of his Secret Service credentials to the pilot in command of the aircraft, be admitted to the flight deck and permitted to occupy an observer seat thereon.

## § 121.551

### Restriction or suspension of operation: Domestic and flag operations.

When a certificate holder conducting domestic or flag operations knows of conditions, including airport and runway conditions, that are a hazard to safe operations, it shall restrict or suspend operations until those conditions are corrected.

## § 121.553

### Restriction or suspension of operation: Supplemental operations.

When a certificate holder conducting supplemental operations or pilot in command knows of conditions, including airport and runway conditions, that are a hazard to safe operations, the certificate holder or pilot in command, as the case may be, shall restrict or suspend operations until those conditions are corrected.

## § 121.555

### Compliance with approved routes and limitations: Domestic and flag operations.

No pilot may operate an airplane in scheduled air transportation—

. Over any route or route segment unless it is specified in the certificate holder's operations specifications; or
. Other than in accordance with the limitations in the operations specifications.

## § 121.557

### Emergencies: Domestic and flag operations.

. In an emergency situation that requires immediate decision and action the pilot in command may take any action that he considers necessary under the circumstances. In such a case he may deviate from prescribed operations procedures and methods, weather minimums, and this chapter, to the extent required in the interests of safety.
. In an emergency situation arising during flight that requires immediate decision and action by an aircraft dispatcher, and that is known to him, the aircraft dispatcher shall advise the pilot in command of the emergency, shall ascertain the decision of the pilot in command, and shall have the decision recorded. If the aircraft dispatcher cannot communicate with the pilot, he shall declare an emergency and take any action that he considers necessary under the circumstances.
. Whenever a pilot in command or dispatcher exercises emergency authority, he shall keep the appropriate ATC facility and dispatch centers fully informed of the progress of the flight. The person declaring the emergency shall send a written report of any deviation through the certificate holder's operations manager, to the Administrator. A dispatcher shall send his report within 10 days after the date of the emergency, and a pilot in command shall send his report within 10 days after returning to his home base.

## § 121.559

### Emergencies: Supplemental operations.

. In an emergency situation that requires immediate decision and action, the pilot in command may take any action that he considers necessary under the circumstances. In such a case, he may deviate from prescribed operations, procedures and methods, weather minimums, and this chapter, to the extent required in the interests of safety.
. In an emergency situation arising during flight that requires immediate decision and action by appropriate management personnel in the case of operations conducted with a flight following service and which is known to them, those personnel shall advise the pilot in command of the emergency, shall ascertain the decision of the pilot in command, and shall have the decision recorded. If they cannot communicate with the pilot, they shall declare an emergency and take any action that they consider necessary under the circumstances.
. Whenever emergency authority is exercised, the pilot in command or the appropriate management personnel shall keep the appropriate communication facility fully informed of the progress of the flight. The person declaring the emergency shall send a written report of any deviation, through the certificate holder's director of operations, to the Administrator within 10 days after the flight is completed or, in the case of operations outside the United States, upon return to the home base.

## § 121.561

### Reporting potentially hazardous meteorological conditions and irregularities of ground facilities or navigation aids.

. Whenever he encounters a meteorological condition or an irregularity in aground facility or navigation aid, in flight, the knowledge of which he considers essential to the safety of other flights, the pilot in command shall notify an appropriate ground station as soon as practicable.
. The ground radio station that is notified under paragraph (a) of this section shall report the information to the agency directly responsible for operating the facility.

## § 121.563

### Reporting mechanical irregularities.

The pilot in command shall ensure that all mechanical irregularities occurring during flight time are entered in the maintenance log of the airplane at the end of that flight time. Before each flight the pilot in command shall ascertain the status of each irregularity entered in the log at the end of the preceding flight.

## § 121.565

### Engine inoperative: Landing; reporting.

. Except as provided in paragraph (b) of this section, whenever an airplane engine fails or whenever an engine is shutdown to prevent possible damage, the pilot in command must land the airplane at the nearest suitable airport, in point of time, at which a safe landing can be made.
. If not more than one engine of an airplane that has three or more engines fails or is shut down to prevent possible damage, the pilot-in-command may proceed to an airport that the pilot selects if, after considering the following, the pilot makes a reasonable decision that proceeding to that airport is as safe as landing at the nearest suitable airport:
.. The nature of the malfunction and the possible mechanical difficulties that may occur if flight is continued.
.. The altitude, weight, and useable fuel at the time that the engine is shutdown.
.. The weather conditions en route and at possible landing points.
.. The air traffic congestion.
.. The kind of terrain.
.. His familiarity with the airport to be used.
. The pilot-in-command must report each engine shutdown in flight to the appropriate communication facility as soon as practicable and must keep that facility fully informed of the progress of the flight.
. If the pilot in command lands at an airport other than the nearest suitable airport, in point of time, he or she shall (upon completing the trip) send a written report, in duplicate, to his or her director of operations stating the reasons for determining that the selection of an airport, other than the nearest airport, was as safe a course of action as landing at the nearest suitable airport. The director of operations shall, within 10 days after the pilot returns to his or her home base, send a copy of this report with the director of operation's comments to the certificate-holding district office.

## § 121.567

### Instrument approach procedures and IFR landing minimums.

No person may make an instrument approach at an airport except in accordance with IFR weather minimums and instrument approach procedures set forth in the certificate holder's operations specifications.

## § 121.569

### Equipment interchange: Domestic and flag operations.

. Before operating under an interchange agreement, each certificate holder conducting domestic or flag operations shall show that—
.. The procedures for the interchange operation conform with this chapter and with safe operating practices;
.. Required crewmembers and dispatchers meet approved training requirements for the airplanes and equipment to be used and are familiar with the communications and dispatch procedures to be used;
.. Maintenance personnel meet training requirements for the airplanes and equipment, and are familiar with the maintenance procedures to be used;
.. Flight crewmembers and dispatchers meet appropriate route and airport qualifications; and
.. The airplanes to be operated are essentially similar to the airplanes of the certificate holder with whom the interchange is effected with respect to the arrangement of flight instruments and the arrangement and motion of controls that are critical to safety unless the Administrator determines that the certificate holder has adequate training programs to insure that any potentially hazardous dissimilarities are safely overcome by flight crew familiarization.
. Each certificate holder conducting domestic or flag operations shall include the pertinent provisions and procedures involved in the equipment interchange agreement in its manuals.

## § 121.570

### Airplane evacuation capability.

. No person may cause an airplane carrying passengers to be moved on the surface, take off, or land unless each automatically deployable emergency evacuation assisting means, installed pursuant to § 121.310(a), is ready for evacuation.
. Each certificate holder shall ensure that, at all times passengers are on board prior to airplane movement on the surface, at least one floor-level exit provides for the egress of passengers through normal or emergency means.

## § 121.571

### Briefing passengers before takeoff.

. Each certificate holder operating a passenger-carrying airplane shall insure that all passengers are orally briefed by the appropriate crewmember as follows:
.. Before each takeoff, on each of the following:
... *Smoking.* Each passenger shall be briefed on when, where, and under what conditions smoking is prohibited including, but not limited to, any applicable requirements of part 252 of this title). This briefing shall include a statement that the Federal Aviation Regulations require passenger compliance with the lighted passenger information signs, posted placards, areas designated for safety purposes as no smoking areas, and crewmember instructions with regard to these items. The briefing shall also include a statement that Federal law prohibits tampering with, disabling, or destroying any smoke detector in an airplane lavatory; smoking in lavatories; and, when applicable, smoking in passenger compartments.
... The location of emergency exits.
... The use of safety belts, including instructions on how to fasten and unfasten the safety belts. Each passenger shall be briefed on when, where, and under what conditions the safety belt must be fastened about that passenger. This briefing shall include a statement that the Federal Aviation Regulations require passenger compliance with lighted passenger information signs and crewmember instructions concerning the use of safety belts.
... The location and use of any required emergency flotation means.
... On operations that do not use a flight attendant, the following additional information:
.. After each takeoff, immediately before or immediately after turning the seat belt sign off, an announcement shall be made that passengers should keep their seat belts fastened, while seated, even when the seat belt sign is off.
.. Except as provided in paragraph (a)(4) of this section, before each takeoff a required crewmember assigned to the flight shall conduct an individual briefing of each person who may need the assistance of another person to move expeditiously to an exit in the event of an emergency. In the briefing the required crewmember shall—
... Brief the person and his attendant, if any, on the routes to each appropriate exit and on the most appropriate time to begin moving to an exit in the event of an emergency; and
... Inquire of the person and his attendant, if any, as to the most appropriate manner of assisting the person so as to prevent pain and further injury.
.. The requirements of paragraph (a)(3) of this section do not apply to a person who has been given a briefing before a previous leg of a flight in the same aircraft when the crewmembers on duty have been advised as to the most appropriate manner of assisting the person so as to prevent pain and further injury.
. Each certificate holder must carry on each passenger-carrying airplane, in convenient locations for use of each passenger, printed cards supplementing the oral briefing. Each card must contain information pertinent only to the type and model of airplane used for that flight, including—
.. Diagrams of, and methods of operating, the emergency exits;
.. Other instructions necessary for use of emergency equipment; and
.. No later than June 12, 2005, for Domestic and Flag scheduled passenger-carrying flights, the sentence, “Final assembly of this airplane was completed in [INSERT NAME OF COUNTRY].”
. The certificate holder shall describe in its manual the procedure to be followed in the briefing required by paragraph (a) of this section.

(A) The placement of seat backs in an upright position before takeoff and landing.

(B) Location of survival equipment.

(C) If the flight involves operations above 12,000 MSL, the normal and emergency use of oxygen.

(D) Location and operation of fire extinguisher.

## § 121.573

### Briefing passengers: Extended overwater operations.

. In addition to the oral briefing required by § 121.571(a), each certificate holder operating an airplane in extended overwater operations shall ensure that all passengers are orally briefed by the appropriate crewmember on the location and operation of life preservers, liferafts, and other flotation means, including a demonstration of the method of donning and inflating a life preserver.
. The certificate holder shall describe in its manual the procedure to be followed in the briefing required by paragraph (a) of this section.
. If the airplane proceeds directly over water after takeoff, the briefing required by paragraph (a) of this section must be done before takeoff.
. If the airplane does not proceed directly over water after takeoff, no part of the briefing required by paragraph (a) of this section has to be given before takeoff, but the entire briefing must be given before reaching the overwater part of the flight.

## § 121.574

### Oxygen and portable oxygen concentrators for medical use by passengers.

. A certificate holder may allow a passenger to carry and operate equipment for the storage, generation, or dispensing of oxygen when all of the conditions in paragraphs (a) through (d) of this section are satisfied. Beginning August 22, 2016, a certificate holder may allow a passenger to carry and operate a portable oxygen concentrator when the conditions in paragraphs (b) and (e) of this section are satisfied.
.. The equipment is—
... Furnished by the certificate holder;
... Of an approved type or is in conformity with the manufacturing, packaging, marking, labeling, and maintenance requirements of 49 CFR parts 171, 172, and 173, except § 173.24(a)(1);
... Maintained by the certificate holder in accordance with an approved maintenance program;
... Free of flammable contaminants on all exterior surfaces;
... Capable of providing a minimum mass flow of oxygen to the user of four liters per minute;
... Constructed so that all valves, fittings, and gauges are protected from damage; and
... Appropriately secured.
.. When the oxygen is stored in the form of a liquid, the equipment has been under the certificate holder's approved maintenance program since its purchase new or since the storage container was last purged.
.. When the oxygen is stored in the form of a compressed gas as defined in 49 CFR 173.115(b)—
... The equipment has been under the certificate holder's approved maintenance program since its purchase new or since the last hydrostatic test of the storage cylinder; and
... The pressure in any oxygen cylinder does not exceed the rated cylinder pressure.
.. Each person using the equipment has a medical need to use it evidenced by a written statement to be kept in that person's possession, signed by a licensed physician which specifies the maximum quantity of oxygen needed each hour and the maximum flow rate needed for the pressure altitude corresponding to the pressure in the cabin of the airplane under normal operating conditions. This paragraph does not apply to the carriage of oxygen in an airplane in which the only passengers carried are persons who may have a medical need for oxygen during flight, no more than one relative or other interested person for each of those persons, and medical attendants.
.. When a physician's statement is required by paragraph (a)(4) of this section, the total quantity of oxygen carried is equal to the maximum quantity of oxygen needed each hour, as specified in the physician's statement, multiplied by the number of hours used to compute the amount of airplane fuel required by this part.
.. The pilot in command is advised when the equipment is on board, and when it is intended to be used.
.. The equipment is stowed, and each person using the equipment is seated, so as not to restrict access to or use of any required emergency, or regular exit or of the aisle in the passenger compartment.
. No person may smoke or create an open flame and no certificate holder may allow any person to smoke or create an open flame within 10 feet of oxygen storage and dispensing equipment carried in accordance with paragraph (a) of this section or a portable oxygen concentrator carried and operated in accordance with paragraph (e) of this section.
. No certificate holder may allow any person to connect or disconnect oxygen dispensing equipment, to or from a gaseous oxygen cylinder while any passenger is aboard the airplane.
. The requirements of this section do not apply to the carriage of supplemental or first-aid oxygen and related equipment required by this chapter.
. *Portable oxygen concentrators*—(1) *Acceptance criteria.* A passenger may carry or operate a portable oxygen concentrator for personal use on board an aircraft and a certificate holder may allow a passenger to carry or operate a portable oxygen concentrator on board an aircraft operated under this part during all phases of flight if the portable oxygen concentrator satisfies all of the requirements in this paragraph (e):
              

(i) Is legally marketed in the United States in accordance with Food and Drug Administration requirements in title 21 of the CFR;

(ii) Does not radiate radio frequency emissions that interfere with aircraft systems;

(iii) Generates a maximum oxygen pressure of less than 200 kPa gauge (29.0 psig/43.8 psia) at 20 °C (68 °F);

(iv) Does not contain any hazardous materials subject to the Hazardous Materials Regulations (49 CFR parts 171 through 180) except as provided in 49 CFR 175.10 for batteries used to power portable electronic devices and that do not require aircraft operator approval; and

(v) Bears a label on the exterior of the device applied in a manner that ensures the label will remain affixed for the life of the device and containing the following certification statement in red lettering: “The manufacturer of this POC has determined this device conforms to all applicable FAA acceptance criteria for POC carriage and use on board aircraft.” The label requirements in this paragraph (e)(1)(v) do not apply to the following portable oxygen concentrators approved by the FAA for use on board aircraft prior to May 24, 2016:

(A) AirSep Focus;

(B) AirSep FreeStyle;

(C) AirSep FreeStyle 5;

(D) AirSep LifeStyle;

(E) Delphi RS-00400;

(F) DeVilbiss Healthcare iGo;

(G) Inogen One;

(H) Inogen One G2;

(I) Inogen One G3;

(J) Inova Labs LifeChoice;

(K) Inova Labs LifeChoice Activox;

(L) International Biophysics LifeChoice;

(M) Invacare Solo2;

(N) Invacare XPO2;

(O) Oxlife Independence Oxygen Concentrator;

(P) Oxus RS-00400;

(Q) Precision Medical EasyPulse;

(R) Respironics EverGo;

(S) Respironics SimplyGo;

(T) SeQual Eclipse;

(U) SeQual eQuinox Oxygen System (model 4000);

(V) SeQual Oxywell Oxygen System (model 4000);

(W) SeQual SAROS; and

(X) VBox Trooper Oxygen Concentrator.

(2) *Operating requirements.* Portable oxygen concentrators that satisfy the acceptance criteria identified in paragraph (e)(1) of this section may be carried or operated by a passenger on an aircraft provided the aircraft operator ensures that all of the conditions in this paragraph (e)(2) are satisfied:

(i) *Exit seats.* No person operating a portable oxygen concentrator is permitted to occupy an exit seat.

(ii) *Stowage of device.* During movement on the surface, takeoff and landing, the device must be stowed under the seat in front of the user, or in another approved stowage location so that it does not block the aisle way or the entryway to the row. If the device is to be operated by the user, it must be operated only at a seat location that does not restrict any passenger's access to, or use of, any required emergency or regular exit, or the aisle(s) in the passenger compartment.

## § 121.575

### Alcoholic beverages.

. No person may drink any alcoholic beverage aboard an aircraft unless the certificate holder operating the aircraft has served that beverage to him.
. No certificate holder may serve any alcoholic beverage to any person aboard any of its aircraft who—
.. Appears to be intoxicated;
.. Is escorting a person or being escorted in accordance with 49 CFR 1544.221; or
.. Has a deadly or dangerous weapon accessible to him while aboard the aircraft in accordance with 49 CFR 1544.219, 1544.221, or 1544.223.
. No certificate holder may allow any person to board any of its aircraft if that person appears to be intoxicated.
. Each certificate holder shall, within five days after the incident, report to the Administrator the refusal of any person to comply with paragraph (a) of this section, or of any disturbance caused by a person who appears to be intoxicated aboard any of its aircraft.

## § 121.576

### Retention of items of mass in passenger and crew compartments.

The certificate holder must provide and use means to prevent each item of galley equipment and each serving cart, when not in use, and each item of crew baggage, which is carried in a passenger or crew compartment from becoming a hazard by shifting under the appropriate load factors corresponding to the emergency landing conditions under which the airplane was type certificated.

## § 121.577

### Stowage of food, beverage, and passenger service equipment during airplane movement on the surface, takeoff, and landing.

. No certificate holder may move an airplane on the surface, take off, or land when any food, beverage, or tableware furnished by the certificate holder is located at any passenger seat.
. No certificate holder may move an airplane on the surface, take off, or land unless each food and beverage tray and seat back tray table is secured in its stowed position.
. No certificate holder may permit an airplane to move on the surface, take off, or land unless each passenger serving cart is secured in its stowed position.
. No certificate holder may permit an airplane to move on the surface, take off, or land unless each movie screen that extends into an aisle is stowed.
. Each passenger shall comply with instructions given by a crewmember with regard to compliance with this section.

## § 121.578

### Cabin ozone concentration.

. For the purpose of this section, the following definitions apply:
.. *Flight segment* means scheduled nonstop flight time between two airports.
.. *Sea level equivalent* refers to conditions of 25 °C and 760 millimeters of mercury pressure.
. Except as provided in paragraphs (d) and (e) of this section, no certificate holder may operate an airplane above the following flight levels unless it is successfully demonstrated to the Administrator that the concentration of ozone inside the cabin will not exceed—
.. For flight above flight level 320, 0.25 parts per million by volume, sea level equivalent, at any time above that flight level; and
.. For flight above flight level 270, 0.1 parts per million by volume, sea level equivalent, time-weighted average for each flight segment that exceeds 4 hours and includes flight above that flight level. (For this purpose, the amount of ozone below flight level 180 is considered to be zero.)
. Compliance with this section must be shown by analysis or tests, based on either airplane operational procedures and performance limitations or the certificate holder's operations. The analysis or tests must show either of the following:
.. Atmospheric ozone statistics indicate, with a statistical confidence of at least 84%, that at the altitudes and locations at which the airplane will be operated cabin ozone concentrations will not exceed the limits prescribed by paragraph (b) of this section.
.. The airplane ventilation system including any ozone control equipment, will maintain cabin ozone concentrations at or below the limits prescribed by paragraph (b) of this section.
. A certificate holder may obtain an authorization to deviate from the requirements of paragraph (b) of this section, by an amendment to its operations specifications, if—
.. It shows that due to circumstances beyond its control or to unreasonable economic burden it cannot comply for a specified period of time; and
.. It has submitted a plan acceptable to the Administrator to effect compliance to the extent possible.
              
. A certificate holder need not comply with the requirements of paragraph (b) of this section for an aircraft—
.. When the only persons carried are flight crewmembers and persons listed in § 121.583;
.. If the aircraft is scheduled for retirement before January 1, 1985; or
.. If the aircraft is scheduled for re-engining under the provisions of subpart E of part 91, until it is re-engined.

## § 121.579

### Minimum altitudes for use of autopilot.

. *Definitions.* For purpose of this section—
.. Altitudes for takeoff/initial climb and go-around/missed approach are defined as above the airport elevation.
.. Altitudes for enroute operations are defined as above terrain elevation.
.. Altitudes for approach are defined as above the touchdown zone elevation (TDZE), unless the altitude is specifically in reference to DA (H) or MDA, in which case the altitude is defined by reference to the DA(H) or MDA itself.
. *Takeoff and initial climb.* No person may use an autopilot for takeoff or initial climb below the higher of 500 feet or an altitude that is no lower than twice the altitude loss specified in the Airplane Flight Manual (AFM), except as follows—
.. At a minimum engagement altitude specified in the AFM; or
.. At an altitude specified by the Administrator, whichever is greater.
. *Enroute.* No person may use an autopilot enroute, including climb and descent, below the following—
.. 500 feet;
.. At an altitude that is no lower than twice the altitude loss specified in the AFM for an autopilot malfunction in cruise conditions; or
.. At an altitude specified by the Administrator, whichever is greater.
. *Approach.* No person may use an autopilot at an altitude lower than 50 feet below the DA(H) or MDA for the instrument procedure being flown, except as follows—
.. For autopilots with an AFM specified altitude loss for approach operations—
... An altitude no lower than twice the specified altitude loss if higher than 50 feet below the MDA or DA(H);
... An altitude no lower than 50 feet higher than the altitude loss specified in the AFM, when the following conditions are met—
... An altitude no lower than the higher of the altitude loss specified in the AFM or 50 feet above the TDZE, when the following conditions are met—
... A greater altitude specified by the Administrator.
.. For autopilots with AFM specified approach altitude limitations, the greater of—
... The minimum use altitude specified for the coupled approach mode selected;
... 50 feet; or
... An altitude specified by Administrator.
.. For autopilots with an AFM specified negligible or zero altitude loss for an autopilot approach mode malfunction, the greater of—
... 50 feet; or
... An altitude specified by Administrator.
.. If executing an autopilot coupled go-around or missed approach using a certificated and functioning autopilot in accordance with paragraph (e) in this section.
. *Go-Around/Missed Approach.* No person may engage an autopilot during a go-around or missed approach below the minimum engagement altitude specified for takeoff and initial climb in paragraph (b) in this section. An autopilot minimum use altitude does not apply to a go-around/missed approach initiated with an engaged autopilot. Performing a go-around or missed approach with an engaged autopilot must not adversely affect safe obstacle clearance.
. *Landing.* Notwithstanding paragraph (d) of this section, autopilot minimum use altitudes do not apply to autopilot operations when an approved automatic landing system mode is being used for landing. Automatic landing systems must be authorized in an operations specification issued to the operator.

(A) Reported weather conditions are less than the basic VFR weather conditions in § 91.155 of this chapter;

(B) Suitable visual references specified in § 91.175 of this chapter have been established on the instrument approach procedure; and

(C) The autopilot is coupled and receiving both lateral and vertical path references;

(A) Reported weather conditions are equal to or better than the basic VFR weather conditions in § 91.155 of this chapter; and

(B) The autopilot is coupled and receiving both lateral and vertical path references; or

## § 121.580

### Prohibition on interference with crewmembers.

No person may assault, threaten, intimidate, or interfere with a crewmember in the performance of the crewmember's duties aboard an aircraft being operated under this part.

## § 121.581

### Observer's seat: En route inspections.

. Except as provided in paragraph (c) of this section, each certificate holder shall make available a seat on the flight deck of each airplane, used by it in air commerce, for occupancy by the Administrator while conducting en route inspections. The location and equipment of the seat, with respect to its suitability for use in conducting en route inspections, is determined by the Administrator.
. In each airplane that has more than one observer's seat, in addition to the seats required for the crew complement for which the airplane was certificated, the forward observer's seat or the observer's seat selected by the Administrator must be made available when complying with paragraph (a) of this section.
. For any airplane type certificated before December 20, 1995, for not more than 30 passengers that does not have an observer seat on the flightdeck, the certificate holder must provide a forward passenger seat with headset or speaker for occupancy by the Administrator while conducting en route inspections.

## § 121.582

### Means to discreetly notify a flightcrew.

Except for all-cargo operations as defined in § 110.2 of this chapter, after October 15, 2007, for all passenger carrying airplanes that require a lockable flightdeck door in accordance with § 121.313(f), the certificate holder must have an approved means by which the cabin crew can discreetly notify the flightcrew in the event of suspicious activity or security breaches in the cabin.

## § 121.583

### Carriage of persons without compliance with the passenger-carrying requirements of this part.

. When authorized by the certificate holder, the following persons, but no others, may be carried aboard an airplane without complying with the passenger-carrying airplane requirements in §§ 121.309(f), 121.310, 121.391, 121.571, and 121.587; the passenger-carrying operation requirements in part 117 and §§ 121.157(c) and 121.291; the requirements pertaining to passengers in §§ 121.285, 121.313(f), 121.317, 121.547, and 121.573; and the information disclosure requirements in § 121.311(k):
.. A crewmember.
.. A company employee.
.. An FAA air carrier inspector, a DOD commercial air carrier evaluator, or an authorized representative of the National Transportation Safety Board, who is performing official duties.
.. A person necessary for—
... The safety of the flight;
... The safe handling of animals;
... The safe handling of hazardous materials whose carriage is governed by regulations in 49 CFR part 175;
... The security of valuable or confidential cargo;
... The preservation of fragile or perishable cargo;
              
... Experiments on, or testing of, cargo containers or cargo handling devices;
... The operation of special equipment for loading or unloading cargo; and
... The loading or unloading of outsize cargo.
.. A person described in paragraph (a)(4) of this section, when traveling to or from his assignment.
.. A person performing duty as an honor guard accompanying a shipment made by or under the authority of the United States.
.. A military courier, military route supervisor, military cargo contract coordinator, or a flight crewmember of another military cargo contract air carrier or commercial operator, carried by a military cargo contract air carrier or commercial operator in operations under a military cargo contract, if that carriage is specifically authorized by the appropriate armed forces.
.. A dependent of an employee of the certificate holder when traveling with the employee on company business to or from outlying stations not served by adequate regular passenger flights.
. No certificate holder may operate an airplane carrying a person covered by paragraph (a) of this section unless—
.. Each person has unobstructed access from his seat to the pilot compartment or to a regular or emergency exit;
.. The pilot in command has a means of notifying each person when smoking is prohibited and when safety belts must be fastened; and
.. The airplane has an approved seat with an approved safety belt for each person. The seat must be located so that the occupant is not in any position to interfere with the flight crewmembers performing their duties.
. Before each takeoff, each certificate holder operating an airplane carrying persons covered by paragraph (a) of this section shall ensure that all such persons have been orally briefed by the appropriate crewmember on—
.. Smoking;
.. The use of seat belts;
.. The location and operation of emergency exits;
.. The use of oxygen and emergency oxygen equipment; and
.. For extended overwater operations, the location of life rafts, and the location and operation of life preservers including a demonstration of the method of donning and inflating a life preserver.
. Each certificate holder operating an airplane carrying persons covered by paragraph (a) of this section shall incorporate procedures for the safe carriage of such persons into the certificate holder's operations manual.
. The pilot in command may authorize a person covered by paragraph (a) of this section to be admitted to the crew compartment of the airplane.

## § 121.584

### Requirement to view the area outside the flightdeck door.

From the time the airplane moves in order to initiate a flight segment through the end of that flight segment, no person may unlock or open the flightdeck door unless:

. A person authorized to be on the flightdeck uses an approved audio procedure and an approved visual device to verify that:
.. The area outside the flightdeck door is secure, and;
.. If someone outside the flightdeck is seeking to have the flightdeck door opened, that person is not under duress, and;
. After the requirements of paragraph (a) of this section have been satisfactorily accomplished, the crewmember in charge on the flightdeck authorizes the door to be unlocked and open.

## § 121.585

### Exit seating.

. Each certificate holder shall determine, to the extent necessary to perform the applicable functions of paragraph (d) of this section, the suitability of each person it permits to occupy an exit seat, in accordance with this section. For the purpose of this section—
. No certificate holder may seat a person in a seat affected by this section if the certificate holder determines that it is likely that the person would be unable to perform one or more of the applicable functions listed in paragraph (d) of this section because—
.. The person lacks sufficient mobility, strength, or dexterity in both arms and hands, and both legs:
... To reach upward, sideways, and downward to the location of emergency exit and exit-slide operating mechanisms;
... To grasp and push, pull, turn, or otherwise manipulate those mechanisms;
... To push, shove, pull, or otherwise open emergency exits;
... To lift out, hold, deposit on nearby seats, or maneuver over the seatbacks to the next row objects the size and weight of over-wing window exit doors;
... To remove obstructions similar in size and weight to over-wing exit doors;
... To reach the emergency exit expeditiously;
... To maintain balance while removing obstructions;
... To exit expeditiously;
... To stabilize an escape slide after deployment; or
... To assist others in getting off an escape slide;
.. The person is less than 15 years of age or lacks the capacity to perform one or more of the applicable functions listed in paragraph (d) of this section without the assistance of an adult companion, parent, or other relative;
.. The person lacks the ability to read and understand instructions required by this section and related to emergency evacuation provided by the certificate holder in printed or graphic form or the ability to understand oral crew commands.
.. The person lacks sufficient visual capacity to perform one or more of the applicable functions in paragraph (d) of this section without the assistance of visual aids beyond contact lenses or eyeglasses;
.. The person lacks sufficient aural capacity to hear and understand instructions shouted by flight attendants, without assistance beyond a hearing aid;
.. The person lacks the ability adequately to impart information orally to other passengers; or,
.. The person has:
... A condition or responsibilities, such as caring for small children, that might prevent the person from performing one or more of the applicable functions listed in paragraph (d) of this section; or
... A condition that might cause the person harm if he or she performs one or more of the applicable functions listed in paragraph (d) of this section.
. Each passenger shall comply with instructions given by a crewmember or other authorized employee of the certificate holder implementing exit seating restrictions established in accordance with this section.
. Each certificate holder shall include on passenger information cards, presented in the language in which briefings and oral commands are given by the crew, at each exit seat affected by this section, information that, in the event of an emergency in which a crewmember is not available to assist, a passenger occupying an exit seat may use if called upon to perform the following functions:
.. Locate the emergency exit;
.. Recognize the emergency exit opening mechanism;
.. Comprehend the instructions for operating the emergency exit;
.. Operate the emergency exit;
.. Assess whether opening the emergency exit will increase the hazards to which passengers may be exposed;
.. Follow oral directions and hand signals given by a crewmember;
.. Stow or secure the emergency exit door so that it will not impede use of the exit;
.. Assess the condition of an escape slide, activate the slide, and stabilize the slide after deployment to assist others in getting off the slide;
.. Pass expeditiously through the emergency exit; and
.. Assess, select, and follow a safe path away from the emergency exit.
. Each certificate holder shall include on passenger information cards, at each exit seat—
.. In the primary language in which emergency commands are given by the crew, the selection criteria set forth in paragraph (b) of this section, and a request that a passenger identify himself or herself to allow reseating if he or she:
... Cannot meet the selection criteria set forth in paragraph (b) of this section;
... Has a nondiscernible condition that will prevent him or her from performing the applicable functions listed in paragraph (d) of this section;
... May suffer bodily harm as the result of performing one or more of those functions; or
... Does not wish to perform those functions; and
.. In each language used by the certificate holder for passenger information cards, a request that a passenger identify himself or herself to allow reseating if he or she lacks the ability to read, speak, or understand the language or the graphic form in which instructions required by this section and related to emergency evacuation are provided by the certificate holder, or the ability to understand the specified language in which crew commands will be given in an emergency.
.. May suffer bodily harm as the result of performing one or more of those functions; or,
.. Does not wish to perform those functions.
              
. Each certificate holder shall make available for inspection by the public at all passenger loading gates and ticket counters at each airport where it conducts passenger operations, written procedures established for making determinations in regard to exit row seating.
. No certificate holder may allow taxi or pushback unless at least one required crewmember has verified that no exit seat is occupied by a person the crewmember determines is likely to be unable to perform the applicable functions listed in paragraph (d) of this section.
. Each certificate holder shall include in its passenger briefings a reference to the passenger information cards, required by paragraphs (d) and (e), the selection criteria set forth in paragraph (b), and the functions to be performed, set forth in paragraph (d) of this section.
. Each certificate holder shall include in its passenger briefings a request that a passenger identify himself or herself to allow reseating if he or she—
.. Cannot meet the selection criteria set forth in paragraph (b) of this section;
.. Has a nondiscernible condition that will prevent him or her from performing the applicable functions listed in paragraph (d) of this section;
.. May suffer bodily harm as the result of performing one or more of those functions listed in paragraph (d) of this section; or,
.. Does not wish to perform those functions listed in paragraph (d) of this section.
              
. [Reserved]
              
. In the event a certificate holder determines in accordance with this section that it is likely that a passenger assigned to an exit seat would be unable to perform the functions listed in paragraph (d) of this section or a passenger requests a non-exit seat, the certificate holder shall expeditiously relocate the passenger to a non-exit seat.
. In the event of full booking in the non-exit seats and if necessary to accommodate a passenger being relocated from an exit seat, the certificate holder shall move a passenger who is willing and able to assume the evacuation functions that may be required, to an exit seat.
. A certificate holder may deny transportation to any passenger under this section only because—
.. The passenger refuses to comply with instructions given by a crewmember or other authorized employee of the certificate holder implementing exit seating restrictions established in accordance with this section, or
.. The only seat that will physically accommodate the person's handicap is an exit seat.
. In order to comply with this section certificate holders shall—
.. Establish procedures that address:
... The criteria listed in paragraph (b) of this section;
... The functions listed in paragraph (d) of this section;
... The requirements for airport information, passenger information cards, crewmember verification of appropriate seating in exit seats, passenger briefings, seat assignments, and denial of transportation as set forth in this section;
... How to resolve disputes arising from implementation of this section, including identification of the certificate holder employee on the airport to whom complaints should be addressed for resolution; and,
.. Submit their procedures for preliminary review and approval to the principal operations inspectors assigned to them at the certificate-holding district office.
. Certificate holders shall assign seats prior to boarding consistent with the criteria listed in paragraph (b) and the functions listed in paragraph (d) of this section, to the maximum extent feasible.
. The procedures required by paragraph (n) of this section will not become effective until final approval is granted by the Director, Flight Standards Service, Washington, DC. Approval will be based solely upon the safety aspects of the certificate holder's procedures.

(i) *Exit seat* means—

(A) Each seat having direct access to an exit; and,

(B) Each seat in a row of seats through which passengers would have to pass to gain access to an exit, from the first seat inboard of the exit to the first aisle inboard of the exit.

(ii) A passenger seat having “direct access” means a seat from which a passenger can proceed directly to the exit without entering an aisle or passing around an obstruction.

(2) Each certificate holder shall make the passenger exit seating determinations required by this paragraph in a non-discriminatory manner consistent with the requirements of this section, by persons designated in the certificate holder's required operations manual.

(3) Each certificate holder shall designate the exit seats for each passenger seating configuration in its fleet in accordance with the definitions in this paragraph and submit those designations for approval as part of the procedures required to be submitted for approval under paragraphs (n) and (p) of this section.

## § 121.586

### Authority to refuse transportation.

. No certificate holder may refuse transportation to a passenger on the basis that, because the passenger may need the assistance of another person to move expeditiously to an exit in the event of an emergency, his transportation would or might be inimical to safety of flight unless—
.. The certificate holder has established procedures (including reasonable notice requirements) for the carriage of passengers who may need the assistance of another person to move expeditiously to an exit in the event of an emergency; and
.. At least one of the following conditions exist:
... The passenger fails to comply with the notice requirements in the certificate holder's procedures.
... The passenger cannot be carried in accordance with the certificate holder's procedures.
. Each certificate holder shall provide the certificate-holding district office with a copy of each procedure it establishes in accordance with paragraph (a)(2) of this section.
. Whenever the Administrator finds that revisions in the procedures described in paragraph (a)(2) of this section are necessary in the interest of safety or in the public interest, the certificate holder, after notification by the Administrator, shall make those revisions in its procedures. Within 30 days after the certificate holder receives such notice, it may file a petition to reconsider the notice with the certificate-holding district office. The filing of a petition to reconsider stays the notice pending a decision by the Administrator. However, if the Administrator finds that there is an emergency that requires immediate action in the interest of safety in air commerce, he may, upon a statement of the reasons, require a change effective without stay.
. Each certificate holder shall make available to the public at each airport it serves a copy of each procedure it establishes in accordance with paragraph (a)(1) of this section.

## § 121.587

### Closing and locking of flightcrew compartment door.

. Except as provided in paragraph (b) of this section, a pilot in command of an airplane that has a lockable flightcrew compartment door in accordance with § 121.313 and that is carrying passengers shall ensure that the door separating the flightcrew compartment from the passenger compartment is closed and locked at all times when the aircraft is being operated.
. The provisions of paragraph (a) of this section do not apply at any time when it is necessary to permit access and egress by persons authorized in accordance with § 121.547 and provided the part 119 operator complies with FAA approved procedures regarding the opening, closing and locking of the flightdeck doors.

## § 121.589

### Carry-on baggage.

. No certificate holder may allow the boarding of carry-on baggage on an airplane unless each passenger's baggage has been scanned to control the size and amount carried on board in accordance with an approved carry-on baggage program in its operations specifications. In addition, no passenger may board an airplane if his/her carry-on baggage exceeds the baggage allowance prescribed in the carry-on baggage program in the certificate holder's operations specifications.
. No certificate holder may allow all passenger entry doors of an airplane to be closed in preparation for taxi or pushback unless at least one required crewmember has verified that each article of baggage is stowed in accordance with this section and § 121.285 (c) and (d).
. No certificate holder may allow an airplane to take off or land unless each article of baggage is stowed:
.. In a suitable closet or baggage or cargo stowage compartment placarded for its maximum weight and providing proper restraint for all baggage or cargo stowed within, and in a manner that does not hinder the possible use of any emergency equipment; or
.. As provided in § 121.285 (c) and (d); or
.. Under a passenger seat.
. Baggage, other than articles of loose clothing, may not be placed in an overhead rack unless that rack is equipped with approved restraining devices or doors.
. Each passenger must comply with instructions given by crewmembers regarding compliance with paragraphs (a), (b), (c), (d), and (g) of this section.
. Each passenger seat under which baggage is allowed to be stowed shall be fitted with a means to prevent articles of baggage stowed under it from sliding forward. In addition, each aisle seat shall be fitted with a means to prevent articles of baggage stowed under it from sliding sideward into the aisle under crash impacts severe enough to induce the ultimate inertia forces specified in the emergency landing condition regulations under which the airplane was type certificated.
. In addition to the methods of stowage in paragraph (c) of this section, flexible travel canes carried by blind individuals may be stowed—
.. Under any series of connected passenger seats in the same row, if the cane does not protrude into an aisle and if the cane is flat on the floor; or
.. Between a nonemergency exit window seat and the fuselage, if the cane is flat on the floor; or
.. Beneath any two nonemergency exit window seats, if the cane is flat on the floor; or
.. In accordance with any other method approved by the Administrator.

## § 121.590

### Use of certificated land airports in the United States.

. Except as provided in paragraphs (b) or (c) of this section, or unless authorized by the Administrator under 49 U.S.C. 44706(c), no air carrier and no pilot being used by an air carrier may operate, in the conduct of a domestic type operation, flag type operation, or supplemental type operation, an airplane at a land airport in any State of the United States, the District of Columbia, or any territory or possession of the United States unless that airport is certificated under part 139 of this chapter. Further, after June 9, 2005 for Class I airports and after December 9, 2005 for Class II, III, and IV airports, when an air carrier and a pilot being used by the air carrier are required to operate at an airport certificated under part 139 of this chapter, the air carrier and the pilot may only operate at that airport if the airport is classified under part 139 to serve the type airplane to be operated and the type of operation to be conducted.
. An air carrier and a pilot being used by the air carrier in the conduct of a domestic type operation, flag type operation, or supplemental type operation may designate and use as a required alternate airport for departure or destination an airport that is not certificated under part 139 of this chapter.
. An air carrier and a pilot used by the air carrier in conducting a domestic type operation, flag type operation, or supplemental type operation may operate an airplane at an airport operated by the U.S. Government that is not certificated under part 139 of this chapter, only if that airport meets the equivalent—
.. Safety standards for airports certificated under part 139 of this chapter; and
.. Airport classification requirements under part 139 to serve the type airplane to be operated and the type of operation to be conducted.
. An air carrier, a commercial operator, and a pilot being used by the air carrier or the commercial operator—when conducting a passenger-carrying airplane operation under this part that is not a domestic type operation, a flag type operation, or a supplemental type operation—may operate at a land airport not certificated under part 139 of this chapter only when the following conditions are met:
.. The airport is adequate for the proposed operation, considering such items as size, surface, obstructions, and lighting.
.. For an airplane carrying passengers at night, the pilot may not take off from, or land at, an airport unless—
... The pilot has determined the wind direction from an illuminated wind direction indicator or local ground communications or, in the case of takeoff, that pilot's personal observations; and
... The limits of the area to be used for landing or takeoff are clearly shown by boundary or runway marker lights. If the area to be used for takeoff or landing is marked by flare pots or lanterns, their use must be authorized by the Administrator.
. A commercial operator and a pilot used by the commercial operator in conducting a domestic type operation, flag type operation, or supplemental type operation may operate an airplane at an airport operated by the U.S. Government that is not certificated under part 139 of this chapter only if that airport meets the equivalent—
.. Safety standards for airports certificated under part 139 of this chapter; and
.. Airport classification requirements under part 139 of this chapter to serve the type airplane to be operated and the type of operation to be conducted.
. For the purpose of this section, the terms—
              
.. An airplane designed for at least 31 passenger seats (as determined by the aircraft type certificate issued by a competent civil aviation authority) at any land airport in any State of the United States, the District of Columbia, or any territory or possession of the United States; or
.. An airplane designed for more than 9 passenger seats but less than 31 passenger seats (as determined by the aircraft type certificate issued by a competent civil aviation authority) at any land airport in any State of the United States (except Alaska), the District of Columbia, or any territory or possession of the United States.

(2) Until December 9, 2005, an air carrier and a pilot being used by the air carrier in the conduct of domestic type operations and flag type operations, may operate an airplane designed for more than 9 but less than 31 passenger seats, at a land airport, in any State of the United States, the District of Columbia, or any territory or possession of the United States, that does not hold an airport operating certificate issued under part 139 of this chapter, and that serves small air carrier aircraft (as defined under “Air carrier aircraft” and “Class III airport” in § 139.5 of this Chapter).

*Domestic type operation* means any domestic operation conducted with—

*Flag type operation* means any flag operation conducted with—

*Supplemental type operation* means any supplemental operation (except an all-cargo operation) conducted with an airplane designed for at least 31 passenger seats (as determined by the aircraft type certificate issued by a competent civil aviation authority) at any land airport in any State of the United States, the District of Columbia, or any territory or possession of the United States.

*United States* means the States of the United States, the District of Columbia, and the territories and possessions of the United States.
              

