# Class E Airspace
:toc:

## § 71.71 - Class E airspace.

Class E Airspace consists of:

[loweralpha]
. The airspace of the United States, including that airspace overlying the waters within 12 nautical miles of the coast of the 48 contiguous states and Alaska, extending upward from 14,500 feet MSL up to, but not including 18,000 feet MSL, and the airspace above FL600, excluding—
[arabic]
.. The Alaska peninsula west of longitude 160°00′00″ W.; and
.. The airspace below 1,500 feet above the surface of the earth.
. The airspace areas designated for an airport in subpart E of FAA Order 7400.11A (incorporated by reference, see § 71.1) within which all aircraft operators are subject to the operating rules specified in part 91 of this chapter.
. The airspace areas listed as domestic airspace areas in subpart E of FAA Order 7400.11A (incorporated by reference, see § 71.1) which extend upward from 700 feet or more above the surface of the earth when designated in conjunction with an airport for which an approved instrument approach procedure has been prescribed, or from 1,200 feet or more above the surface of the earth for the purpose of transitioning to or from the terminal or en route environment. When such areas are designated in conjunction with airways or routes, the extent of such designation has the lateral extent identical to that of a Federal airway and extends upward from 1,200 feet or higher. Unless otherwise specified, the airspace areas in the paragraph extend upward from 1,200 feet or higher above the surface to, but not including, 14,500 feet MSL.
. The Federal airways described in subpart E of FAA Order 7400.11A (incorporated by reference, see § 71.1).
. The airspace areas listed as en route domestic airspace areas in subpart E of FAA Order 7400.11A (incorporated by reference, see § 71.1). Unless otherwise specified, each airspace area has a lateral extent identical to that of a Federal airway and extends upward from 1,200 feet above the surface of the earth to the overlying or adjacent controlled airspace.
. The airspace areas listed as offshore airspace areas in subpart E of FAA Order 7400.11A (incorporated by reference, see § 71.1) that are designated in international airspace within areas of domestic radio navigational signal or ATC radar coverage, and within which domestic ATC procedures are applied. Unless otherwise specified, each airspace area extends upward from a specified altitude up to, but not including, 18,000 feet MSL.

