# Instrument and Equipment Requirements
:toc:

## § 125.201 - Inoperable instruments and equipment.

[loweralpha]
. No person may take off an airplane with inoperable instruments or equipment installed unless the following conditions are met:
[arabic]
.. An approved Minimum Equipment List exists for that airplane.
.. The Flight Standards District Office having certification responsibility has issued the certificate holder operations specifications authorizing operations in accordance with an approved Minimum Equipment List. The flight crew shall have direct access at all times prior to flight to all of the information contained in the approved Minimum Equipment List through printed or other means approved by the Administrator in the certificate holders operations specifications. An approved Minimum Equipment List, as authorized by the operations specifications, constitutes an approved change to the type design without requiring recertification.
.. The approved Minimum Equipment List must:
[lowerroman]
... Be prepared in accordance with the limitations specified in paragraph (b) of this section.
... Provide for the operation of the airplane with certain instruments and equipment in an inoperable condition.
.. Records identifying the inoperable instruments and equipment and the information required by paragraph (a)(3)(ii) of this section must be available to the pilot.
.. The airplane is operated under all applicable conditions and limitations contained in the Minimum Equipment List and the operations specifications authorizing use of the Minimum Equipment List.
. The following instruments and equipment may not be included in the Minimum Equipment List:
[arabic]
.. Instruments and equipment that are either specifically or otherwise required by the airworthiness requirements under which the airplane is type certificated and which are essential for safe operations under all operating conditions.
.. Instruments and equipment required by an airworthiness directive to be in operable condition unless the airworthiness directive provides otherwise.
.. Instruments and equipment required for specific operations by this part.
. Notwithstanding paragraphs (b)(1) and (b)(3) of this section, an airplane with inoperable instruments or equipment may be operated under a special flight permit under §§ 21.197 and 21.199 of this chapter.

## § 125.203 - Communication and navigation equipment.

[loweralpha]
. *Communication equipment—general.* No person may operate an airplane unless it has two-way radio communication equipment able, at least in flight, to transmit to, and receive from, appropriate facilities 22 nautical miles away.
. *Navigation equipment for operations over the top.* No person may operate an airplane over the top unless it has navigation equipment suitable for the route to be flown.
. *Communication and navigation equipment for IFR or extended over-water operations—General.* Except as provided in paragraph (f) of this section, no person may operate an airplane carrying passengers under IFR or in extended over-water operations unless—
[arabic]
.. The en route navigation aids necessary for navigating the airplane along the route (e.g., ATS routes, arrival and departure routes, and instrument approach procedures, including missed approach procedures if a missed approach routing is specified in the procedure) are available and suitable for use by the aircraft navigation systems required by this section;
.. The airplane used in those operations is equipped with at least the following equipment—
[lowerroman]
... Except as provided in paragraph (d) of this section, two approved independent navigation systems suitable for navigating the airplane along the route within the degree of accuracy required for ATC;
... One marker beacon receiver providing visual and aural signals;
... One ILS receiver;
... Two transmitters;
... Two microphones;
... Two headsets or one headset and one speaker; and
... Two independent communication systems, one of which must have two-way voice communication capability, capable of transmitting to, and receiving from, at least one appropriate facility from any place on the route to be flown; and
.. Any RNAV system used to meet the navigation equipment requirements of this section is authorized in the certificate holder's operations specifications.
. *Use of a single independent navigation system for operations under IFR—not for extended overwater operations.* Notwithstanding the requirements of paragraph (c)(2)(i) of this section, the airplane may be equipped with a single independent navigation system suitable for navigating the airplane along the route to be flown within the degree of accuracy required for ATC if—
[arabic]
.. It can be shown that the airplane is equipped with at least one other independent navigation system suitable, in the event of loss of the navigation capability of the single independent navigation system permitted by this paragraph at any point along the route, for proceeding safely to a suitable airport and completing an instrument approach; and
.. The airplane has sufficient fuel so that the flight may proceed safely to a suitable airport by use of the remaining navigation system, and complete an instrument approach and land.
. *Use of VOR navigation equipment.* If VOR navigation equipment is required by paragraph (c) or (d) of this section, no person may operate an airplane unless it is equipped with at least one approved DME or a suitable RNAV system.
. *Extended over-water operations.* Notwithstanding the requirements of paragraph (c) of this section, installation and use of a single long-range navigation system and a single long-range communication system for extended over-water operations in certain geographic areas may be authorized by the Administrator and approved in the certificate holder's operations specifications. The following are among the operational factors the Administrator may consider in granting an authorization:
[arabic]
.. The ability of the flight crew to navigate the airplane along the route to be flown within the degree of accuracy required for ATC;
.. The length of the route being flown; and
.. The duration of the very high frequency communications gap.

## § 125.204 - Portable electronic devices.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person may operate, nor may any operator or pilot in command of an aircraft allow the operation of, any portable electronic device on any U.S.-registered civil aircraft operating under this part.
. Paragraph (a) of this section does not apply to—
[arabic]
.. Portable voice recorders;
.. Hearing aids;
.. Heart pacemakers;
.. Electric shavers;
.. Portable oxygen concentrators that comply with the requirements in § 125.219; or
.. Any other portable electronic device that the Part 125 certificate holder has determined will not cause interference with the navigation or communication system of the aircraft on which it is to be used.
. The determination required by paragraph (b)(6) of this section shall be made by that Part 125 certificate holder operating the particular device to be used.

## § 125.205 - Equipment requirements: Airplanes under IFR.

No person may operate an airplane under IFR unless it has—

[loweralpha]
. A vertical speed indicator;
. A free-air temperature indicator;
. A heated pitot tube for each airspeed indicator;
. A power failure warning device or vacuum indicator to show the power available for gyroscopic instruments from each power source;
. An alternate source of static pressure for the altimeter and the airspeed and vertical speed indicators;
. At least two generators each of which is on a separate engine, or which any combination of one-half of the total number are rated sufficiently to supply the electrical loads of all required instruments and equipment necessary for safe emergency operation of the airplane; and
. Two independent sources of energy (with means of selecting either), of which at least one is an engine-driven pump or generator, each of which is able to drive all gyroscopic instruments and installed so that failure of one instrument or source does not interfere with the energy supply to the remaining instruments or the other energy source. For the purposes of this paragraph, each engine-driven source of energy must be on a different engine.
. For the purposes of paragraph (f) of this section, a continuous inflight electrical load includes one that draws current continuously during flight, such as radio equipment, electrically driven instruments, and lights, but does not include occasional intermittent loads.
[lowerroman]
.. An airspeed indicating system with heated pitot tube or equivalent means for preventing malfunctioning due to icing.

(j) A sensitive altimeter.

(k) Instrument lights providing enough light to make each required instrument, switch, or similar instrument easily readable and installed so that the direct rays are shielded from the flight crewmembers' eyes and that no objectionable reflections are visible to them. There must be a means of controlling the intensity of illumination unless it is shown that nondimming instrument lights are satisfactory.

## § 125.206 - Pitot heat indication systems.

[loweralpha]
. Except as provided in paragraph (b) of this section, after April 12, 1981, no person may operate a transport category airplane equipped with a flight instrument pitot heating system unless the airplane is equipped with an operable pitot heat indication system that complies with § 25.1326 of this chapter in effect on April 12, 1978.
. A certificate holder may obtain an extension of the April 12, 1981, compliance date specified in paragraph (a) of this section, but not beyond April 12, 1983, from the Director, Flight Standards Service if the certificate holder—
[arabic]
.. Shows that due to circumstances beyond its control it cannot comply by the specified compliance date; and
.. Submits by the specified compliance date a schedule for compliance acceptable to the Director, indicating that compliance will be achieved at the earliest practicable date.

## § 125.207 - Emergency equipment requirements.

[loweralpha]
. No person may operate an airplane having a seating capacity of 20 or more passengers unless it is equipped with the following emergency equipment:
[arabic]
.. One approved first aid kit for treatment of injuries likely to occur in flight or in a minor accident, which meets the following specifications and requirements:
[lowerroman]
... Each first aid kit must be dust and moisture proof and contain only materials that either meet Federal Specifications GGK-391a, as revised, or as approved by the Administrator.
... Required first aid kits must be readily accessible to the cabin flight attendants.
... Except as provided in paragraph (a)(1)(iv) of this section, at time of takeoff, each first aid kit must contain at least the following or other contents approved by the Administrator:
... Protective latex gloves or equivalent nonpermeable gloves may be placed in the first aid kit or in a location that is readily accessible to crewmembers.
.. A crash axe carried so as to be accessible to the crew but inaccessible to passengers during normal operations.
.. Signs that are visible to all occupants to notify them when smoking is prohibited and when safety belts should be fastened. The signs must be so constructed that they can be turned on and off by a crewmember. They must be turned on for each takeoff and each landing and when otherwise considered to be necessary by the pilot in command.
.. The additional emergency equipment specified in appendix A of this part.
. *Megaphones.* Each passenger-carrying airplane must have a portable battery-powered megaphone or megaphones readily accessible to the crewmembers assigned to direct emergency evacuation, installed as follows:
[arabic]
.. One megaphone on each airplane with a seating capacity of more than 60 and less than 100 passengers, at the most rearward location in the passenger cabin where it would be readily accessible to a normal flight attendant seat. However, the Administrator may grant a deviation from the requirements of this paragraph if the Administrator finds that a different location would be more useful for evacuation of persons during an emergency.
.. Two megaphones in the passenger cabin on each airplane with a seating capacity of more than 99 and less than 200 passengers, one installed at the forward end and the other at the most rearward location where it would be readily accessible to a normal flight attendant seat.
              
.. Three megaphones in the passenger cabin on each airplane with a seating capacity of more than 199 passengers, one installed at the forward end, one installed at the most rearward location where it would be readily accessible to a normal flight attendant seat, and one installed in a readily accessible location in the mid-section of the airplane.

## § 125.209 - Emergency equipment: Extended overwater operations.

[loweralpha]
. No person may operate an airplane in extended overwater operations unless it carries, installed in conspicuously marked locations easily accessible to the occupants if a ditching occurs, the following equipment:
[arabic]
.. An approved life preserver equipped with an approved survivor locator light, or an approved flotation means, for each occupant of the aircraft. The life preserver or other flotation means must be easily accessible to each seated occupant. If a flotation means other than a life preserver is used, it must be readily removable from the airplane.
.. Enough approved life rafts (with proper buoyancy) to carry all occupants of the airplane, and at least the following equipment for each raft clearly marked for easy identification—
[lowerroman]
... One canopy (for sail, sunshade, or rain catcher);
... One radar reflector (or similar device);
... One life raft repair kit;
... One bailing bucket;
... One signaling mirror;
... One police whistle;
... One raft knife;
... One CO*2* bottle for emergency inflation;
... One inflation pump;
... Two oars;
... One 75-foot retaining line;
... One magnetic compass;
... One dye marker;
... One flashlight having at least two size “D” cells or equivalent;
... At least one approved pyrotechnic signaling device;
... A 2-day supply of emergency food rations supplying at least 1,000 calories a day for each person;
... One sea water desalting kit for each two persons that raft is rated to carry, or two pints of water for each person the raft is rated to carry;
... One fishing kit; and
... One book on survival appropriate for the area in which the airplane is operated.
. No person may operate an airplane in extended overwater operations unless there is attached to one of the life rafts required by paragraph (a) of this section, an approved survival type emergency locator transmitter. Batteries used in this transmitter must be replaced (or recharged, if the batteries are rechargeable) when the transmitter has been in use for more than one cumulative hour, or, when 50 percent of their useful life (or for rechargeable batteries, 50 percent of their useful life of charge) has expired, as established by the transmitter manufacturer under its approval. The new expiration date for replacing (or recharging) the battery must be legibly marked on the outside of the transmitter. The battery useful life (or useful life of charge) requirements of this paragraph do not apply to batteries (such as water-activated batteries) that are essentially unaffected during probable storage intervals.

## § 125.211 - Seat and safety belts.

[loweralpha]
. No person may operate an airplane unless there are available during the takeoff, en route flight, and landing—
[arabic]
.. An approved seat or berth for each person on board the airplane who is at least 2 years old; and
.. An approved safety belt for separate use by each person on board the airplane who is at least 2 years old, except that two persons occupying a berth may share one approved safety belt and two persons occupying a multiple lounge or divan seat may share one approved safety belt during en route flight only.
. Except as provided in paragraphs (b)(1) and (b)(2) of this section, each person on board an airplane operated under this part shall occupy an approved seat or berth with a separate safety belt properly secured about him or her during movement on the surface, takeoff, and landing. A safety belt provided for the occupant of a seat may not be used for more than one person who has reached his or her second birthday. Notwithstanding the preceding requirements, a child may:
[arabic]
.. Be held by an adult who is occupying an approved seat or berth, provided the child has not reached his or her second birthday and the child does not occupy or use any restraining device; or
.. Notwithstanding any other requirement of this chapter, occupy an approved child restraint system furnished by the certificate holder or one of the persons described in paragraph (b)(2)(i) of this section, provided:
[lowerroman]
... The child is accompanied by a parent, guardian, or attendant designated by the child's parent or guardian to attend to the safety of the child during the flight;
... Except as provided in paragraph (b)(2)(ii)(D) of this section, the approved child restraint system bears one or more labels as follows:
[upperalpha]
.... Seats manufactured to U.S. standards between January 1, 1981, and February 25, 1985, must bear the label: “This child restraint system conforms to all applicable Federal motor vehicle safety standards”;
.... Seats manufactured to U.S. standards on or after February 26, 1985, must bear two labels:
[arabic]
..... (*1*) “This child restraint system conforms to all applicable Federal motor vehicle safety standards”; and
..... (*2*) “THIS RESTRAINT IS CERTIFIED FOR USE IN MOTOR VEHICLES AND AIRCRAFT” in red lettering;
.... Seats that do not qualify under paragraphs (b)(2)(ii)(A) and (b)(2)(ii)(B) of this section must bear a label or markings showing:
[arabic]
..... (*1*) That the seat was approved by a foreign government;
..... (*2*) That the seat was manufactured under the standards of the United Nations;
..... (*3*) That the seat or child restraint device furnished by the certificate holder was approved by the FAA through Type Certificate or Supplemental Type Certificate; or
..... (*4*) That the seat or child restraint device furnished by the certificate holder, or one of the persons described in paragraph (b)(2)(i) of this section, was approved by the FAA in accordance with § 21.8(d) of this chapter or Technical Standard Order C-100b, or a later version. The child restraint device manufactured by AmSafe, Inc. (CARES, Part No. 4082) and approved by the FAA in accordance with § 21.305(d) (2010 ed.) of this chapter may continue to bear a label or markings showing FAA approval in accordance with § 21.305(d) (2010 ed.) of this chapter.
.... Except as provided in § 125.211(b)(2)(ii)(C)(*3*) and § 125.211(b)(2)(ii)(C)(*4*), booster-type child restraint systems (as defined in Federal Motor Vehicle Safety Standard No. 213 (49 CFR 571.213)), vest- and harness-type child restraint systems, and lap held child restraints are not approved for use in aircraft; and
... The certificate holder complies with the following requirements:
[upperalpha]
.... The restraint system must be properly secured to an approved forward-facing seat or berth;
.... The child must be properly secured in the restraint system and must not exceed the specified weight limit for the restraint system; and
.... The restraint system must bear the appropriate label(s).
. Except as provided in paragraph (c)(3) of this section, the following prohibitions apply to certificate holders:
[arabic]
.. Except as provided in § 125.211(b)(2)(ii)(C)(*3*) and § 125.211(b)(2)(ii)(C)(*4*), no certificate holder may permit a child, in an aircraft, to occupy a booster-type child restraint system, a vest-type child restraint system, a harness-type child restraint system, or a lap held child restraint system during take off, landing, and movement on the surface.
.. Except as required in paragraph (c)(1) of this section, no certificate holder may prohibit a child, if requested by the child's parent, guardian, or designated attendant, from occupying a child restraint system furnished by the child's parent, guardian, or designated attendant provided:
              
[lowerroman]
... The child holds a ticket for an approved seat or berth or such seat or berth is otherwise made available by the certificate holder for the child's use;
... The requirements of paragraph (b)(2)(i) of this section are met;
... The requirements of paragraph (b)(2)(iii) of this section are met; and
... The child restraint system has one or more of the labels described in paragraphs (b)(2)(ii)(A) through (b)(2)(ii)(C) of this section.
.. This section does not prohibit the certificate holder from providing child restraint systems authorized by this section or, consistent with safe operating practices, determining the most appropriate passenger seat location for the child restraint system.
. Each sideward facing seat must comply with the applicable requirements of § 25.785(c) of this chapter.
. No certificate holder may take off or land an airplane unless each passenger seat back is in the upright position. Each passenger shall comply with instructions given by a crewmember in compliance with this paragraph. This paragraph does not apply to seats on which cargo or persons who are unable to sit erect for a medical reason are carried in accordance with procedures in the certificate holder's manual if the seat back does not obstruct any passenger's access to the aisle or to any emergency exit.
. Each occupant of a seat equipped with a shoulder harness must fasten the shoulder harness during takeoff and landing, except that, in the case of crewmembers, the shoulder harness need not be fastened if the crewmember cannot perform his required duties with the shoulder harness fastened.

## § 125.213 - Miscellaneous equipment.

No person may conduct any operation unless the following equipment is installed in the airplane:

[loweralpha]
. If protective fuses are installed on an airplane, the number of spare fuses approved for the airplane and appropriately described in the certificate holder's manual.
. A windshield wiper or equivalent for each pilot station.
. A power supply and distribution system that meets the requirements of §§ 25.1309, 25.1331, 25.1351 (a) and (b) (1) through (4), 25.1353, 25.1355, and 25.1431(b) or that is able to produce and distribute the load for the required instruments and equipment, with use of an external power supply if any one power source or component of the power distribution system fails. The use of common elements in the system may be approved if the Administrator finds that they are designed to be reasonably protected against malfunctioning. Engine-driven sources of energy, when used, must be on separate engines.
. A means for indicating the adequacy of the power being supplied to required flight instruments.
. Two independent static pressure systems, vented to the outside atmospheric pressure so that they will be least affected by air flow variation or moisture or other foreign matter, and installed so as to be airtight except for the vent. When a means is provided for transferring an instrument from its primary operating system to an alternative system, the means must include a positive positioning control and must be marked to indicate clearly which system is being used.
. A placard on each door that is the means of access to a required passenger emergency exit to indicate that it must be open during takeoff and landing.
. A means for the crew, in an emergency, to unlock each door that leads to a compartment that is normally accessible to passengers and that can be locked by passengers.

## § 125.215 - Operating information required.

[loweralpha]
. The operator of an airplane must provide the following materials, in current and appropriate form, accessible to the pilot at the pilot station, and the pilot shall use them:
[arabic]
.. A cockpit checklist.
              
.. An emergency cockpit checklist containing the procedures required by paragraph (c) of this section, as appropriate.
.. Pertinent aeronautical charts.
.. For IFR operations, each pertinent navigational en route, terminal area, and approach and letdown chart;
.. One-engine-inoperative climb performance data and, if the airplane is approved for use in IFR or over-the-top operations, that data must be sufficient to enable the pilot to determine that the airplane is capable of carrying passengers over-the-top or in IFR conditions at a weight that will allow it to climb, with the critical engine inoperative, at least 50 feet a minute when operating at the MEA's of the route to be flown or 5,000 feet MSL, whichever is higher.
. Each cockpit checklist required by paragraph (a)(1) of this section must contain the following procedures:
[arabic]
.. Before starting engines;
.. Before take-off;
.. Cruise;
.. Before landing;
.. After landing;
.. Stopping engines.
. Each emergency cockpit checklist required by paragraph (a)(2) of this section must contain the following procedures, as appropriate:
[arabic]
.. Emergency operation of fuel, hydraulic, electrical, and mechanical systems.
.. Emergency operation of instruments and controls.
.. Engine inoperative procedures.
.. Any other emergency procedures necessary for safety.

## § 125.217 - Passenger information.

[loweralpha]
. Except as provided in paragraph (b) of this section, no person may operate an airplane carrying passengers unless it is equipped with signs that meet the requirements of § 25.791 of this chapter and that are visible to passengers and flight attendants to notify them when smoking is prohibited and when safety belts must be fastened. The signs must be so constructed that the crew can turn them on and off. They must be turned on during airplane movement on the surface, for each takeoff, for each landing, and when otherwise considered to be necessary by the pilot in command.
. No passenger or crewmember may smoke while any “No Smoking” sign is lighted nor may any passenger or crewmember smoke in any lavatory.
. Each passenger required by § 125.211(b) to occupy a seat or berth shall fasten his or her safety belt about him or her and keep it fastened while any “Fasten Seat Belt” sign is lighted.
. Each passenger shall comply with instructions given him or her by crewmembers regarding compliance with paragraphs (b) and (c) of this section.

## § 125.219 - Oxygen and portable oxygen concentrators for medical use by passengers.

[loweralpha]
. Except as provided in paragraphs (d) and (f) of this section, no certificate holder may allow the carriage or operation of equipment for the storage, generation or dispensing of medical oxygen unless the conditions in paragraphs (a) through (c) of this section are satisfied. Beginning August 22, 2016, a certificate holder may allow a passenger to carry and operate a portable oxygen concentrator when the conditions in paragraphs (b) and (f) of this section are satisfied.
[arabic]
.. The equipment must be—
[lowerroman]
... Of an approved type or in conformity with the manufacturing, packaging, marking, labeling, and maintenance requirements of title 49 CFR parts 171, 172, and 173, except § 173.24(a)(1);
... When owned by the certificate holder, maintained under the certificate holder's approved maintenance program;
... Free of flammable contaminants on all exterior surfaces;
... Constructed so that all valves, fittings, and gauges are protected from damage during that carriage or operation; and
... Appropriately secured.
.. When the oxygen is stored in the form of a liquid, the equipment must have been under the certificate holder's approved maintenance program since its purchase new or since the storage container was last purged.
              
.. When the oxygen is stored in the form of a compressed gas as defined in title 49 CFR 173.115(b)—
[lowerroman]
... When owned by the certificate holder, it must be maintained under its approved maintenance program; and
... The pressure in any oxygen cylinder must not exceed the rated cylinder pressure.
.. The pilot in command must be advised when the equipment is on board and when it is intended to be used.
.. The equipment must be stowed, and each person using the equipment must be seated so as not to restrict access to or use of any required emergency or regular exit or of the aisle in the passenger compartment.
. No person may smoke or create an open flame and no certificate holder may allow any person to smoke or create an open flame within 10 feet of oxygen storage and dispensing equipment carried under paragraph (a) of this section or a portable oxygen concentrator carried and operated under paragraph (f) of this section.
. No certificate holder may allow any person other than a person trained in the use of medical oxygen equipment to connect or disconnect oxygen bottles or any other ancillary component while any passenger is aboard the airplane.
. Paragraph (a)(1)(i) of this section does not apply when that equipment is furnished by a professional or medical emergency service for use on board an airplane in a medical emergency when no other practical means of transportation (including any other properly equipped certificate holder) is reasonably available and the person carried under the medical emergency is accompanied by a person trained in the use of medical oxygen.
. Each certificate holder who, under the authority of paragraph (d) of this section, deviates from paragraph (a)(1)(i) of this section under a medical emergency shall, within 10 days, excluding Saturdays, Sundays, and Federal holidays, after the deviation, send to the FAA Flight Standards district office charged with the overall inspection of the certificate holder a complete report of the operation involved, including a description of the deviation and the reasons for it.
. *Portable oxygen concentrators*—(1) *Acceptance criteria.* A passenger may carry or operate a portable oxygen concentrator for personal use on board an aircraft and a certificate holder may allow a passenger to carry or operate a portable oxygen concentrator on board an aircraft operated under this part during all phases of flight if the portable oxygen concentrator satisfies all of the requirements in this paragraph (f):
[lowerroman]
.. Is legally marketed in the United States in accordance with Food and Drug Administration requirements in title 21 of the CFR;
.. Does not radiate radio frequency emissions that interfere with aircraft systems;
.. Generates a maximum oxygen pressure of less than 200 kPa gauge (29.0 psig/43.8 psia) at 20 °C (68 °F);
.. Does not contain any hazardous materials subject to the Hazardous Materials Regulations (49 CFR parts 171 through 180) except as provided in 49 CFR 175.10 for batteries used to power portable electronic devices and that do not require aircraft operator approval; and
.. Bears a label on the exterior of the device applied in a manner that ensures the label will remain affixed for the life of the device and containing the following certification statement in red lettering: “The manufacturer of this POC has determined this device conforms to all applicable FAA acceptance criteria for POC carriage and use on board aircraft.” The label requirements in this paragraph (f)(1)(v) do not apply to the following portable oxygen concentrators approved by the FAA for use on board aircraft prior to May 24, 2016:
[upperalpha]
... AirSep Focus;
... AirSep FreeStyle;
... AirSep FreeStyle 5;
... AirSep LifeStyle;
... Delphi RS-00400;
... DeVilbiss Healthcare iGo;
... Inogen One;
... Inogen One G2;
... Inogen One G3;
... Inova Labs LifeChoice;
... Inova Labs LifeChoice Activox;
... International Biophysics LifeChoice;
... Invacare Solo2;
              
... Invacare XPO2;
... Oxlife Independence Oxygen Concentrator;
... Oxus RS-00400;
... Precision Medical EasyPulse;
... Respironics EverGo;
... Respironics SimplyGo;
... SeQual Eclipse;
... SeQual eQuinox Oxygen System (model 4000);
... SeQual Oxywell Oxygen System (model 4000);
... SeQual SAROS; and
... VBox Trooper Oxygen Concentrator.

(2) *Operating requirements.* Portable oxygen concentrators that satisfy the acceptance criteria identified in paragraph (f)(1) of this section may be carried or used by a passenger on an aircraft provided the aircraft operator ensures that all of the conditions in this paragraph (f)(2) are satisfied:

[lowerroman]
. *Exit seats.* No person operating a portable oxygen concentrator is permitted to occupy an exit seat.
. *Stowage of device.* During movement on the surface, takeoff and landing, the device must be stowed under the seat in front of the user, or in another approved stowage location so that it does not block the aisle way or the entryway to the row. If the device is to be operated by the user, it must be operated only at a seat location that does not restrict any passenger's access to, or use of, any required emergency or regular exit, or the aisle(s) in the passenger compartment.

## § 125.221 - Icing conditions: Operating limitations.

[loweralpha]
. No pilot may take off an airplane that has frost, ice, or snow adhering to any propeller, windshield, stabilizing or control surface; to a powerplant installation; or to an airspeed, altimeter, rate of climb, flight attitude instrument system, or wing, except that takeoffs may be made with frost under the wing in the area of the fuel tanks if authorized by the FAA.
. No certificate holder may authorize an airplane to take off and no pilot may take off an airplane any time conditions are such that frost, ice, or snow may reasonably be expected to adhere to the airplane unless the pilot has completed the testing required under § 125.287(a)(9) and unless one of the following requirements is met:
[arabic]
.. A pretakeoff contamination check, that has been established by the certificate holder and approved by the Administrator for the specific airplane type, has been completed within 5 minutes prior to beginning takeoff. A pretakeoff contamination check is a check to make sure the wings and control surfaces are free of frost, ice, or snow.
.. The certificate holder has an approved alternative procedure and under that procedure the airplane is determined to be free of frost, ice, or snow.
.. The certificate holder has an approved deicing/anti-icing program that complies with § 121.629(c) of this chapter and the takeoff complies with that program.
. No pilot may fly under IFR into known or forecast light or moderate icing conditions, or under VFR into known light or moderate icing conditions, unless—
[arabic]
.. The aircraft has functioning deicing or anti-icing equipment protecting each propeller, windshield, wing, stabilizing or control surface, and each airspeed, altimeter, rate of climb, or flight attitude instrument system;
.. The airplane has ice protection provisions that meet appendix C of this part; or
.. The airplane meets transport category airplane type certification provisions, including the requirements for certification for flight in icing conditions.
. Except for an airplane that has ice protection provisions that meet appendix C of this part or those for transport category airplane type certification, no pilot may fly an airplane into known or forecast severe icing conditions.
. If current weather reports and briefing information relied upon by the pilot in command indicate that the forecast icing condition that would otherwise prohibit the flight will not be encountered during the flight because of changed weather conditions since the forecast, the restrictions in paragraphs (b) and (c) of this section based on forecast conditions do not apply.

## § 125.223 - Airborne weather radar equipment requirements.

[loweralpha]
. No person may operate an airplane governed by this part in passenger-carrying operations unless approved airborne weather radar equipment is installed in the airplane.
. No person may begin a flight under IFR or night VFR conditions when current weather reports indicate that thunderstorms, or other potentially hazardous weather conditions that can be detected with airborne weather radar equipment, may reasonably be expected along the route to be flown, unless the airborne weather radar equipment required by paragraph (a) of this section is in satisfactory operating condition.
. If the airborne weather radar equipment becomes inoperative en route, the airplane must be operated under the instructions and procedures specified for that event in the manual required by § 125.71.
. This section does not apply to airplanes used solely within the State of Hawaii, within the State of Alaska, within that part of Canada west of longitude 130 degrees W, between latitude 70 degrees N, and latitude 53 degrees N, or during any training, test, or ferry flight.
. Without regard to any other provision of this part, an alternate electrical power supply is not required for airborne weather radar equipment.

## § 125.224 - Collision avoidance system.

Effective January 1, 2005, any airplane you operate under this part 125 must be equipped and operated according to the following table:

## § 125.225 - Flight data recorders.

[loweralpha]
. Except as provided in paragraph (d) of this section, after October 11, 1991, no person may operate a large airplane type certificated before October 1, 1969, for operations above 25,000 feet altitude, nor a multiengine, turbine powered airplane type certificated before October 1, 1969, unless it is equipped with one or more approved flight recorders that utilize a digital method of recording and storing data and a method of readily retrieving that data from the storage medium. The following information must be able to be determined within the ranges, accuracies, resolution, and recording intervals specified in appendix D of this part:
[arabic]
.. Time;
.. Altitude;
.. Airspeed;
.. Vertical acceleration;
.. Heading;
.. Time of each radio transmission to or from air traffic control;
.. Pitch attitude;
.. Roll attitude;
.. Longitudinal acceleration;
.. Control column or pitch control surface position; and
.. Thrust of each engine.
              
. Except as provided in paragraph (d) of this section, after October 11, 1991, no person may operate a large airplane type certificated after September 30, 1969, for operations above 25,000 feet altitude, nor a multiengine, turbine powered airplane type certificated after September 30, 1969, unless it is equipped with one or more approved flight recorders that utilize a digital method of recording and storing data and a method of readily retrieving that data from the storage medium. The following information must be able to be determined within the ranges, accuracies, resolutions, and recording intervals specified in appendix D of this part:
[arabic]
.. Time;
.. Altitude;
.. Airspeed;
.. Vertical acceleration;
.. Heading;
.. Time of each radio transmission either to or from air traffic control;
.. Pitch attitude;
.. Roll attitude;
.. Longitudinal acceleration;
.. Pitch trim position;
.. Control column or pitch control surface position;
.. Control wheel or lateral control surface position;
.. Rudder pedal or yaw control surface position;
.. Thrust of each engine;
.. Position of each trust reverser;
.. Trailing edge flap or cockpit flap control position; and
.. Leading edge flap or cockpit flap control position.
. After October 11, 1991, no person may operate a large airplane equipped with a digital data bus and ARINC 717 digital flight data acquisition unit (DFDAU) or equivalent unless it is equipped with one or more approved flight recorders that utilize a digital method of recording and storing data and a method of readily retrieving that data from the storage medium. Any parameters specified in appendix D of this part that are available on the digital data bus must be recorded within the ranges, accuracies, resolutions, and sampling intervals specified.
. No person may operate under this part an airplane that is manufactured after October 11, 1991, unless it is equipped with one or more approved flight recorders that utilize a digital method of recording and storing data and a method of readily retrieving that data from the storage medium. The parameters specified in appendix D of this part must be recorded within the ranges, accuracies, resolutions and sampling intervals specified. For the purpose of this section, “manufactured” means the point in time at which the airplane inspection acceptance records reflect that the airplane is complete and meets the FAA-approved type design data.
. Whenever a flight recorder required by this section is installed, it must be operated continuously from the instant the airplane begins the takeoff roll until it has completed the landing roll at an airport.
. Except as provided in paragraph (g) of this section, and except for recorded data erased as authorized in this paragraph, each certificate holder shall keep the recorded data prescribed in paragraph (a), (b), (c), or (d) of this section, as applicable, until the airplane has been operated for at least 25 hours of the operating time specified in § 125.227(a) of this chapter. A total of 1 hour of recorded data may be erased for the purpose of testing the flight recorder or the flight recorder system. Any erasure made in accordance with this paragraph must be of the oldest recorded data accumulated at the time of testing. Except as provided in paragraph (g) of this section, no record need be kept more than 60 days.
. In the event of an accident or occurrence that requires immediate notification of the National Transportation Safety Board under 49 CFR part 830 and that results in termination of the flight, the certificate holder shall remove the recording media from the airplane and keep the recorded data required by paragraph (a), (b), (c), or (d) of this section, as applicable, for at least 60 days or for a longer period upon the request of the Board or the Administrator.
. Each flight recorder required by this section must be installed in accordance with the requirements of § 25.1459 of this chapter in effect on August 31, 1977. The correlation required by § 25.1459(c) of this chapter need be established only on one airplane of any group of airplanes.
[arabic]
.. That are of the same type;
.. On which the flight recorder models and their installations are the same; and
.. On which there are no differences in the type design with respect to the installation of the first pilot's instruments associated with the flight recorder. The most recent instrument calibration, including the recording medium from which this calibration is derived, and the recorder correlation must be retained by the certificate holder.
[lowerroman]
... Each flight recorder required by this section that records the data specified in paragraphs (a), (b), (c), or (d) of this section must have an approved device to assist in locating that recorder under water.

(j) After August 20, 2001, this section applies only to the airplane models listed in § 125.226(l)(2). All other airplanes must comply with the requirements of § 125.226.

## § 125.226 - Digital flight data recorders.

[loweralpha]
. Except as provided in paragraph (l) of this section, no person may operate under this part a turbine-engine-powered transport category airplane unless it is equipped with one or more approved flight recorders that use a digital method of recording and storing data and a method of readily retrieving that data from the storage medium. The operational parameters required to be recorded by digital flight data recorders required by this section are as follows: the phrase “when an information source is installed” following a parameter indicates that recording of that parameter is not intended to require a change in installed equipment:
[arabic]
.. Time;
.. Pressure altitude;
.. Indicated airspeed;
.. Heading—primary flight crew reference (if selectable, record discrete, true or magnetic);
.. Normal acceleration (Vertical);
.. Pitch attitude;
.. Roll attitude;
.. Manual radio transmitter keying, or CVR/DFDR synchronization reference;
.. Thrust/power of each engine—primary flight crew reference;
.. Autopilot engagement status;
.. Longitudinal acceleration;
.. Pitch control input;
.. Lateral control input;
.. Rudder pedal input;
.. Primary pitch control surface position;
.. Primary lateral control surface position;
.. Primary yaw control surface position;
.. Lateral acceleration;
.. Pitch trim surface position or parameters of paragraph (a)(82) of this section if currently recorded;
.. Trailing edge flap or cockpit flap control selection (except when parameters of paragraph (a)(85) of this section apply);
.. Leading edge flap or cockpit flap control selection (except when parameters of paragraph (a)(86) of this section apply);
.. Each Thrust reverser position (or equivalent for propeller airplane);
.. Ground spoiler position or speed brake selection (except when parameters of paragraph (a)(87) of this section apply);
.. Outside or total air temperature;
.. Automatic Flight Control System (AFCS) modes and engagement status, including autothrottle;
.. Radio altitude (when an information source is installed);
.. Localizer deviation, MLS Azimuth;
.. Glideslope deviation, MLS Elevation;
.. Marker beacon passage;
.. Master warning;
.. Air/ground sensor (primary airplane system reference nose or main gear);
.. Angle of attack (when information source is installed);
.. Hydraulic pressure low (each system);
.. Ground speed (when an information source is installed);
.. Ground proximity warning system;
.. Landing gear position or landing gear cockpit control selection;
              
.. Drift angle (when an information source is installed);
.. Wind speed and direction (when an information source is installed);
.. Latitude and longitude (when an information source is installed);
.. Stick shaker/pusher (when an information source is installed);
.. Windshear (when an information source is installed);
.. Throttle/power lever position;
.. Additional engine parameters (as designed in appendix E of this part);
.. Traffic alert and collision avoidance system;
.. DME 1 and 2 distances;
.. Nav 1 and 2 selected frequency;
.. Selected barometric setting (when an information source is installed);
.. Selected altitude (when an information source is installed);
.. Selected speed (when an information source is installed);
.. Selected mach (when an information source is installed);
.. Selected vertical speed (when an information source is installed);
.. Selected heading (when an information source is installed);
.. Selected flight path (when an information source is installed);
.. Selected decision height (when an information source is installed);
.. EFIS display format;
.. Multi-function/engine/alerts display format;
.. Thrust command (when an information source is installed);
.. Thrust target (when an information source is installed);
.. Fuel quantity in CG trim tank (when an information source is installed);
.. Primary Navigation System Reference;
.. Icing (when an information source is installed);
.. Engine warning each engine vibration (when an information source is installed);
.. Engine warning each engine over temp. (when an information source is installed);
.. Engine warning each engine oil pressure low (when an information source is installed);
.. Engine warning each engine over speed (when an information source is installed);
.. Yaw trim surface position;
.. Roll trim surface position;
.. Brake pressure (selected system);
.. Brake pedal application (left and right);
.. Yaw of sideslip angle (when an information source is installed);
.. Engine bleed valve position (when an information source is installed);
.. De-icing or anti-icing system selection (when an information source is installed);
.. Computed center of gravity (when an information source is installed);
.. AC electrical bus status;
.. DC electrical bus status;
.. APU bleed valve position (when an information source is installed);
.. Hydraulic pressure (each system);
.. Loss of cabin pressure;
.. Computer failure;
.. Heads-up display (when an information source is installed);
.. Para-visual display (when an information source is installed);
.. Cockpit trim control input position-pitch;
.. Cockpit trim control input position—roll;
.. Cockpit trim control input position—yaw;
.. Trailing edge flap and cockpit flap control position;
.. Leading edge flap and cockpit flap control position;
.. Ground spoiler position and speed brake selection;
.. All cockpit flight control input forces (control wheel, control column, rudder pedal);
.. Yaw damper status;
.. Yaw damper command; and
.. Standby rudder valve status.
. For all turbine-engine powered transport category airplanes manufactured on or before October 11, 1991, by August 20, 2001—
[arabic]
.. For airplanes not equipped as of July 16, 1996, with a flight data acquisition unit (FDAU), the parameters listed in paragraphs (a)(1) through (a)(18) of this section must be recorded within the ranges and accuracies specified in Appendix D of this part, and—
[lowerroman]
... For airplanes with more than two engines, the parameter described in paragraph (a)(18) is not required unless sufficient capacity is available on the existing recorder to record that parameter.
... Parameters listed in paragraphs (a)(12) through (a)(17) each may be recorded from a single source.
.. For airplanes that were equipped as of July 16, 1996, with a flight data acquisition unit (FDAU), the parameters listed in paragraphs (a)(1) through (a)(22) of this section must be recorded within the ranges, accuracies, and recording intervals specified in Appendix E of this part. Parameters listed in paragraphs (a)(12) through (a)(17) each may be recorded from a single source.
.. The approved flight recorder required by this section must be installed at the earliest time practicable, but no later than the next heavy maintenance check after August 18, 1999 and no later than August 20, 2001. A heavy maintenance check is considered to be any time an airplane is scheduled to be out of service for 4 or more days and is scheduled to include access to major structural components.
. For all turbine-engine-powered transport category airplanes manufactured on or before October 11, 1991—
[arabic]
.. That were equipped as of July 16, 1996, with one or more digital data bus(es) and an ARINC 717 digital flight data acquisition unit (DFDAU) or equivalent, the parameters specified in paragraphs (a)(1) through (a)(22) of this section must be recorded within the ranges, accuracies, resolutions, and sampling intervals specified in Appendix E of this part by August 20, 2001. Parameters listed in paragraphs (a)(12) through (a)(14) each may be recorded from a single source.
.. Commensurate with the capacity of the recording system (DFDAU or equivalent and the DFDR), all additional parameters for which information sources are installed and which are connected to the recording system must be recorded within the ranges, accuracies, resolutions, and sampling intervals specified in Appendix E of this part by August 20, 2001.
.. That were subject to § 125.225(e) of this part, all conditions of § 125.225(c) must continue to be met until compliance with paragraph (c)(1) of this section is accomplished.
. For all turbine-engine-powered transport category airplanes that were manufactured after October 11, 1991—
[arabic]
.. The parameters listed in paragraphs (a)(1) through (a)(34) of this section must be recorded within the ranges, accuracies, resolutions, and recording intervals specified in Appendix E of this part by August 20, 2001. Paramaters listed in paragraphs (a)(12) through (a)(14) each may be recorded from a single source.
.. Commensurate with the capacity of the recording system, all additional parameters for which information sources are installed and which are connected to the recording system, must be recorded within the ranges, accuracies, resolutions, and sampling intervals specified in Appendix E of this part by August 20, 2001.
. For all turbine-engine-powered transport category airplanes that are manufactured after August 18, 2000—
[arabic]
.. The parameters listed in paragraph (a) (1) through (57) of this section must be recorded within the ranges, accuracies, resolutions, and recording intervals specified in Appendix E of this part.
.. Commensurate with the capacity of the recording system, all additional parameters for which information sources are installed and which are connected to the recording system, must be recorded within the ranges, accuracies, resolutions, and sampling intervals specified in Appendix E of this part.
.. In addition to the requirements of paragraphs (e)(1) and (e)(2) of this section, all Boeing 737 model airplanes must also comply with the requirements of paragraph (n) of this section, as applicable.
. For all turbine-engine-powered transport category airplanes manufactured after August 19, 2002—
[arabic]
.. The parameters listed in paragraphs (a)(1) through (a)(88) of this section must be recorded within the ranges, accuracies, resolutions, and recording intervals specified in Appendix E to this part.
              
.. In addition to the requirements of paragraphs (f)(1) of this section, all Boeing 737 model airplanes must also comply with the requirements of paragraph (n) of this section.
. Whenever a flight data recorder required by this section is installed, it must be operated continuously from the instant the airplane begins its takeoff roll until it has completed its landing roll.
. Except as provided in paragraph (i) of this section, and except for recorded data erased as authorized in this paragraph, each certificate holder shall keep the recorded data prescribed by this section, as appropriate, until the airplane has been operated for at least 25 hours of the operating time specified in § 121.359(a) of this part. A total of 1 hour of recorded data may be erased for the purpose of testing the flight recorder or the flight recorder system. Any erasure made in accordance with this paragraph must be of the oldest recorded data accumulated at the time of testing. Except as provided in paragraph (i) of this section, no record need to be kept more than 60 days.
[lowerroman]
.. In the event of an accident or occurrence that requires immediate notification of the National Transportation Safety Board under 49 CFR 830 of its regulations and that results in termination of the flight, the certificate holder shall remove the recorder from the airplane and keep the recorder data prescribed by this section, as appropriate, for at least 60 days or for a longer period upon the request of the Board or the Administrator.

(j) Each flight data recorder system required by this section must be installed in accordance with the requirements of § 25.1459(a) (except paragraphs (a)(3)(ii) and (7)), (b), (d) and (e) of this chapter. A correlation must be established between the values recorded by the flight data recorder and the corresponding values being measured. The correlation must contain a sufficient number of correlation points to accurately establish the conversion from the recorded values to engineering units or discrete state over the full operating range of the parameter. Except for airplanes having separate altitude and airspeed sensors that are an integral part of the flight data recorder system, a single correlation may be established for any group of airplanes—

[arabic]
. That are of the same type;
. On which the flight recorder system and its installation are the same; and
. On which there is no difference in the type design with respect to the installation of those sensors associated with the flight data recorder system. Documentation sufficient to convert recorded data into the engineering units and discrete values specified in the applicable appendix must be maintained by the certificate holder.

(k) Each flight data recorder required by this section must have an approved device to assist in locating that recorder under water.

(l) The following airplanes that were manufactured before August 18, 1997 need not comply with this section, but must continue to comply with applicable paragraphs of § 125.225 of this chapter, as appropriate:

[arabic]
. Airplanes that meet the Stage 2 noise levels of part 36 of this chapter and are subject to § 91.801(c) of this chapter, until January 1, 2000. On and after January 1, 2000, any Stage 2 airplane otherwise allowed to be operated under Part 91 of this chapter must comply with the applicable flight data recorder requirements of this section for that airplane.
. British Aerospace 1-11, General Dynamics Convair 580, General Dynamics Convair 600, General Dynamics Convair 640, deHavilland Aircraft Company Ltd. DHC-7, Fairchild Industries FH 227, Fokker F-27 (except Mark 50), F-28 Mark 1000 and Mark 4000, Gulfstream Aerospace G-159, Jetstream 4100 Series, Lockheed Aircraft Corporation Electra 10-A, Lockheed Aircraft Corporation Electra 10-B, Lockheed Aircraft Corporation Electra 10-E, Lockheed Aircraft Corporation Electra L-188, Lockheed Martin Model 382 (L-100) Hercules, Maryland Air Industries, Inc. F27, Mitsubishi Heavy Industries, Ltd. YS-11, Short Bros. Limited SD3-30, Short Bros. Limited SD3-60.

(m) All aircraft subject to the requirements of this section that are manufactured on or after April 7, 2010, must have a flight data recorder installed that also—
              

[arabic]
. Meets the requirements in § 25.1459(a)(3), (a)(7), and (a)(8) of this chapter; and
. Retains the 25 hours of recorded information required in paragraph (f) of this section using a recorder that meets the standards of TSO-C124a, or later revision.

(n) In addition to all other applicable requirements of this section, all Boeing 737 model airplanes manufactured after August 18, 2000 must record the parameters listed in paragraphs (a)(88) through (a)(91) of this section within the ranges, accuracies, resolutions, and recording intervals specified in Appendix E to this part. Compliance with this paragraph is required no later than February 2, 2011.

## § 125.227 - Cockpit voice recorders.

[loweralpha]
. No certificate holder may operate a large turbine engine powered airplane or a large pressurized airplane with four reciprocating engines unless an approved cockpit voice recorder is installed in that airplane and is operated continuously from the start of the use of the checklist (before starting engines for the purpose of flight) to completion of the final checklist at the termination of the flight.
. Each certificate holder shall establish a schedule for completion, before the prescribed dates, of the cockpit voice recorder installations required by paragraph (a) of this section. In addition, the certificate holder shall identify any airplane specified in paragraph (a) of this section he intends to discontinue using before the prescribed dates.
. The cockpit voice recorder required by this section must also meet the following standards:
[arabic]
.. The requirements of part 25 of this chapter in effect after October 11, 1991.
.. After September 1, 1980, each recorder container must—
[lowerroman]
... Be either bright orange or bright yellow;
... Have reflective tape affixed to the external surface to facilitate its location under water; and
... Have an approved underwater locating device on or adjacent to the container which is secured in such a manner that it is not likely to be separated during crash impact, unless the cockpit voice recorder and the flight recorder, required by § 125.225 of this chapter, are installed adjacent to each other in such a manner that they are not likely to be separated during crash impact.
. In complying with this section, an approved cockpit voice recorder having an erasure feature may be used so that, at any time during the operation of the recorder, information recorded more than 30 minutes earlier may be erased or otherwise obliterated.
. For those aircraft equipped to record the uninterrupted audio signals received by a boom or a mask microphone the flight crewmembers are required to use the boom microphone below 18,000 feet mean sea level. No person may operate a large turbine engine powered airplane or a large pressurized airplane with four reciprocating engines manufactured after October 11, 1991, or on which a cockpit voice recorder has been installed after October 11, 1991, unless it is equipped to record the uninterrupted audio signal received by a boom or mask microphone in accordance with § 25.1457(c)(5) of this chapter.
. In the event of an accident or occurrence requiring immediate notification of the National Transportation Safety Board under 49 CFR part 830 of its regulations, which results in the termination of the flight, the certificate holder shall keep the recorded information for at least 60 days or, if requested by the Administrator or the Board, for a longer period. Information obtained from the record is used to assist in determining the cause of accidents or occurrences in connection with investigations under 49 CFR part 830. The Administrator does not use the record in any civil penalty or certificate action.
. By April 7, 2012, all turbine engine-powered airplanes subject to this section that are manufactured before April 7, 2010, must have a cockpit voice recorder installed that also—
              
[arabic]
.. Meets the requirements of § 25.1457(a)(3), (a)(4), (a)(5), and (d)(6) of this chapter;
.. Retains at least the last 2 hours of recorded information using a recorder that meets the standards of TSO-C123a, or later revision; and
.. Is operated continuously from the start of the use of the checklist (before starting the engines for the purpose of flight), to the completion of the final checklist at the termination of the flight.
. All turbine engine-powered airplanes subject to this section that are manufactured on or after April 7, 2010, must have a cockpit voice recorder installed that also—
[arabic]
.. Is installed in accordance with the requirements of § 25.1457 (except for paragraph (a)(6)) of this chapter;
.. Retains at least the last 2 hours of recorded information using a recorder that meets the standards of TSO-C123a, or later revision; and
.. Is operated continuously from the start of the use of the checklist (before starting the engines for the purpose of flight), to the completion of the final checklist at the termination of the flight.
.. For all airplanes manufactured on or after December 6, 2010, also meets the requirements of § 25.1457(a)(6) of this chapter.
[lowerroman]
... All airplanes required by this part to have a cockpit voice recorder and a flight data recorder, that install datalink communication equipment on or after December 6, 2010, must record all datalink messages as required by the certification rule applicable to the airplane.

## § 125.228 - Flight data recorders: filtered data.

[loweralpha]
. A flight data signal is filtered when an original sensor signal has been changed in any way, other than changes necessary to:
[arabic]
.. Accomplish analog to digital conversion of the signal;
.. Format a digital signal to be DFDR compatible; or
.. Eliminate a high frequency component of a signal that is outside the operational bandwidth of the sensor.
. An original sensor signal for any flight recorder parameter required to be recorded under § 125.226 may be filtered only if the recorded signal value continues to meet the requirements of Appendix D or E of this part, as applicable.
. For a parameter described in § 125.226(a) (12) through (17), (42), or (88), or the corresponding parameter in Appendix D of this part, if the recorded signal value is filtered and does not meet the requirements of Appendix D or E of this part, as applicable, the certificate holder must:
[arabic]
.. Remove the filtering and ensure that the recorded signal value meets the requirements of Appendix D or E of this part, as applicable; or
.. Demonstrate by test and analysis that the original sensor signal value can be reconstructed from the recorded data. This demonstration requires that:
[lowerroman]
... The FAA determine that the procedure and the test results submitted by the certificate holder as its compliance with paragraph (c)(2) of this section are repeatable; and
... The certificate holder maintains documentation of the procedure required to reconstruct the original sensor signal value. This documentation is also subject to the requirements of § 125.226(i).
. *Compliance.* Compliance is required as follows:
[arabic]
.. No later than October 20, 2011, each operator must determine, for each airplane it operates, whether the airplane's DFDR system is filtering any of the parameters listed in paragraph (c) of this section. The operator must create a record of this determination for each airplane it operates, and maintain it as part of the correlation documentation required by § 125.226(j)(3) of this part.
.. For airplanes that are not filtering any listed parameter, no further action is required unless the airplane's DFDR system is modified in a manner that would cause it to meet the definition of filtering on any listed parameter.
              
.. For airplanes found to be filtering a parameter listed in paragraph (c) of this section, the operator must either:
[lowerroman]
... No later than April 21, 2014, remove the filtering; or
... No later than April 22, 2013, submit the necessary procedure and test results required by paragraph (c)(2) of this section.
.. After April 21, 2014, no aircraft flight data recording system may filter any parameter listed in paragraph (c) of this section that does not meet the requirements of Appendix D or E of this part, unless the certificate holder possesses test and analysis procedures and the test results that have been approved by the FAA. All records of tests, analysis and procedures used to comply with this section must be maintained as part of the correlation documentation required by § 125.226(j)(3) of this part.

