# Applicability
:toc:

## § 133.1

### Applicability.

Except for aircraft subject to part 107 of this chapter, this part prescribes—

. Airworthiness certification rules for rotorcraft used in; and
. Operating and certification rules governing the conduct of rotorcraft external-load operations in the United States by any person.
. The certification rules of this part do not apply to—
.. Rotorcraft manufacturers when developing external-load attaching means;
.. Rotorcraft manufacturers demonstrating compliance of equipment utilized under this part or appropriate portions of part 27 or 29 of this chapter;
.. Operations conducted by a person demonstrating compliance for the issuance of a certificate or authorization under this part;
.. Training flights conducted in preparation for the demonstration of compliance with this part; or
.. A Federal, State, or local government conducting operations with public aircraft.
. For the purpose of this part, a person other than a crewmember or a person who is essential and directly connected with the external-load operation may be carried only in approved Class D rotorcraft-load combinations.

