# Anchorage, Alaska, Terminal Area
:toc:

## § 93.51

### Applicability.

This subpart prescribes special air traffic rules for aircraft operating in the Anchorage, Alaska, Terminal Area.

## § 93.53

### Description of area.

The Anchorage, Alaska, Terminal Area is designated as that airspace extending upward from the surface to the upper limit of each of the segments described in § 93.55. It is bounded by a line beginning at Point MacKenzie, extending westerly along the bank of Knik Arm to a point intersecting the 350° bearing from the Anchorage International ATCT; thence north to intercept the 5.2-mile arc centered on the geographical center of Anchorage, Alaska, ATCT; thence counterclockwise along that arc to its intersection with a line bearing 180° from the intersection of the new Seward Highway and International Airport Road; thence due north to O'Malley Road; thence east along O'Malley Road to its intersection with Lake Otis Parkway; thence northerly along Lake Otis Parkway to its intersection with Abbott Road; thence east along Abbott Road to its intersection with Abbott Loop Road; thence north to its intersection with Tudor Road; thence easterly along Tudor Road to its intersection with Muldoon Road; thence northerly along Muldoon Road to the intersection of the Glenn Highway; thence north and east along the Glenn Highway to Ski Bowl Road; thence southeast along the Ski Bowl Road to a point one-half mile south of the Glenn Highway; thence north and east one-half mile south of and parallel to the Glenn Highway to its intersection with a line one-half mile east of and parallel to the Bryant Airport Runway 16/34 extended centerline; thence northeast along a line one-half mile east of and parallel to Bryant Airport Runway 16/34 extended centerline to lat. 61°17′13″ N., long. 149°37′35″ W.; thence west along lat. 61°17′13″ N., to long. 149°43′08″ W.; thence north along long. 149°43′08″ W., to lat. 61°17′30″ N.; thence to lat. 61°17′58″ N., long 149°44′08″ W.; thence to lat. 61°19′10″ N., long. 149°46′44″ W.; thence north along long. 149°46′44″ W., to intercept the 4.7-mile radius arc centered on Elmendorf Air Force Base (AFB), Alaska; thence counterclockwise along the 4.7-mile radius arc to its intersection with the west bank of Knik Arm; thence southerly along the west bank of Knik Arm to the point of beginning.

## § 93.55

### Subdivision of Terminal Area.

The Anchorage, Alaska, Terminal Area is subdivided as follows:

. *International segment.* That area from the surface to and including 4,100 feet MSL, within a 5.2-mile radius of the Anchorage International ATCT; excluding that airspace east of the 350° bearing from the Anchorage International ATCT and north of the 090° bearing from the Anchorage International ATCT and east of a line bearing 180° and 360° from the intersection of the new Seward Highway and International Airport Road and the airspace extending upward from the surface to but not including 600 feet MSL, south of lat. 61°08′28″ N.
. *Merrill segment.* That area from the surface to and including 2,500 feet MSL, within a line beginning at Point Noname; thence direct to the mouth of Ship Creek; thence direct to the intersection of the Glenn Highway and Muldoon Road; thence south along Muldoon Road to Tudor Road; thence west along Tudor Road to the new Seward Highway; thence direct to West Anchorage High School; thence direct to Point MacKenzie; thence via the north bank of Knik Arm to the point of beginning.
. *Lake Hood segment.* That area from the surface to and including 2,500 feet MSL, within a line beginning at Point MacKenzie; thence direct to West Anchorage High School; thence direct to the intersection of Tudor Road and the new Seward Highway; thence south along the new Seward Highway to the 090° bearing from the Anchorage International ATCT; thence west direct to the Anchorage International ATCT; thence north along the 350° bearing from the Anchorage International ATCT to the north bank of Knik arm; thence via the north bank of Knik Arm to the point of beginning.
. *Elmendorf segment.* That area from the surface to and including 3,000 feet MSL, within a line beginning at Point Noname; thence via the north bank of Knik Arm to the intersection of the 4.7-mile radius of Elmendorf AFB; thence clockwise along the 4.7-mile radius of Elmendorf AFB to long. 149°46′44″ W.; thence south along long. 149°46′44″ W. to lat. 61°19′10″ N.; thence to lat. 61°17′58″ N., long. 149°44′08″ W.; thence to lat. 61°17′30″ N., long. 149°43′08″ W.; thence south along long. 149°43′08″ W. to the Glenn Highway; thence south and west along the Glenn Highway to Muldoon Road; thence direct to the mouth of Ship Creek; thence direct to the point of beginning.
. *Bryant segment.* That area from the surface to and including 2,000 feet MSL, within a line beginning at lat. 61°17′13″ N., long. 149°37′35″ W.; thence west along lat. 61°17′13″ N., to long. 149°43′08″ W.; thence south along long. 149°43′08″ W., to the Glenn Highway; thence north and east along the Glenn Highway to Ski Bowl Road; thence southeast along the Ski Bowl Road to a point one-half mile south of the Glenn Highway; thence north and east one-half mile south of and parallel to the Glenn Highway to its intersection with a line one-half mile east of and parallel to the Bryant Airport Runway 16/34 extended centerline; thence northeast along a line one-half mile east of and parallel to Bryant Airport runway 16/34 extended centerline to the point of beginning.
. *Seward Highway segment.* That area from the surface to and including 4,100 feet MSL, within a line beginning at the intersection of a line bearing 180° from the intersection of the new Seward Highway and International Airport Road, and O'Malley Road; thence east along O'Malley Road to its intersection with Lake Otis Park Way, lat. 61°07′23″ N., long 149°50′03″ W.; thence northerly along Lake Otis Park Way to its intersection with Abbott Road, lat. 61°08′14″ N., long. 149°50′03″ W.; thence east along Abbott Road to its intersection with Abbott Loop Road, lat. 61°08′14″ N., long. 149°48′16″ W.; thence due north to intersect with Tudor Road, lat. 61°10′51″ N., long. 149°48′16″ W.; thence west along Tudor Road to its intersection with the new Seward Highway, lat. 61°10′51″ N., long. 149°51′38″ W.; thence south along the new Seward Highway to its intersection with a line bearing 180° and 360° from the intersection of the new Seward Highway and International Airport Road; thence south to the point of beginning.

## § 93.57

### General rules: All segments.

. Each person operating an aircraft to, from, or on an airport within the Anchorage, Alaska, Terminal Area shall operate that aircraft according to the rules set forth in this section and §§ 93.59, 93.61, 93.63, 93.65, 93.67, or 93.68 as applicable, unless otherwise authorized or required by ATC.
. Each person operating an airplane within the Anchorage, Alaska Terminal Area shall conform to the flow of traffic depicted on the appropriate aeronautical charts.
. Each person operating a helicopter shall operate it in a manner so as to avoid the flow of airplanes.
. Except as provided in § 93.65 (d) and (e), and § 93.67(b), each person operating an aircraft in the Anchorage, Alaska, Terminal Area shall operate that aircraft only within the designated segment containing the arrival or departure airport.
. Except as provided in §§ 93.63(d) and 93.67(b), each person operating an aircraft in the Anchorage, Alaska, Terminal Area shall maintain two-way radio communications with the ATCT serving the segment containing the arrival or departure airport.

## § 93.59

### General rules: International segment.

. No person may operate an aircraft at an altitude between 1,200 feet MSL and 2,000 feet MSL in that portion of this segment lying north of the midchannel of Knik Arm.
. Each person operating an airplane at a speed of more than 105 knots within this segment (except that part described in paragraph (a) of this section) shall operate that airplane at an altitude of at least 1,600 feet MSL until maneuvering for a safe landing requires further descent.
. Each person operating an airplane at a speed of 105 knots or less within this segment (except that part described in paragraph (a) of this section) shall operate that airplane at an altitude of at least 900 feet MSL until maneuvering for a safe landing requires further descent.

## § 93.61

### General rules: Lake Hood segment.

. No person may operate an aircraft at an altitude between 1,200 feet MSL and 2,000 feet MSL in that portion of this segment lying north of the midchannel of Knik Arm.
. Each person operating an airplane within this segment (except that part described in paragraph (a) of this section) shall operate that airplane at an altitude of at least 600 feet MSL until maneuvering for a safe landing requires further descent.

## § 93.63

### General rules: Merrill segment.

. No person may operate an aircraft at an altitude between 600 feet MSL and 2,000 feet MSL in that portion of this segment lying north of the midchannel of Knik Arm.
. Each person operating an airplane at a speed of more than 105 knots within this segment (except for that part described in paragraph (a) of this section) shall operate that airplane at an altitude of at least 1,200 feet MSL until maneuvering for a safe landing requires further descent.
. Each person operating an airplane at a speed of 105 knots or less within this segment (except for that part described in paragraph (a) of this section) shall operate that airplane at an altitude of at least 900 feet MSL until maneuvering for a safe landing requires further descent.
. Whenever the Merrill ATCT is not operating, each person operating an aircraft either in that portion of the Merrill segment north of midchannel of Knik Arm, or in the Seward Highway segment at or below 1200 feet MSL, shall contact Anchorage Approach Control for wake turbulence and other advisories. Aircraft operating within the remainder of the segment should self-announce intentions on the Merrill Field CTAF.

## § 93.65

### General rules: Elmendorf segment.

. Each person operating a turbine-powered aircraft within this segment shall operate that aircraft at an altitude of at least 1,700 feet MSL until maneuvering for a safe landing requires further descent.
. Each person operating an airplane (other than turbine-powered aircraft) at a speed of more than 105 knots within this segment shall operate that airplane at an altitude of at least 1,200 feet MSL until maneuvering for a safe landing requires further descent.
. Each person operating an airplane (other than turbine-powered aircraft) at a speed of 105 knots or less within the segment shall operate that airplane at an altitude of at least 800 feet MSL until maneuvering for a safe landing requires further descent.
. A person landing or departing from Elmendorf AFB, may operate that aircraft at an altitude between 1,500 feet MSL and 1,700 feet MSL within that portion of the International and Lake Hood segments lying north of the midchannel of Knik Arm.
. A person landing or departing from Elmendorf AFB, may operate that aircraft at an altitude between 900 feet MSL and 1,700 feet MSL within that portion of the Merrill segment lying north of the midchannel of Knik Arm.
. A person operating in VFR conditions, at or below 600 feet MSL, north of a line beginning at the intersection of Farrell Road and the long. 149°43′08″ W.; thence west along Farrell Road to the east end of Sixmile Lake; thence west along a line bearing on the middle of Lake Lorraine to the northwest bank of Knik Arm; is not required to establish two-way radio communications with ATC.

## § 93.67

### General rules: Bryant segment.

. Each person operating an airplane to or from the Bryant Airport shall conform to the flow of traffic shown on the appropriate aeronautical charts, and while in the traffic pattern, shall operate that airplane at an altitude of at least 1,000 feet MSL until maneuvering for a safe landing requires further descent.
. Each person operating an aircraft within the Bryant segment should self-announce intentions on the Bryant Airport CTAF.

## § 93.68

### General rules: Seward Highway segment.

. Each person operating an airplane in the Seward Highway segment shall operate that airplane at an altitude of at least 1,000 feet MSL unless maneuvering for a safe landing requires further descent.
. Each person operating an aircraft at or below 1,200 feet MSL that will transition to or from the Lake Hood or Merrill segment shall contact the appropriate ATCT prior to entering the Seward Highway segment. All other persons operating an airplane at or below 1,200 feet MSL in this segment shall contact Anchorage Approach Control.
. At all times, each person operating an aircraft above 1,200 MSL shall contact Anchorage Approach Control prior to entering the Seward Highway segment.

## § 93.69

### Special requirements, Lake Campbell and Sixmile Lake Airports.

Each person operating an aircraft to or from Lake Campbell or Sixmile Lake Airport shall conform to the flow of traffic for the Lake operations that are depicted on the appropriate aeronautical charts.

