# Operating Rules
:toc:

## § 142.61

### Applicability.

This subpart prescribes the operating rules applicable to a training center certificated under this part and operating a course or training program curriculum approved in accordance with subpart B of this part.

## § 142.63

### Privileges.

A certificate holder may allow flight simulator instructors and evaluators to meet recency of experience requirements through the use of a qualified and approved flight simulator or qualified and approved flight training device if that flight simulator or flight training device is—

. Used in a course approved in accordance with subpart B of this part; or
. Approved under the Advanced Qualification Program for meeting recency of experience requirements.

## § 142.65

### Limitations.

. A certificate holder shall—
.. Ensure that a flight simulator or flight training device freeze, slow motion, or repositioning feature is not used during testing or checking; and
.. Ensure that a repositioning feature is used during line operational simulation for evaluation and line-oriented flight training only to advance along a flight route to the point where the descent and approach phase of the flight begins.
. When flight testing, flight checking, or line operational simulation is being conducted, the certificate holder must ensure that one of the following occupies each crewmember position:
.. A crewmember qualified in the aircraft category, class, and type, if a type rating is required, provided that no flight instructor who is giving instruction may occupy a crewmember position.
.. A student, provided that no student may be used in a crewmember position with any other student not in the same specific course.
. The holder of a training center certificate may not recommend a trainee for a certificate or rating, unless the trainee—
.. Has satisfactorily completed the training specified in the course approved under § 142.37; and
.. Has passed the final tests required by § 142.37.
. The holder of a training center certificate may not graduate a student from a course unless the student has satisfactorily completed the curriculum requirements of that course.

