# Evaluations and Determinations of Effects of Noise Compatibility Programs
:toc:

## § 150.31

### Preliminary review: Acknowledgments.

. Upon receipt of a noise compatibility program submitted under § 150.23, the Regional Airports Division Manager acknowledges to the airport operator receipt of the program and conducts a preliminary review of the submission.
. If, based on the preliminary review, the Regional Airports Division Manager finds that the submission does not conform to the requirements of this part, he disapproves and returns the unacceptable program to the airport operator for reconsideration and development of a program in accordance with this part.
. If, based on the preliminary review, the Regional Airports Division Manager finds that the program conforms to the requirements of this part, the Regional Airports Division Manager publishes in the *Federal Register* a notice of receipt of the program for comment which indicates the following:
.. The airport covered by the program, and the date of receipt.
.. The availability of the program for examination in the offices of the Regional Airports Division Manager and the airport operator.
.. That comments on the program are invited and, will be considered by the FAA.
. The date of signature of the published notice of receipt starts the 180-day approval period for the program.

## § 150.33

### Evaluation of programs.

. The FAA conducts an evaluation of each noise compatibility program and, based on that evaluation, either approves or disapproves the program. The evaluation includes consideration of proposed measures to determine whether they—
.. May create an undue burden on interstate or foreign commerce (including unjust discrimination);
              
.. Are reasonably consistent with obtaining the goal of reducing existing noncompatible land uses and preventing the introduction of additional noncompatible land uses; and
.. Include the use of new or modified flight procedures to control the operation of aircraft for purposes of noise control, or affect flight procedures in any way.
. The evaluation may also include an evaluation of those proposed measures to determine whether they may adversely affect the exercise of the authority and responsibilities of the Administrator under the Federal Aviation Act of 1958, as amended.
. To the extent considered necessary, the FAA may—
.. Confer with the airport operator and other persons known to have information and views material to the evaluation;
.. Explore the objectives of the program and the measures, and any alternative measures, for achieving the objectives.
.. Examine the program for developing a range of alternatives that would eliminate the reasons, if any, for disapproving the program.
.. Convene an informal meeting with the airport operator and other persons involved in developing or implementing the program for the purposes of gathering all facts relevant to the determination of approval or disapproval of the program and of discussing any needs to accommodate or modify the program as submitted.
. If requested by the FAA, the airport operator shall furnish all information needed to complete FAA's review under (c).
. An airport operator may, at any time before approval or disapproval of a program, withdraw or revise the program. If the airport operator withdraws or revises the program or indicates to the Regional Airports Division Manager, in writing, the intention to revise the program, the Regional Airports Division Manager terminates the evaluation and notifies the airport operator of that action. That termination cancels the 180-day review period. The FAA does not evaluate a second program for any airport until any previously submitted program has been withdrawn or a determination on it is issued. A new evaluation is commenced upon receipt of a revised program, and a new 180-day approval period is begun, unless the Regional Airports Division Manager finds that the modification made, in light of the overall revised program, can be integrated into the unmodified portions of the revised program without exceeding the original 180-day approval period or causing undue expense to the government.

## § 150.35

### Determinations; publications; effectivity.

. The FAA issues a determination approving or disapproving each airport noise compatibility program (and revised program). Portions of a program may be individually approved or disapproved. No conditional approvals will be issued. A determination on a program acceptable under this part is issued within 180 days after the program is received under § 150.23 of this part or it may be considered approved, except that this time period may be exceeded for any portion of a program relating to the use of flight procedures for noise control purposes. A determination on portions of a program covered by the exceptions to the 180-day review period for approval will be issued within a reasonable time after receipt of the program. Determinations relating to the use of any flight procedure for noise control purposes may be issued either in connection with the determination on other portions of the program or separately. Except as provided by this paragraph, no approval of any noise compatibility program, or any portion of a program, may be implied in the absence of the FAA's express approval.
. The Administrator approves programs under this part, if—
.. It is found that the program measures to be implemented would not create an undue burden on interstate or foreign commerce (including any unjust discrimination) and are reasonably consistent with achieving the goals of reducing existing noncompatible land uses around the airport and of preventing the introduction of additional noncompatible land uses;
.. The program provides for revision if made necessary by the revision of the noise map; and
.. Those aspects of programs relating to the use of flight procedures for noise control can be implemented within the period covered by the program and without—
... Reducing the level of aviation safety provided;
... Derogating the requisite level of protection for aircraft, their occupants and persons and property on the ground;
... Adversely affecting the efficient use and management of the Navigable Airspace and Air Traffic Control Systems; or
... Adversely affecting any other powers and responsibilities of the Administrator prescribed by law or any other program, standard, or requirement established in accordance with law.
. When a determination is issued, the Regional Airports Division Manager notifies the airport operator and publishes a notice of approval or disapproval in the *Federal Register* identifying the nature and extent of the determination.
. Approvals issued under this part for a program or portion thereof become effective as specified therein and may be withdrawn when one of the following occurs:
.. The program or portion thereof is required to be revised under this part or under its own terms, and is not so revised;
.. If a revision has been submitted for approval, a determination is issued on the revised program or portion thereof, that is inconsistent with the prior approval.
.. A term or condition of the program, or portion thereof, or its approval is violated by the responsible government body.
.. A flight procedure or other FAA action upon which the approved program or portion thereof is dependent is subsequently disapproved, significantly altered, or rescinded by the FAA.
.. The airport operator requests rescission of the approval.
.. Impacts on flight procedures, air traffic management, or air commerce occur which could not be foreseen at the time of approval.
              
. Determinations may contain conditions which must be satisfied prior to implementation of any portion of the program relating to flight procedures affecting airport or aircraft operations.
. Noise exposure maps for current and forecast year map conditions that are submitted and approved with noise compatibility programs are considered to be the new FAA accepted noise exposure maps for purposes of part 150.

