# Special Rule for Model Aircraft
:toc:

## § 101.41 - Applicability.

This subpart prescribes rules governing the operation of a model aircraft (or an aircraft being developed as a model aircraft) that meets all of the following conditions as set forth in section 336 of Public Law 112-95:

[loweralpha]
. The aircraft is flown strictly for hobby or recreational use;
. The aircraft is operated in accordance with a community-based set of safety guidelines and within the programming of a nationwide community-based organization;
. The aircraft is limited to not more than 55 pounds unless otherwise certified through a design, construction, inspection, flight test, and operational safety program administered by a community-based organization;
. The aircraft is operated in a manner that does not interfere with and gives way to any manned aircraft; and
. When flown within 5 miles of an airport, the operator of the aircraft provides the airport operator and the airport air traffic control tower (when an air traffic facility is located at the airport) with prior notice of the operation.

## § 101.43 - Endangering the safety of the National Airspace System.

No person may operate model aircraft so as to endanger the safety of the national airspace system.

