# General
:toc:

## § 101.1 - Applicability.

[loweralpha]
. This part prescribes rules governing the operation in the United States, of the following:
[arabic]
.. Except as provided for in § 101.7, any balloon that is moored to the surface of the earth or an object thereon and that has a diameter of more than 6 feet or a gas capacity of more than 115 cubic feet.
.. Except as provided for in § 101.7, any kite that weighs more than 5 pounds and is intended to be flown at the end of a rope or cable.
.. Any amateur rocket except aerial firework displays.
.. Except as provided for in § 101.7, any unmanned free balloon that—
[lowerroman]
... Carries a payload package that weighs more than four pounds and has a weight/size ratio of more than three ounces per square inch on any surface of the package, determined by dividing the total weight in ounces of the payload package by the area in square inches of its smallest surface;
... Carries a payload package that weighs more than six pounds;
... Carries a payload, of two or more packages, that weighs more than 12 pounds; or
... Uses a rope or other device for suspension of the payload that requires an impact force of more than 50 pounds to separate the suspended payload from the balloon.
.. Any model aircraft that meets the conditions specified in § 101.41. For purposes of this part, a model aircraft is an unmanned aircraft that is:
[lowerroman]
... Capable of sustained flight in the atmosphere;
... Flown within visual line of sight of the person operating the aircraft; and
... Flown for hobby or recreational purposes.
. For the purposes of this part, a *gyroglider* attached to a vehicle on the surface of the earth is considered to be a kite.

## § 101.3 - Waivers.

No person may conduct operations that require a deviation from this part except under a certificate of waiver issued by the Administrator.

## § 101.5 - Operations in prohibited or restricted areas.

No person may operate a moored balloon, kite, amateur rocket, or unmanned free balloon in a prohibited or restricted area unless he has permission from the using or controlling agency, as appropriate.

## § 101.7 - Hazardous operations.

[loweralpha]
. No person may operate any moored balloon, kite, amateur rocket, or unmanned free balloon in a manner that creates a hazard to other persons, or their property.
. No person operating any moored balloon, kite, amateur rocket, or unmanned free balloon may allow an object to be dropped therefrom, if such action creates a hazard to other persons or their property.

