# Individuals Certificated Under Parts 61, 63, and 65
:toc:

## § 120.11

### Refusal to submit to a drug or alcohol test by a Part 61 certificate holder.

. This section applies to all individuals who hold a certificate under part 61 of this chapter and who are subject to drug and alcohol testing under this part.
. Refusal by the holder of a certificate issued under part 61 of this chapter to take a drug or alcohol test required under the provisions of this part is grounds for:
.. Denial of an application for any certificate, rating, or authorization issued under part 61 of this chapter for a period of up to 1 year after the date of such refusal; and
.. Suspension or revocation of any certificate, rating, or authorization issued under part 61 of this chapter.

## § 120.13

### Refusal to submit to a drug or alcohol test by a Part 63 certificate holder.

. This section applies to all individuals who hold a certificate under part 63 of this chapter and who are subject to drug and alcohol testing under this part.
. Refusal by the holder of a certificate issued under part 63 of this chapter to take a drug or alcohol test required under the provisions of this part is grounds for:
              
.. Denial of an application for any certificate or rating issued under part 63 of this chapter for a period of up to 1 year after the date of such refusal; and
.. Suspension or revocation of any certificate or rating issued under part 63 of this chapter.

## § 120.15

### Refusal to submit to a drug or alcohol test by a Part 65 certificate holder.

. This section applies to all individuals who hold a certificate under part 65 of this chapter and who are subject to drug and alcohol testing under this part.
. Refusal by the holder of a certificate issued under part 65 of this chapter to take a drug or alcohol test required under the provisions of this part is grounds for:
.. Denial of an application for any certificate or rating issued under part 65 of this chapter for a period of up to 1 year after the date of such refusal; and
.. Suspension or revocation of any certificate or rating issued under part 65 of this chapter.

