# Recreational Pilots
:toc:

## § 61.96 - Applicability and eligibility requirements: General.

[loweralpha]
. This subpart prescribes the requirement for the issuance of recreational pilot certificates and ratings, the conditions under which those certificates and ratings are necessary, and the general operating rules for persons who hold those certificates and ratings.
. To be eligible for a recreational pilot certificate, a person who applies for that certificate must:
[arabic]
.. Be at least 17 years of age;
.. Be able to read, speak, write, and understand the English language. If the applicant is unable to meet one of these requirements due to medical reasons, then the Administrator may place such operating limitations on that applicant's pilot certificate as are necessary for the safe operation of the aircraft;
.. Receive a logbook endorsement from an authorized instructor who—
[lowerroman]
... Conducted the training or reviewed the applicant's home study on the aeronautical knowledge areas listed in § 61.97(b) of this part that apply to the aircraft category and class rating sought; and
... Certified that the applicant is prepared for the required knowledge test.
.. Pass the required knowledge test on the aeronautical knowledge areas listed in § 61.97(b) of this part;
.. Receive flight training and a logbook endorsement from an authorized instructor who—
[lowerroman]
... Conducted the training on the areas of operation listed in § 61.98(b) of this part that apply to the aircraft category and class rating sought; and
... Certified that the applicant is prepared for the required practical test.
.. Meet the aeronautical experience requirements of § 61.99 of this part that apply to the aircraft category and class rating sought before applying for the practical test;
.. Pass the practical test on the areas of operation listed in § 61.98(b) that apply to the aircraft category and class rating;
.. Comply with the sections of this part that apply to the aircraft category and class rating; and
.. Hold either a student pilot certificate or sport pilot certificate.

## § 61.97 - Aeronautical knowledge.

[loweralpha]
. *General.* A person who applies for a recreational pilot certificate must receive and log ground training from an authorized instructor or complete a home-study course on the aeronautical knowledge areas of paragraph (b) of this section that apply to the aircraft category and class rating sought.
. *Aeronautical knowledge areas.*
[arabic]
.. Applicable Federal Aviation Regulations of this chapter that relate to recreational pilot privileges, limitations, and flight operations;
.. Accident reporting requirements of the National Transportation Safety Board;
.. Use of the applicable portions of the “Aeronautical Information Manual” and FAA advisory circulars;
.. Use of aeronautical charts for VFR navigation using pilotage with the aid of a magnetic compass;
.. Recognition of critical weather situations from the ground and in flight, windshear avoidance, and the procurement and use of aeronautical weather reports and forecasts;
.. Safe and efficient operation of aircraft, including collision avoidance, and recognition and avoidance of wake turbulence;
.. Effects of density altitude on takeoff and climb performance;
.. Weight and balance computations;
.. Principles of aerodynamics, powerplants, and aircraft systems;
.. Stall awareness, spin entry, spins, and spin recovery techniques, if applying for an airplane single-engine rating;
.. Aeronautical decision making and judgment; and
.. Preflight action that includes—
[lowerroman]
... How to obtain information on runway lengths at airports of intended use, data on takeoff and landing distances, weather reports and forecasts, and fuel requirements; and
... How to plan for alternatives if the planned flight cannot be completed or delays are encountered.

## § 61.98 - Flight proficiency.

[loweralpha]
. *General.* A person who applies for a recreational pilot certificate must receive and log ground and flight training from an authorized instructor on the areas of operation of this section that apply to the aircraft category and class rating sought.
. *Areas of operation.*
[arabic]
.. *For a single-engine airplane rating:*
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Airport operations;
... Takeoffs, landings, and go-arounds;
... Performance maneuvers;
... Ground reference maneuvers;
... Navigation;
... Slow flight and stalls;
... Emergency operations; and
... Postflight procedures.
.. *For a helicopter rating:*
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Airport and heliport operations;
... Hovering maneuvers;
... Takeoffs, landings, and go-arounds;
... Performance maneuvers;
... Ground reference maneuvers;
... Navigation;
... Emergency operations; and
... Postflight procedures.
.. *For a gyroplane rating:*
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Airport operations;
... Takeoffs, landings, and go-arounds;
... Performance maneuvers;
... Ground reference maneuvers;
... Navigation;
... Flight at slow airspeeds;
... Emergency operations; and
... Postflight procedures.

## § 61.99 - Aeronautical experience.

A person who applies for a recreational pilot certificate must receive and log at least 30 hours of flight time that includes at least—

[loweralpha]
. 15 hours of flight training from an authorized instructor on the areas of operation listed in § 61.98 of this part that consists of at least:
[arabic]
.. Except as provided in § 61.100 of this part, 2 hours of flight training en route to an airport that is located more than 25 nautical miles from the airport where the applicant normally trains, which includes at least three takeoffs and three landings at the airport located more than 25 nautical miles from the airport where the applicant normally trains; and
.. Three hours of flight training with an authorized instructor in the aircraft for the rating sought in preparation for the practical test within the preceding 2 calendar months from the month of the test.
. 3 hours of solo flying in the aircraft for the rating sought, on the areas of operation listed in § 61.98 of this part that apply to the aircraft category and class rating sought.

## § 61.100 - Pilots based on small islands.

[loweralpha]
. An applicant located on an island from which the flight training required in § 61.99(a)(1) of this part cannot be accomplished without flying over water for more than 10 nautical miles from the nearest shoreline need not comply with the requirements of that section. However, if other airports that permit civil operations are available to which a flight may be made without flying over water for more than 10 nautical miles from the nearest shoreline, the applicant must show completion of a dual flight between two airports, which must include three landings at the other airport.
. An applicant who complies with paragraph (a) of this section and meets all requirements for the issuance of a recreational pilot certificate, except the requirements of § 61.99(a)(1) of this part, will be issued a pilot certificate with an endorsement containing the following limitation, “Passenger carrying prohibited on flights more than 10 nautical miles from (the appropriate island).” The limitation may be subsequently amended to include another island if the applicant complies with the requirements of paragraph (a) of this section for another island.
. Upon meeting the requirements of § 61.99(a)(1) of this part, the applicant may have the limitation(s) in paragraph (b) of this section removed.

## § 61.101 - Recreational pilot privileges and limitations.

[loweralpha]
. A person who holds a recreational pilot certificate may:
[arabic]
.. Carry no more than one passenger; and
.. Not pay less than the pro rata share of the operating expenses of a flight with a passenger, provided the expenses involve only fuel, oil, airport expenses, or aircraft rental fees.
. A person who holds a recreational pilot certificate may act as pilot in command of an aircraft on a flight within 50 nautical miles from the departure airport, provided that person has—
[arabic]
.. Received ground and flight training for takeoff, departure, arrival, and landing procedures at the departure airport;
.. Received ground and flight training for the area, terrain, and aids to navigation that are in the vicinity of the departure airport;
.. Been found proficient to operate the aircraft at the departure airport and the area within 50 nautical miles from that airport; and
.. Received from an authorized instructor a logbook endorsement, which is carried in the person's possession in the aircraft, that permits flight within 50 nautical miles from the departure airport.
. A person who holds a recreational pilot certificate may act as pilot in command of an aircraft on a flight that exceeds 50 nautical miles from the departure airport, provided that person has—
[arabic]
.. Received ground and flight training from an authorized instructor on the cross-country training requirements of subpart E of this part that apply to the aircraft rating held;
.. Been found proficient in cross-country flying; and
.. Received from an authorized instructor a logbook endorsement, which is carried on the person's possession in the aircraft, that certifies the person has received and been found proficient in the cross-country training requirements of subpart E of this part that apply to the aircraft rating held.
. A person who holds a recreational pilot certificate may act as pilot in command of an aircraft in Class B, C, and D airspace, at an airport located in Class B, C, or D airspace, and to, from, through, or at an airport having an operational control tower, provided that person has—
[arabic]
.. Received and logged ground and flight training from an authorized instructor on the following aeronautical knowledge areas and areas of operation, as appropriate to the aircraft rating held:
[lowerroman]
... The use of radios, communications, navigation system and facilities, and radar services.
... Operations at airports with an operating control tower to include three takeoffs and landings to a full stop, with each landing involving a flight in the traffic pattern at an airport with an operating control tower.
... Applicable flight rules of part 91 of this chapter for operations in Class B, C, and D airspace and air traffic control clearances;
.. Been found proficient in those aeronautical knowledge areas and areas of operation specified in paragraph (d)(1) of this section; and
.. Received from an authorized instructor a logbook endorsement, which is carried on the person's possession or readily accessible in the aircraft, that certifies the person has received and been found proficient in those aeronautical knowledge areas and areas of operation specified in paragraph (d)(1) of this section.
. Except as provided in paragraphs (d) and (i) of this section, a recreational pilot may not act as pilot in command of an aircraft—
[arabic]
.. That is certificated—
[lowerroman]
... For more than four occupants;
... With more than one powerplant;
... With a powerplant of more than 180 horsepower, except aircraft certificated in the rotorcraft category; or
... With retractable landing gear;
.. That is classified as a multiengine airplane, powered-lift, glider, airship, balloon, powered parachute, or weight-shift-control aircraft;
.. That is carrying a passenger or property for compensation or hire;
.. For compensation or hire;
.. In furtherance of a business;
.. Between sunset and sunrise;
.. In Class A, B, C, and D airspace, at an airport located in Class B, C, or D airspace, or to, from, through, or at an airport having an operational control tower;
.. At an altitude of more than 10,000 feet MSL or 2,000 feet AGL, whichever is higher;
.. When the flight or surface visibility is less than 3 statute miles;
.. Without visual reference to the surface;
.. On a flight outside the United States, unless authorized by the country in which the flight is conducted;
.. To demonstrate that aircraft in flight as an aircraft salesperson to a prospective buyer;
.. That is used in a passenger-carrying airlift and sponsored by a charitable organization; and
.. That is towing any object.
. A recreational pilot may not act as a pilot flight crewmember on any aircraft for which more than one pilot is required by the type certificate of the aircraft or the regulations under which the flight is conducted, except when:
[arabic]
.. Receiving flight training from a person authorized to provide flight training on board an airship; and
.. No person other than a required flight crewmember is carried on the aircraft.
. A person who holds a recreational pilot certificate, has logged fewer than 400 flight hours, and has not logged pilot-in-command time in an aircraft within the 180 days preceding the flight shall not act as pilot in command of an aircraft until the pilot receives flight training and a logbook endorsement from an authorized instructor, and the instructor certifies that the person is proficient to act as pilot in command of the aircraft. This requirement can be met in combination with the requirements of §§ 61.56 and 61.57 of this part, at the discretion of the authorized instructor.
. A recreational pilot certificate issued under this subpart carries the notation, “Holder does not meet ICAO requirements.”
[lowerroman]
.. For the purpose of obtaining additional certificates or ratings while under the supervision of an authorized instructor, a recreational pilot may fly as the sole occupant of an aircraft:
              
[arabic]
... For which the pilot does not hold an appropriate category or class rating;
... Within airspace that requires communication with air traffic control; or
... Between sunset and sunrise, provided the flight or surface visibility is at least 5 statute miles.

(j) In order to fly solo as provided in paragraph (i) of this section, the recreational pilot must meet the appropriate aeronautical knowledge and flight training requirements of § 61.87 for that aircraft. When operating an aircraft under the conditions specified in paragraph (i) of this section, the recreational pilot shall carry the logbook that has been endorsed for each flight by an authorized instructor who:

[arabic]
. Has given the recreational pilot training in the make and model of aircraft in which the solo flight is to be made;
. Has found that the recreational pilot has met the applicable requirements of § 61.87; and
. Has found that the recreational pilot is competent to make solo flights in accordance with the logbook endorsement.

