# Airport Traffic Control Towers
:toc:

## § 170.11 - Scope.

This subpart sets forth establishment and discontinuance criteria for Airport Traffic Control Towers.

## § 170.13 - Airport Traffic Control Tower (ATCT) establishment criteria.

[loweralpha]
. The following criteria along with general facility establishment standards must be met before an airport can qualify for an ATCT:
[arabic]
.. The airport, whether publicly or privately owned, must be open to and available for use by the public as defined in the Airport and Airway Improvement Act of 1982;
.. The airport must be recognized by and contained within the National Plan of Integrated Airport Systems;
.. The airport owners/authorities must have entered into appropriate assurances and covenants to guarantee that the airport will continue in operation for a long enough period to permit the amortization of the ATCT investment;
.. The FAA must be furnished appropriate land without cost for construction of the ATCT; and
.. The airport must meet the benefit-cost ratio criteria specified herein utilizing three consecutive FAA annual counts and projections of future traffic during the expected life of the tower facility. (An FAA annual count is a fiscal year or a calendar year activity summary. Where actual traffic counts are unavailable or not recorded, adequately documented FAA estimates of the scheduled and nonscheduled activity may be used.)
. An airport meets the establishment criteria when it satisfies paragraphs (a)(1) through (a)(5) of this section and its benefit-cost ratio equals or exceeds one. As defined in § 170.3 of this part, the benefit-cost ratio is the ratio of the present value of the ATCT life cycle benefits (BPV) to the present value of ATCT life cycle costs (CPV).
              
. The satisfaction of all the criteria listed in this section does not guarantee that the airport will receive an ATCT.

## § 170.15 - ATCT discontinuance criteria.

An ATCT will be subject to discontinuance when the continued operation and maintenance costs less termination costs (CMPV) of the ATCT exceed the present value of its remaining life-cycle benefits (BPV):
              

