# Nondiscrimination in Airport Aid Program
:toc:

## § 152.401

### Applicability.

. This subpart is applicable to all grantees and other covered organizations under this part, and implements the requirements of section 30 of the Airport and Airway Development Act of 1970, which provides:
              
. Each grantee, covered organization, or covered suborganization under this part shall negotiate reformation of any contract, subcontract, lease, sublease, or other agreement to include any appropriate provision necessary to effect compliance with this subpart by July 17, 1980.

## § 152.403

### Definitions.

As used in this subpart—

*AADA* means the Airport and Airway Development Act of 1970, as amended (49 U.S.C. 1701 *et seq.*).

*Affirmative action plan* means a set of specific and result-oriented procedures to which a sponsor, planning agency, state, or the aviation related activity on an airport commits itself to achieve equal employment opportunity.

*Airport development* means—(1) Any work involved in constructing, improving, or repairing a public airport or portion thereof, including the removal, lowering, relocation, and marking and lighting of airport hazards, and including navigation aids used by aircraft landing at, or taking off from, a public airport, and including safety equipment required by rule or regulation for certification of the airport under section 612 of the Federal Aviation Act of 1958, and security equipment required of the sponsor by the Secretary by rule or regulation for the safety and security of persons and property on the airport, and including snow removal equipment, and including the purchase of noise suppressing equipment, the construction of physical barriers, and landscaping for the purpose of diminishing the effect of aircraft noise on any area adjacent to a public airport;

(2) Any acquisition of land or of any interest therein, or of any easement through or other interest in airspace, including land for future airport development, which is necessary to permit any such work or to remove or mitigate or prevent or limit the establishment of, airport hazards; and

(3) Any acquisition of land or of any interest therein necessary to insure that such land is used only for purposes which are compatible with the noise levels of the operation of a public airport.

*Aviation related activity* means a commercial enterprise—(1) Which is operated on the airport pursuant to an agreement with the grantee or airport operator or to a derivative subagreement;

(2) Which employs persons on the airport; and

(3) Which—(i) Is related primarily to the aeronautical activities on the airport;

(ii) Provides goods or services to the public which is attracted to the airport by aeronautical activities;

(iii) Provides services or supplies to other aeronautical related or public service airport businesses or to the airport; or

(iv) Performs construction work on the airport.

*Aviation workforce* includes, with respect to grantees, each person employed by the grantee on an airport or, for an aviation purpose, off the airport.

*Covered organization* means a grantee, a subgrantee, or an aviation related activity.

*Covered suborganization* is a subgrantee or sub-aviation related activity, of a covered organization.

*Department* means the United States Department of Transportation;

*Grant* means Federal financial assistance in the form of funds provided to a sponsor, planning agency, or state under this part;

*Grantee* means the recipient of a grant.

*Minority* means a person who is—(1) Black and not of Hispanic origin: A person having origins in any of the black racial groups of Africa;

(2) Hispanic: A person of Mexican, Puerto Rican, Cuban, Central or South American or other Spanish culture or origin, regardless of race;

(3) Asian or Pacific Islander: A person having origins in any or the original peoples of the Far East, Southeast Asia, the Indian subcontinent, or the Pacific Islands, including, but not limited to China, Japan, Korea, the Philippine Islands, and Samoa; or

(4) American Indian or Alaskan Native: A person having origins in any of the original peoples of North America who maintains cultural identification through tribal affiliation or community recognition.

*Planning agency* means any planning agency designated by the Secretary which is authorized by the laws of the State or States (including the Commonwealth of Puerto Rico, the Virgin Islands, American Samoa, the Trust Territory of the Pacific Islands, and Guam) or political subdivisions concerned to engage in areawide planning for the area in which assistance under this part is to be used;
              

*Secretary* means the Secretary of Transportation or an authorized representative of the Secretary within the Department of Transportation;

*SMSA* means Standard Metropolitan Statistical Area.

*Sponsor* means any public agency that, either individually or jointly with one or more other public agencies, submits to the Administrator, in accordance with this part, an application for financial assistance, or that conducts a project for airport development or airport master planning, funded under this part;

*Underutilization* means having fewer minorities or women in a particular job group than would reasonable be expected from their availability in—

(1) The SMSA; or

(2) In the absence of a defined SMSA, in the counties contiguous to the employer's location, or the location where the work is to be performed, and in the areas from which persons may reasonably be expected to commute.

## § 152.405

### Assurances.

The following assurances shall be included in each application for financial assistance under this part:

. *Assurance.* The grantee assures that it will undertake an affirmative action program, as required by 14 CFR part 152, subpart E, to ensure that no person shall, on the grounds of race, creed, color, national origin, or sex, be excluded from participating in any employment, contracting, or leasing activities covered in 14 CFR part 152, subpart E. The grantee assures that no person shall be excluded, on these grounds, from participating in or receiving the services or benefits of any program or activity covered by this subpart. The grantee assures that it will require that its covered organizations provide assurances to the grantee that they similarly will undertake affirmative action programs and that they will require assurances from their suborganizations, as required by 14 CFR part 152, subpart E, to the same effect.
. *Assurance.* The grantee agrees to comply with any affirmative action plan or steps for equal employment opportunity required by 14 CFR part 152, subpart E, as part of the affirmative action program, and by any Federal, State, or local agency or court, including those resulting from a conciliation agreement, a consent decree, court order, or similar mechanism. The grantee agrees that State or local affirmative action plans will be used in lieu of any affirmative action plan or steps required by 14 CFR part 152, subpart E, only when they fully meet the standards set forth in 14 CFR 152.409. The grantee agrees to obtain a similar assurance from its covered organizations, and to cause them to require a similar assurance of their covered suborganizations, as required by 14 CFR part 152, subpart E.

## § 152.407

### Affirmative action plan: General.

. Except as provided in paragraph (b) of this section, each of the following shall have an affirmative action plan that meets the requirements of § 152.409 and is kept on file for review by the FAA Office of Civil Rights:
.. Each sponsor who employs 50 or more employees in its aviation workforce.
.. Each planning Agency which employs 50 or more employees in its agency for aviation purposes.
.. Each state political division, administering a grant under the AADA to develop standards for airport development at general aviation airports, which employs 50 or more employees in its aviation workforce.
. A grantee is in compliance with paragraph (a) of this section, if it is subject to, and keeps on file for review by the FAA Office of Civil Rights, one of the following:
.. An affirmative action plan acceptable to another Federal agency.
.. An affirmative action plan for a State or local agency that the covered organization certifies meets the standards in § 152.409.
.. A conciliation agreement, consent decree, or court order which provides short and long-range goals for equal employment opportunity similar to those which would be established in an affirmative action plan meeting the standards in § 152.409.
. Each sponsor shall require each aviation related activity (other than construction contractors) which employs 50 or more employees on the airport to prepare, and keep on file for review by the FAA Office of Civil Rights, an affirmative action plan developed in accordance with the standards in § 152.409, unless the activity is subject to one of the mechanisms described in paragraphs (b) (1) through (3) of this section.
. Each sponsor shall require each aviation related activity described in paragraph (c) of this section to similarly require each of its covered suborganizations (other than construction contractors) which employs 50 or more employees on the airport to prepare, and to keep on file for review by the FAA Office of Civil Rights, an affirmative action plan developed in accordance with the standards in § 152.409, unless the suborganization is subject to one of the mechanisms described in paragraphs (b) (1) through (3) of this section.

## § 152.409

### Affirmative action plan standards.

. Each affirmative action plan required by this subpart shall be developed in accordance with the following:
.. An analysis of the employer's aviation workforce which groups employees into the following job categories:
... Officials and managers.
... Professionals.
... Technicians.
... Sales workers.
... Office and clerical workers.
... Craft workers (skilled).
... Operatives (semi-skilled).
... Laborers (unskilled).
... Service workers.
.. A comparison separately made of the percent of minorities and women in the employer's present aviation workforce (in each of the job categories listed in paragraph (a)(1) of this section) with the percent of minorities and women in each of those categories in the total workforce located in the SMSA, or, in the absence of an SMSA, in the counties contiguous to the employer's location or the location where the work is to be performed and in the areas from which persons may reasonably be expected to commute. This data on the total workforce of the applicable area will be supplied to grantees by the FAA. Grantees shall make this data available to the other organizations covered by this subpart. The comparison for minorities must be made only when minorities constitute at least 2 percent of the total workforce in the geographical area used for the comparison.
.. A comparison, for the aviation workforce, of the total number of applicants and persons hired with the total number of minority and female applicants, and minorities and females hired, for the past year. Where this data is unavailable, the employer shall establish and maintain a system to provide the data, and shall make the comparison 120 days after establishing the data system.
.. Where the percentage of minorities and women in the employer's aviation workforce, in each job category, is less than the minority and female percentage in any job category in the workforce of the geographical area used, an analysis, based on the comparison required by paragraph (a)(3) of this section, determining whether any of the following exists:
... Insufficient flow of minority and female applicants.
... Disparate rejection of minority and female applicants. The FAA generally considers disparate rejection to exist whenever a selection rate for any race, sex, or ethnic group is less than 80 percent of the rate for the race, sex, or ethnic group with the highest selection rate.
. Each affirmative action plan required by this part shall be implemented through an action-oriented program with goals and timetables designed to eliminate obstacles to equal opportunity for women and minorities in recruitment and hiring, which shall include, but not be limited to:
.. Where disparate rejection of minority and female applicants is indicated by the analysis required by paragraph (a)(4) of this section, validation of those portions of the testing or selection procedures which cause the disparity in accordance with the “Uniform Guidelines on Employee Selection” (43 FR 38290; August 25, 1978), within 120 days of the analysis.
              
.. Where testing or selection procedures cannot be validated, discontinuation of their use.
.. Where an insufficient flow of minority and female applicants (less than the percentage available) is indicated by the analysis required by paragraph (a)(4) of this section, good faith efforts to increase the flow of minority and female applicants through the following steps, as appropriate:
... Development or reaffirmation of an equal opportunity policy and dissemination of that policy internally and externally.
... Contact with minority and women's organizations, schools with predominant minority or female enrollments, and other recruitment sources for minorities and women.
... Encouragement of State and local employment agencies, unions, and other recruiting sources to ensure that minorities and women have ample information on, and opportunity to apply for, vacancies and to participate in examinations.
... Participation in special employment programs such as Co-operative Education Programs with predominantly minority and women's colleges, “After School” or Work Study programs, and Summer Employment.
... Participation in “Job Fairs.”
... Participation of minority and female employees in Career Days, Youth Motivation Programs, and counseling and related activities in the community.
... Encouragement of minority and female employees to refer applicants.
... Motivation, training, and employment programs for minority and female hard-core unemployed.

## § 152.411

### Affirmative action steps.

. Each grantee which is not described in § 152.407(a) and is not subject to an affirmative action plan, regulatory goals and timetables, or other mechanism providing for short and long-range goals for equal employment opportunity, shall make good faith efforts to recruit and hire minorities and women for its aviation workforce as vacancies occur, by taking the affirmative action steps in § 152.409(b)(3), as follows:
.. If it has 15 or more employees in its aviation workforce or employed for aviation purposes, by taking the affirmative action steps in § 152.409(b)(3), as appropriate; or
.. If it has less than 15 employees in its aviation workforce or employed for aviation purposes, by taking the affirmative action steps in § 152.409(b)(3) (i) and (ii), as appropriate.
. Except as provided in paragraph (c) of this section, each sponsor shall require each of its aviation related activities on its airport, that is not subject to an affirmative action plan, regulatory goals and timetables, or other mechanism which provides short and long-range goals for equal employment opportunity, to take affirmative action steps and cause them to similarly require affirmative action steps of their covered suborganizations, as follows:
.. Each aviation related activity or covered suborganization with less than 50 but more than 14 employees, must take the affirmative action steps enumerated in § 152.409(b)(3), as appropriate.
.. Each aviation related activity or covered suborganization with less than 15 employees, must take the affirmative action steps enumerated in § 152.409(b)(3) (i) and (ii), as appropriate.
. Each sponsor shall require each construction contractor, that has a contract of $10,000 or more on its airport and that is not subject to an affirmative action plan, regulatory goals or timetables, or other mechanism which provides short and long-range goals for equal employment opportunity, to take the following affirmative action steps:
.. The contractor must establish and maintain a current list of minority and female recruitment sources; provide written notification to these recruitment sources and to community organizations when employment opportunities are available; and maintain a record of each organization's response.
.. The contractor must maintain a current file of the names, addresses, and telephone numbers of each minority and female walk-in applicant and each referral from a union, a recruitment source, or community organization and the action taken with respect to each individual. Where an individual is sent to the union hiring hall for referral, but not referred back to the contractor, or, if referred, not employed by the contractor, this shall be documented. The documentation shall include an explanation of, and information on, any additional actions that the contractor may have taken.
.. The contractor must disseminate its equal employment opportunity policy internally—
... By providing notice of the policy to unions and training programs;
... By including it in policy manuals and collective bargaining agreements;
... By publicizing it in the company newspaper, report, or other publication; and
... By specific review of the policy with all management personnel and with all employees at least once a year.
.. The contractor must disseminate the contractors's equal employment opportunity policy externally—
... By stating it in each employment advertisement in the news media, including news media with high minority and female readership; and
... By providing written notification to, or participating in discussions with, other contractors and subcontractors with whom the contractor does business.
.. The contractor must direct its recruitment efforts to minority and female organizations, to schools with minority and female students, and to organizations which recruit and train minorities and women, in the contractor's recruitment area.
.. The contractor must encourage present minority and female employees to recruit other minorities and women.
.. The contractor must, where possible, provide after school, summer, and vacation employment to minority and female youth.
. Each sponsor shall require each of its prime construction contractors on its airport, with a contract of $10,000 or more, to require each of the contractor's subcontractors on the airport to comply with the affirmative action steps in paragraph (c) of this section, with which it does not already comply, unless the subcontractor is subject to an affirmative action plan, regulatory goals or timetables, or other mechanism which provides short and long-range goals for equal employment opportunity, or the subcontract is less than $10,000.

## § 152.413

### Notice requirement.

Each grantee shall give adequate notice to employees and applicants for employment, through posters provided by the Secretary, that the FAA is committed to the requirements of section 30 of the AADA, to ensure that no person shall, on the grounds of race, creed, color, national origin, or sex, be excluded from participating in any activity conducted with funds authorized under this part.

## § 152.415

### Records and reports.

. Each grantee shall keep on file for a period of three years or for the period during which the Federal financial assistance is made available, whichever is longer, reports (other than those transmitted to the FAA), records, and affirmative action plans, if applicable, that will enable the FAA Office of Civil Rights to ascertain if there has been and is compliance with this subpart.
. Each sponsor shall require its covered organizations to keep on file, for the period set forth in paragraph (a) of this section, reports (other than those submitted to the FAA), records, and affirmative action plans, if applicable, that will enable the FAA Office of Civil Rights to ascertain if there has been and is compliance with this subpart, and shall cause them to require their covered suborganizations to keep similar records as applicable.
. Each grantee, employing 15 or more person, shall annually submit to the FAA a compliance report on a form provided by the FAA and a statistical report on a Form EEO-1 of the Equal Employment Opportunity Commission (EEOC) or any superseding EEOC form. If a grantee already is submitting a Form EEO-1 to another agency, the grantee may submit a copy of that form to the FAA as its statistical report. The information provided shall include goals and timetables, if established in compliance with the requirements of § 152.409 or with the requirements of another Federal agency or a State or local agency.
. Each sponsor shall—
              
.. Require each of its aviation-related activities (except construction contractors), employing 15 or more persons, to annually submit to the sponsor the reports required by paragraph (c) of this section, on the same basis as stated in paragraph (c) of this section, and shall cause each aviation-related activity to require its covered suborganizations, with 15 or more employees, to annually submit the reports required by paragraph (c) of this section through the prime organization to the sponsor, for transmittal by the sponsor to the FAA.
.. Annually collect from its aviation related activities employing less than 15 employees, and transmit to the FAA an aggregate employment report, that includes the employment of sponsors with less than 15 employees, on an EEO-1 or any superseding EEOC form.
. Each sponsor shall require each of its construction contractors on its airport, with a contract of $10,000 or more, which is not subject to E.O. 11246 and the regulations of the Department of Labor (DOL), to submit to the sponsor, at the conclusion of the project, a compliance report on a form provided by the FAA and a statistical report on a DOL Form 257 or any superseding DOL form. For projects exceeding six months, the sponsor shall require a midway compliance report. The sponsor shall submit these reports to the FAA.
. Each sponsor shall cause each of its construction contractors on its airport to require each of the contractor's subcontractors, with a subcontract of $10,000 or more, which are not subject to E.O. 11246 and the regulations of the DOL, to submit the reports required by paragraph (e) of this section to the prime contractor for submission to the sponsor. The sponsor shall transmit these reports to the FAA.
. Each organization required to prepare an affirmative action plan for the FAA under this subpart shall update it annually and as changed circumstances require. Each organization that has prepared a plan in compliance with the requirements of another Federal agency or a State or local agency, shall update it in accordance with the requirements of that agency.

## § 152.417

### Monitoring employment.

. Each grantee shall allow the FAA Office of Civil Rights to monitor its equal employment opportunity compliance with this subpart through on-site reviews and desk audits. Reviews or audits will include the records submitted under § 152.415.
. As it deems necessary, the FAA Office of Civil Rights will conduct on-site or desk audits of covered aviation related activities on airports.

## § 152.419

### Minority business.

Each person subject to this subpart is required to comply with the Minority Business Enterprise Regulations of the Department.

## § 152.421

### Public accommodations, services, and benefits.

Requirements relating to the provision of public accommodations, services, and other benefits to beneficiaries under Title VI of the Civil Rights Act of 1964 (42 U.S.C. 2000d *et seq.*) and part 21 of the regulations of the Office of the Secretary of Transportation (49 CFR part 21) implementing Title VI are made applicable, where appropriate, to nondiscrimination and affirmative action on the basis of sex or creed, and shall be complied with by each applicant for assistance and each grantee.

## § 152.423

### Investigation and enforcement.

. *Complaints.* Any person who believes that he or she has been subjected to discrimination prohibited by this subpart may personally, or through a representative, file a complaint with the Director of the Departmental Office of Civil Rights. A complaint must be in writing and filed not later than 180 days after the date of the alleged discrimination, unless the time for filing is extended by the Director.
. *Investigations and informal resolutions.* The Departmental Office of Civil Rights will make a prompt investigation whenever a complaint, compliance review, report, or any other information indicates a possible failure to comply with this subpart. The procedures in 49 CFR part 21, augmented as appropriate by the investigative procedures of part 13 of this chapter, will be followed, except that—
              
.. Compliance with a regulation of the Department applicable to minority business enterprise will be investigated and enforced through the procedures contained in that regulation; and
.. Except as provided in paragraph (c) of this section, allegations of noncompliance with regulations governing equal employment opportunity of another Federal agency or a State or local agency, will be referred, for investigation and enforcement, to the Federal agency or, in the discretion of the Departmental Office of Civil Rights, to the State or local agency.
. When the FAA (under section 30 of the AADA) and another Federal agency, a referral agency recognized by the Equal Employment Opportunity Commission, or a court have concurrent jurisdiction over a matter—
.. If the other agency or court makes a finding on the record that noncompliance or discrimination has occurred, the FAA will accept the finding, and determine what sanctions or remedies are appropriate under section 30 as a result of the finding, after permitting the party against whom the finding was made to be heard on the determination of the sanctions or remedies; or
.. If it appears that delay, through referral to another agency, will result in the continued expenditure of Federal funds under this part without compliance with this subpart, the Secretary may—
... Investigate the matter;
... Make a determination as to compliance with section 30; and
... Impose appropriate sanctions and remedies.
. Nothing in this section shall preclude the Director of the Departmental Office of Civil Rights from initiating an investigation when it appears that the investigation of the complaint may reveal a pattern or practice of discrimination or noncompliance with the requirements of this subpart in the employment practices of a grantee or other covered organization.

## § 152.425

### Effect of subpart.

Nothing contained in this subpart diminishes or supersedes the obligations imposed by Title VI of the Civil Rights Act of 1964 (42 U.S.C. 2000d), Executive Order 11246 (42 U.S.C. 2000e (note)), or any other Federal law or Executive Order relating to civil rights.

