# Suspension and Termination of Grants
:toc:

## § 152.501

### Applicability.

This subpart contains procedures for suspending or terminating grants for airport development projects and airport planning.

## § 152.503

### Suspension of grant.

. If the sponsor or planning agency fails to comply with the conditions of the grant, the FAA may, by written notice to the sponsor or planning agency, suspend the grant and withhold further payments pending—
.. Corrective action by the sponsor or planning agency; or
.. A decision to terminate the grant.
. Except as provided in paragraph (c), after receipt of notice of suspension, the sponsor or planning agency may not incur additional obligations of grant funds during the suspension.
. All necessary and proper costs that the sponsor or planning agency could not reasonably avoid during the period of suspension will be allowed, if those costs are in accordance with appendix C of this part.

## § 152.505

### Termination for cause.

. If the sponsor or planning agency fails to comply with the conditions of the grant, the FAA may, by written notice to the sponsor or planning agency, terminate the grant in whole, or in part.
. The notice of termination will contain—
.. The reasons for the termination, and
.. The effective date of termination.
. After receipt of the notice of termination, the sponsor or planning agency may not incur additional obligations of grant funds.
. Payments to be made to the sponsor or planning agency, or recoveries of payments by the FAA, under the grant shall be in accordance with the legal rights and liabilities of the parties.

## § 152.507

### Termination for convenience.

. When the continuation of the project would not produce beneficial results commensurate with the further expenditure of funds, the grant may be terminated in whole, or in part, upon mutual agreement of the FAA and the sponsor or planning agency.
. If an agreement to terminate is made, the sponsor or planning agency—
.. May not incur new obligations for the terminated portion after the effective date; and
.. Shall cancel as many obligations, relating to the terminated portion, as possible.
. The sponsor or planning agency is allowed full credit for the Federal share of the noncancellable obligations that were properly incurred by the sponsor before the termination.

## § 152.509

### Request for reconsideration.

If a grant is suspended or terminated under this subpart, the sponsor or planning agency may request the Administrator to reconsider the suspension or termination.

