# Notice Requirements for Stage 2 Restrictions
:toc:

## § 161.201

### Scope.

. This subpart applies to:
.. An airport imposing a noise or access restriction on the operation of Stage 2 aircraft, but not Stage 3 aircraft, proposed after October 1, 1990.
.. An airport imposing an amendment to a Stage 2 restriction, if the amendment is proposed after October 1, 1990, and reduces or limits Stage 2 aircraft operations (compared to the restriction that it amends) or affects aircraft safety.
. This subpart does not apply to an airport imposing a Stage 2 restriction specifically exempted in § 161.7 or a Stage 2 restriction contained in an agreement as long as the restriction is not enforced against aircraft operators that are not parties to the agreement.

## § 161.203

### Notice of proposed restriction.

. An airport operator may not implement a Stage 2 restriction within the scope of § 161.201 unless the airport operator provides an analysis of the proposed restriction, prepared in accordance with § 161.205, and a public notice and opportunity for comment as prescribed in this subpart. The notice and analysis required by this subpart shall be completed at least 180 days prior to the effective date of the restriction.
. Except as provided in § 161.211, an airport operator must publish a notice of the proposed restriction in an areawide newspaper or newspapers that either singly or together has general circulation throughout the airport noise study area; post a notice in the airport in a prominent location accessible to airport users and the public; and directly notify in writing the following parties:
.. Aircraft operators providing scheduled passenger or cargo service at the airport; operators of aircraft based at the airport; potential new entrants that are known to be interested in serving the airport; and aircraft operators known to be routinely providing nonscheduled service that may be affected by the proposed restriction;
.. The Federal Aviation Administration;
.. Each Federal, state, and local agency with land-use control jurisdiction within the airport noise study area;
.. Fixed-base operators and other airport tenants whose operations may be affected by the proposed restriction; and
.. Community groups and business organizations that are known to be interested in the proposed restriction.
. Each notice provided in accordance with paragraph (b) of this section shall include:
.. The name of the airport and associated cities and states;
.. A clear, concise description of the proposed restriction, including a statement that it will be a mandatory Stage 2 restriction, and where the complete text of the restriction, and any sanctions for noncompliance, are available for public inspection;
.. A brief discussion of the specific need for, and goal of, the restriction;
.. Identification of the operators and the types of aircraft expected to be affected;
              
.. The proposed effective date of the restriction, the proposed method of implementation (e.g., city ordinance, airport rule, lease), and any proposed enforcement mechanism;
.. An analysis of the proposed restriction, as required by § 161.205 of this subpart, or an announcement of where the analysis is available for public inspection;
.. An invitation to comment on the proposed restriction and analysis, with a minimum 45-day comment period;
.. Information on how to request copies of the complete text of the proposed restriction, including any sanctions for noncompliance, and the analysis (if not included with the notice); and
.. The address for submitting comments to the airport operator, including identification of a contact person at the airport.
. At the time of notice, the airport operator shall provide the FAA with a full text of the proposed restriction, including any sanctions for noncompliance.
. The Federal Aviation Administration will publish an announcement of the proposed Stage 2 restriction in the *Federal Register.*
              

## § 161.205

### Required analysis of proposed restriction and alternatives.

. Each airport operator proposing a noise or access restriction on Stage 2 aircraft operations shall prepare the following and make it available for public comment:
.. An analysis of the anticipated or actual costs and benefits of the proposed noise or access restriction;
.. A description of alternative restrictions; and
.. A description of the alternative measures considered that do not involve aircraft restrictions, and a comparison of the costs and benefits of such alternative measures to costs and benefits of the proposed noise or access restriction.
. In preparing the analyses required by this section, the airport operator shall use the noise measurement systems and identify the airport noise study area as specified in §§ 161.9 and 161.11, respectively; shall use currently accepted economic methodology; and shall provide separate detail on the costs and benefits of the proposed restriction with respect to the operations of Stage 2 aircraft weighing less than 75,000 pounds if the restriction applies to this class. The airport operator shall specify the methods used to analyze the costs and benefits of the proposed restriction and the alternatives.
. The kinds of information set forth in § 161.305 are useful elements of an adequate analysis of a noise or access restriction on Stage 2 aircraft operations.

## § 161.207

### Comment by interested parties.

Each airport operator shall establish a public docket or similar method for receiving and considering comments, and shall make comments available for inspection by interested parties upon request. Comments must be retained as long as the restriction is in effect.

## § 161.209

### Requirements for proposal changes.

. Each airport operator shall promptly advise interested parties of any changes to a proposed restriction, including changes that affect noncompatible land uses, and make available any changes to the proposed restriction and its analysis. Interested parties include those that received direct notice under § 161.203(b), or those that were required to be consulted in accordance with the procedures in § 161.211 of this part, and those that have commented on the proposed restriction.
. If there are substantial changes to the proposed restriction or the analysis during the 180-day notice period, the airport operator shall initiate new notice following the procedures in § 161.203 or, alternatively, the procedures in § 161.211. A substantial change includes, but is not limited to, a proposal that would increase the burden on any aviation user class.
. In addition to the information in § 161.203(c), new notice must indicate that the airport operator is revising a previous notice, provide the reason for making the revision, and provide a new effective date (if any) for the restriction. The effective date of the restriction must be at least 180 days after the date the new notice and revised analysis are made available for public comment.

## § 161.211

### Optional use of 14 CFR part 150 procedures.

. An airport operator may use the procedures in part 150 of this chapter, instead of the procedures described in §§ 161.203(b) and 161.209(b), as a means of providing an adequate public notice and comment opportunity on a proposed Stage 2 restriction.
. If the airport operator elects to use 14 CFR part 150 procedures to comply with this subpart, the operator shall:
.. Ensure that all parties identified for direct notice under § 161.203(b) are notified that the airport's 14 CFR part 150 program will include a proposed Stage 2 restriction under part 161, and that these parties are offered the opportunity to participate as consulted parties during the development of the 14 CFR part 150 program;
.. Provide the FAA with a full text of the proposed restriction, including any sanctions for noncompliance, at the time of the notice;
.. Include the information in § 161.203 (c)(2) through (c)(5) and 161.205 in the analysis of the proposed restriction for the part 14 CFR part 150 program;
.. Wait 180 days following the availability of the above analysis for review by the consulted parties and compliance with the above notice requirements before implementing the Stage 2 restriction; and
.. Include in its 14 CFR part 150 submission to the FAA evidence of compliance with paragraphs (b)(1) and (b)(4) of this section, and the analysis in paragraph (b)(3) of this section, together with a clear identification that the 14 CFR part 150 program includes a proposed Stage 2 restriction under part 161.
. The FAA determination on the 14 CFR part 150 submission does not constitute approval or disapproval of the proposed Stage 2 restriction under part 161.
. An amendment of a restriction may also be processed under 14 CFR part 150 procedures in accordance with this section.

## § 161.213

### Notification of a decision not to implement a restriction.

If a proposed restriction has been through the procedures prescribed in this subpart and the restriction is not subsequently implemented, the airport operator shall so advise the interested parties. Interested parties are described in § 161.209(a).

