# Application and Approval
:toc:

## § 158.20

### Submission of required documents.

. Letters and reports required by this part may be transmitted to the appropriate recipient (the public agency, air carrier, and/or the FAA) via e-mail, courier, facsimile, or U.S. Postal Service.
.. Documents sent electronically to the FAA must be prepared in a format readable by the FAA. Interested parties can obtain the format at their local FAA Airports Office.
.. Any transmission to FAA Headquarters, using regular U.S. Postal Service, is subject to inspection that may result in delay and damage due to the security process.
. Once the database development is completed with air carrier capability, public agencies and air carriers may use the FAA's national PFC database to post their required quarterly reports, and, in that case, do not have to distribute the reports in any other way.

## § 158.21

### General.

This subpart specifies the consultation and application requirements under which a public agency may obtain approval to impose a PFC and use PFC revenue on a project. This subpart also establishes the procedure for the Administrator's review and approval of applications and amendments and establishes requirements for use of excess PFC revenue.

## § 158.23

### Consultation with air carriers and foreign air carriers.

. *Notice by public agency.* A public agency must provide written notice to air carriers and foreign air carriers having a significant business interest at the airport where the PFC is proposed. A public agency must provide this notice before the public agency files an application with the FAA for authority to impose a PFC under § 158.25(b). In addition, public agencies must provide this notice before filing an application with the FAA for authority to use PFC revenue under § 158.25(c). Public agencies must also provide this notice before filing a notice of intent to impose and/or use a PFC under § 158.30. Finally, a public agency must provide this notice before filing a request to amend the FAA's decision with respect to an approved PFC as discussed in § 158.37(b)(1). The notice shall include:
.. Descriptions of projects being considered for funding by PFC's;
.. The PFC level for each project, the proposed charge effective date, the estimated charge expiration date, and the estimated total PFC revenue;
.. For a request by a public agency that any class or classes of carriers not be required to collect the PFC—
... The designation of each such class,
... The names of the carriers belonging to each such class, to the extent the names are known,
... The estimated number of passengers enplaned annually by each such class, and
... The public agency's reasons for requesting that carriers in each such class not be required to collect the PFC; and
.. Except as provided in § 158.25(c)(2), the date and location of a meeting at which the public agency will present such projects to air carriers and foreign air carriers operating at the airport.
. *Meeting.* The meeting required by paragraph (a)(4) of this section shall be held no sooner than 30 days nor later than 45 days after issuance of the written notice required by paragraph (a) of this section. At or before the meeting, the public agency shall provide air carriers and foreign air carriers with—
.. A description of projects;
.. An explanation of the need for the projects; and
.. A detailed financial plan for the projects, including—
... The estimated allowable project costs allocated to major project elements;
... The anticipated total amount of PFC revenue that will be used to finance the projects; and
... The source and amount of other funds, if any, needed to finance the projects.
. *Requirements of air carriers and foreign air carriers.* (1) Within 30 days following issuance of the notice required by paragraph (a) of this section, each carrier must provide the public agency with a written acknowledgement that it received the notice.

(2) Within 30 days following the meeting, each carrier must provide the public agency with a written certification of its agreement or disagreement with the proposed project. A certification of disagreement shall contain the reasons for such disagreement. The absence of such reasons shall void a certification of disagreement.

(3) If a carrier fails to provide the public agency with timely acknowledgement of the notice or timely certification of agreement or disagreement with the proposed project, the carrier is considered to have certified its agreement.

## § 158.24

### Notice and opportunity for public comment.

. *Notice by public agency.* A public agency must provide written notice and an opportunity for public comment before:
. *Notice contents.* The notice required by § 158.24(a) must include:
. *Distribution of notice.* The public agency must make the notice available to the public and interested agencies through one or more of the following methods:
.. Publication in local newspapers of general circulation;
.. Publication in other local media;
.. Posting the notice on the public agency's Internet Web site; or
.. Any other method acceptable to the Administrator.

(i) Filing an application with the FAA for authority to impose a PFC under § 158.25(b);

(ii) Filing an application with the FAA for authority to use PFC revenue under § 158.25(c);
              

(iii) Filing a notice of intent to impose and/or use a PFC under § 158.30; and

(iv) Filing a request to amend a previously approved PFC as discussed in § 158.37(b)(1).

(2) The notice must allow the public to file comments for at least 30 days, but no more than 45 days, after the date of publication of the notice or posting on the public agency's Web site, as applicable.

(i) A description of the project(s) the public agency is considering for funding by PFC's;

(ii) A brief justification for each project the public agency is considering for funding by PFC's;

(iii) The PFC level for each project;

(iv) The estimated total PFC revenue the public agency will use for each project;

(v) The proposed charge effective date for the application or notice of intent;

(vi) The estimated charge expiration date for the application or notice of intent;

(vii) The estimated total PFC revenue the public agency will collect for the application or notice of intent; and

(viii) The name of and contact information for the person within the public agency to whom comments should be sent.

(2) The public agency must make available a more detailed project justification or the justification documents to the public upon request.

## § 158.25

### Applications.

. *General.* This section specifies the information the public agency must file when applying for authority to impose a PFC and for authority to use PFC revenue on a project. A public agency may apply for such authority at any commercial service airport it controls. The public agency must use the proposed PFC to finance airport-related projects at that airport or at any existing or proposed airport that the public agency controls. A public agency may apply for authority to impose a PFC before or concurrent with an application to use PFC revenue. If a public agency chooses to apply, it must do so by using FAA Form 5500-1, PFC Application (latest edition) and all applicable Attachments. The public agency must provide the information required under paragraphs (b) or (c), or both, of this section.
. *Application for authority to impose a PFC.* This paragraph sets forth the information to be submitted by all public agencies seeking authority to impose a PFC. A separate application shall be submitted for each airport at which a PFC is to be imposed. The application shall be signed by an authorized official of the public agency, and, unless otherwise authorized by the Administrator, must include the following:
.. The name and address of the public agency.
.. The name and telephone number of the official submitting the application on behalf of the public agency.
.. The official name of the airport at which the PFC is to be imposed.
.. The official name of the airport at which a project is proposed.
.. A copy of the airport capital plan or other documentation of planned improvements for each airport at which a PFC financed project is proposed.
.. A description of each project proposed.
.. The project justification, including the extent to which the project achieves one or more of the objectives set forth in § 158.15(a) and (if a PFC level above $3 is requested) the requirements of § 158.17. In addition—
... For any project for terminal development, including gates and related areas, the public agency shall discuss any existing conditions that limit competition between and among air carriers and foreign air carriers at the airport, any initiatives it proposes to foster opportunities for enhanced competition between and among such carriers, and the expected results of such initiatives; or
... For any terminal development project at a covered airport, the public agency shall submit a competition plan in accordance with § 158.19.
.. The charge to be imposed for each project.
.. The proposed charge effective date.
.. The estimated charge expiration date.
.. Information on the consultation with air carriers and foreign air carriers having a significant business interest at the airport and the public comment process, including:
... A list of such carriers and those notified;
... A list of carriers that acknowledged receipt of the notice provided under § 158.23(a);
... Lists of carriers that certified agreement and that certified disagreement with the project;
... Information on which method under § 158.24(b) the public agency used to meet the public notice requirement; and
... A summary of substantive comments by carriers contained in any certifications of disagreement with each project and disagreements with each project provided by the public, and the public agency's reasons for continuing despite such disagreements.
.. If the public agency is also filing a request under § 158.11—
... The request;
... A copy of the information provided to the carriers under § 158.23(a)(3);
... A copy of the carriers' comments with respect to such information;
... A list of any class or classes of carriers that would not be required to collect a PFC if the request is approved; and
... The public agency's reasons for submitting the request in the face of opposing comments.
.. A copy of information regarding the financing of the project presented to the carriers and foreign air carriers under § 158.23 of this part and as revised during the consultation.
.. A copy of all comments received as a result of the carrier consultation and public comment processes.
.. For an application not accompanied by a concurrent application for authority to use PFC revenue:
... A description of any alternative methods being considered by the public agency to accomplish the objectives of the project;
... A description of alternative uses of the PFC revenue to ensure such revenue will be used only on eligible projects in the event the proposed project is not ultimately approved for use of PFC revenue;
... A timetable with projected dates for completion of project formulation activities and submission of an application to use PFC revenue; and
... A projected date of project implementation and completion.
.. A signed statement certifying that the public agency will comply with the assurances set forth in Appendix A to this part.
.. Such additional information as the Administrator may require.
. *Application for authority to use PFC revenue.* A public agency may use PFC revenue only for projects approved under this paragraph. This paragraph sets forth the information that a public agency shall submit, unless otherwise authorized by the Administrator, when applying for the authority to use PFC revenue to finance specific projects.
.. An application submitted concurrently with an application for the authority to impose a PFC, must include:
... The information required under paragraphs (b)(1) through (15) of this section;
... An FAA Form 5500-1, Attachment G, Airport Layout Plan, Airspace, and Environmental Findings (latest edition) providing the following information:
... The information required by §§ 158.25(b)(16) and 158.25(b)(17).
.. An application where the authority to impose a PFC has been previously approved:
... Must not be filed until the public agency conducts further consultation with air carriers and foreign air carriers under § 158.23. However, the meeting required under § 158.23(a)(4) is optional if there are no changes to the projects after approval of the impose authority and further opportunity for public comment under § 158.24; and
... Must include a summary of further air carrier consultation and the public agency's response to any disagreements submitted under the air carrier consultation and public comment processes conducted under paragraph (c)(2)(i) of this section;
... Must include the following, updated and changed where appropriate:
... An FAA Form 5500-1, Attachment G, Airport Layout Plan, Airspace, and Environmental Findings (latest edition) providing the following information:
... The information required by §§ 158.25(b)(16) and 158.25(b)(17).

(A) For projects required to be shown on an ALP, the ALP depicting the project has been approved by the FAA and the date of such approval;

(B) All environmental reviews required by the National Environmental Policy Act (NEPA) of 1969 have been completed and a copy of the final FAA environmental determination with respect to the project has been approved, and the date of such approval, if such determination is required; and

(C) The final FAA airspace determination with respect to the project has been completed, and the date of such determination, if an airspace study is required.

(A) FAA Form 5500-1 without attachments except as required below;

(B) For any projects where there have been no changes since the FAA approved authority to impose a PFC for those projects, a list of projects included in this application for use authority. The FAA will consider the information on these projects, filed with the impose authority application, incorporated by reference; and

(C) For any project that has changed since receiving impose authority, the public agency must file an Attachment B for that project clearly describing the changes to the project.

(A) For projects required to be shown on an ALP, the ALP depicting the project has been approved by the FAA and the date of such approval;

(B) All environmental reviews required by the National Environmental Policy Act (NEPA) of 1969 have been completed and a copy of the final FAA environmental determination with respect to the project has been approved, and the date of such approval, if such determination is required; and

(C) The final FAA airspace determination with respect to the project has been completed, and the date of such determination, if an airspace study is required; and

## § 158.27

### Review of applications.

. *General.* This section describes the process for review of all applications filed under § 158.25 of this part.
. *Determination of completeness.* Within 30 days after receipt of an application by the FAA Airports office, the Administrator determines whether the application substantially complies with the requirements of § 158.25.
. *Process for substantially complete application.* If the Administrator determines the application is substantially complete, the following procedures apply:
.. The Administrator advises the public agency by letter that its application is substantially complete.
.. The Administrator may opt to publish a notice in the *Federal Register* advising that the Administrator intends to rule on the application and inviting public comment, as set forth in paragraph (e) of this section. If the Administrator publishes a notice, the Administrator will provide a copy of the notice to the public agency.
.. If the Administrator publishes a notice, the public agency—
... Shall make available for inspection, upon request, a copy of the application, notice, and other documents germane to the application, and
... May publish the notice in a newspaper of general circulation in the area where the airport covered by the application is located.
.. After reviewing the application and any public comments received from a *Federal Register* notice, the Administrator issues a final decision approving or disapproving the application, in whole or in part, before 120 days after the FAA Airports office received the application.
. *Process for applications not substantially complete.* If the Administrator determines an application is not substantially complete, the following procedures apply:
.. The Administrator notifies the public agency in writing that its application is not substantially complete. The notification will list the information required to complete the application.
.. Within 15 days after the Administrator sends such notification, the public agency shall advise the Administrator in writing whether it intends to supplement its application.
.. If the public agency declines to supplement the application, the Administrator follows the procedures for review of an application set forth in paragraph (c) of this section and issues a final decision approving or disapproving the application, in whole or in part, no later than 120 days after the application was received by the FAA Airports office.
.. If the public agency supplements its application, the original application is deemed to be withdrawn for purposes of applying the statutory deadline for the Administrator's decision. Upon receipt of the supplement, the Administrator issues a final decision approving or disapproving the supplemented application, in whole or in part, no later than 120 days after the supplement was received by the FAA Airports office.
. *The Federal Register notice.* The *Federal Register* notice includes the following information:
.. The name of the public agency and the airport at which the PFC is to be imposed;
.. A brief description of the PFC project, the level of the proposed PFC, the proposed charge effective date, the proposed charge expiration date and the total estimated PFC revenue;
.. The address and telephone number of the FAA Airports office at which the application may be inspected;
.. The Administrator's determination on whether the application is substantially complete and any information required to complete the application; and
.. The due dates for any public comments.
. *Public comments.* (1) Interested persons may file comments on the application within 30 days after publication of the Administrator's notice in the *Federal Register.*
              

(2) Three copies of these comments shall be submitted to the FAA Airports office identified in the *Federal Register* notice.

(3) Commenters shall also provide one copy of their comments to the public agency.

(4) Comments from air carriers and foreign air carriers may be in the same form as provided to the public agency under § 158.23.

## § 158.29

### The Administrator's decision.

. *Authority to impose a PFC.* (1) An application to impose a PFC will be approved in whole or in part only after a determination that—
. *Authority to use PFC revenue on an approved project.* (1) An application for authority to use PFC revenue will be approved in whole or in part only after a determination that—
. *Disapproval of application.* (1) If an application is disapproved, the Administrator notifies the public agency in writing of the decision and the reasons for the disapproval.
. The Administrator publishes a monthly notice of PFC approvals and disapprovals in the *Federal Register.*
              

(i) The amount and duration of the PFC will not result in revenue that exceeds amounts necessary to finance the project;

(ii) The project will achieve the objectives and criteria set forth in § 158.15 except for those projects approved under § 158.18.

(iii) If a PFC level above $3 is being approved, the project meets the criteria set forth in § 158.17;

(iv) The collection process, including any request by the public agency not to require a class of carriers to collect PFC's, is reasonable, not arbitrary, nondiscriminatory, and otherwise in compliance with the law;

(v) The public agency has not been found to be in violation of 49 U.S.C. 47524 and 47526;

(vi) The public agency has not been found to be in violation of 49 U.S.C. 47107(b) governing the use of airport revenue;

(vii) If the public agency has not applied for authority to use PFC revenue, a finding that there are alternative uses of the PFC revenue to ensure that such revenue will be used on approved projects; and
              

(viii) If applicable, the public agency has submitted a competition plan in accordance with § 158.19.

(2) The Administrator notifies the public agency in writing of the decision on the application. The notification will list the projects and alternative uses that may qualify for PFC financing under § 158.15, and (if a PFC level above $3 is being approved) § 158.17, PFC level, total approved PFC revenue including the amounts approved at $3 and less, $4, and/or $4.50, duration of authority to impose and earliest permissible charge effective date.

(i) The amount and duration of the PFC will not result in revenue that exceeds amounts necessary to finance the project;

(ii) The project will achieve the objectives and criteria set forth in § 158.15 except for those projects approved under § 158.18.

(iii) If a PFC level above $3 is being approved, the project meets the criteria set forth in § 158.17; and

(iv) All applicable requirements pertaining to the ALP for the airport, airspace studies for the project, and the National Environmental Policy Act of 1969 (NEPA), have been satisfied.

(2) The Administrator notifies the public agency in writing of the decision on the application. The notification will list the approved projects, PFC level, total approved PFC revenue, total approved for collection, including the amounts approved at $3 and less, $4, and/or $4.50, and any limit on the duration of authority to impose a PFC as prescribed under § 158.33.

(3) Approval to use PFC revenue to finance a project shall be construed as approval of that project.

(2) A public agency reapplying for approval to impose or use a PFC must comply with §§ 158.23, 158.24, and 158.25.

## § 158.30

### PFC Authorization at Non-Hub Airports.

. *General.* This section specifies the procedures a public agency controlling a non-hub airport must follow when notifying the FAA of its intent to impose a PFC and to use PFC revenue on a project under this section. In addition, this section describes the FAA's rules for reviewing and acknowledging a notice of intent filed under this section. A public agency may notify the FAA of its intent to impose a PFC before or concurrent with a notice of intent to use PFC revenue. A public agency must file a notice of intent in the manner and form prescribed by the Administrator and must include the information required under paragraphs (b), (c), or both, of this section.
. *Notice of intent to impose a PFC.* This paragraph sets forth the information a public agency must file to notify the FAA of its intent to impose a PFC under this section. The public agency must file a separate notice of intent for each airport at which the public agency plans on imposing a PFC. An authorized official of the public agency must sign the notice of intent and, unless authorized by the Administrator, must include:
.. A completed FAA Form 5500-1, PFC Application (latest edition) without attachments except as required below;
.. Project information (in the form and manner prescribed by the FAA) including the project title, PFC funds sought, PFC level sought, and, if an existing Airport Improvement Program (AIP) grant already covers this project, the grant agreement number.
.. If an existing AIP grant does not cover this project, the notice of intent must include the information in paragraph (b)(2) of this section as well as the following:
... Additional information describing the proposed schedule for the project,
              
... A description of how this project meets one of the PFC objectives in § 158.15(a), and
... A description of how this project meets the adequate justification requirement in § 158.15(c).
.. A copy of any comments received by the public agency during the air carrier consultation and public comment processes (§§ 158.23 and 158.24) and the public agency's response to any disagreements.
.. If applicable, a request to exclude a class of carriers from the requirement to collect the PFC (§ 158.11).
.. A signed statement certifying that the public agency will comply with the assurances set forth in Appendix A to this part.
.. Any additional information the Administrator may require.
. *Notice of intent to use PFC revenue.* A public agency may use PFC revenue only for projects included in notices filed under this paragraph or approved under § 158.29. This paragraph sets forth the information that a public agency must file, unless otherwise authorized by the Administrator, in its notice of intent to use PFC revenue to finance specific projects under this section.
.. A notice of intent to use PFC revenue filed concurrently with a notice of intent to impose a PFC must include:
... The information required under paragraphs (b)(1) through (7) of this section;
... A completed FAA Form 5500-1, Attachment G, Airport Layout Plan, Airspace, and Environmental Findings (latest edition) for all projects not included in an existing Federal airport program grant.
.. A notice of intent to use PFC revenue where the FAA has previously acknowledged a notice of intent to impose a PFC must:
... Be preceded by further consultation with air carriers and the opportunity for public comment under §§ 158.23 and 158.24 of this part. However, a meeting with the air carriers is optional if all information is the same as that provided with the impose authority notice;
... Include a copy of any comments received by the public agency during the air carrier consultation and public comment processes (§§ 158.23 and 158.24) and the public agency's response to any disagreements or negative comments; and
... Include any updated and changed information:
. *FAA review of notices of intent.* (1) The FAA will review the notice of intent to determine that:
. *FAA acknowledgment of notices of intent.* Within 30 days of receipt of the public agency's notice of intent about its PFC program, the FAA will issue a written acknowledgment of the public agency's notice. The FAA's acknowledgment may concur with all proposed projects, may object to some or all proposed projects, or may object to the notice of intent in its entirety. The FAA's acknowledgment will include the reason(s) for any objection(s).
              
. Public agency actions following issuance of FAA acknowledgment letter. If the FAA does not object to either a project or the notice of intent in its entirety, the public agency may implement its PFC program. The public agency's implementation must follow the information specified in its notice of intent. If the FAA objects to a project, the public agency may not collect or use PFC revenue on that project. If the FAA objects to the notice of intent in its entirety, the public agency may not implement the PFC program proposed in that notice. When implementing a PFC under this section, except for § 158.25, a public agency must comply with all sections of part 158.
. *Acknowledgment not an order.* An FAA acknowledgment issued under this section is not considered an order issued by the Secretary for purposes of 49 U.S.C. 46110 (Judicial Review).
. *Sunset provision.* This section will expire May 9, 2008.

(A) Required by paragraphs (b)(1), (2), (5), (6), and (7) of this section; and

(B) Required by paragraph (c)(1)(ii) of this section.

(A) The amount and duration of the PFC will not result in revenue that exceeds the amount necessary to finance the project(s);

(B) Each proposed project meets the requirements of § 158.15;

(C) Each project proposed at a PFC level above $3.00 meets the requirements of § 158.17(a)(2) and (3);

(D) All applicable airport layout plan, airspace, and environmental requirements have been met for each project;

(E) Any request by the public agency to exclude a class of carriers from the requirement to collect the PFC is reasonable, not arbitrary, nondiscriminatory, and otherwise complies with the law; and

(F) The consultation and public comment processes complied with §§ 158.23 and 158.24.

(2) The FAA will also make a determination regarding the public agency's compliance with 49 U.S.C. 47524 and 47526 governing airport noise and access restrictions and 49 U.S.C. 47107(b) governing the use of airport revenue. Finally, the FAA will review all comments filed during the air carrier consultation and public comment processes.

## § 158.31

### Duration of authority to impose a PFC after project implementation.

A public agency that has begun implementing an approved project may impose a PFC until—

. The charge expiration date is reached;
. The total PFC revenue collected plus interest earned thereon equals the allowable cost of the approved project;
. The authority to collect the PFC is terminated by the Administrator under subpart E of this part; or
. The public agency is determined by the Administrator to be in violation of 49 U.S.C. 47524 and 47526, and the authority to collect the PFC is terminated under that statute's implementing regulations under this title.

## § 158.33

### Duration of authority to impose a PFC before project implementation.

. A public agency shall not impose a PFC beyond the lesser of the following—
.. 2 years after approval to use PFC revenue on an approved project if the project has not been implemented, or
.. 5 years after the charge effective date; or
.. 5 years after the FAA's decision on the application (if the charge effective date is more than 60 days after the decision date) if an approved project is not implemented.
. If, in the Administrator's judgment, the public agency has not made sufficient progress toward implementation of an approved project within the times specified in paragraph (a) of this section, the Administrator begins termination proceedings under subpart E of this part.
. The authority to impose a PFC following approval shall automatically expire without further action by the Administrator on the following dates:
.. 3 years after the charge effective date; or 3 years after the FAA's decision on the application if the charge effective date is more than 60 days after the decision date unless—
... The public agency has filed an application for approval to use PFC revenue for an eligible project that is pending before the FAA;
... An application to use PFC revenue has been approved; or
... A request for extension (not to exceed 2 years) to submit an application for project approval, under § 158.35, has been granted; or
.. 5 years after the charge effective date; or 5 years after the FAA's decision on the application (if the charge effective date is more than 60 days after the decision date) unless the public agency has obtained project approval.
. If the authority to impose a PFC expires under paragraph (c) of this section, the public agency must provide the FAA with a list of the air carriers and foreign air carriers operating at the airport and all other collecting carriers that have remitted PFC revenue to the public agency in the preceding 12 months. The FAA notifies each of the listed carriers to terminate PFC collection no later than 30 days after the date of notification by the FAA.
. Restriction on reauthorization to impose a PFC. Whenever the authority to impose a PFC has expired or been terminated under this section, the Administrator will not grant new approval to impose a PFC in advance of implementation of an approved project.

## § 158.35

### Extension of time to submit application to use PFC revenue.

. A public agency may request an extension of time to submit an application to use PFC revenue after approval of an application to impose PFC's. At least 30 days prior to submitting such request, the public agency shall publish notice of its intention to request an extension in a local newspaper of general circulation and shall request comments. The notice shall include progress on the project, a revised schedule for obtaining project approval and reasons for the delay in submitting the application.
. The request shall be submitted at least 120 days prior to the charge expiration date and, unless otherwise authorized by the Administrator, shall be accompanied by the following:
.. A description of progress on the project application to date.
.. A revised schedule for submitting the application.
.. An explanation of the reasons for delay in submitting the application.
.. A summary financial report depicting the total amount of PFC revenue collected plus interest, the projected amount to be collected during the period of the requested extension, and any public agency funds used on the project for which reimbursement may be sought.
.. A summary of any further consultation with air carriers and foreign air carriers operating at the airport.
.. A summary of comments received in response to the local notice.
. The Administrator reviews the request for extension and accompanying information, to determine whether—
.. The public agency has shown good cause for the delay in applying for project approval;
.. The revised schedule is satisfactory; and
.. Further collection will not result in excessive accumulation of PFC revenue.
. The Administrator, upon determining that the agency has shown good cause for the delay and that other elements of the request are satisfactory, grants the request for extension to the public agency. The Administrator advises the public agency in writing not more than 90 days after receipt of the request. The duration of the extension shall be as specified in § 158.33 of this part.

## § 158.37

### Amendment of approved PFC.

. A public agency may amend the FAA's decision with respect to an approved PFC to:
. The public agency must file a request to the Administrator to amend the FAA's decision with respect to an approved PFC. The request must include or demonstrate:
.. Further consultation with the air carriers and foreign air carriers and seek public comment in accordance with §§ 158.23 and 158.24 when applying for those requests to:
.. A copy of any comments received from the processes in paragraph (b)(1)(A) of this section for the carrier consultation and the opportunity for public comment in accordance with §§ 158.23 and 158.24;
.. The public agency's reasons for continuing despite any objections;
.. A description of the proposed amendment;
.. Justification, if the amendment involves an increase in the PFC amount for a project by more than 25 percent of the original approved amount if that amount is $1,000,000 or greater, an increase in the PFC amount by any percentage if the original approved amount was less than $1,000,000 and the amended approved amount is $1,000,000 or greater, a change in the approved project scope, or any increase in the approved PFC level to be collected from each passenger.
.. A description of how each project meets the requirements of § 158.17(b), for each project proposed for an increase of the PFC level above $3.00 at a medium or large hub airport;
.. A signed statement certifying that the public agency has met the requiements of § 158.19, if applicable, for any amendment proposing to increase the PFC level above $3.00 at a medium or large hub airport; and
.. Any other information the Administrator may require.
. The Administrator will approve, partially approve or disapprove the amendment request and notify the public agency of the decision within 30 days of receipt of the request. If a PFC level of more than $3.00 is approved, the Administrator must find the project meets the requirements of §§ 158.17 and 158.19, if applicable, before the public agency can implement the new PFC level.
. The public agency must notify the carriers of any change to the FAA's decision with respect to an approved PFC resulting from an amendment. The effective date of any new PFC level must be no earlier than the first day of a month which is at least 30 days from the date the public agency notifies the carriers.

(i) Increase or decrease the level of PFC the public agency wants to collect from each passenger,

(ii) Increase or decrease the total approved PFC revenue,

(iii) Change the scope of an approved project,

(iv) Delete an approved project, or

(v) Establish a new class of carriers under § 158.11 or amend any such class previously approved.

(2) A public agency may not amend the FAA's decision with respect to an approved PFC to add projects, change an approved project to a different facility type, or alter an approved project to accomplish a different purpose.

(A) Amend the approved PFC amount for a project by more than 25 percent of the original approved amount if the amount was $1,000,000 or greater,

(B) Amend the approved PFC amount for a project by any percentage if the original approved amount was below $1,000,000 and the amended approved amount is $1,000,000 or greater,

(C) Change the scope of a project, or

(D) Increase the PFC level to be collected from each passenger.

(ii) No further consultation with air carriers and foreign air carriers or public comment is required by a public agency in accordance with §§ 158.23 and 158.24 when applying for an amendment in the following situations:

(A) To institute a decrease in the level of PFC to be collected from each passenger;

(B) To institute a decrease in the total PFC revenue;

(C) To institute an increase of 25 percent or less of the original approved amount if the amount was more than $1,000,000; or

(D) To institute an increase of any amount if the original approved amount of the project was less than $1,000,000 and if the amended approved amount of the project remains below $1,000,000; or

(E) To establish a new class of carriers under § 158.11 or amend any such class previously approved; or

(F) To delete an approved project.

## § 158.39

### Use of excess PFC revenue.

. If the PFC revenue remitted to the public agency, plus interest earned thereon, exceeds the allowable cost of the project, the public agency must use the excess funds for approved projects or to retire outstanding PFC-financed bonds.
. For bond-financed projects, any excess PFC revenue collected under debt servicing requirements shall be retained by the public agency and used for approved projects or retirement of outstanding PFC-financed bonds.
. When the authority to impose a PFC has expired or has been terminated, accumulated PFC revenue shall be used for approved projects or retirement of outstanding PFC-financed bonds.
. Within 30 days after the authority to impose a PFC has expired or been terminated, the public agency must present a plan to the appropriate FAA Airports office to begin using accumulated PFC revenue. The plan must include a timetable for submitting any necessary application under this part. If the public agency fails to submit such a plan, or if the plan is not acceptable to the Administrator, the Administrator may reduce Federal airport grant program apportioned funds.

