# General
:toc:

## § 67.1 - Applicability.

This part prescribes the medical standards and certification procedures for issuing medical certificates for airmen and for remaining eligible for a medical certificate.

## § 67.3 - Issue.

A person who meets the medical standards prescribed in this part, based on medical examination and evaluation of the person's history and condition, is entitled to an appropriate medical certificate.

## § 67.4 - Application.

An applicant for first-, second- and third-class medical certification must:

[loweralpha]
. Apply on a form and in a manner prescribed by the Administrator;
. Be examined by an aviation medical examiner designated in accordance with part 183 of this chapter. An applicant may obtain a list of aviation medical examiners from the FAA Office of Aerospace Medicine homepage on the FAA Web site, from any FAA Regional Flight Surgeon, or by contacting the Manager of the Aerospace Medical Education Division, P.O. Box 26200, Oklahoma City, Oklahoma 73125.
. Show proof of age and identity by presenting a government-issued photo identification (such as a valid U.S. driver's license, identification card issued by a driver's license authority, military identification, or passport). If an applicant does not have government-issued identification, he or she may use non-photo, government-issued identification (such as a birth certificate or voter registration card) in conjunction with photo identification (such as a work identification card or a student identification card).

## § 67.7 - Access to the National Driver Register.

At the time of application for a certificate issued under this part, each person who applies for a medical certificate shall execute an express consent form authorizing the Administrator to request the chief driver licensing official of any state designated by the Administrator to transmit information contained in the National Driver Register about the person to the Administrator. The Administrator shall make information received from the National Driver Register, if any, available on request to the person for review and written comment.

