# Drug Testing Program Requirements
:toc:

## § 120.101 - Scope.

This subpart contains the standards and components that must be included in a drug testing program required by this part.

## § 120.103 - General.

[loweralpha]
. *Purpose.* The purpose of this subpart is to establish a program designed to help prevent accidents and injuries resulting from the use of prohibited drugs by employees who perform safety-sensitive functions.
. *DOT procedures.*
[arabic]
.. Each employer shall ensure that drug testing programs conducted pursuant to 14 CFR parts 65, 91, 121, and 135 comply with the requirements of this subpart and the “Procedures for Transportation Workplace Drug Testing Programs” published by the Department of Transportation (DOT) (49 CFR part 40).
.. An employer may not use or contract with any drug testing laboratory that is not certified by the Department of Health and Human Services (HHS) under the National Laboratory Certification Program.
. *Employer responsibility.* As an employer, you are responsible for all actions of your officials, representatives, and service agents in carrying out the requirements of this subpart and 49 CFR part 40.
. *Applicable Federal Regulations.* The following applicable regulations appear in 49 CFR or 14 CFR:
[arabic]
.. 49 CFR Part 40—Procedures for Transportation Workplace Drug Testing Programs
.. 14 CFR:
[lowerroman]
... § 67.107—First-Class Airman Medical Certificate, Mental.
... § 67.207—Second-Class Airman Medical Certificate, Mental.
... § 67.307—Third-Class Airman Medical Certificate, Mental.
... § 91.147—Passenger carrying flight for compensation or hire.
... § 135.1—Applicability
. Falsification. No individual may make, or cause to be made, any of the following:
[arabic]
.. Any fraudulent or intentionally false statement in any application of a drug testing program.
.. Any fraudulent or intentionally false entry in any record or report that is made, kept, or used to show compliance with this part.
.. Any reproduction or alteration, for fraudulent purposes, of any report or record required to be kept by this part.

## § 120.105 - Employees who must be tested.

Each employee, including any assistant, helper, or individual in a training status, who performs a safety-sensitive function listed in this section directly or by contract (including by subcontract at any tier) for an employer as defined in this subpart must be subject to drug testing under a drug testing program implemented in accordance with this subpart. This includes full-time, part-time, temporary, and intermittent employees regardless of the degree of supervision. The safety-sensitive functions are:

[loweralpha]
. Flight crewmember duties.
. Flight attendant duties.
. Flight instruction duties.
. Aircraft dispatcher duties.
. Aircraft maintenance and preventive maintenance duties.
. Ground security coordinator duties.
. Aviation screening duties.
. Air traffic control duties.
[lowerroman]
.. Operations control specialist duties.

## § 120.107 - Substances for which testing must be conducted.

Each employer shall test each employee who performs a safety-sensitive function for evidence of marijuana, cocaine, opiates, phencyclidine (PCP), and amphetamines during each test required by § 120.109.

## § 120.109 - Types of drug testing required.

Each employer shall conduct the types of testing described in this section in accordance with the procedures set forth in this subpart and the DOT “Procedures for Transportation Workplace Drug Testing Programs” (49 CFR part 40).

[loweralpha]
. *Pre-employment drug testing.*
[arabic]
.. No employer may hire any individual for a safety-sensitive function listed in § 120.105 unless the employer first conducts a pre-employment test and receives a verified negative drug test result for that individual.
.. No employer may allow an individual to transfer from a nonsafety-sensitive to a safety-sensitive function unless the employer first conducts a pre-employment test and receives a verified negative drug test result for the individual.
.. Employers must conduct another pre-employment test and receive a verified negative drug test result before hiring or transferring an individual into a safety-sensitive function if more than 180 days elapse between conducting the pre-employment test required by paragraphs (a)(1) or (2) of this section and hiring or transferring the individual into a safety-sensitive function, resulting in that individual being brought under an FAA drug testing program.
.. If the following criteria are met, an employer is permitted to conduct a pre-employment test, and if such a test is conducted, the employer must receive a negative test result before putting the individual into a safety-sensitive function:
[lowerroman]
... The individual previously performed a safety-sensitive function for the employer and the employer is not required to pre-employment test the individual under paragraphs (a)(1) or (2) of this section before putting the individual to work in a safety-sensitive function;
... The employer removed the individual from the employer's random testing program conducted under this subpart for reasons other than a verified positive test result on an FAA-mandated drug test or a refusal to submit to such testing; and
... The individual will be returning to the performance of a safety-sensitive function.
.. Before hiring or transferring an individual to a safety-sensitive function, the employer must advise each individual that the individual will be required to undergo pre-employment testing in accordance with this subpart, to determine the presence of marijuana, cocaine, opiates, phencyclidine (PCP), and amphetamines, or a metabolite of those drugs in the individual's system. The employer shall provide this same notification to each individual required by the employer to undergo pre-employment testing under paragraph (a)(4) of this section.
. *Random drug testing.*
[arabic]
.. Except as provided in paragraphs (b)(2) through (b)(4) of this section, the minimum annual percentage rate for random drug testing shall be 50 percent of covered employees.
.. The Administrator's decision to increase or decrease the minimum annual percentage rate for random drug testing is based on the reported positive rate for the entire industry. All information used for this determination is drawn from the statistical reports required by § 120.119. In order to ensure reliability of the data, the Administrator considers the quality and completeness of the reported data, may obtain additional information or reports from employers, and may make appropriate modifications in calculating the industry positive rate. Each year, the Administrator will publish in the *Federal Register* the minimum annual percentage rate for random drug testing of covered employees. The new minimum annual percentage rate for random drug testing will be applicable starting January 1 of the calendar year following publication.
.. When the minimum annual percentage rate for random drug testing is 50 percent, the Administrator may lower this rate to 25 percent of all covered employees if the Administrator determines that the data received under the reporting requirements of this subpart for two consecutive calendar years indicate that the reported positive rate is less than 1.0 percent.
.. When the minimum annual percentage rate for random drug testing is 25 percent, and the data received under the reporting requirements of this subpart for any calendar year indicate that the reported positive rate is equal to or greater than 1.0 percent, the Administrator will increase the minimum annual percentage rate for random drug testing to 50 percent of all covered employees.
.. The selection of employees for random drug testing shall be made by a scientifically valid method, such as a random-number table or a computer-based random number generator that is matched with employees' Social Security numbers, payroll identification numbers, or other comparable identifying numbers. Under the selection process used, each covered employee shall have an equal chance of being tested each time selections are made.
.. As an employer, you must select and test a percentage of employees at least equal to the minimum annual percentage rate each year.
[lowerroman]
... As an employer, to determine whether you have met the minimum annual percentage rate, you must divide the number of random testing results for safety-sensitive employees by the average number of safety-sensitive employees eligible for random testing.
[upperalpha]
.... To calculate whether you have met the annual minimum percentage rate, count all random positives, random negatives, and random refusals as your “random testing results.”
.... To calculate the average number of safety-sensitive employees eligible for random testing throughout the year, add the total number of safety-sensitive employees eligible for testing during each random testing period for the year and divide that total by the number of random testing periods. Only safety-sensitive employees are to be in an employer's random testing pool, and all safety-sensitive employees must be in the random pool. If you are an employer conducting random testing more often than once per month (*e.g.,* you select daily, weekly, bi-weekly) you do not need to compute this total number of safety-sensitive employees more than on a once per month basis.
... As an employer, you may use a service agent to perform random selections for you, and your safety-sensitive employees may be part of a larger random testing pool of safety-sensitive employees. However, you must ensure that the service agent you use is testing at the appropriate percentage established for your industry and that only safety-sensitive employees are in the random testing pool. For example:
[upperalpha]
.... If the service agent has your employees in a random testing pool for your company alone, you must ensure that the testing is conducted at least at the minimum annual percentage rate under this part.
.... If the service agent has your employees in a random testing pool combined with other FAA-regulated companies, you must ensure that the testing is conducted at least at the minimum annual percentage rate under this part.
.... If the service agent has your employees in a random testing pool combined with other DOT-regulated companies, you must ensure that the testing is conducted at least at the highest rate required for any DOT-regulated company in the pool.
.. Each employer shall ensure that random drug tests conducted under this subpart are unannounced and that the dates for administering random tests are spread reasonably throughout the calendar year.
.. Each employer shall require that each safety-sensitive employee who is notified of selection for random drug testing proceeds to the collection site immediately; provided, however, that if the employee is performing a safety-sensitive function at the time of the notification, the employer shall instead ensure that the employee ceases to perform the safety-sensitive function and proceeds to the collection site as soon as possible.
.. If a given covered employee is subject to random drug testing under the drug testing rules of more than one DOT agency, the employee shall be subject to random drug testing at the percentage rate established for the calendar year by the DOT agency regulating more than 50 percent of the employee's function.
.. If an employer is required to conduct random drug testing under the drug testing rules of more than one DOT agency, the employer may—
[lowerroman]
... Establish separate pools for random selection, with each pool containing the covered employees who are subject to testing at the same required rate; or
... Randomly select covered employees for testing at the highest percentage rate established for the calendar year by any DOT agency to which the employer is subject.
.. An employer required to conduct random drug testing under the anti-drug rules of more than one DOT agency shall provide each such agency access to the employer's records of random drug testing, as determined to be necessary by the agency to ensure the employer's compliance with the rule.
. *Post-accident drug testing.* Each employer shall test each employee who performs a safety-sensitive function for the presence of marijuana, cocaine, opiates, phencyclidine (PCP), and amphetamines, or a metabolite of those drugs in the employee's system if that employee's performance either contributed to an accident or can not be completely discounted as a contributing factor to the accident. The employee shall be tested as soon as possible but not later than 32 hours after the accident. The decision not to administer a test under this section must be based on a determination, using the best information available at the time of the determination, that the employee's performance could not have contributed to the accident. The employee shall submit to post-accident testing under this section.
. *Drug testing based on reasonable cause.* Each employer must test each employee who performs a safety-sensitive function and who is reasonably suspected of having used a prohibited drug. The decision to test must be based on a reasonable and articulable belief that the employee is using a prohibited drug on the basis of specific contemporaneous physical, behavioral, or performance indicators of probable drug use. At least two of the employee's supervisors, one of whom is trained in detection of the symptoms of possible drug use, must substantiate and concur in the decision to test an employee who is reasonably suspected of drug use; except that in the case of an employer, other than a part 121 certificate holder, who employs 50 or fewer employees who perform safety-sensitive functions, one supervisor who is trained in detection of symptoms of possible drug use must substantiate the decision to test an employee who is reasonably suspected of drug use.
. *Return to duty drug testing.* Each employer shall ensure that before an individual is returned to duty to perform a safety-sensitive function after refusing to submit to a drug test required by this subpart or receiving a verified positive drug test result on a test conducted under this subpart the individual shall undergo a return-to-duty drug test. No employer shall allow an individual required to undergo return-to-duty testing to perform a safety-sensitive function unless the employer has received a verified negative drug test result for the individual. The test cannot occur until after the SAP has determined that the employee has successfully complied with the prescribed education and/or treatment.
. *Follow-up drug testing.*
[arabic]
.. Each employer shall implement a reasonable program of unannounced testing of each individual who has been hired to perform or who has been returned to the performance of a safety-sensitive function after refusing to submit to a drug test required by this subpart or receiving a verified positive drug test result on a test conducted under this subpart.
.. The number and frequency of such testing shall be determined by the employer's Substance Abuse Professional conducted in accordance with the provisions of 49 CFR part 40, but shall consist of at least six tests in the first 12 months following the employee's return to duty.
.. The employer must direct the employee to undergo testing for alcohol in accordance with subpart F of this part, in addition to drugs, if the Substance Abuse Professional determines that alcohol testing is necessary for the particular employee. Any such alcohol testing shall be conducted in accordance with the provisions of 49 CFR part 40.
.. Follow-up testing shall not exceed 60 months after the date the individual begins to perform or returns to the performance of a safety-sensitive function. The Substance Abuse Professional may terminate the requirement for follow-up testing at any time after the first six tests have been conducted, if the Substance Abuse Professional determines that such testing is no longer necessary.

## § 120.111 - Administrative and other matters.

[loweralpha]
. *MRO record retention requirements.*
[arabic]
.. Records concerning drug tests confirmed positive by the laboratory shall be maintained by the MRO for 5 years. Such records include the MRO copies of the custody and control form, medical interviews, documentation of the basis for verifying as negative test results confirmed as positive by the laboratory, any other documentation concerning the MRO's verification process.
.. Should the employer change MRO's for any reason, the employer shall ensure that the former MRO forwards all records maintained pursuant to this rule to the new MRO within ten working days of receiving notice from the employer of the new MRO's name and address.
.. Any employer obtaining MRO services by contract, including a contract through a C/TPA, shall ensure that the contract includes a recordkeeping provision that is consistent with this paragraph, including requirements for transferring records to a new MRO.
. *Access to records.* The employer and the MRO shall permit the Administrator or the Administrator's representative to examine records required to be kept under this subpart and 49 CFR part 40. The Administrator or the Administrator's representative may require that all records maintained by the service agent for the employer must be produced at the employer's place of business.
. *Release of drug testing information.* An employer shall release information regarding an employee's drug testing results, evaluation, or rehabilitation to a third party in accordance with 49 CFR part 40. Except as required by law, this subpart, or 49 CFR part 40, no employer shall release employee information.
. *Refusal to submit to testing.* Each employer must notify the FAA within 2 working days of any employee who holds a certificate issued under part 61, part 63, or part 65 of this chapter who has refused to submit to a drug test required under this subpart. Notification must be sent to: Federal Aviation Administration, Office of Aerospace Medicine, Drug Abatement Division (AAM-800), 800 Independence Avenue, SW., Washington, DC 20591, or by fax to (202) 267-5200.
. *Permanent disqualification from service.*
[arabic]
.. An employee who has verified positive drug test results on two drug tests required by this subpart of this chapter, and conducted after September 19, 1994, is permanently precluded from performing for an employer the safety-sensitive duties the employee performed prior to the second drug test.
.. An employee who has engaged in prohibited drug use during the performance of a safety-sensitive function after September 19, 1994 is permanently precluded from performing that safety-sensitive function for an employer.
              
. *DOT management information system annual reports.* Copies of any annual reports submitted to the FAA under this subpart must be maintained by the employer for a minimum of 5 years.

## § 120.113 - Medical Review Officer, Substance Abuse Professional, and Employer Responsibilities.

[loweralpha]
. The employer shall designate or appoint a Medical Review Officer (MRO) who shall be qualified in accordance with 49 CFR part 40 and shall perform the functions set forth in 49 CFR part 40 and this subpart. If the employer does not have a qualified individual on staff to serve as MRO, the employer may contract for the provision of MRO services as part of its drug testing program.
. *Medical Review Officer (MRO).* The MRO must perform the functions set forth in subpart G of 49 CFR part 40, and subpart E of this part. The MRO shall not delay verification of the primary test result following a request for a split specimen test unless such delay is based on reasons other than the fact that the split specimen test result is pending. If the primary test result is verified as positive, actions required under this rule (*e.g.,* notification to the Federal Air Surgeon, removal from safety-sensitive position) are not stayed during the 72-hour request period or pending receipt of the split specimen test result.
. *Substance Abuse Professional (SAP).* The SAP must perform the functions set forth in 49 CFR part 40, subpart O.
. *Additional Medical Review Officer, Substance Abuse Professional, and Employer Responsibilities Regarding 14 CFR part 67 Airman Medical Certificate Holders.*
[arabic]
.. As part of verifying a confirmed positive test result or refusal to submit to a test, the MRO must ask and the individual must answer whether he or she holds an airman medical certificate issued under 14 CFR part 67 or would be required to hold an airman medical certificate to perform a safety-sensitive function for the employer. If the individual answers in the affirmative to either question, in addition to notifying the employer in accordance with 49 CFR part 40, the MRO must forward to the Federal Air Surgeon, at the address listed in paragraph (d)(5) of this section, the name of the individual, along with identifying information and supporting documentation, within 2 working days after verifying a positive drug test result or refusal to submit to a test.
.. During the SAP interview required for a verified positive test result or a refusal to submit to a test, the SAP must ask and the individual must answer whether he or she holds or would be required to hold an airman medical certificate issued under 14 CFR part 67 to perform a safety-sensitive function for the employer. If the individual answers in the affirmative, the individual must obtain an airman medical certificate issued by the Federal Air Surgeon dated after the verified positive drug test result date or refusal to test date. After the individual obtains this airman medical certificate, the SAP may recommend to the employer that the individual may be returned to a safety-sensitive position. The receipt of an airman medical certificate does not alter any obligations otherwise required by 49 CFR part 40 or this subpart.
.. An employer must forward to the Federal Air Surgeon within 2 working days of receipt, copies of all reports provided to the employer by a SAP regarding the following:
[lowerroman]
... An individual who the MRO has reported to the Federal Air Surgeon under § 120.113 (d)(1); or
... An individual who the employer has reported to the Federal Air Surgeon under § 120.111(d).
.. The employer must not permit an employee who is required to hold an airman medical certificate under 14 CFR part 67 to perform a safety-sensitive duty to resume that duty until the employee has:
[lowerroman]
... Been issued an airman medical certificate from the Federal Air Surgeon after the date of the verified positive drug test result or refusal to test; and
... Met the return to duty requirements in accordance with 49 CFR part 40.
.. Reports required under this section shall be forwarded to the Federal Air Surgeon, Federal Aviation Administration, Office of Aerospace Medicine, Attn: Drug Abatement Division (AAM-800), 800 Independence Avenue, SW., Washington, DC 20591.
.. MROs, SAPs, and employers who send reports to the Federal Air Surgeon must keep a copy of each report for 5 years.

## § 120.115 - Employee Assistance Program (EAP).

[loweralpha]
. The employer shall provide an EAP for employees. The employer may establish the EAP as a part of its internal personnel services or the employer may contract with an entity that will provide EAP services to an employee. Each EAP must include education and training on drug use for employees and training for supervisors making determinations for testing of employees based on reasonable cause.
. *EAP education program.*
[arabic]
.. Each EAP education program must include at least the following elements:
[lowerroman]
... Display and distribution of informational material;
... Display and distribution of a community service hot-line telephone number for employee assistance; and
... Display and distribution of the employer's policy regarding drug use in the workplace.
.. The employer's policy shall include information regarding the consequences under the rule of using drugs while performing safety-sensitive functions, receiving a verified positive drug test result, or refusing to submit to a drug test required under the rule.
. *EAP training program.*
[arabic]
.. Each employer shall implement a reasonable program of initial training for employees. The employee training program must include at least the following elements:
[lowerroman]
... The effects and consequences of drug use on individual health, safety, and work environment;
... The manifestations and behavioral cues that may indicate drug use and abuse; and
.. The employer's supervisory personnel who will determine when an employee is subject to testing based on reasonable cause shall receive specific training on specific, contemporaneous physical, behavioral, and performance indicators of probable drug use in addition to the training specified in § 120.115 (c).
.. The employer shall ensure that supervisors who will make reasonable cause determinations receive at least 60 minutes of initial training.
.. The employer shall implement a reasonable recurrent training program for supervisory personnel making reasonable cause determinations during subsequent years.
.. Documentation of all training given to employees and supervisory personnel must be included in the training program.
.. The employer shall identify the employee and supervisor EAP training in the employer's drug testing program.

## § 120.117 - Implementing a drug testing program.

[loweralpha]
. Each company must meet the requirements of this subpart. Use the following chart to determine whether your company must obtain an Antidrug and Alcohol Misuse Prevention Program Operations Specification, Letter of Authorization, or Drug and Alcohol Testing Program Registration from the FAA:
. Use the following chart for implementing a drug testing program if you are applying for a part 119 certificate with authority to operate under parts 121 or 135 of this chapter, if you intend to begin operations as defined in § 91.147 of this chapter, or if you intend to begin air traffic control operations (not operated by the FAA or by or under contract to the U.S. Military). Use it to determine whether you need to have an Antidrug and Alcohol Misuse Prevention Program Operations Specification, Letter of Authorization, or Drug and Alcohol Testing Program Registration from the FAA. Your employees who perform safety-sensitive functions must be tested in accordance with this subpart. The chart follows:
. If you are an individual or company that intends to provide safety-sensitive services by contract to a part 119 certificate holder with authority to operate under parts 121 and/or 135 of this chapter, an operation as defined in § 91.147 of this chapter, or an air traffic control facility not operated by the FAA or by or under contract to the U.S. military, use the following chart to determine what you must do if you opt to have your own drug testing program.
. *Obtaining an Antidrug and Alcohol Misuse Prevention Program Operations Specification.*
[arabic]
.. To obtain an Antidrug and Alcohol Misuse Prevention Program Operations Specification, you must contact your FAA Principal Operations Inspector or Principal Maintenance Inspector. Provide him/her with the following information:
[lowerroman]
... Company name.
... Certificate number.
... Telephone number.
... Address where your drug and alcohol testing program records are kept.
... Whether you have 50 or more safety-sensitive employees, or 49 or fewer safety-sensitive employees. (Part 119 certificate holders with authority to operate only under part 121 of this chapter are not required to provide this information.)
.. You must certify on your Antidrug and Alcohol Misuse Prevention Program Operations Specification issued by your FAA Principal Operations Inspector or Principal Maintenance Inspector that you will comply with this part and 49 CFR part 40.
.. You are required to obtain only one Antidrug and Alcohol Misuse Prevention Program Operations Specification to satisfy this requirement under this part.
.. You must update the Antidrug and Alcohol Misuse Prevention Program Operations Specification when any changes to the information contained in the Operation Specification occur.
. *Register your Drug and Alcohol Testing Program by obtaining a Letter of Authorization from the FAA in accordance with § 91.147.*
[arabic]
.. A drug and alcohol testing program is considered registered when the following information is submitted to the Flight Standards District Office nearest your principal place of business:
[lowerroman]
... Company name.
... Telephone number.
... Address where your drug and alcohol testing program records are kept.
... Type of safety-sensitive functions you or your employees perform (such as flight instruction duties, aircraft dispatcher duties, maintenance or preventive maintenance duties, ground security coordinator duties, aviation screening duties, air traffic control duties).
... Whether you have 50 or more covered employees, or 49 or fewer covered employees.
... A signed statement indicating that your company will comply with this part and 49 CFR part 40.
.. This Letter of Authorization will satisfy the requirements for both your drug testing program under this subpart and your alcohol testing program under subpart F of this part.
.. Update the Letter of Authorization information as changes occur. Send the updates to the Flight Standards District Office nearest your principal place of business.
.. If you are a part 119 certificate holder with authority to operate under parts 121 or 135 and intend to begin operations as defined in § 91.147 of this chapter, you must also advise the Federal Aviation Administration, Office of Aerospace Medicine, Drug Abatement Division (AAM-800), 800 Independence Avenue SW., Washington, DC 20591.
. *Obtaining a Drug and Alcohol Testing Program Registration from the FAA.*
[arabic]
.. Except as provided in paragraphs (d) and (e) of this section, to obtain a Drug and Alcohol Testing Program Registration from the FAA, you must submit the following information to the Office of Aerospace Medicine, Drug Abatement Division:
[lowerroman]
... Company name.
... Telephone number.
... Address where your drug and alcohol testing program records are kept.
... Type of safety-sensitive functions you or your employees perform (such as flight instruction duties, aircraft dispatcher duties, maintenance or preventive maintenance duties, ground security coordinator duties, aviation screening duties, air traffic control duties).
... Whether you have 50 or more covered employees, or 49 or fewer covered employees.
... A signed statement indicating that: your company will comply with this part and 49 CFR part 40; and you intend to provide safety-sensitive functions by contract (including subcontract at any tier) to a part 119 certificate holder with authority to operate under part 121 or part 135 of this chapter, an operator as defined in § 91.147 of this chapter, or an air traffic control facility not operated by the FAA or by or under contract to the U.S. military.
.. Send this information to the Federal Aviation Administration, Office of Aerospace Medicine, Drug Abatement Division (AAM-800), 800 Independence Avenue SW., Washington, DC 20591.
.. This Drug and Alcohol Testing Program Registration will satisfy the registration requirements for both your drug testing program under this subpart and your alcohol testing program under subpart F of this part.
.. Update the registration information as changes occur. Send the updates to the address specified in paragraph (f)(2) of this section.

## § 120.119 - Annual reports.

[loweralpha]
. Annual reports of testing results must be submitted to the FAA by March 15 of the succeeding calendar year for the prior calendar year (January 1 through December 31) in accordance with the following provisions:
[arabic]
.. Each part 121 certificate holder shall submit an annual report each year.
.. Each entity conducting a drug testing program under this part, other than a part 121 certificate holder, that has 50 or more employees performing a safety-sensitive function on January 1 of any calendar year shall submit an annual report to the FAA for that calendar year.
.. The Administrator reserves the right to require that aviation employers not otherwise required to submit annual reports prepare and submit such reports to the FAA. Employers that will be required to submit annual reports under this provision will be notified in writing by the FAA.
. As an employer, you must use the Management Information System (MIS) form and instructions as required by 49 CFR part 40 (at 49 CFR 40.26 and appendix H to 49 CFR part 40). You may also use the electronic version of the MIS form provided by DOT. The Administrator may designate means (*e.g.,* electronic program transmitted via the Internet) other than hard-copy, for MIS form submission. For information on where to submit MIS forms and for the electronic version of the form, *see: http://www.faa.gov/about/office_org/headquarters_offices/avs/offices/aam/drug_alcohol.*
              
. A service agent may prepare the MIS report on behalf of an employer. However, a company official (*e.g.,* Designated Employer Representative as defined in 49 CFR part 40) must certify the accuracy and completeness of the MIS report, no matter who prepares it.

## § 120.121 - Preemption.

[loweralpha]
. The issuance of 14 CFR parts 65, 91, 121, and 135 by the FAA preempts any State or local law, rule, regulation, order, or standard covering the subject matter of 14 CFR parts 65, 91, 121, and 135, including but not limited to, drug testing of aviation personnel performing safety-sensitive functions.
. The issuance of 14 CFR parts 65, 91, 121, and 135 does not preempt provisions of state criminal law that impose sanctions for reckless conduct of an individual that leads to actual loss of life, injury, or damage to property whether such provisions apply specifically to aviation employees or generally to the public.

## § 120.123 - Drug testing outside the territory of the United States.

[loweralpha]
. No part of the testing process (including specimen collection, laboratory processing, and MRO actions) shall be conducted outside the territory of the United States.
[arabic]
.. Each employee who is assigned to perform safety-sensitive functions solely outside the territory of the United States shall be removed from the random testing pool upon the inception of such assignment.
.. Each covered employee who is removed from the random testing pool under this section shall be returned to the random testing pool when the employee resumes the performance of safety-sensitive functions wholly or partially within the territory of the United States.
. The provisions of this subpart shall not apply to any individual who performs a function listed in § 120.105 by contract for an employer outside the territory of the United States.

## § 120.125 - Waivers from 49 CFR 40.21.

An employer subject to this part may petition the Drug Abatement Division, Office of Aerospace Medicine, for a waiver allowing the employer to stand down an employee following a report of a laboratory confirmed positive drug test or refusal, pending the outcome of the verification process.

[loweralpha]
. Each petition for a waiver must be in writing and include substantial facts and justification to support the waiver. Each petition must satisfy the substantive requirements for obtaining a waiver, as provided in 49 CFR 40.21.
. Each petition for a waiver must be submitted to the Federal Aviation Administration, Office of Aerospace Medicine, Drug Abatement Division (AAM-800), 800 Independence Avenue, SW., Washington, DC 20591.
. The Administrator may grant a waiver subject to 49 CFR 40.21(d).

