# Helicopter Air Ambulance Equipment, Operations, and Training Requirements
:toc:

## § 135.601 - Applicability and definitions.

[loweralpha]
. *Applicability.* This subpart prescribes the requirements applicable to each certificate holder conducting helicopter air ambulance operations.
. *Definitions.* For purposes of this subpart, the following definitions apply:
[arabic]
.. *Helicopter air ambulance operation* means a flight, or sequence of flights, with a patient or medical personnel on board, for the purpose of medical transportation, by a part 135 certificate holder authorized by the Administrator to conduct helicopter air ambulance operations. A helicopter air ambulance operation includes, but is not limited to—
[lowerroman]
... Flights conducted to position the helicopter at the site at which a patient or donor organ will be picked up.
... Flights conducted to reposition the helicopter after completing the patient, or donor organ transport.
... Flights initiated for the transport of a patient or donor organ that are terminated due to weather or other reasons.
.. *Medical personnel* means a person or persons with medical training, including but not limited to flight physicians, flight nurses, or flight paramedics, who are carried aboard a helicopter during helicopter air ambulance operations in order to provide medical care.
.. *Mountainous* means designated mountainous areas as listed in part 95 of this chapter.
.. *Nonmountainous* means areas other than mountainous areas as listed in part 95 of this chapter.

## § 135.603 - Pilot-in-command instrument qualifications.

After April 24, 2017, no certificate holder may use, nor may any person serve as, a pilot in command of a helicopter air ambulance operation unless that person meets the requirements of § 135.243 and holds a helicopter instrument rating or an airline transport pilot certificate with a category and class rating for that aircraft, that is not limited to VFR.

## § 135.605 - Helicopter terrain awareness and warning system (HTAWS).

[loweralpha]
. After April 24, 2017, no person may operate a helicopter in helicopter air ambulance operations unless that helicopter is equipped with a helicopter terrain awareness and warning system (HTAWS) that meets the requirements in TSO-C194 and Section 2 of RTCA DO-309.
. The certificate holder's Rotorcraft Flight Manual must contain appropriate procedures for—
[arabic]
.. The use of the HTAWS; and
.. Proper flight crew response to HTAWS audio and visual warnings.
. Certificate holders with HTAWS required by this section with an approved deviation under § 21.618 of this chapter are in compliance with this section.
. The standards required in this section are incorporated by reference into this section with the approval of the Director of the Federal Register under 5 U.S.C. 552(a) and 1 CFR part 51. To enforce any edition other than that specified in this section, the FAA must publish notice of change in the *Federal Register* and the material must be available to the public. All approved material is available for inspection at the FAA's Office of Rulemaking (ARM-1), 800 Independence Avenue SW., Washington, DC 20591 (telephone (202) 267-9677) and from the sources indicated below. It is also available for inspection at the National Archives and Records Administration (NARA). For information on the availability of this material at NARA, call (202) 741-6030 or go to *http://www.archives.gov/federal_register/code_of_federal_regulations/ibr_locations.html.*
              
[arabic]
.. U.S. Department of Transportation, Subsequent Distribution Office, DOT Warehouse M30, Ardmore East Business Center, 3341 Q 75th Avenue, Landover, MD 20785; telephone (301) 322-5377. Copies are also available on the FAA's Web site. Use the following link and type the TSO number in the search box: *http://rgl.faa.gov/Regulatory_and_Guidance_Library/rgTSO.nsf/Frameset?OpenPage.*
              
[lowerroman]
... TSO C-194, Helicopter Terrain Awareness and Warning System (HTAWS), Dec. 17, 2008.
... [Reserved]
.. RTCA, Inc., 1150 18th Street NW., Suite 910, Washington, DC 20036, telephone (202) 833-9339, and are also available on RTCA's Web site at *http://www.rtca.org/onlinecart/index.cfm.*
              
[lowerroman]
... RTCA DO-309, Minimum Operational Performance Standards (MOPS) for Helicopter Terrain Awareness and Warning System (HTAWS) Airborne Equipment, Mar. 13, 2008.
... [Reserved]

## § 135.607 - Flight Data Monitoring System.

After April 23, 2018, no person may operate a helicopter in air ambulance operations unless it is equipped with an approved flight data monitoring system capable of recording flight performance data. This system must:

[loweralpha]
. Receive electrical power from the bus that provides the maximum reliability for operation without jeopardizing service to essential or emergency loads, and
. Be operated from the application of electrical power before takeoff until the removal of electrical power after termination of flight.

## § 135.609 - VFR ceiling and visibility requirements for Class G airspace.

[loweralpha]
. Unless otherwise specified in the certificate holder's operations specifications, when conducting VFR helicopter air ambulance operations in Class G airspace, the weather minimums in the following table apply:
. A certificate holder may designate local flying areas in a manner acceptable to the Administrator, that must—
[arabic]
.. Not exceed 50 nautical miles in any direction from each designated location;
.. Take into account obstacles and terrain features that are easily identifiable by the pilot in command and from which the pilot in command may visually determine a position; and
.. Take into account the operating environment and capabilities of the certificate holder's helicopters.
. A pilot must demonstrate a level of familiarity with the local flying area by passing an examination given by the certificate holder within the 12 calendar months prior to using the local flying area.

## § 135.611 - IFR operations at locations without weather reporting.

[loweralpha]
. If a certificate holder is authorized to conduct helicopter IFR operations, the Administrator may authorize the certificate holder to conduct IFR helicopter air ambulance operations at airports with an instrument approach procedure and at which a weather report is not available from the U.S. National Weather Service (NWS), a source approved by the NWS, or a source approved by the FAA, subject to the following limitations:
[arabic]
.. The certificate holder must obtain a weather report from a weather reporting facility operated by the NWS, a source approved by the NWS, or a source approved by the FAA, that is located within 15 nautical miles of the airport. If a weather report is not available, the certificate holder may obtain the area forecast from the NWS, a source approved by the NWS, or a source approved by the FAA, for information regarding the weather observed in the vicinity of the airport;
.. Flight planning for IFR flights conducted under this paragraph must include selection of an alternate airport that meets the requirements of §§ 135.221 and 135.223;
.. In Class G airspace, IFR departures with visual transitions are authorized only after the pilot in command determines that the weather conditions at the departure point are at or above takeoff minimums depicted in the published Obstacle Departure Procedure or VFR minimum ceilings and visibilities in accordance with § 135.609.
.. All approaches must be conducted at Category A approach speeds as established in part 97 or those required for the type of approach being used.
. Each helicopter air ambulance operated under this section must be equipped with functioning severe weather detection equipment.
. Pilots conducting operations pursuant to this section may use the weather information obtained in paragraph (a) to satisfy the weather report and forecast requirements of § 135.213 and § 135.225(a).
. After completing a landing at the airport at which a weather report is not available, the pilot in command is authorized to determine if the weather meets the takeoff requirements of part 97 of this chapter or the certificate holder's operations specification, as applicable.

## § 135.613 - Approach/departure IFR transitions.

[loweralpha]
. *Approaches.* When conducting an authorized instrument approach and transitioning from IFR to VFR flight, upon transitioning to VFR flight the following weather minimums apply—
[arabic]
.. For Point-in-Space (PinS) Copter Instrument approaches annotated with a “Proceed VFR” segment, if the distance from the missed approach point to the landing area is 1 NM or less, flight visibility must be at least 1 statute mile and the ceiling on the approach chart applies;
.. For all instrument approaches, including PinS when paragraph (a)(1) of this section does not apply, if the distance from the missed approach point to the landing area is 3 NM or less, the applicable VFR weather minimums are—
[lowerroman]
... For Day Operations: No less than a 600-foot ceiling and 2 statute miles flight visibility;
... For Night Operations: No less than a 600-foot ceiling and 3 statute miles flight visibility; or
.. For all instrument approaches, including PinS, if the distance from the missed approach point to the landing area is greater than 3 NM, the VFR weather minimums required by the class of airspace.
. *Departures.* For transitions from VFR to IFR upon departure—
[arabic]
.. The VFR weather minimums of paragraph (a) of this section apply if—
[lowerroman]
... An FAA-approved obstacle departure procedure is followed; and
... An IFR clearance is obtained on or before reaching a predetermined location that is not more than 3 NM from the departure location.
.. If the departure does not meet the requirements of paragraph (b)(1) of this section, the VFR weather minimums required by the class of airspace apply.

## § 135.615 - VFR flight planning.

[loweralpha]
. *Pre-flight.* Prior to conducting VFR operations, the pilot in command must—
[arabic]
.. Determine the minimum safe cruise altitude by evaluating the terrain and obstacles along the planned route of flight;
.. Identify and document the highest obstacle along the planned route of flight; and
.. Using the minimum safe cruise altitudes in paragraphs (b)(1)-(2) of this section, determine the minimum required ceiling and visibility to conduct the planned flight by applying the weather minimums appropriate to the class of airspace for the planned flight.
. *Enroute.* While conducting VFR operations, the pilot in command must ensure that all terrain and obstacles along the route of flight are cleared vertically by no less than the following:
[arabic]
.. 300 feet for day operations.
.. 500 feet for night operations.
. *Rerouting the planned flight path.* A pilot in command may deviate from the planned flight path for reasons such as weather conditions or operational considerations. Such deviations do not relieve the pilot in command of the weather requirements or the requirements for terrain and obstacle clearance contained in this part and in part 91 of this chapter. Rerouting, change in destination, or other changes to the planned flight that occur while the helicopter is on the ground at an intermediate stop require evaluation of the new route in accordance with paragraph (a) of this section.
. *Operations manual.* Each certificate holder must document its VFR flight planning procedures in its operations manual.

## § 135.617 - Pre-flight risk analysis.

[loweralpha]
. Each certificate holder conducting helicopter air ambulance operations must establish, and document in its operations manual, an FAA-approved preflight risk analysis that includes at least the following—
[arabic]
.. Flight considerations, to include obstacles and terrain along the planned route of flight, landing zone conditions, and fuel requirements;
.. Human factors, such as crew fatigue, life events, and other stressors;
.. Weather, including departure, en route, destination, and forecasted;
.. A procedure for determining whether another helicopter air ambulance operator has refused or rejected a flight request; and
.. Strategies and procedures for mitigating identified risks, including procedures for obtaining and documenting approval of the certificate holder's management personnel to release a flight when a risk exceeds a level predetermined by the certificate holder.
. Each certificate holder must develop a preflight risk analysis worksheet to include, at a minimum, the items in paragraph (a) of this section.
. Prior to the first leg of each helicopter air ambulance operation, the pilot in command must conduct a preflight risk analysis and complete the preflight risk analysis worksheet in accordance with the certificate holder's FAA-approved procedures. The pilot in command must sign the preflight risk analysis worksheet and specify the date and time it was completed.
. The certificate holder must retain the original or a copy of each completed preflight risk analysis worksheet at a location specified in its operations manual for at least 90 days from the date of the operation.

## § 135.619 - Operations control centers.

[loweralpha]
. *Operations control center.* After April 22, 2016, certificate holders authorized to conduct helicopter air ambulance operations, with 10 or more helicopter air ambulances assigned to the certificate holder's operations specifications, must have an operations control center. The operations control center must be staffed by operations control specialists who, at a minimum—
[arabic]
.. Provide two-way communications with pilots;
.. Provide pilots with weather briefings, to include current and forecasted weather along the planned route of flight;
.. Monitor the progress of the flight; and
.. Participate in the preflight risk analysis required under § 135.617 to include the following:
[lowerroman]
... Ensure the pilot has completed all required items on the preflight risk analysis worksheet;
... Confirm and verify all entries on the preflight risk analysis worksheet;
... Assist the pilot in mitigating any identified risk prior to takeoff; and
... Acknowledge in writing, specifying the date and time, that the preflight risk analysis worksheet has been accurately completed and that, according to their professional judgment, the flight can be conducted safely.
. *Operations control center staffing.* Each certificate holder conducting helicopter air ambulance operations must provide enough operations control specialists at each operations control center to ensure the certificate holder maintains operational control of each flight.
. *Documentation of duties and responsibilities.* Each certificate holder must describe in its operations manual the duties and responsibilities of operations control specialists, including preflight risk mitigation strategies and control measures, shift change checklist, and training and testing procedures to hold the position, including procedures for retesting.
. *Training requirements.* No certificate holder may use, nor may any person perform the duties of, an operations control specialist unless the operations control specialist has satisfactorily completed the training requirements of this paragraph.
[arabic]
.. *Initial training.* Before performing the duties of an operations control specialist, each person must satisfactorily complete the certificate holder's FAA-approved operations control specialist initial training program and pass an FAA-approved knowledge and practical test given by the certificate holder. Initial training must include a minimum of 80 hours of training on the topics listed in paragraph (f) of this section. A certificate holder may reduce the number of hours of initial training to a minimum of 40 hours for persons who have obtained, at the time of beginning initial training, a total of at least 2 years of experience during the last 5 years in any one or in any combination of the following areas—
[lowerroman]
... In military aircraft operations as a pilot, flight navigator, or meteorologist;
... In air carrier operations as a pilot, flight engineer, certified aircraft dispatcher, or meteorologist; or
... In aircraft operations as an air traffic controller or a flight service specialist.
.. *Recurrent training.* Every 12 months after satisfactory completion of the initial training, each operations control specialist must complete a minimum of 40 hours of recurrent training on the topics listed in paragraph (f) of this section and pass an FAA-approved knowledge and practical test given by the certificate holder on those topics.
. *Training records.* The certificate holder must maintain a training record for each operations control specialist employed by the certificate holder for the duration of that individual's employment and for 90 days thereafter. The training record must include a chronological log for each training course, including the number of training hours and the examination dates and results.
. *Training topics.* Each certificate holder must have an FAA-approved operations control specialist training program that covers at least the following topics—
[arabic]
.. Aviation weather, including:
[lowerroman]
... General meteorology;
... Prevailing weather;
... Adverse and deteriorating weather;
... Windshear;
... Icing conditions;
... Use of aviation weather products;
... Available sources of information; and
... Weather minimums;
.. Navigation, including:
[lowerroman]
... Navigation aids;
... Instrument approach procedures;
... Navigational publications; and
... Navigation techniques;
.. Flight monitoring, including:
[lowerroman]
... Available flight-monitoring procedures; and
... Alternate flight-monitoring procedures;
.. Air traffic control, including:
[lowerroman]
... Airspace;
... Air traffic control procedures;
... Aeronautical charts; and
... Aeronautical data sources;
.. Aviation communication, including:
[lowerroman]
... Available aircraft communications systems;
... Normal communication procedures;
... Abnormal communication procedures; and
... Emergency communication procedures;
.. Aircraft systems, including:
[lowerroman]
... Communications systems;
... Navigation systems;
... Surveillance systems;
... Fueling systems;
... Specialized systems;
... General maintenance requirements; and
... Minimum equipment lists;
.. Aircraft limitations and performance, including:
[lowerroman]
... Aircraft operational limitations;
... Aircraft performance;
... Weight and balance procedures and limitations; and
... Landing zone and landing facility requirements;
.. Aviation policy and regulations, including:
[lowerroman]
... 14 CFR Parts 1, 27, 29, 61, 71, 91, and 135;
... 49 CFR Part 830;
... Company operations specifications;
... Company general operations policies;
... Enhanced operational control policies;
... Aeronautical decision making and risk management;
... Lost aircraft procedures; and
... Emergency and search and rescue procedures, including plotting coordinates in degrees, minutes, seconds format, and degrees, decimal minutes format;
              
.. Crew resource management, including:
[lowerroman]
... Concepts and practical application;
... Risk management and risk mitigation; and
... Pre-flight risk analysis procedures required under § 135.617;
.. Local flying area orientation, including:
[lowerroman]
... Terrain features;
... Obstructions;
... Weather phenomena for local area;
... Airspace and air traffic control facilities;
... Heliports, airports, landing zones, and fuel facilities;
... Instrument approaches;
... Predominant air traffic flow;
... Landmarks and cultural features, including areas prone to flat-light, whiteout, and brownout conditions; and
... Local aviation and safety resources and contact information; and
.. Any other requirements as determined by the Administrator to ensure safe operations.
. *Operations control specialist duty time limitations.*
[arabic]
.. Each certificate holder must establish the daily duty period for an operations control specialist so that it begins at a time that allows that person to become thoroughly familiar with operational considerations, including existing and anticipated weather conditions in the area of operations, helicopter operations in progress, and helicopter maintenance status, before performing duties associated with any helicopter air ambulance operation. The operations control specialist must remain on duty until relieved by another qualified operations control specialist or until each helicopter air ambulance monitored by that person has completed its flight or gone beyond that person's jurisdiction.
.. Except in cases where circumstances or emergency conditions beyond the control of the certificate holder require otherwise—
[lowerroman]
... No certificate holder may schedule an operations control specialist for more than 10 consecutive hours of duty;
... If an operations control specialist is scheduled for more than 10 hours of duty in 24 consecutive hours, the certificate holder must provide that person a rest period of at least 8 hours at or before the end of 10 hours of duty;
... If an operations control specialist is on duty for more than 10 consecutive hours, the certificate holder must provide that person a rest period of at least 8 hours before that person's next duty period;
... Each operations control specialist must be relieved of all duty with the certificate holder for at least 24 consecutive hours during any 7 consecutive days.
. *Drug and alcohol testing.* Operations control specialists must be tested for drugs and alcohol according to the certificate holder's Drug and Alcohol Testing Program administered under part 120 of this chapter.

## § 135.621 - Briefing of medical personnel.

[loweralpha]
. Except as provided in paragraph (b) of this section, prior to each helicopter air ambulance operation, each pilot in command, or other flight crewmember designated by the certificate holder, must ensure that all medical personnel have been briefed on the following—
[arabic]
.. Passenger briefing requirements in § 135.117(a) and (b); and
.. Physiological aspects of flight;
.. Patient loading and unloading;
.. Safety in and around the helicopter;
.. In-flight emergency procedures;
.. Emergency landing procedures;
.. Emergency evacuation procedures;
.. Efficient and safe communications with the pilot; and
.. Operational differences between day and night operations, if appropriate.
. The briefing required in paragraphs (a)(2) through (9) of this section may be omitted if all medical personnel on board have satisfactorily completed the certificate holder's FAA-approved medical personnel training program within the preceding 24 calendar months. Each training program must include a minimum of 4 hours of ground training, and 4 hours of training in and around an air ambulance helicopter, on the topics set forth in paragraph (a)(2) through (9) of this section.
. Each certificate holder must maintain a record for each person trained under this section that—
[arabic]
.. Contains the individual's name, the most recent training completion date, and a description, copy, or reference to training materials used to meet the training requirement.
.. Is maintained for 24 calendar months following the individual's completion of training.

