# Hazardous Materials Training Program
:toc:

## § 135.501

### Applicability and definitions.

. This subpart prescribes the requirements applicable to each certificate holder for training each crewmember and person performing or directly supervising any of the following job functions involving any item for transport on board an aircraft:
.. Acceptance;
.. Rejection;
.. Handling;
.. Storage incidental to transport;
.. Packaging of company material; or
.. Loading.
. *Definitions.* For purposes of this subpart, the following definitions apply:
.. *Company material (COMAT)*—Material owned or used by a certificate holder.
.. *Initial hazardous materials training*—The basic training required for each newly hired person, or each person changing job functions, who performs or directly supervises any of the job functions specified in paragraph (a) of this section.
.. *Recurrent hazardous materials training*—The training required every 24 months for each person who has satisfactorily completed the certificate holder's approved initial hazardous materials training program and performs or directly supervises any of the job functions specified in paragraph (a) of this section.

## § 135.503

### Hazardous materials training: General.

. Each certificate holder must establish and implement a hazardous materials training program that:
.. Satisfies the requirements of Appendix O of part 121 of this part;
.. Ensures that each person performing or directly supervising any of the job functions specified in § 135.501(a) is trained to comply with all applicable parts of 49 CFR parts 171 through 180 and the requirements of this subpart; and
.. Enables the trained person to recognize items that contain, or may contain, hazardous materials regulated by 49 CFR parts 171 through 180.
. Each certificate holder must provide initial hazardous materials training and recurrent hazardous materials training to each crewmember and person performing or directly supervising any of the job functions specified in § 135.501(a).
. Each certificate holder's hazardous materials training program must be approved by the FAA prior to implementation.

## § 135.505

### Hazardous materials training required.

. *Training requirement.* Except as provided in paragraphs (b), (c) and (f) of this section, no certificate holder may use any crewmember or person to perform any of the job functions or direct supervisory responsibilities, and no person may perform any of the job functions or direct supervisory responsibilities, specified in § 135.501(a) unless that person has satisfactorily completed the certificate holder's FAA-approved initial or recurrent hazardous materials training program within the past 24 months.
. *New hire or new job function.* A person who is a new hire and has not yet satisfactorily completed the required initial hazardous materials training, or a person who is changing job functions and has not received initial or recurrent training for a job function involving storage incidental to transport, or loading of items for transport on an aircraft, may perform those job functions for not more than 30 days from the date of hire or a change in job function, if the person is under the direct visual supervision of a person who is authorized by the certificate holder to supervise that person and who has successfully completed the certificate holder's FAA-approved initial or recurrent training program within the past 24 months.
. *Persons who work for more than one certificate holder.* A certificate holder that uses or assigns a person to perform or directly supervise a job function specified in § 135.501(a), when that person also performs or directly supervises the same job function for another certificate holder, need only train that person in its own policies and procedures regarding those job functions, if all of the following are met:
.. The certificate holder using this exception receives written verification from the person designated to hold the training records representing the other certificate holder that the person has satisfactorily completed hazardous materials training for the specific job function under the other certificate holder's FAA approved hazardous material training program under appendix O of part 121 of this chapter; and
.. The certificate holder who trained the person has the same operations specifications regarding the acceptance, handling, and transport of hazardous materials as the certificate holder using this exception.
. *Recurrent hazardous materials training—Completion date.* A person who satisfactorily completes recurrent hazardous materials training in the calendar month before, or the calendar month after, the month in which the recurrent training is due, is considered to have taken that training during the month in which it is due. If the person completes this training earlier than the month before it is due, the month of the completion date becomes his or her new anniversary month.
. *Repair stations.* A certificate holder must ensure that each repair station performing work for, or on the certificate holder's behalf is notified in writing of the certificate holder's policies and operations specification authorization permitting or prohibition against the acceptance, rejection, handling, storage incidental to transport, and transportation of hazardous materials, including company material. This notification requirement applies only to repair stations that are regulated by 49 CFR parts 171 through 180.
. *Certificate holders operating at foreign locations.* This exception applies if a certificate holder operating at a foreign location where the country requires the certificate holder to use persons working in that country to load aircraft. In such a case, the certificate holder may use those persons even if they have not been trained in accordance with the certificate holder's FAA approved hazardous materials training program. Those persons, however, must be under the direct visual supervision of someone who has successfully completed the certificate holder's approved initial or recurrent hazardous materials training program in accordance with this part. This exception applies only to those persons who load aircraft.

## § 135.507

### Hazardous materials training records.

. *General requirement.* Each certificate holder must maintain a record of all training required by this part received within the preceding three years for each person who performs or directly supervises a job function specified in § 135.501(a). The record must be maintained during the time that the person performs or directly supervises any of those job functions, and for 90 days thereafter. These training records must be kept for direct employees of the certificate holder, as well as independent contractors, subcontractors, and any other person who performs or directly supervises these job functions for the certificate holder.
. *Location of records.* The certificate holder must retain the training records required by paragraph (a) of this section for all initial and recurrent training received within the preceding 3 years for all persons performing or directly supervising the job functions listed in Appendix O of part 121 of this chapter at a designated location. The records must be available upon request at the location where the trained person performs or directly supervises the job function specified in § 135.501(a). Records may be maintained electronically and provided on location electronically. When the person ceases to perform or directly supervise a hazardous materials job function, the certificate holder must retain the hazardous materials training records for an additional 90 days and make them available upon request at the last location where the person worked.
. *Content of records.* Each record must contain the following:
.. The individual's name;
.. The most recent training completion date;
.. A description, copy or reference to training materials used to meet the training requirement;
.. The name and address of the organization providing the training; and
.. A copy of the certification issued when the individual was trained, which shows that a test has been completed satisfactorily.
. *New hire or new job function.* Each certificate holder using a person under the exception in § 135.505(b) must maintain a record for that person. The records must be available upon request at the location where the trained person performs or directly supervises the job function specified in § 135.501(a). Records may be maintained electronically and provided on location electronically. The record must include the following:
.. A signed statement from an authorized representative of the certificate holder authorizing the use of the person in accordance with the exception;
.. The date of hire or change in job function;
.. The person's name and assigned job function;
.. The name of the supervisor of the job function; and
.. The date the person is to complete hazardous materials training in accordance with Appendix O of part 121 of this chapter.

