# Continued Airworthiness and Safety Improvements
:toc:

## § 121.1101

### Purpose and definition.

. This subpart requires persons holding an air carrier or operating certificate under part 119 of this chapter to support the continued airworthiness of each airplane. These requirements may include, but are not limited to, revising the maintenance program, incorporating design changes, and incorporating revisions to Instructions for Continued Airworthiness.
. For purposes of this subpart, the “FAA Oversight Office” is the aircraft certification office or office of the Transport Airplane Directorate with oversight responsibility for the relevant type certificate or supplemental type certificate, as determined by the Administrator.

## § 121.1103

### Reserved

## § 121.1105

### Aging airplane inspections and records reviews.

. *Applicability.* This section applies to all airplanes operated by a certificate holder under this part, except for those airplanes operated between any point within the State of Alaska and any other point within the State of Alaska.
. *Operation after inspection and records review.* After the dates specified in this paragraph, a certificate holder may not operate an airplane under this part unless the Administrator has notified the certificate holder that the Administrator has completed the aging airplane inspection and records review required by this section. During the inspection and records review, the certificate holder must demonstrate to the Administrator that the maintenance of age-sensitive parts and components of the airplane has been adequate and timely enough to ensure the highest degree of safety.
.. *Airplanes exceeding 24 years in service on December 8, 2003; initial and repetitive inspections and records reviews.* For an airplane that has exceeded 24 years in service on December 8, 2003, no later than December 5, 2007, and thereafter at intervals not to exceed 7 years.
.. *Airplanes exceeding 14 years in service but not 24 years in service on December 8, 2003; initial and repetitive inspections and records reviews.* For an airplane that has exceeded 14 years in service but not 24 years in service on December 8, 2003, no later than December 4, 2008, and thereafter at intervals not to exceed 7 years.
.. *Airplanes not exceeding 14 years in service on December 8, 2003; initial and repetitive inspections and records reviews.* For an airplane that has not exceeded 14 years in service on December 8, 2003, no later than 5 years after the start of the airplane's 15th year in service and thereafter at intervals not to exceed 7 years.
. *Unforeseen schedule conflict.* In the event of an unforeseen scheduling conflict for a specific airplane, the Administrator may approve an extension of up to 90 days beyond an interval specified in paragraph (b) of this section.
. *Airplane and records availability.* The certificate holder must make available to the Administrator each airplane for which an inspection and records review is required under this section, in a condition for inspection specified by the Administrator, together with records containing the following information:
.. Total years in service of the airplane;
.. Total time in service of the airframe;
.. Total flight cycles of the airframe;
.. Date of the last inspection and records review required by this section;
.. Current status of life-limited parts of the airframe;
.. Time since the last overhaul of all structural components required to be overhauled on a specific time basis;
.. Current inspection status of the airplane, including the time since the last inspection required by the inspection program under which the airplane is maintained;
.. Current status of applicable airworthiness directives, including the date and methods of compliance, and if the airworthiness directive involves recurring action, the time and date when the next action is required;
.. A list of major structural alterations; and
.. A report of major structural repairs and the current inspection status for those repairs.
              
. *Notification to Administrator.* Each certificate holder must notify the Administrator at least 60 days before the date on which the airplane and airplane records will be made available for the inspection and records review.

## § 121.1107

### Repairs assessment for pressurized fuselages.

. No certificate holder may operate an Airbus Model A300 (excluding the -600 series), British Aerospace Model BAC 1-11, Boeing Model 707, 720, 727, 737, or 747, McDonnel Douglas Model DC-8, DC-9/MD-80 or DC-10, Fokker Model F28, or Lockheed Model L-1011 airplane beyond the applicable flight cycle implementation time specified below, or May 25, 2001, whichever occurs later, unless operations specifications have been issued to reference repair assessment guidelines applicable to the fuselage pressure boundary (fuselage skin, door skin, and bulkhead webs), and those guidelines are incorporated in its maintenance program. The repair assessment guidelines must be approved by the FAA Aircraft Certification Office (ACO), or office of the Transport Airplane Directorate, having cognizance over the type certificate for the affected airplane.
.. For the Airbus Model A300 (excluding the -600 series), the flight cycle implementation time is:
... Model B2: 36,000 flights.
... Model B4-100 (including Model B4-2C): 30,000 flights above the window line, and 36,000 flights below the window line.
... Model B4-200: 25,500 flights above the window line, and 34,000 flights below the window line.
.. For all models of the British Aerospace BAC 1-11, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 707, the flight cycle implementation time is 15,000 flights.
.. For all models of the Boeing 720, the flight cycle implementation time is 23,000 flights.
.. For all models of the Boeing 727, the flight cycle implementation time is 45,000 flights.
.. For all models of the Boeing 737, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 747, the flight cycle implementation time is 15,000 flights.
.. For all models of the McDonnell Douglas DC-8, the flight cycle implementation time is 30,000 flights.
.. For all models of the McDonnell Douglas DC-9/MD-80, the flight cycle implementation time is 60,000 flights.
.. For all models of the McDonnell Douglas DC-10, the flight cycle implementation time is 30,000 flights.
.. For all models of the Lockheed L-1011, the flight cycle implementation time is 27,000 flights.
.. For the Fokker F-28 Mark 1000, 2000, 3000, and 4000, the flight cycle implementation time is 60,000 flights.
. [Reserved]

## § 121.1109

### Supplemental inspections.

. *Applicability.* Except as specified in paragraph (b) of this section, this section applies to transport category, turbine powered airplanes with a type certificate issued after January 1, 1958, that as a result of original type certification or later increase in capacity have—
.. A maximum type certificated passenger seating capacity of 30 or more; or
.. A maximum payload capacity of 7,500 pounds or more.
. *Exception.* This section does not apply to an airplane operated by a certificate holder under this part between any point within the State of Alaska and any other point within the State of Alaska.
. *General requirements.* After December 20, 2010, a certificate holder may not operate an airplane under this part unless the following requirements have been met:
.. *Baseline Structure.* The certificate holder's maintenance program for the airplane includes FAA-approved damage-tolerance-based inspections and procedures for airplane structure susceptible to fatigue cracking that could contribute to a catastrophic failure. For the purpose of this section, this structure is termed “fatigue critical structure.”
.. *Adverse effects of repairs, alterations, and modifications.* The maintenance program for the airplane includes a means for addressing the adverse effects repairs, alterations, and modifications may have on fatigue critical structure and on inspections required by paragraph (c)(1) of this section. The means for addressing these adverse effects must be approved by the FAA Oversight Office.
.. *Changes to maintenance program.* The changes made to the maintenance program required by paragraphs (c)(1) and (c)(2) of this section, and any later revisions to these changes, must be submitted to the Principal Maintenance Inspector for review and approval.

## § 121.1111

### Electrical wiring interconnection systems (EWIS) maintenance program.

. Except as provided in paragraph (f) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity, have—
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7500 pounds or more.
. After March 10, 2011, no certificate holder may operate an airplane identified in paragraph (a) of this section unless the maintenance program for that airplane includes inspections and procedures for electrical wiring interconnection systems (EWIS).
. The proposed EWIS maintenance program changes must be based on EWIS Instructions for Continued Airworthiness (ICA) that have been developed in accordance with the provisions of Appendix H of part 25 of this chapter applicable to each affected airplane (including those ICA developed for supplemental type certificates installed on each airplane) and that have been approved by the FAA Oversight Office.
.. For airplanes subject to § 26.11 of this chapter, the EWIS ICA must comply with paragraphs H25.5(a)(1) and (b).
.. For airplanes subject to § 25.1729 of this chapter, the EWIS ICA must comply with paragraph H25.4 and all of paragraph H25.5.
. After March 10, 2011, before returning an airplane to service after any alterations for which EWIS ICA are developed, the certificate holder must include in the airplane's maintenance program inspections and procedures for EWIS based on those ICA.
. The EWIS maintenance program changes identified in paragraphs (c) and (d) of this section and any later EWIS revisions must be submitted to the Principal Inspector for review and approval.
. This section does not apply to the following airplane models:
.. Lockheed L-188
.. Bombardier CL-44
.. Mitsubishi YS-11
.. British Aerospace BAC 1-11
.. Concorde
.. deHavilland D.H. 106 Comet 4C
.. VFW-Vereinigte Flugtechnische Werk VFW-614
.. Illyushin Aviation IL 96T
.. Bristol Aircraft Britannia 305
.. Handley Page Herald Type 300
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C
.. Airbus Caravelle
.. Lockheed L-300

## § 121.1113

### Fuel tank system maintenance program.

. Except as provided in paragraph (g) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity, have—
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7500 pounds or more.
. For each airplane on which an auxiliary fuel tank is installed under a field approval, before June 16, 2008, the certificate holder must submit to the FAA Oversight Office proposed maintenance instructions for the tank that meet the requirements of Special Federal Aviation Regulation No. 88 (SFAR 88) of this chapter.
. After December 16, 2008, no certificate holder may operate an airplane identified in paragraph (a) of this section unless the maintenance program for that airplane has been revised to include applicable inspections, procedures, and limitations for fuel tanks systems.
. The proposed fuel tank system maintenance program revisions must be based on fuel tank system Instructions for Continued Airworthiness (ICA) that have been developed in accordance with the applicable provisions of SFAR 88 of this chapter or § 25.1529 and part 25, Appendix H, of this chapter, in effect on June 6, 2001 (including those developed for auxiliary fuel tanks, if any, installed under supplemental type certificates or other design approval) and that have been approved by the FAA Oversight Office.
. After December 16, 2008, before returning an aircraft to service after any alteration for which fuel tank ICA are developed under SFAR 88 or under § 25.1529 in effect on June 6, 2001, the certificate holder must include in the maintenance program for the airplane inspections and procedures for the fuel tank system based on those ICA.
. The fuel tank system maintenance program changes identified in paragraphs (d) and (e) of this section and any later fuel tank system revisions must be submitted to the Principal Inspector for review and approval.
. This section does not apply to the following airplane models:
.. Bombardier CL-44
.. Concorde
.. deHavilland D.H. 106 Comet 4C
.. VFW-Vereinigte Flugtechnische Werk VFW-614
.. Illyushin Aviation IL 96T
.. Bristol Aircraft Britannia 305
.. Handley Page Herald Type 300
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C
.. Airbus Caravelle
.. Lockheed L-300

## § 121.1115

### Limit of validity.

. *Applicability.* This section applies to certificate holders operating any transport category, turbine-powered airplane with a maximum takeoff gross weight greater than 75,000 pounds and a type certificate issued after January 1, 1958, regardless of whether the maximum takeoff gross weight is a result of an original type certificate or a later design change. This section also applies to certificate holders operating any transport category, turbine-powered airplane with a type certificate issued after January 1, 1958, regardless of the maximum takeoff gross weight, for which a limit of validity of the engineering data that supports the structural maintenance program (hereafter referred to as LOV) is required in accordance with § 25.571 or § 26.21 of this chapter after January 14, 2011.
. *Limit of validity.* No certificate holder may operate an airplane identified in paragraph (a) of this section after the applicable date identified in Table 1 of this section unless an Airworthiness Limitations section approved under Appendix H to part 25 or § 26.21 of this chapter is incorporated into its maintenance program. The ALS must—
.. Include an LOV approved under § 25.571 or § 26.21 of this chapter, as applicable, except as provided in paragraph (f) of this section; and
.. Be clearly distinguishable within its maintenance program.
. *Operation of airplanes excluded from § 26.21.* No certificate holder may operate an airplane identified in § 26.21(g) of this chapter after July 14, 2013, unless an Airworthiness Limitations section approved under Appendix H to part 25 or § 26.21 of this chapter is incorporated into its maintenance program. The ALS must—
.. Include an LOV approved under § 25.571 or § 26.21 of this chapter, as applicable, except as provided in paragraph (f) of this section; and
.. Be clearly distinguishable within its maintenance program.
. *Extended limit of validity.* No certificate holder may operate an airplane beyond the LOV, or extended LOV, specified in paragraph (b)(1), (c), (d), or (f) of this section, as applicable, unless the following conditions are met:
              
.. An ALS must be incorporated into its maintenance program that—
... Includes an extended LOV and any widespread fatigue damage airworthiness limitation items approved under § 26.23 of this chapter; and
... Is approved under § 26.23 of this chapter.
.. The extended LOV and the airworthiness limitation items pertaining to widespread fatigue damage must be clearly distinguishable within its maintenance program.
. *Principal Maintenance Inspector approval.* Certificate holders must submit the maintenance program revisions required by paragraphs (b), (c), and (d) of this section to the Principal Maintenance Inspector for review and approval.
. *Exception.* For any airplane for which an LOV has not been approved as of the applicable compliance date specified in paragraph (c) or Table 1 of this section, instead of including an approved LOV in the ALS, an operator must include the applicable default LOV specified in Table 1 or Table 2 of this section, as applicable, in the ALS.

## § 121.1117

### Flammability reduction means.

. *Applicability.* Except as provided in paragraph (o) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity have:
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7,500 pounds or more.
. *New Production Airplanes.* Except in accordance with § 121.628, no certificate holder may operate an airplane identified in Table 1 of this section (including all-cargo airplanes) for which the State of Manufacture issued the original certificate of airworthiness or export airworthiness approval after December 27, 2010 unless an Ignition Mitigation Means (IMM) or Flammability Reduction Means (FRM) meeting the requirements of § 26.33 of this chapter is operational.
. *Auxiliary Fuel Tanks.* After the applicable date stated in paragraph (e) of this section, no certificate holder may operate any airplane subject to § 26.33 of this chapter that has an Auxiliary Fuel Tank installed pursuant to a field approval, unless the following requirements are met:
.. The certificate holder complies with 14 CFR 26.35 by the applicable date stated in that section.
.. The certificate holder installs Flammability Impact Mitigation Means (FIMM), if applicable, that is approved by the FAA Oversight Office.
.. Except in accordance with § 121.628, the FIMM, if applicable, is operational.
. *Retrofit.* Except as provided in paragraphs (j), (k), and (l) of this section, after the dates specified in paragraph (e) of this section, no certificate holder may operate an airplane to which this section applies unless the requirements of paragraphs (d)(1) and (d)(2) of this section are met.
.. IMM, FRM or FIMM, if required by §§ 26.33, 26.35, or 26.37 of this chapter, that are approved by the FAA Oversight Office, are installed within the compliance times specified in paragraph (e) of this section.
.. Except in accordance with § 121.628, the IMM, FRM or FIMM, as applicable, are operational.
. *Compliance Times.* Except as provided in paragraphs (k) and (l) of this section, the installations required by paragraph (d) of this section must be accomplished no later than the applicable dates specified in paragraph (e)(1), (e)(2), or (e)(3) of this section.
.. Fifty percent of each certificate holder's fleet identified in paragraph (d)(1) of this section must be modified no later than December 26, 2014.
.. One hundred percent of each certificate holder's fleet identified in paragraph (d)(1) of this section must be modified no later than December 26, 2017.
.. For those certificate holders that have only one airplane of a model identified in Table 1 of this section, the airplane must be modified no later than December 26, 2017.
              
. *Compliance After Installation.* Except in accordance with § 121.628, no certificate holder may—
.. Operate an airplane on which IMM or FRM has been installed before the dates specified in paragraph (e) of this section unless the IMM or FRM is operational, or
.. Deactivate or remove an IMM or FRM once installed unless it is replaced by a means that complies with paragraph (d) of this section.
. *Maintenance Program Revisions.* No certificate holder may operate an airplane for which airworthiness limitations have been approved by the FAA Oversight Office in accordance with §§ 26.33, 26.35, or 26.37 of this chapter after the airplane is modified in accordance with paragraph (d) of this section unless the maintenance program for that airplane is revised to include those applicable airworthiness limitations.
. After the maintenance program is revised as required by paragraph (g) of this section, before returning an airplane to service after any alteration for which airworthiness limitations are required by §§ 25.981, 26.33, or 26.37 of this chapter, the certificate holder must revise the maintenance program for the airplane to include those airworthiness limitations.
. The maintenance program changes identified in paragraphs (g) and (h) of this section must be submitted to the operator's Principal Maintenance Inspector responsible for review and approval prior to incorporation.
. The requirements of paragraph (d) of this section do not apply to airplanes operated in all-cargo service, but those airplanes are subject to paragraph (f) of this section.
. The compliance dates specified in paragraph (e) of this section may be extended by one year, provided that—
.. No later than March 26, 2009, the certificate holder notifies its assigned Flight Standards Office or Principal Inspector that it intends to comply with this paragraph;
.. No later than June 24, 2009, the certificate holder applies for an amendment to its operations specification in accordance with § 119.51 of this chapter and revises the manual required by § 121.133 to include a requirement for the airplane models specified in Table 2 of this section to use ground air conditioning systems for actual gate times of more than 30 minutes, when available at the gate and operational, whenever the ambient temperature exceeds 60 degrees Fahrenheit; and
.. Thereafter, the certificate holder uses ground air conditioning systems as described in paragraph (k)(2) of this section on each airplane subject to the extension.
. For any certificate holder for which the operating certificate is issued after December 26, 2008, the compliance date specified in paragraph (e) of this section may be extended by one year, provided that the certificate holder meets the requirements of paragraph (k)(2) of this section when its initial operations specifications are issued and, thereafter, uses ground air conditioning systems as described in paragraph (k)(2) of this section on each airplane subject to the extension.
. After the date by which any person is required by this section to modify 100 percent of the affected fleet, no certificate holder may operate in passenger service any airplane model specified in Table 2 of this section unless the airplane has been modified to comply with § 26.33(c) of this chapter.
. No certificate holder may operate any airplane on which an auxiliary fuel tank is installed after December 26, 2017 unless the FAA has certified the tank as compliant with § 25.981 of this chapter, in effect on December 26, 2008.
. *Exclusions.* The requirements of this section do not apply to the following airplane models:
.. Convair CV-240, 340, 440, including turbine powered conversions.
.. Lockheed L-188 Electra.
.. Vickers VC-10.
.. Douglas DC-3, including turbine powered conversions.
.. Bombardier CL-44.
              
.. Mitsubishi YS-11.
.. BAC 1-11.
.. Concorde.
.. deHavilland D.H. 106 Comet 4C.
.. VFW—Vereinigte Flugtechnische VFW-614.
.. Illyushin Aviation IL 96T.
.. Bristol Aircraft Britannia 305.
.. Handley Page Herald Type 300.
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C.
.. Airbus Caravelle.
.. Fokker F-27/Fairchild Hiller FH-227.
.. Lockheed L-300.

## § 121.1119

### Fuel tank vent explosion protection.

. *Applicability.* This section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that have:
.. A maximum type-certificated passenger capacity of 30 or more; or
.. A maximum payload capacity of 7,500 pounds or more.
. *New production airplanes.* No certificate holder may operate an airplane for which the State of Manufacture issued the original certificate of airworthiness or export airworthiness approval after August 23, 2018 unless means, approved by the Administrator, to prevent fuel tank explosions caused by propagation of flames from outside the fuel tank vents into the fuel tank vapor spaces are installed and operational.

