# Operating Rules
:toc:

## § 145.201 - Privileges and limitations of certificate.

[loweralpha]
. A certificated repair station may—
[arabic]
.. Perform maintenance, preventive maintenance, or alterations in accordance with part 43 on any article for which it is rated and within the limitations in its operations specifications.
.. Arrange for another person to perform the maintenance, preventive maintenance, or alterations of any article for which the certificated repair station is rated. If that person is not certificated under part 145, the certificated repair station must ensure that the noncertificated person follows a quality control system equivalent to the system followed by the certificated repair station.
.. Approve for return to service any article for which it is rated after it has performed maintenance, preventive maintenance, or an alteration in accordance with part 43.
. A certificated repair station may not maintain or alter any article for which it is not rated, and may not maintain or alter any article for which it is rated if it requires special technical data, equipment, or facilities that are not available to it.
. A certificated repair station may not approve for return to service'
[arabic]
.. Any article unless the maintenance, preventive maintenance, or alteration was performed in accordance with the applicable approved technical data or data acceptable to the FAA.
.. Any article after a major repair or major alteration unless the major repair or major alteration was performed in accordance with applicable approved technical data; and
.. Any experimental aircraft after a major repair or major alteration performed under § 43.1(b) unless the major repair or major alteration was performed in accordance with methods and applicable technical data acceptable to the FAA.

## § 145.203 - Work performed at another location.

A certificated repair station may temporarily transport material, equipment, and personnel needed to perform maintenance, preventive maintenance, alterations, or certain specialized services on an article for which it is rated to a place other than the repair station's fixed location if the following requirements are met:
              

[loweralpha]
. The work is necessary due to a special circumstance, as determined by the FAA; or
. It is necessary to perform such work on a recurring basis, and the repair station's manual includes the procedures for accomplishing maintenance, preventive maintenance, alterations, or specialized services at a place other than the repair station's fixed location.

## § 145.205 - Maintenance, preventive maintenance, and alterations performed for certificate holders under parts 121, 125, and 135, and for foreign air carriers or foreign persons operating a U.S.-registered aircraft in common carriage under part 129.

[loweralpha]
. A certificated repair station that performs maintenance, preventive maintenance, or alterations for an air carrier or commercial operator that has a continuous airworthiness maintenance program under part 121 or part 135 must follow the air carrier's or commercial operator's program and applicable sections of its maintenance manual.
. A certificated repair station that performs inspections for a certificate holder conducting operations under part 125 must follow the operator's FAA-approved inspection program.
. A certificated repair station that performs maintenance, preventive maintenance, or alterations for a foreign air carrier or foreign person operating a U.S.-registered aircraft under part 129 must follow the operator's FAA-approved maintenance program.
. The FAA may grant approval for a certificated repair station to perform line maintenance for an air carrier certificated under part 121 or part 135 of this chapter, or a foreign air carrier or foreign person operating a U.S.-registered aircraft in common carriage under part 129 of this chapter on any aircraft of that air carrier or person, provided-
[arabic]
.. The certificated repair station performs such line maintenance in accordance with the operator's manual, if applicable, and approved maintenance program;
.. The certificated repair station has the necessary equipment, trained personnel, and technical data to perform such line maintenance; and
.. The certificated repair station's operations specifications include an authorization to perform line maintenance.

## § 145.206 - Notification of hazardous materials authorizations.

[loweralpha]
. Each repair station must acknowledge receipt of the part 121 or part 135 operator notification required under §§ 121.1005(e) and 135.505(e) of this chapter prior to performing work for, or on behalf of that certificate holder.
. Prior to performing work for or on behalf of a part 121 or part 135 operator, each repair station must notify its employees, contractors, or subcontractors that handle or replace aircraft components or other items regulated by 49 CFR parts 171 through 180 of each certificate holder's operations specifications authorization permitting, or prohibition against, carrying hazardous materials. This notification must be provided subsequent to the notification by the part 121 or part 135 operator of such operations specifications authorization/designation.

## § 145.207 - Repair station manual.

[loweralpha]
. A certificated repair station must prepare and follow a repair station manual acceptable to the FAA.
. A certificated repair station must maintain a current repair station manual.
. A certificated repair station's current repair station manual must be accessible for use by repair station personnel required by subpart D of this part.
. A certificated repair station must provide to its certificate holding district office the current repair station manual in a format acceptable to the FAA.
. A certificated repair station must notify its certificate holding district office of each revision of its repair station manual in accordance with the procedures required by § 145.209(j).

## § 145.209 - Repair station manual contents.

A certificated repair station's manual must include the following:

[loweralpha]
. An organizational chart identifying—
[arabic]
.. Each management position with authority to act on behalf of the repair station,
.. The area of responsibility assigned to each management position, and
.. The duties, responsibilities, and authority of each management position;
. Procedures for maintaining and revising the rosters required by § 145.161;
. A description of the certificated repair station's operations, including the housing, facilities, equipment, and materials as required by subpart C of this part;
. Procedures for—
[arabic]
.. Revising the capability list provided for in § 145.215 and notifying the certificate holding district office of revisions to the list, including how often the certificate holding district office will be notified of revisions; and
.. The self-evaluation required under § 145.215(c) for revising the capability list, including methods and frequency of such evaluations, and procedures for reporting the results to the appropriate manager for review and action;
. Procedures for revising the training program required by § 145.163 and submitting revisions to the certificate holding district office for approval;
. Procedures to govern work performed at another location in accordance with § 145.203;
. Procedures for maintenance, preventive maintenance, or alterations performed under § 145.205;
. for—
[arabic]
.. Maintaining and revising the contract maintenance information required by § 145.217(a)(2)(i), including submitting revisions to the certificate holding district office for approval; and
.. Maintaining and revising the contract maintenance information required by § 145.217(a)(2)(ii) and notifying the certificate holding district office of revisions to this information, including how often the certificate holding district office will be notified of revisions;
[lowerroman]
... A description of the required records and the recordkeeping system used to obtain, store, and retrieve the required records;

(j) Procedures for revising the repair station's manual and notifying its certificate holding district office of revisions to the manual, including how often the certificate holding district office will be notified of revisions; and

(k) A description of the system used to identify and control sections of the repair station manual.

## § 145.211 - Quality control system.

[loweralpha]
. A certificated repair station must establish and maintain a quality control system acceptable to the FAA that ensures the airworthiness of the articles on which the repair station or any of its contractors performs maintenance, preventive maintenance, or alterations.
. Repair station personnel must follow the quality control system when performing maintenance, preventive maintenance, or alterations under the repair station certificate and operations specifications.
. A certificated repair station must prepare and keep current a quality control manual in a format acceptable to the FAA that includes the following:
[arabic]
.. A description of the system and procedures used for—
[lowerroman]
... Inspecting incoming raw materials to ensure acceptable quality;
... Performing preliminary inspection of all articles that are maintained;
... Inspecting all articles that have been involved in an accident for hidden damage before maintenance, preventive maintenance, or alteration is performed;
... Establishing and maintaining proficiency of inspection personnel;
... Establishing and maintaining current technical data for maintaining articles;
... Qualifying and surveilling noncertificated persons who perform maintenance, prevention maintenance, or alterations for the repair station;
... Performing final inspection and return to service of maintained articles;
              
... Calibrating measuring and test equipment used in maintaining articles, including the intervals at which the equipment will be calibrated; and
... Taking corrective action on deficiencies;
.. References, where applicable, to the manufacturer's inspection standards for a particular article, including reference to any data specified by that manufacturer;
.. A sample of the inspection and maintenance forms and instructions for completing such forms or a reference to a separate forms manual; and
.. Procedures for revising the quality control manual required under this section and notifying the certificate holding district office of the revisions, including how often the certificate holding district office will be notified of revisions.
. A certificated repair station must notify its certificate holding district office of revisions to its quality control manual.

## § 145.213 - Inspection of maintenance, preventive maintenance, or alterations.

[loweralpha]
. A certificated repair station must inspect each article upon which it has performed maintenance, preventive maintenance, or alterations as described in paragraphs (b) and (c) of this section before approving that article for return to service.
. A certificated repair station must certify on an article's maintenance release that the article is airworthy with respect to the maintenance, preventive maintenance, or alterations performed after—
[arabic]
.. The repair station performs work on the article; and
.. An inspector inspects the article on which the repair station has performed work and determines it to be airworthy with respect to the work performed.
. For the purposes of paragraphs (a) and (b) of this section, an inspector must meet the requirements of § 145.155.
. Except for individuals employed by a repair station located outside the United States, only an employee appropriately certificated as a mechanic or repairman under part 65 is authorized to sign off on final inspections and maintenance releases for the repair station.

## § 145.215 - Capability list.

[loweralpha]
. A certificated repair station with a limited rating may perform maintenance, preventive maintenance, or alterations on an article if the article is listed on a current capability list acceptable to the FAA or on the repair station's operations specifications.
. The capability list must identify each article by make and model or other nomenclature designated by the article's manufacturer and be available in a format acceptable to the FAA.
. An article may be listed on the capability list only if the article is within the scope of the ratings of the repair station's certificate, and only after the repair station has performed a self-evaluation in accordance with the procedures under § 145.209(d)(2). The repair station must perform this self-evaluation to determine that the repair station has all of the housing, facilities, equipment, material, technical data, processes, and trained personnel in place to perform the work on the article as required by part 145. The repair station must retain on file documentation of the evaluation.
. Upon listing an additional article on its capability list, the repair station must provide its certificate holding district office with a copy of the revised list in accordance with the procedures required in § 145.209(d)(1).

## § 145.217 - Contract maintenance.

[loweralpha]
. A certificated repair station may contract a maintenance function pertaining to an article to an outside source provided—
[arabic]
.. The FAA approves the maintenance function to be contracted to the outside source; and
.. The repair station maintains and makes available to its certificate holding district office, in a format acceptable to the FAA, the following information:
[lowerroman]
... The maintenance functions contracted to each outside facility; and
              
... The name of each outside facility to whom the repair station contracts maintenance functions and the type of certificate and ratings, if any, held by each facility.
. A certificated repair station may contract a maintenance function pertaining to an article to a noncertificated person provided—
[arabic]
.. The noncertificated person follows a quality control system equivalent to the system followed by the certificated repair station;
.. The certificated repair station remains directly in charge of the work performed by the noncertificated person; and
.. The certificated repair station verifies, by test and/or inspection, that the work has been performed satisfactorily by the noncertificated person and that the article is airworthy before approving it for return to service.
. A certificated repair station may not provide only approval for return to service of a complete type-certificated product following contract maintenance, preventive maintenance, or alterations.

## § 145.219 - Recordkeeping.

[loweralpha]
. A certificated repair station must retain records in English that demonstrate compliance with the requirements of part 43. The records must be retained in a format acceptable to the FAA.
. A certificated repair station must provide a copy of the maintenance release to the owner or operator of the article on which the maintenance, preventive maintenance, or alteration was performed.
. A certificated repair station must retain the records required by this section for at least 2 years from the date the article was approved for return to service.
. A certificated repair station must make all required records available for inspection by the FAA and the National Transportation Safety Board.

## § 145.221 - Service difficulty reports.

[loweralpha]
. A certificated repair station must report to the FAA within 96 hours after it discovers any serious failure, malfunction, or defect of an article. The report must be in a format acceptable to the FAA.
. The report required under paragraph (a) of this section must include as much of the following information as is available:
[arabic]
.. Aircraft registration number;
.. Type, make, and model of the article;
.. Date of the discovery of the failure, malfunction, or defect;
.. Nature of the failure, malfunction, or defect;
.. Time since last overhaul, if applicable;
.. Apparent cause of the failure, malfunction, or defect; and
.. Other pertinent information that is necessary for more complete identification, determination of seriousness, or corrective action.
. The holder of a repair station certificate that is also the holder of a part 121, 125, or 135 certificate; type certificate (including a supplemental type certificate); parts manufacturer approval; or technical standard order authorization, or that is the licensee of a type certificate holder, does not need to report a failure, malfunction, or defect under this section if the failure, malfunction, or defect has been reported under parts 21, 121, 125, or 135 of this chapter.
. A certificated repair station may submit a service difficulty report for the following:
[arabic]
.. A part 121 certificate holder, provided the report meets the requirements of part 121 of this chapter, as appropriate.
.. A part 125 certificate holder, provided the report meets the requirements of part 125 of this chapter, as appropriate.
.. A part 135 certificate holder, provided the report meets the requirements of part 135 of the chapter, as appropriate.
. A certificated repair station authorized to report a failure, malfunction, or defect under paragraph (d) of this section must not report the same failure, malfunction, or defect under paragraph (a) of this section. A copy of the report submitted under paragraph (d) of this section must be forwarded to the certificate holder.

## § 145.223 - FAA inspections.

[loweralpha]
. A certificated repair station must allow the FAA to inspect that repair station at any time to determine compliance with this chapter.
. A certificated repair station may not contract for the performance of a maintenance function on an article with a noncertificated person unless it provides in its contract with the noncertificated person that the FAA may make an inspection and observe the performance of the noncertificated person's work on the article.
. A certificated repair station may not return to service any article on which a maintenance function was performed by a noncertificated person if the noncertificated person does not permit the FAA to make the inspection described in paragraph (b) of this section.

