# Airline Transport Pilots
:toc:

## § 61.151 - Applicability.

This subpart prescribes the requirements for the issuance of airline transport pilot certificates and ratings, the conditions under which those certificates and ratings are necessary, and the general operating rules for persons who hold those certificates and ratings.

## § 61.153 - Eligibility requirements: General.

To be eligible for an airline transport pilot certificate, a person must:

[loweralpha]
. Meet the following age requirements:
[arabic]
.. For an airline transport pilot certificate obtained under the aeronautical experience requirements of §§ 61.159, 61.161, or 61.163, be at least 23 years of age; or
.. For an airline transport pilot certificate obtained under the aeronautical experience requirements of § 61.160, be at least 21 years of age.
. Be able to read, speak, write, and understand the English language. If the applicant is unable to meet one of these requirements due to medical reasons, then the Administrator may place such operating limitations on that applicant's pilot certificate as are necessary for the safe operation of the aircraft;
. Be of good moral character;
. Meet at least one of the following requirements:
[arabic]
.. Holds a commercial pilot certificate with an instrument rating issued under this part;
.. Meet the military experience requirements under § 61.73 of this part to qualify for a commercial pilot certificate, and an instrument rating if the person is a rated military pilot or former rated military pilot of an Armed Force of the United States; or
.. Holds either a foreign airline transport pilot license with instrument privileges, or a foreign commercial pilot license with an instrument rating, that—
[lowerroman]
... Was issued by a contracting State to the Convention on International Civil Aviation; and
... Contains no geographical limitations.
. After July 31, 2014, for an airline transport pilot certificate with an airplane category multiengine class rating or an airline transport pilot certificate obtained concurrently with an airplane type rating, receive a graduation certificate from an authorized training provider certifying completion of the airline transport pilot certification training program specified in § 61.156 before applying for the knowledge test required by paragraph (g) of this section;
. Meet the aeronautical experience requirements of this subpart that apply to the aircraft category and class rating sought before applying for the practical test;
. Pass a knowledge test on the aeronautical knowledge areas of § 61.155(c) of this part that apply to the aircraft category and class rating sought;
. Pass the practical test on the areas of operation listed in § 61.157(e) of this part that apply to the aircraft category and class rating sought; and
[lowerroman]
.. Comply with the sections of this subpart that apply to the aircraft category and class rating sought.

## § 61.155 - Aeronautical knowledge.

[loweralpha]
. *General.* The knowledge test for an airline transport pilot certificate is based on the aeronautical knowledge areas listed in paragraph (c) of this section that are appropriate to the aircraft category and class rating sought.
. *Aircraft type rating.* A person who is applying for an additional aircraft type rating to be added to an airline transport pilot certificate is not required to pass a knowledge test if that person's airline transport pilot certificate lists the aircraft category and class rating that is appropriate to the type rating sought.
. *Aeronautical knowledge areas.*
[arabic]
.. Applicable Federal Aviation Regulations of this chapter that relate to airline transport pilot privileges, limitations, and flight operations;
.. Meteorology, including knowledge of and effects of fronts, frontal characteristics, cloud formations, icing, and upper-air data;
.. General system of weather and NOTAM collection, dissemination, interpretation, and use;
.. Interpretation and use of weather charts, maps, forecasts, sequence reports, abbreviations, and symbols;
.. National Weather Service functions as they pertain to operations in the National Airspace System;
.. Windshear and microburst awareness, identification, and avoidance;
.. Principles of air navigation under instrument meteorological conditions in the National Airspace System;
.. Air traffic control procedures and pilot responsibilities as they relate to en route operations, terminal area and radar operations, and instrument departure and approach procedures;
.. Aircraft loading, weight and balance, use of charts, graphs, tables, formulas, and computations, and their effect on aircraft performance;
.. Aerodynamics relating to an aircraft's flight characteristics and performance in normal and abnormal flight regimes;
.. Human factors;
.. Aeronautical decision making and judgment;
.. Crew resource management to include crew communication and coordination; and
.. After July 31, 2014, for airplane category multiengine class rating or airplane type rating, the content of the airline transport pilot certification training program in § 61.156.
. An applicant who successfully completes the knowledge test for an airline transport pilot certificate prior to August 1, 2014, must successfully complete the practical test within 24 months from the month in which the knowledge test was successfully completed. An applicant who passes the knowledge test prior to August 1, 2014, but fails to successfully complete the airplane category with a multiengine class rating practical test within 24 months must complete the airline transport pilot certification training program specified in § 61.156 and retake the knowledge test prior to applying for the airplane category with a multiengine class rating practical test.

## § 61.156 - Training requirements: Airplane category—multiengine class rating or airplane type rating concurrently with airline transport pilot certificate.

After July 31, 2014, a person who applies for the knowledge test for an airline transport pilot certificate with an airplane category multiengine class rating must present a graduation certificate from an authorized training provider under part 121, 135, 141, or 142 of this chapter certifying the applicant has completed the following training in a course approved by the Administrator.

[loweralpha]
. *Academic training.* The applicant for the knowledge test must receive at least 30 hours of classroom instruction that includes the following:
[arabic]
.. At least 8 hours of instruction on aerodynamics including high altitude operations;
.. At least 2 hours of instruction on meteorology, including adverse weather phenomena and weather detection systems; and
.. At least 14 hours of instruction on air carrier operations, including the following areas:
[lowerroman]
... Physiology;
... Communications;
... Checklist philosophy;
... Operational control;
... Minimum equipment list/configuration deviation list;
... Ground operations;
... Turbine engines;
... Transport category aircraft performance;
... Automation, navigation, and flight path warning systems.
.. At least 6 hours of instruction on leadership, professional development, crew resource management, and safety culture.
. *FSTD training.* The applicant for the knowledge test must receive at least 10 hours of training in a flight simulation training device qualified under part 60 of this chapter that represents a multiengine turbine airplane. The training must include the following:
[arabic]
.. At least 6 hours of training in a Level C or higher full flight simulator qualified under part 60 of this chapter that represents a multiengine turbine airplane with a maximum takeoff weight of 40,000 pounds or greater. The training must include the following areas:
[lowerroman]
... Low energy states/stalls;
... Upset recovery techniques; and
... Adverse weather conditions, including icing, thunderstorms, and crosswinds with gusts.
.. The remaining FSTD training may be completed in a Level 4 or higher flight simulation training device. The training must include the following areas:
[lowerroman]
... Navigation including flight management systems; and
... Automation including autoflight.
. *Deviation authority.* The Administrator may issue deviation authority from the weight requirement in paragraph (b)(1) of this section upon a determination that the objectives of the training can be met in an alternative device.

## § 61.157 - Flight proficiency.

[loweralpha]
. *General.*
[arabic]
.. The practical test for an airline transport pilot certificate is given for—
[lowerroman]
... An airplane category and single engine class rating.
... An airplane category and multiengine class rating.
... A rotorcraft category and helicopter class rating.
... A powered-lift category rating.
... An aircraft type rating.
.. A person who is applying for an airline transport pilot practical test must meet—
[lowerroman]
... The eligibility requirements of § 61.153; and
... The aeronautical knowledge and aeronautical experience requirements of this subpart that apply to the aircraft category and class rating sought.
. *Aircraft type rating.* Except as provided in paragraph (c) of this section, a person who applies for an aircraft type rating to be added to an airline transport pilot certificate or applies for a type rating to be concurrently completed with an airline transport pilot certificate:
[arabic]
.. Must receive and log ground and flight training from an authorized instructor on the areas of operation under this section that apply to the aircraft type rating;
.. Must receive a logbook endorsement from an authorized instructor that certifies the applicant completed the training on the areas of operation listed under paragraph (e) of this section that apply to the aircraft type rating; and
              
.. Must perform the practical test in actual or simulated instrument conditions, except as provided under paragraph (g) of this section.
. *Exceptions.* A person who applies for an aircraft type rating to be added to an airline transport pilot certificate or an aircraft type rating concurrently with an airline transport pilot certificate, and who is an employee of a certificate holder operating under part 121 or part 135 of this chapter, does not need to comply with the requirements of paragraph (b) of this section if the applicant presents a training record that shows completion of that certificate holder's approved training program for the aircraft type rating.
. *Upgrading type ratings.* Any type rating(s) and limitations on a pilot certificate of an applicant who completes an airline transport pilot practical test will be included at the airline transport pilot certification level, provided the applicant passes the practical test in the same category and class of aircraft for which the applicant holds the type rating(s).
. *Areas of operation.*
[arabic]
.. For an airplane category—single engine class rating:
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Takeoff and departure phase;
... In-flight maneuvers;
... Instrument procedures;
... Landings and approaches to landings;
... Normal and abnormal procedures;
... Emergency procedures; and
... Postflight procedures.
.. For an airplane category—multiengine class rating:
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Takeoff and departure phase;
... In-flight maneuvers;
... Instrument procedures;
... Landings and approaches to landings;
... Normal and abnormal procedures;
... Emergency procedures; and
... Postflight procedures.
.. For a powered-lift category rating:
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Takeoff and departure phase;
... In-flight maneuvers;
... Instrument procedures;
... Landings and approaches to landings;
... Normal and abnormal procedures;
... Emergency procedures; and
... Postflight procedures.
.. For a rotorcraft category—helicopter class rating:
[lowerroman]
... Preflight preparation;
... Preflight procedures;
... Takeoff and departure phase;
... In-flight maneuvers;
... Instrument procedures;
... Landings and approaches to landings;
... Normal and abnormal procedures;
... Emergency procedures; and
... Postflight procedures.
. *Proficiency and competency checks conducted under part 121, part 135, or subpart K of part 91.*
[arabic]
.. Successful completion of any of the following checks satisfies the flight proficiency requirements of this section for the issuance of an airline transport pilot certificate and/or the appropriate aircraft rating:
[lowerroman]
... A proficiency check under § 121.441 of this chapter.
... Both a competency check under § 135.293(a)(2) and § 135.293(b) of this chapter and pilot-in-command instrument proficiency check under § 135.297 of this chapter.
... Both a competency check under § 91.1065 of this chapter and a pilot-in-command instrument proficiency check under § 91.1069 of this chapter.
.. The checks specified in paragraph (f)(1) of this section must be conducted by one of the following:
[lowerroman]
... An FAA Aviation Safety Inspector.
... An Aircrew Program Designee who is authorized to perform proficiency and/or competency checks for the air carrier whose approved training program has been satisfactorily completed by the pilot applicant.
... A Training Center Evaluator with appropriate certification authority who is also authorized to perform the portions of the competency and/or proficiency checks required by paragraph (f)(1) of this section for the air carrier whose approved training program has been satisfactorily completed by the pilot applicant.
. *Aircraft not capable of instrument maneuvers and procedures.* An applicant may add a type rating to an airline transport pilot certificate with an aircraft that is not capable of the instrument maneuvers and procedures required on the practical test under the following circumstances—
[arabic]
.. The rating is limited to “VFR only.”
.. The type rating is added to an airline transport pilot certificate that has instrument privileges in that category and class of aircraft.
.. The “VFR only” limitation may be removed for that aircraft type after the applicant:
[lowerroman]
... Passes a practical test in that type of aircraft on the appropriate instrument maneuvers and procedures in § 61.157; or
... Becomes qualified in § 61.73(d) for that type of aircraft.
. *Multiengine airplane with a single-pilot station.* An applicant for a type rating, at the ATP certification level, in a multiengine airplane with a single-pilot station must perform the practical test in the multi-seat version of that airplane. The practical test may be performed in the single-seat version of that airplane if the Examiner is in a position to observe the applicant during the practical test in the case where there is no multi-seat version of that multiengine airplane.
[lowerroman]
.. *Single engine airplane with a single-pilot station.* An applicant for a type rating, at the ATP certification level, in a single engine airplane with a single-pilot station must perform the practical test in the multi-seat version of that single engine airplane. The practical test may be performed in the single-seat version of that airplane if the Examiner is in a position to observe the applicant during the practical test in the case where there is no multi-seat version of that single engine airplane.

(j) *Waiver authority.* An Examiner who conducts a practical test may waive any task for which the FAA has provided waiver authority.

## § 61.158 - Reserved


Reserved

## § 61.159 - Aeronautical experience: Airplane category rating.

[loweralpha]
. Except as provided in paragraphs (b), (c), and (d) of this section, a person who is applying for an airline transport pilot certificate with an airplane category and class rating must have at least 1,500 hours of total time as a pilot that includes at least:
[arabic]
.. 500 hours of cross-country flight time.
.. 100 hours of night flight time.
.. 50 hours of flight time in the class of airplane for the rating sought. A maximum of 25 hours of training in a full flight simulator representing the class of airplane for the rating sought may be credited toward the flight time requirement of this paragraph if the training was accomplished as part of an approved training course in parts 121, 135, 141, or 142 of this chapter. A flight training device or aviation training device may not be used to satisfy this requirement.
.. 75 hours of instrument flight time, in actual or simulated instrument conditions, subject to the following:
[lowerroman]
... Except as provided in paragraph (a)(4)(ii) of this section, an applicant may not receive credit for more than a total of 25 hours of simulated instrument time in a flight simulator or flight training device.
... A maximum of 50 hours of training in a flight simulator or flight training device may be credited toward the instrument flight time requirements of paragraph (a)(4) of this section if the training was accomplished in a course conducted by a training center certificated under part 142 of this chapter.
... Training in a flight simulator or flight training device must be accomplished in a flight simulator or flight training device, representing an airplane.
.. 250 hours of flight time in an airplane as a pilot in command, or as second in command performing the duties of pilot in command while under the supervision of a pilot in command, or any combination thereof, which includes at least—
[lowerroman]
... 100 hours of cross-country flight time; and
... 25 hours of night flight time.
.. Not more than 100 hours of the total aeronautical experience requirements of paragraph (a) of this section or § 61.160 may be obtained in a full flight simulator or flight training device provided the device represents an airplane and the aeronautical experience was accomplished as part of an approved training course in parts 121, 135, 141, or 142 of this chapter.
. A person who has performed at least 20 night takeoffs and landings to a full stop may substitute each additional night takeoff and landing to a full stop for 1 hour of night flight time to satisfy the requirements of paragraph (a)(2) of this section; however, not more than 25 hours of night flight time may be credited in this manner.
. A commercial pilot may credit the following second-in-command flight time or flight-engineer flight time toward the 1,500 hours of total time as a pilot required by paragraph (a) of this section:
[arabic]
.. Second-in-command time, provided the time is acquired in an airplane—
[lowerroman]
... Required to have more than one pilot flight crewmember by the airplane's flight manual, type certificate, or the regulations under which the flight is being conducted;
... Engaged in operations under subpart K of part 91, part 121, or part 135 of this chapter for which a second in command is required; or
... That is required by the operating rules of this chapter to have more than one pilot flight crewmember.
.. Flight-engineer time, provided the time—
[lowerroman]
... Is acquired in an airplane required to have a flight engineer by the airplane's flight manual or type certificate;
... Is acquired while engaged in operations under part 121 of this chapter for which a flight engineer is required;
... Is acquired while the person is participating in a pilot training program approved under part 121 of this chapter; and
... Does not exceed more than 1 hour for each 3 hours of flight engineer flight time for a total credited time of no more than 500 hours.
.. Flight-engineer time, provided the flight time—
[lowerroman]
... Is acquired as a U.S. Armed Forces' flight engineer crewmember in an airplane that requires a flight engineer crewmember by the flight manual;
... Is acquired while the person is participating in a flight engineer crewmember training program for the U.S. Armed Forces; and
... Does not exceed 1 hour for each 3 hours of flight engineer flight time for a total credited time of no more than 500 hours.
. An applicant is issued an airline transport pilot certificate with the limitation, “Holder does not meet the pilot in command aeronautical experience requirements of ICAO,” as prescribed under Article 39 of the Convention on International Civil Aviation, if the applicant does not meet the ICAO requirements contained in Annex 1 “Personnel Licensing” to the Convention on International Civil Aviation, but otherwise meets the aeronautical experience requirements of this section.
. An applicant is entitled to an airline transport pilot certificate without the ICAO limitation specified under paragraph (d) of this section when the applicant presents satisfactory evidence of having met the ICAO requirements under paragraph (d) of this section and otherwise meets the aeronautical experience requirements of this section.

## § 61.160 - Aeronautical experience—airplane category restricted privileges.

[loweralpha]
. Except for a person who has been removed from flying status for lack of proficiency or because of a disciplinary action involving aircraft operations, a U.S. military pilot or former U.S. military pilot may apply for an airline transport pilot certificate with an airplane category multiengine class rating or an airline transport pilot certificate concurrently with an airplane type rating with a minimum of 750 hours of total time as a pilot if the pilot presents:
[arabic]
.. An official Form DD-214 (Certificate of Release or Discharge from Active Duty) indicating that the person was honorably discharged from the U.S. Armed Forces or an official U.S. Armed Forces record that shows the pilot is currently serving in the U.S. Armed Forces; and
.. An official U.S. Armed Forces record that shows the person graduated from a U.S. Armed Forces undergraduate pilot training school and received a rating qualification as a military pilot.
. A person may apply for an airline transport pilot certificate with an airplane category multiengine class rating or an airline transport pilot certificate concurrently with an airplane type rating with a minimum of 1,000 hours of total time as a pilot if the person:
[arabic]
.. Holds a Bachelor's degree with an aviation major from an institution of higher education, as defined in § 61.1, that has been issued a letter of authorization by the Administrator under § 61.169;
.. Completes 60 semester credit hours of aviation and aviation-related coursework that has been recognized by the Administrator as coursework designed to improve and enhance the knowledge and skills of a person seeking a career as a professional pilot;
.. Holds a commercial pilot certificate with an airplane category and instrument rating if:
[lowerroman]
... The required ground training was completed as part of an approved part 141 curriculum at the institution of higher education; and
... The required flight training was completed as part of an approved part 141 curriculum at the institution of higher education or at a part 141 pilot school that has a training agreement under § 141.26 of this chapter with the institution of higher education; and
.. Presents official transcripts or other documentation acceptable to the Administrator from the institution of higher education certifying that the graduate has satisfied the requirements in paragraphs (b)(1) through (3) of this section.
. A person may apply for an airline transport pilot certificate with an airplane category multiengine class rating or an airline transport pilot certificate concurrently with an airplane type rating with a minimum of 1,250 hours of total time as a pilot if the person:
[arabic]
.. Holds an Associate's degree with an aviation major from an institution of higher education, as defined in § 61.1, that has been issued a letter of authorization by the Administrator under § 61.169;
.. Completes at least 30 semester credit hours of aviation and aviation-related coursework that has been recognized by the Administrator as coursework designed to improve and enhance the knowledge and skills of a person seeking a career as a professional pilot;
.. Holds a commercial pilot certificate with an airplane category and instrument rating if:
[lowerroman]
... The required ground training was completed as part of an approved part 141 curriculum at the institution of higher education; and
... The required flight training was completed as part of an approved part 141 curriculum at the institution of higher education or at a part 141 pilot school that has a written training agreement under § 141.26 of this chapter with the institution of higher education; and
.. Presents official transcripts or other documentation acceptable to the Administrator from the institution of higher education certifying that the graduate has satisfied the requirements in paragraphs (c)(1) through (3) of this section.
. A graduate of an institution of higher education who completes fewer than 60 semester credit hours but at least 30 credit hours and otherwise satisfies the requirements of paragraph (b) may apply for airline transport pilot certificate with an airplane category multiengine class rating or an airline transport pilot certificate concurrently with an airplane type rating with a minimum of 1,250 hours of total time as a pilot.
. A person who applies for an airline transport pilot certificate under the total flight times listed in paragraphs (a), (b), and (c) of this section must otherwise meet the aeronautical experience requirements of § 61.159, except that the person may apply for an airline transport pilot certificate with 200 hours of cross-country flight time.
. A person who has 1,500 hours total time as a pilot, 200 hours of cross-country flight time, and otherwise meets the aeronautical experience requirements of § 61.159 may apply for an airline transport pilot certificate under this section.
. An airline transport pilot certificate obtained under this section is subject to the pilot in command limitations set forth in § 61.167(b) and must contain the following limitation, “Restricted in accordance with 14 CFR 61.167.” The pilot is entitled to an airline transport pilot certificate without the limitation specified in this paragraph when the applicant presents satisfactory evidence of having met the aeronautical experience requirements of § 61.159 and the age requirement of § 61.153(a)(1).
. An applicant who meets the aeronautical experience requirements of paragraphs (a), (b), (c), and (d) of this section is issued an airline transport pilot certificate with the limitation, “Holder does not meet the pilot in command aeronautical experience requirements of ICAO,” as prescribed under Article 39 of the Convention on International Civil Aviation if the applicant does not meet the ICAO requirements contained in Annex 1 “Personnel Licensing” to the Convention on International Civil Aviation. An applicant is entitled to an airline transport pilot certificate without the ICAO limitation specified under this paragraph when the applicant presents satisfactory evidence of having met the ICAO requirements and otherwise meets the aeronautical experience requirements of § 61.159.

## § 61.161 - Aeronautical experience: Rotorcraft category and helicopter class rating.

[loweralpha]
. A person who is applying for an airline transport pilot certificate with a rotorcraft category and helicopter class rating, must have at least 1,200 hours of total time as a pilot that includes at least:
[arabic]
.. 500 hours of cross-country flight time;
.. 100 hours of night flight time, of which 15 hours are in helicopters;
.. 200 hours of flight time in helicopters, which includes at least 75 hours as a pilot in command, or as second in command performing the duties of a pilot in command under the supervision of a pilot in command, or any combination thereof; and
.. 75 hours of instrument flight time in actual or simulated instrument meteorological conditions, of which at least 50 hours are obtained in flight with at least 25 hours in helicopters as a pilot in command, or as second in command performing the duties of a pilot in command under the supervision of a pilot in command, or any combination thereof.
. Training in a flight simulator or flight training device may be credited toward the instrument flight time requirements of paragraph (a)(4) of this section, subject to the following:
[arabic]
.. Training in a flight simulator or a flight training device must be accomplished in a flight simulator or flight training device that represents a rotorcraft.
.. Except as provided in paragraph (b)(3) of this section, an applicant may receive credit for not more than a total of 25 hours of simulated instrument time in a flight simulator and flight training device.
.. A maximum of 50 hours of training in a flight simulator or flight training device may be credited toward the instrument flight time requirements of paragraph (a)(4) of this section if the aeronautical experience is accomplished in an approved course conducted by a training center certificated under part 142 of this chapter.

## § 61.163 - Aeronautical experience: Powered-lift category rating.

[loweralpha]
. A person who is applying for an airline transport pilot certificate with a powered-lift category rating must have at least 1,500 hours of total time as a pilot that includes at least:
[arabic]
.. 500 hours of cross-country flight time;
.. 100 hours of night flight time;
.. 250 hours in a powered-lift as a pilot in command, or as a second in command performing the duties of a pilot in command under the supervision of a pilot in command, or any combination thereof, which includes at least—
[lowerroman]
... 100 hours of cross-country flight time; and
... 25 hours of night flight time.
.. 75 hours of instrument flight time in actual or simulated instrument conditions, subject to the following:
[lowerroman]
... Except as provided in paragraph (a)(4)(ii) of this section, an applicant may not receive credit for more than a total of 25 hours of simulated instrument time in a flight simulator or flight training device.
... A maximum of 50 hours of training in a flight simulator or flight training device may be credited toward the instrument flight time requirements of paragraph (a)(4) of this section if the training was accomplished in a course conducted by a training center certificated under part 142 of this chapter.
... Training in a flight simulator or flight training device must be accomplished in a flight simulator or flight training device that represents a powered-lift.
. Not more than 100 hours of the total aeronautical experience requirements of paragraph (a) of this section may be obtained in a flight simulator or flight training device that represents a powered-lift, provided the aeronautical experience was obtained in an approved course conducted by a training center certificated under part 142 of this chapter.

## § 61.165 - Additional aircraft category and class ratings.

[loweralpha]
. *Rotorcraft category and helicopter class rating.* A person applying for an airline transport certificate with a rotorcraft category and helicopter class rating who holds an airline transport pilot certificate with another aircraft category rating must:
[arabic]
.. Meet the eligibility requirements of § 61.153 of this part;
.. Pass a knowledge test on the aeronautical knowledge areas of § 61.155(c) of this part;
.. Comply with the requirements in § 61.157(b) of this part, if appropriate;
.. Meet the applicable aeronautical experience requirements of § 61.161 of this part; and
.. Pass the practical test on the areas of operation of § 61.157(e)(4) of this part.
. *Airplane category rating with a single-engine class rating.* A person applying for an airline transport certificate with an airplane category and single-engine class rating who holds an airline transport pilot certificate with another aircraft category rating must:
[arabic]
.. Meet the eligibility requirements of § 61.153 of this part;
.. Pass a knowledge test on the aeronautical knowledge areas of § 61.155(c) of this part;
.. Comply with the requirements in § 61.157(b) of this part, if appropriate;
.. Meet the applicable aeronautical experience requirements of § 61.159 of this part; and
.. Pass the practical test on the areas of operation of § 61.157(e)(1) of this part.
. *Airplane category rating with a multiengine class rating.* A person applying for an airline transport certificate with an airplane category and multiengine class rating who holds an airline transport certificate with another aircraft category rating must:
[arabic]
.. Meet the eligibility requirements of § 61.153 of this part;
.. After July 31, 2014, successfully complete the airline transport pilot certification training program specified in § 61.156;
.. Pass a knowledge test for an airplane category multiengine class rating or type rating on the aeronautical knowledge areas of § 61.155(c);
              
.. Comply with the requirements in § 61.157(b) of this part, if appropriate;
.. Meet the aeronautical experience requirements of § 61.159 or § 61.160; and
.. Pass the practical test on the areas of operation of § 61.157(e)(2) of this part.
. *Powered-lift category.* A person applying for an airline transport pilot certificate with a powered-lift category rating who holds an airline transport certificate with another aircraft category rating must:
[arabic]
.. Meet the eligibility requirements of § 61.153 of this part;
.. Pass a required knowledge test on the aeronautical knowledge areas of § 61.155(c) of this part;
.. Comply with the requirements in § 61.157(b) of this part, if appropriate;
.. Meet the applicable aeronautical experience requirements of § 61.163 of this part; and
.. Pass the required practical test on the areas of operation of § 61.157(e)(3) of this part.
. *Additional class rating within the same aircraft category.* Except as provided in paragraph (f) of this section, a person applying for an airline transport pilot certificate with an additional class rating who holds an airline transport certificate in the same aircraft category must—
[arabic]
.. Meet the eligibility requirements of § 61.153, except paragraph (g) of that section;
.. Comply with the requirements in § 61.157(b) of this part, if applicable;
.. Meet the applicable aeronautical experience requirements of subpart G of this part; and
.. Pass a practical test on the areas of operation of § 61.157(e) appropriate to the aircraft rating sought.
. *Adding a multiengine class rating or airplane type rating to an airline transport pilot certificate with a single engine class rating.* A person applying to add a multiengine class rating or airplane type rating to an airline transport pilot certificate with an airplane category single engine class rating must—
[arabic]
.. Meet the eligibility requirements of § 61.153;
.. After July 31, 2014, pass a required knowledge test on the aeronautical knowledge areas of § 61.155(c), as applicable to multiengine airplanes; unless a pilot can present valid airline transport pilot knowledge test results from a test taken prior to August 1, 2014.
.. Comply with the requirements in § 61.157(b), if applicable;
.. Meet the applicable aeronautical experience requirements of § 61.159; and
.. Pass a practical test on the areas of operation of § 61.157(e)(2).
. *Category class ratings for the operation of aircraft with experimental certificates.* Notwithstanding the provisions of paragraphs (a) through (f) of this section, a person holding an airline transport certificate may apply for a category and class rating limited to a specific make and model of experimental aircraft, provided—
[arabic]
.. The person has logged at least 5 hours flight time while acting as pilot in command in the same category, class, make, and model of aircraft that has been issued an experimental certificate;
.. The person has received a logbook endorsement from an authorized instructor who has determined that he or she is proficient to act as pilot in command of the same category, class, make, and model of aircraft for which application is made; and
.. The flight time specified in paragraph (g)(1) of this section must be logged between September 1, 2004 and August 31, 2005.

## § 61.167 - Airline transport pilot privileges and limitations.

[loweralpha]
. *Privileges.*
[arabic]
.. A person who holds an airline transport pilot certificate is entitled to the same privileges as a person who holds a commercial pilot certificate with an instrument rating.
.. A person who holds an airline transport pilot certificate and has met the aeronautical experience requirements of § 61.159 or § 61.161, and the age requirements of § 61.153(a)(1) of this part may instruct—
[lowerroman]
... Other pilots in air transportation service in aircraft of the category, class, and type, as applicable, for which the airline transport pilot is rated and endorse the logbook or other training record of the person to whom training has been given;
... In flight simulators, and flight training devices representing the aircraft referenced in paragraph (a)(2)(i) of this section, when instructing under the provisions of this section and endorse the logbook or other training record of the person to whom training has been given;
... Only as provided in this section, except that an airline transport pilot who also holds a flight instructor certificate can exercise the instructor privileges under subpart H of this part for which he or she is rated; and
... In an aircraft, only if the aircraft has functioning dual controls, when instructing under the provisions of this section.
.. Excluding briefings and debriefings, an airline transport pilot may not instruct in aircraft, flight simulators, and flight training devices under this section—
[lowerroman]
... For more than 8 hours in any 24-consecutive-hour period; or
... For more than 36 hours in any 7-consecutive-day period.
.. An airline transport pilot may not instruct in Category II or Category III operations unless he or she has been trained and successfully tested under Category II or Category III operations, as applicable.
. *Limitations.* A person who holds an airline transport pilot certificate and has not satisfied the age requirement of § 61.153(a)(1) and the aeronautical experience requirements of § 61.159 may not:
[arabic]
.. Act as pilot in command in operations conducted under part 121, § 91.1053(a)(2)(i), or § 135.243(a)(1) of this chapter, or
.. Serve as second in command in flag or supplemental operations in part 121 of this chapter requiring three or more pilots.

## § 61.169 - Letters of authorization for institutions of higher education.

[loweralpha]
. An institution of higher education that is accredited, as defined in § 61.1, may apply for a letter of authorization for the purpose of certifying its graduates for an airline transport pilot certificate under the academic and aeronautical experience requirements in § 61.160. The application must be in a form and manner acceptable to the Administrator.
. An institution of higher education must comply with the provisions of the letter of authorization and may not certify a graduate unless it determines that the graduate has satisfied the requirements of § 61.160, as appropriate.
. The Administrator may rescind or amend a letter of authorization if the Administrator determines that the institution of higher education is not complying or is unable to comply with the provisions of the letter of authorization.

## §§ 61.170-69.171 - Reserved


Reserved

