# Agreements
:toc:

## § 161.101 - Scope.

[loweralpha]
. This subpart applies to an airport operator's noise or access restriction on the operation of Stage 3 aircraft that is implemented pursuant to an agreement between an airport operator and all aircraft operators affected by the proposed restriction that are serving or will be serving such airport within 180 days of the date of the proposed restriction.
. For purposes of this subpart, an agreement shall be in writing and signed by:
[arabic]
.. The airport operator;
.. Those aircraft operators currently operating at the airport who would be affected by the noise or access restriction; and
.. All new entrants that have submitted the information required under § 161.105(a) of this part.
. This subpart does not apply to restrictions exempted in § 161.7 of this part.
. This subpart does not limit the right of an airport operator to enter into an agreement with one or more aircraft operators that restricts the operation of Stage 2 or Stage 3 aircraft as long as the restriction is not enforced against aircraft operators that are not party to the agreement. Such an agreement is not covered by this subpart except that an aircraft operator may apply for sanctions pursuant to subpart F of this part for restrictions the airport operator seeks to impose other than those in the agreement.

## § 161.103 - Notice of the proposed restriction.

[loweralpha]
. An airport operator may not implement a Stage 3 restriction pursuant to an agreement with all affected aircraft operators unless there has been public notice and an opportunity for comment as prescribed in this subpart.
. In order to establish a restriction in accordance with this subpart, the airport operator shall, at least 45 days before implementing the restriction, publish a notice of the proposed restriction in an areawide newspaper or newspapers that either singly or together has general circulation throughout the airport vicinity or airport noise study area, if one has been delineated; post a notice in the airport in a prominent location accessible to airport users and the public; and directly notify in writing the following parties:
[arabic]
.. Aircraft operators providing scheduled passenger or cargo service at the airport; affected operators of aircraft based at the airport; potential new entrants that are known to be interested in serving the airport; and aircraft operators known to be routinely providing non-scheduled service;
.. The Federal Aviation Administration;
.. Each Federal, state, and local agency with land use control jurisdiction within the vicinity of the airport, or the airport noise study area, if one has been delineated;
.. Fixed-base operators and other airport tenants whose operations may be affected by the proposed restriction; and
.. Community groups and business organizations that are known to be interested in the proposed restriction.
. Each direct notice provided in accordance with paragraph (b) of this section shall include:
[arabic]
.. The name of the airport and associated cities and states;
.. A clear, concise description of the proposed restriction, including sanctions for noncompliance and a statement that it will be implemented pursuant to a signed agreement;
.. A brief discussion of the specific need for and goal of the proposed restriction;
.. Identification of the operators and the types of aircraft expected to be affected;
.. The proposed effective date of the restriction and any proposed enforcement mechanism;
.. An invitation to comment on the proposed restriction, with a minimum 45-day comment period;
.. Information on how to request copies of the restriction portion of the agreement, including any sanctions for noncompliance;
.. A notice to potential new entrant aircraft operators that are known to be interested in serving the airport of the requirements set forth in § 161.105 of this part; and
.. Information on how to submit a new entrant application, comments, and the address for submitting applications and comments to the airport operator, including identification of a contact person at the airport.
. The Federal Aviation Administration will publish an announcement of the proposed restriction in the *Federal Register.*
              

## § 161.105 - Requirements for new entrants.

[loweralpha]
. Within 45 days of the publication of the notice of a proposed restriction by the airport operator under § 161.103(b) of this part, any person intending to provide new air service to the airport within 180 days of the proposed date of implementation of the restriction (as evidenced by submission of a plan of operations to the airport operator) must notify the airport operator if it would be affected by the restriction contained in the proposed agreement, and either that it—
[arabic]
.. Agrees to the restriction; or
.. Objects to the restriction.
. Failure of any person described in § 161.105(a) of this part to notify the airport operator that it objects to the proposed restriction will constitute waiver of the right to claim that it did not consent to the agreement and render that person ineligible to use lack of signature as ground to apply for sanctions under subpart F of this part for two years following the effective date of the restriction. The signature of such a person need not be obtained by the airport operator in order to comply with § 161.107(a) of this part.
. All other new entrants are also ineligible to use lack of signature as ground to apply for sanctions under subpart F of this part for two years.

## § 161.107 - Implementation of the restriction.

[loweralpha]
. To be eligible to implement a Stage 3 noise or access restriction under this subpart, an airport operator shall have the restriction contained in an agreement as defined in § 161.101(b) of this part.
. An airport operator may not implement a restriction pursuant to an agreement until the notice and comment requirements of § 161.103 of this part have been met.
. Each airport operator must notify the Federal Aviation Administration of the implementation of a restriction pursuant to an agreement and must include in the notice evidence of compliance with § 161.103 and a copy of the signed agreement.

## § 161.109 - Notice of termination of restriction pursuant to an agreement.

An airport operator must notify the FAA within 10 days of the date of termination of a restriction pursuant to an agreement under this subpart.

## § 161.111 - Availability of data and comments on a restriction implemented pursuant to an agreement.

The airport operator shall retain all relevant supporting data and all comments relating to a restriction implemented pursuant to an agreement for as long as the restriction is in effect. The airport operator shall make these materials available for inspection upon request by the FAA. The information shall be made available for inspection by any person during the pendency of any petition for reevaluation found justified by the FAA.

## § 161.113 - Effect of agreements; limitation on reevaluation.

[loweralpha]
. Except as otherwise provided in this subpart, a restriction implemented by an airport operator pursuant to this subpart shall have the same force and effect as if it had been a restriction implemented in accordance with subpart D of this part.
. A restriction implemented by an airport operator pursuant to this subpart may be subject to reevaluation by the FAA under subpart E of this part.

