# Repairmen
:toc:

## § 65.101 - Eligibility requirements: General.

[loweralpha]
. To be eligible for a repairman certificate a person must—
[arabic]
.. Be at least 18 years of age;
.. Be specially qualified to perform maintenance on aircraft or components thereof, appropriate to the job for which he is employed;
.. Be employed for a specific job requiring those special qualifications by a certificated repair station, or by a certificated commercial operator or certificated air carrier, that is required by its operating certificate or approved operations specifications to provide a continuous airworthiness maintenance program according to its maintenance manuals;
.. Be recommended for certification by his employer, to the satisfaction of the Administrator, as able to satisfactorily maintain aircraft or components, appropriate to the job for which he is employed;
.. Have either—
[lowerroman]
... At least 18 months of practical experience in the procedures, practices, inspection methods, materials, tools, machine tools, and equipment generally used in the maintenance duties of the specific job for which the person is to be employed and certificated; or
... Completed formal training that is acceptable to the Administrator and is specifically designed to qualify the applicant for the job on which the applicant is to be employed; and
.. Be able to read, write, speak, and understand the English language, or, in the case of an applicant who does not meet this requirement and who is employed outside the United States by a certificated repair station, a certificated U.S. commercial operator, or a certificated U.S. air carrier, described in paragraph (a)(3) of this section, have this certificate endorsed “Valid only outside the United States.”
. This section does not apply to the issuance of a repairman certificate (experimental aircraft builder) under § 65.104 or to a repairman certificate (light-sport aircraft) under § 65.107.

## § 65.103 - Repairman certificate: Privileges and limitations.

[loweralpha]
. A certificated repairman may perform or supervise the maintenance, preventive maintenance, or alteration of aircraft or aircraft components appropriate to the job for which the repairman was employed and certificated, but only in connection with duties for the certificate holder by whom the repairman was employed and recommended.
. A certificated repairman may not perform or supervise duties under the repairman certificate unless the repairman understands the current instructions of the certificate holder by whom the repairman is employed and the manufacturer's instructions for continued airworthiness relating to the specific operations concerned.
. This section does not apply to the holder of a repairman certificate (light-sport aircraft) while that repairman is performing work under that certificate.

## § 65.104 - Repairman certificate—experimental aircraft builder—Eligibility, privileges and limitations.

[loweralpha]
. To be eligible for a repairman certificate (experimental aircraft builder), an individual must—
[arabic]
.. Be at least 18 years of age;
.. Be the primary builder of the aircraft to which the privileges of the certificate are applicable;
.. Show to the satisfaction of the Administrator that the individual has the requisite skill to determine whether the aircraft is in a condition for safe operations; and
.. Be a citizen of the United States or an individual citizen of a foreign country who has lawfully been admitted for permanent residence in the United States.
. The holder of a repairman certificate (experimental aircraft builder) may perform condition inspections on the aircraft constructed by the holder in accordance with the operating limitations of that aircraft.
. Section 65.103 does not apply to the holder of a repairman certificate (experimental aircraft builder) while performing under that certificate.

## § 65.105 - Display of certificate.

Each person who holds a repairman certificate shall keep it within the immediate area where he normally exercises the privileges of the certificate and shall present it for inspection upon the request of the Administrator or an authorized representative of the National Transportation Safety Board, or of any Federal, State, or local law enforcement officer.

## § 65.107 - Repairman certificate (light-sport aircraft): Eligibility, privileges, and limits.

[loweralpha]
. Use the following table to determine your eligibility for a repairman certificate (light-sport aircraft) and appropriate rating:
. The holder of a repairman certificate (light-sport aircraft) with an inspection rating may perform the annual condition inspection on a light-sport aircraft:
[arabic]
.. That is owned by the holder;
.. That has been issued an experimental certificate for operating a light-sport aircraft under § 21.191(i) of this chapter; and
.. That is in the same class of light-sport-aircraft for which the holder has completed the training specified in paragraph (a)(2)(ii) of this section.
. The holder of a repairman certificate (light-sport aircraft) with a maintenance rating may—
[arabic]
.. Approve and return to service an aircraft that has been issued a special airworthiness certificate in the light-sport category under § 21.190 of this chapter, or any part thereof, after performing or inspecting maintenance (to include the annual condition inspection and the 100-hour inspection required by § 91.327 of this chapter), preventive maintenance, or an alteration (excluding a major repair or a major alteration on a product produced under an FAA approval);
.. Perform the annual condition inspection on a light-sport aircraft that has been issued an experimental certificate for operating a light-sport aircraft under § 21.191(i) of this chapter; and
.. Only perform maintenance, preventive maintenance, and an alteration on a light-sport aircraft that is in the same class of light-sport aircraft for which the holder has completed the training specified in paragraph (a)(3)(ii) of this section. Before performing a major repair, the holder must complete additional training acceptable to the FAA and appropriate to the repair performed.
. The holder of a repairman certificate (light-sport aircraft) with a maintenance rating may not approve for return to service any aircraft or part thereof unless that person has previously performed the work concerned satisfactorily. If that person has not previously performed that work, the person may show the ability to do the work by performing it to the satisfaction of the FAA, or by performing it under the direct supervision of a certificated and appropriately rated mechanic, or a certificated repairman, who has had previous experience in the specific operation concerned. The repairman may not exercise the privileges of the certificate unless the repairman understands the current instructions of the manufacturer and the maintenance manuals for the specific operation concerned.

