# Emergency Medical Equipment and Training
:toc:

## § 121.801

### Applicability.

This subpart prescribes the emergency medical equipment and training requirements applicable to all certificate holders operating passenger-carrying airplanes under this part. Nothing in this subpart is intended to require certificate holders or its agents to provide emergency medical care or to establish a standard of care for the provision of emergency medical care.

## § 121.803

### Emergency medical equipment.

. No person may operate a passenger-carrying airplane under this part unless it is equipped with the emergency medical equipment listed in this section.
. Each equipment item listed in this section—
.. Must be inspected regularly in accordance with inspection periods established in the operations specifications to ensure its condition for continued serviceability and immediate readiness to perform its intended emergency purposes;
.. Must be readily accessible to the crew and, with regard to equipment located in the passenger compartment, to passengers;
.. Must be clearly identified and clearly marked to indicate its method of operation; and
              
.. When carried in a compartment or container, must be carried in a compartment or container marked as to contents and the compartment or container, or the item itself, must be marked as to date of last inspection.
. For treatment of injuries, medical events, or minor accidents that might occur during flight time each airplane must have the following equipment that meets the specifications and requirements of appendix A of this part:
.. Approved first-aid kits.
.. In airplanes for which a flight attendant is required, an approved emergency medical kit.
.. In airplanes for which a flight attendant is required, an approved emergency medical kit as modified effective April 12, 2004.
.. In airplanes for which a flight attendant is required and with a maximum payload capacity of more than 7,500 pounds, an approved automated external defibrillator as of April 12, 2004.

## § 121.805

### Crewmember training for in-flight medical events.

. Each training program must provide the instruction set forth in this section with respect to each airplane type, model, and configuration, each required crewmember, and each kind of operation conducted, insofar as appropriate for each crewmember and the certificate holder.
. Training must provide the following:
.. Instruction in emergency medical event procedures, including coordination among crewmembers.
.. Instruction in the location, function, and intended operation of emergency medical equipment.
.. Instruction to familiarize crewmembers with the content of the emergency medical kit.
.. Instruction to familiarize crewmembers with the content of the emergency medical kit as modified on April 12, 2004.
.. For each flight attendant—
... Instruction, to include performance drills, in the proper use of automated external defibrillators.
... Instruction, to include performance drills, in cardiopulmonary resuscitation.
... Recurrent training, to include performance drills, in the proper use of an automated external defibrillators and in cardiopulmonary resuscitation at least once every 24 months.
. The crewmember instruction, performance drills, and recurrent training required under this section are not required to be equivalent to the expert level of proficiency attained by professional emergency medical personnel.

