# Mechanics
:toc:

## § 65.71 - Eligibility requirements: General.

[loweralpha]
. To be eligible for a mechanic certificate and associated ratings, a person must—
[arabic]
.. Be at least 18 years of age;
.. Be able to read, write, speak, and understand the English language, or in the case of an applicant who does not meet this requirement and who is employed outside of the United States by a U.S. air carrier, have his certificate endorsed “Valid only outside the United States”;
.. Have passed all of the prescribed tests within a period of 24 months; and
.. Comply with the sections of this subpart that apply to the rating he seeks.
. A certificated mechanic who applies for an additional rating must meet the requirements of § 65.77 and, within a period of 24 months, pass the tests prescribed by §§ 65.75 and 65.79 for the additional rating sought.

## § 65.73 - Ratings.

[loweralpha]
. The following ratings are issued under this subpart:
[arabic]
.. Airframe.
.. Powerplant.
. A mechanic certificate with an aircraft or aircraft engine rating, or both, that was issued before, and was valid on, June 15, 1952, is equal to a mechanic certificate with an airframe or powerplant rating, or both, as the case may be, and may be exchanged for such a corresponding certificate and rating or ratings.

## § 65.75 - Knowledge requirements.

[loweralpha]
. Each applicant for a mechanic certificate or rating must, after meeting the applicable experience requirements of § 65.77, pass a written test covering the construction and maintenance of aircraft appropriate to the rating he seeks, the regulations in this subpart, and the applicable provisions of parts 43 and 91 of this chapter. The basic principles covering the installation and maintenance of propellers are included in the powerplant test.
              
. The applicant must pass each section of the test before applying for the oral and practical tests prescribed by § 65.79. A report of the written test is sent to the applicant.

## § 65.77 - Experience requirements.

Each applicant for a mechanic certificate or rating must present either an appropriate graduation certificate or certificate of completion from a certificated aviation maintenance technician school or documentary evidence, satisfactory to the Administrator, of—

[loweralpha]
. At least 18 months of practical experience with the procedures, practices, materials, tools, machine tools, and equipment generally used in constructing, maintaining, or altering airframes, or powerplants appropriate to the rating sought; or
. At least 30 months of practical experience concurrently performing the duties appropriate to both the airframe and powerplant ratings.

## § 65.79 - Skill requirements.

Each applicant for a mechanic certificate or rating must pass an oral and a practical test on the rating he seeks. The tests cover the applicant's basic skill in performing practical projects on the subjects covered by the written test for that rating. An applicant for a powerplant rating must show his ability to make satisfactory minor repairs to, and minor alterations of, propellers.

## § 65.80 - Certificated aviation maintenance technician school students.

Whenever an aviation maintenance technician school certificated under part 147 of this chapter shows to an FAA inspector that any of its students has made satisfactory progress at the school and is prepared to take the oral and practical tests prescribed by § 65.79, that student may take those tests during the final subjects of his training in the approved curriculum, before he meets the applicable experience requirements of § 65.77 and before he passes each section of the written test prescribed by § 65.75.

## § 65.81 - General privileges and limitations.

[loweralpha]
. A certificated mechanic may perform or supervise the maintenance, preventive maintenance or alteration of an aircraft or appliance, or a part thereof, for which he is rated (but excluding major repairs to, and major alterations of, propellers, and any repair to, or alteration of, instruments), and may perform additional duties in accordance with §§ 65.85, 65.87, and 65.95. However, he may not supervise the maintenance, preventive maintenance, or alteration of, or approve and return to service, any aircraft or appliance, or part thereof, for which he is rated unless he has satisfactorily performed the work concerned at an earlier date. If he has not so performed that work at an earlier date, he may show his ability to do it by performing it to the satisfaction of the Administrator or under the direct supervision of a certificated and appropriately rated mechanic, or a certificated repairman, who has had previous experience in the specific operation concerned.
. A certificated mechanic may not exercise the privileges of his certificate and rating unless he understands the current instructions of the manufacturer, and the maintenance manuals, for the specific operation concerned.

## § 65.83 - Recent experience requirements.

A certificated mechanic may not exercise the privileges of his certificate and rating unless, within the preceding 24 months—

[loweralpha]
. The Administrator has found that he is able to do that work; or
. He has, for at least 6 months—
[arabic]
.. Served as a mechanic under his certificate and rating;
.. Technically supervised other mechanics;
.. Supervised, in an executive capacity, the maintenance or alteration of aircraft; or
              
.. Been engaged in any combination of paragraph (b) (1), (2), or (3) of this section.

## § 65.85 - Airframe rating; additional privileges.

[loweralpha]
. Except as provided in paragraph (b) of this section, a certificated mechanic with an airframe rating may approve and return to service an airframe, or any related part or appliance, after he has performed, supervised, or inspected its maintenance or alteration (excluding major repairs and major alterations). In addition, he may perform the 100-hour inspection required by part 91 of this chapter on an airframe, or any related part or appliance, and approve and return it to service.
. A certificated mechanic with an airframe rating can approve and return to service an airframe, or any related part or appliance, of an aircraft with a special airworthiness certificate in the light-sport category after performing and inspecting a major repair or major alteration for products that are not produced under an FAA approval provided the work was performed in accordance with instructions developed by the manufacturer or a person acceptable to the FAA.

## § 65.87 - Powerplant rating; additional privileges.

[loweralpha]
. Except as provided in paragraph (b) of this section, a certificated mechanic with a powerplant rating may approve and return to service a powerplant or propeller or any related part or appliance, after he has performed, supervised, or inspected its maintenance or alteration (excluding major repairs and major alterations). In addition, he may perform the 100-hour inspection required by part 91 of this chapter on a powerplant or propeller, or any part thereof, and approve and return it to service.
. A certificated mechanic with a powerplant rating can approve and return to service a powerplant or propeller, or any related part or appliance, of an aircraft with a special airworthiness certificate in the light-sport category after performing and inspecting a major repair or major alteration for products that are not produced under an FAA approval, provided the work was performed in accordance with instructions developed by the manufacturer or a person acceptable to the FAA.

## § 65.89 - Display of certificate.

Each person who holds a mechanic certificate shall keep it within the immediate area where he normally exercises the privileges of the certificate and shall present it for inspection upon the request of the Administrator or an authorized representative of the National Transportation Safety Board, or of any Federal, State, or local law enforcement officer.

## § 65.91 - Inspection authorization.

[loweralpha]
. An application for an inspection authorization is made on a form and in a manner prescribed by the Administrator.
. An applicant who meets the requirements of this section is entitled to an inspection authorization.
. To be eligible for an inspection authorization, an applicant must—
[arabic]
.. Hold a currently effective mechanic certificate with both an airframe rating and a powerplant rating, each of which is currently effective and has been in effect for a total of at least 3 years;
.. Have been actively engaged, for at least the 2-year period before the date he applies, in maintaining aircraft certificated and maintained in accordance with this chapter;
.. Have a fixed base of operations at which he may be located in person or by telephone during a normal working week but it need not be the place where he will exercise his inspection authority;
.. Have available to him the equipment, facilities, and inspection data necessary to properly inspect airframes, powerplants, propellers, or any related part or appliance; and
              
.. Pass a written test on his ability to inspect according to safety standards for returning aircraft to service after major repairs and major alterations and annual and progressive inspections performed under part 43 of this chapter.
              

## § 65.92 - Inspection authorization: Duration.

[loweralpha]
. Each inspection authorization expires on March 31 of each odd-numbered year. However, the holder may exercise the privileges of that authorization only while he holds a currently effective mechanic certificate with both a currently effective airframe rating and a currently effective powerplant rating.
. An inspection authorization ceases to be effective whenever any of the following occurs:
[arabic]
.. The authorization is surrendered, suspended, or revoked.
.. The holder no longer has a fixed base of operation.
.. The holder no longer has the equipment, facilities, and inspection data required by § 65.91(c) (3) and (4) for issuance of his authorization.
. The holder of an inspection authorization that is suspended or revoked shall, upon the Administrator's request, return it to the Administrator.

## § 65.93 - Inspection authorization: Renewal.

[loweralpha]
. To be eligible for renewal of an inspection authorization for a 2-year period an applicant must present evidence during the month of March of each odd-numbered year, at an FAA Flight Standards District Office or an International Field Office, that the applicant still meets the requirements of § 65.91(c) (1) through (4). In addition, during the time the applicant held the inspection authorization, the applicant must show completion of one of the activities in § 65.93(a) (1) through (5) below by March 31 of the first year of the 2-year inspection authorization period, and completion of one of the five activities during the second year of the 2-year period:
[arabic]
.. Performed at least one annual inspection for each 90 days that the applicant held the current authority; or
.. Performed at least two major repairs or major alterations for each 90 days that the applicant held the current authority; or
.. Performed or supervised and approved at least one progressive inspection in accordance with standards prescribed by the Administrator; or
.. Attended and successfully completed a refresher course, acceptable to the Administrator, of not less than 8 hours of instruction; or
.. Passed an oral test by an FAA inspector to determine that the applicant's knowledge of applicable regulations and standards is current.
. The holder of an inspection authorization that has been in effect:
[arabic]
.. for less than 90 days before the expiration date need not comply with paragraphs (a)(1) through (5) of this section.
.. for less than 90 days before March 31 of an even-numbered year need not comply with paragraphs (a)(1) through (5) of this section for the first year of the 2-year inspection authorization period.
. An inspection authorization holder who does not complete one of the activities set forth in § 65.93(a) (1) through (5) of this section by March 31 of the first year of the 2-year inspection authorization period may not exercise inspection authorization privileges after March 31 of the first year. The inspection authorization holder may resume exercising inspection authorization privileges after passing an oral test from an FAA inspector to determine that the applicant's knowledge of the applicable regulations and standards is current. An inspection authorization holder who passes this oral test is deemed to have completed the requirements of § 65.93(a) (1) through (5) by March 31 of the first year.

## § 65.95 - Inspection authorization: Privileges and limitations.

[loweralpha]
. The holder of an inspection authorization may—
[arabic]
.. Inspect and approve for return to service any aircraft or related part or appliance (except any aircraft maintained in accordance with a continuous airworthiness program under part 121 of this chapter) after a major repair or major alteration to it in accordance with part 43 [New] of this chapter, if the work was done in accordance with technical data approved by the Administrator; and
.. Perform an annual, or perform or supervise a progressive inspection according to §§ 43.13 and 43.15 of this chapter.
. When he exercises the privileges of an inspection authorization the holder shall keep it available for inspection by the aircraft owner, the mechanic submitting the aircraft, repair, or alteration for approval (if any), and shall present it upon the request of the Administrator or an authorized representative of the National Transportation Safety Board, or of any Federal, State, or local law enforcement officer.
. If the holder of an inspection authorization changes his fixed base of operation, he may not exercise the privileges of the authorization until he has notified the FAA Flight Standards District Office or International Field Office for the area in which the new base is located, in writing, of the change.

