# General
:toc:

## § 121.1

### Applicability.

This part prescribes rules governing—

. The domestic, flag, and supplemental operations of each person who holds or is required to hold an Air Carrier Certificate or Operating Certificate under part 119 of this chapter.
. Each person employed or used by a certificate holder conducting operations under this part including maintenance, preventive maintenance, and alteration of aircraft.
. Each person who applies for provisional approval of an Advanced Qualification Program curriculum, curriculum segment, or portion of a curriculum segment under SFAR No. 58 of 14 CFR part 121, and each person employed or used by an air carrier or commercial operator under this part to perform training, qualification, or evaluation functions under an Advanced Qualification Program under SFAR No. 58 of 14 CFR part 121.
. Nonstop Commercial Air Tours conducted for compensation or hire in accordance with § 119.1(e)(2) of this chapter must comply with drug and alcohol requirements in §§ 121.455, 121.457, 121.458 and 121.459, and with the provisions of part 136, subpart A of this chapter by September 11, 2007. An operator who does not hold an air carrier certificate or an operating certificate is permitted to use a person who is otherwise authorized to perform aircraft maintenance or preventive maintenance duties and who is not subject to anti-drug and alcohol misuse prevention programs to perform—
.. Aircraft maintenance or preventive maintenance on the operator's aircraft if the operator would otherwise be required to transport the aircraft more than 50 nautical miles further than the repair point closest to the operator's principal base of operations to obtain these services; or
.. Emergency repairs on the operator's aircraft if the aircraft cannot be safely operated to a location where an employee subject to FAA-approved programs can perform the repairs.
. Each person who is on board an aircraft being operated under this part.
              
. Each person who is an applicant for an Air Carrier Certificate or an Operating Certificate under part 119 of this chapter, when conducting proving tests.
. This part also establishes requirements for operators to take actions to support the continued airworthiness of each airplane.

## § 121.2

### Compliance schedule for operators that transition to part 121; certain new entrant operators.

. *Applicability.* This section applies to the following:
.. Each certificate holder that was issued an air carrier or operating certificate and operations specifications under the requirements of part 135 of this chapter or under SFAR No. 38-2 of 14 CFR part 121 before January 19, 1996, and that conducts scheduled passenger-carrying operations with:
... Nontransport category turbopropeller powered airplanes type certificated after December 31, 1964, that have a passenger seat configuration of 10-19 seats;
... Transport category turbopropeller powered airplanes that have a passenger seat configuration of 20-30 seats; or
... Turbojet engine powered airplanes having a passenger seat configuration of 1-30 seats.
.. Each person who, after January 19, 1996, applies for or obtains an initial air carrier or operating certificate and operations specifications to conduct scheduled passenger-carrying operations in the kinds of airplanes described in paragraphs (a)(1)(i), (a)(1)(ii), or paragraph (a)(1)(iii) of this section.
. *Obtaining operations specifications.* A certificate holder described in paragraph (a)(1) of this section may not, after March 20, 1997, operate an airplane described in paragraphs (a)(1)(i), (a)(1)(ii), or (a)(1)(iii) of this section in scheduled passenger-carrying operations, unless it obtains operations specifications to conduct its scheduled operations under this part on or before March 20, 1997.
. *Regular or accelerated compliance.* Except as provided in paragraphs (d), (e), and (i) of this section, each certificate holder described in paragraphs (a)(1) of this section shall comply with each applicable requirement of this part on and after March 20, 1997 or on and after the date on which the certificate holder is issued operations specifications under this part, whichever occurs first. Except as provided in paragraphs (d) and (e) of this section, each person described in paragraph (a)(2) of this section shall comply with each applicable requirement of this part on and after the date on which that person is issued a certificate and operations specifications under this part.
. *Delayed compliance dates.* Unless paragraph (e) of this section specifies an earlier compliance date, no certificate holder that is covered by paragraph (a) of this section may operate an airplane in 14 CFR part 121 operations on or after a date listed in this paragraph (d) unless that airplane meets the applicable requirement of this paragraph (d):
.. *Nontransport category turbopropeller powered airplanes type certificated after December 31, 1964, that have a passenger seat configuration of 10-19 seats.* No certificate holder may operate under this part an airplane that is described in paragraph (a)(1)(i) of this section on or after a date listed in paragraph (d)(1) of this section unless that airplane meets the applicable requirement listed in paragraph (d)(1) of this section:
... December 20, 1997:
... December 20, 1999: Section 121.342, Pitot heat indication system.
... December 20, 2010:
... March 12, 1999: Section 121.310(b)(1), Interior emergency exit locating sign.
.. *Transport category turbopropeller powered airplanes that have a passenger seat configuration of 20-30 seats.* No certificate holder may operate under this part an airplane that is described in paragraph (a)(1)(ii) of this section on or after a date listed in paragraph (d)(2) of this section unless that airplane meets the applicable requirement listed in paragraph (d)(2) of this section:
... December 20, 1997:
... December 20, 2010: § 121.305(j), third attitude indicator.
. *Newly manufactured airplanes.* No certificate holder that is described in paragraph (a) of this section may operate under this part an airplane manufactured on or after a date listed in this paragraph unless that airplane meets the applicable requirement listed in this paragraph (e).
.. For nontransport category turbopropeller powered airplanes type certificated after December 31, 1964, that have a passenger seat configuration of 10-19 seats:
... Manufactured on or after March 20, 1997:
... Manufactured on or after December 20, 1997; Section 121.317(a), Fasten seat belt light.
... Manufactured on or after December 20, 1999: Section 121.293, Takeoff warning system.
... Manufactured on or after March 12, 1999: Section 121.310(b)(1), Interior emergency exit locating sign.
.. For transport category turbopropeller powered airplanes that have a passenger seat configuration of 20-30 seats manufactured on or after March 20, 1997: Section 121.305(j), Third attitude indicator.
. *New type certification requirements.* No person may operate an airplane for which the application for a type certificate was filed after March 29, 1995, in 14 CFR part 121 operations unless that airplane is type certificated under part 25 of this chapter.
. *Transition plan.* Before March 19, 1996 each certificate holder described in paragraph (a)(1) of this section must submit to the FAA a transition plan (containing a calendar of events) for moving from conducting its scheduled operations under the commuter requirements of part 135 of this chapter to the requirements for domestic or flag operations under this part. Each transition plan must contain details on the following:
.. Plans for obtaining new operations specifications authorizing domestic or flag operations;
.. Plans for being in compliance with the applicable requirements of this part on or before March 20, 1997; and
.. Plans for complying with the compliance date schedules contained in paragraphs (d) and (e) of this section.
. *Continuing requirements.* A certificate holder described in paragraph (a) of this section shall comply with the applicable airplane operating and equipment requirements of part 135 of this chapter for the airplanes described in paragraph (a)(1) of this section, until the airplane meets the specific compliance dates in paragraphs (d) and (e) of this section.
. Any training or qualification obtained by a crewmember under part 135 of this chapter before March 20, 1997, is entitled to credit under this part for the purpose of meeting the requirements of this part, as determined by the Administrator. Records kept by a certificate holder under part 135 of this chapter before March 20, 1997, can be annotated, with the approval of the Administrator, to reflect crewmember training and qualification credited toward part 121 requirements.

(A) Section 121.289, Landing gear aural warning.

(B) Section 121.308, Lavatory fire protection.

(C) Section 121.310(e), Emergency exit handle illumination.

(D) Section 121.337(b)(8), Protective breathing equipment.

(E) Section 121.340, Emergency flotation means.

(A) For airplanes described in § 121.157(f), the Airplane Performance Operating Limitations in §§ 121.189 through 121.197.
              

(B) Section 121.161(b), Ditching approval.

(C) Section 121.305(j), Third attitude indicator.

(D) Section 121.312(c), Passenger seat cushion flammability.

(A) Section 121.308, Lavatory fire protection.

(B) Section 121.337(b) (8) and (9), Protective breathing equipment.

(C) Section 121.340, Emergency flotation means.

(A) Section 121.305(j), Third attitude indicator.

(B) Section 121.311(f), Safety belts and shoulder harnesses.

## § 121.4

### Applicability of rules to unauthorized operators.

The rules in this part which refer to a person certificated under part 119 of this chapter apply also to any person who engages in an operation governed by this part without the appropriate certificate and operations specifications required by part 119 of this chapter.

## § 121.7

### Definitions.

The following definitions apply to those sections of part 121 that apply to ETOPS:

*Adequate Airport* means an airport that an airplane operator may list with approval from the FAA because that airport meets the landing limitations of § 121.197 and is either—

(1) An airport that meets the requirements of part 139, subpart D of this chapter, excluding those that apply to aircraft rescue and firefighting service, or

(2) A military airport that is active and operational.

*ETOPS Alternate Airport* means an adequate airport listed in the certificate holder's operations specifications that is designated in a dispatch or flight release for use in the event of a diversion during ETOPS. This definition applies to flight planning and does not in any way limit the authority of the pilot-in-command during flight.

*ETOPS Area of Operation* means one of the following areas:

(1) For turbine-engine-powered airplanes with two engines, an area beyond 60 minutes from an adequate airport, computed using a one-engine-inoperative cruise speed under standard conditions in still air.

(2) For turbine-engine-powered passenger-carrying airplanes with more than two engines, an area beyond 180 minutes from an adequate airport, computed using a one-engine-inoperative cruise speed under standard conditions in still air.

*ETOPS Entry Point* means the first point on the route of an ETOPS flight, determined using a one-engine-inoperative cruise speed under standard conditions in still air, that is—

(1) More than 60 minutes from an adequate airport for airplanes with two engines;

(2) More than 180 minutes from an adequate airport for passenger-carrying airplanes with more than two engines.

*ETOPS Qualified Person* means a person, performing maintenance for the certificate holder, who has satisfactorily completed the certificate holder's ETOPS training program.

*Maximum Diversion Time* means, for the purposes of ETOPS route planning, the longest diversion time authorized for a flight under the operator's ETOPS authority. It is calculated under standard conditions in still air at a one-engine-inoperative cruise speed.

*North Pacific Area of Operation* means Pacific Ocean areas north of 40° N latitudes including NOPAC ATS routes, and published PACOTS tracks between Japan and North America.

*North Polar Area* means the entire area north of 78° N latitude.

*One-engine-inoperative-Cruise Speed* means a speed within the certified operating limits of the airplane that is specified by the certificate holder and approved by the FAA for —

(1) Calculating required fuel reserves needed to account for an inoperative engine; or

(2) Determining whether an ETOPS alternate is within the maximum diversion time authorized for an ETOPS flight.

*South Polar Area* means the entire area South of 60° S latitude.

## § 121.9

### Fraud and falsification.

. No person may make, or cause to be made, any of the following:
.. A fraudulent or intentionally false statement in any application or any amendment thereto, or in any other record or test result required by this part.
.. A fraudulent or intentionally false statement in, or a known omission from, any record or report that is kept, made, or used to show compliance with this part, or to exercise any privileges under this chapter.
. The commission by any person of any act prohibited under paragraph (a) of this section is a basis for any one or any combination of the following:
.. A civil penalty.
.. Suspension or revocation of any certificate held by that person that was issued under this chapter.
.. The denial of an application for any approval under this part.
.. The removal of any approval under this part.

## § 121.11

### Rules applicable to operations in a foreign country.

Each certificate holder shall, while operating an airplane within a foreign country, comply with the air traffic rules of the country concerned and the local airport rules, except where any rule of this part is more restrictive and may be followed without violating the rules of that country.

## § 121.15

### Carriage of narcotic drugs, marihuana, and depressant or stimulant drugs or substances.

If a certificate holder operating under this part permits any aircraft owned or leased by that holder to be engaged in any operation that the certificate holder knows to be in violation of § 91.19(a) of this chapter, that operation is a basis for suspending or revoking the certificate.

