# Distance Measuring Equipment (DME)
:toc:

## § 171.151 - Scope.

This subpart sets forth minimum requirements for the approval and operation of non-Federal DME facilities that are to be involved in the approval of instrument flight rules and air traffic control procedures related to those facilities.

## § 171.153 - Requests for IFR procedure.

[loweralpha]
. Each person who requests an IFR procedure based on a DME facility that he owns must submit the following information with that request:
[arabic]
.. A description of the facility and evidence that the equipment meets the performance requirements of § 171.157 and is installed in accordance with § 171.159.
.. A proposed procedure for operating the facility.
.. A proposed maintenance organization and maintenance manual that meets the requirement of § 171.161.
.. A statement of intention to meet the requirements of this subpart.
.. A showing that the facility has an acceptable level of operational reliability and an acceptable standard of performance. Previous equivalent operational experience with a facility with identical design and operational characteristics will be considered in showing compliance with this paragraph.
. After the Federal Aviation Administration inspects and evaluates the facility, it advises the owner of the results and of any required changes in the facility or the maintenance manual or maintenance organization. The owner must then correct the deficiencies, if any, and operate the facility for an in-service evaluation by the Federal Aviation Administration.

## § 171.155 - Minimum requirements for approval.

[loweralpha]
. The following are the minimum requirements that must be met before the Federal Aviation Administration will approve an IFR procedure for a non-Federal DME:
[arabic]
.. A suitable frequency channel must be available.
.. The facility's performance, as determined by air and ground inspection, must meet the requirements of § 171.157.
.. The installation of the equipment must meet the requirements of § 171.159.
.. The owner must agree to operate and maintain the facility in accordance with § 171.161.
.. The owner must agree to furnish periodic reports, as set forth in § 171.163, and must agree to allow the Federal Aviation Administration to inspect the facility and its operation whenever necessary.
.. The owner must assure the Federal Aviation Administration that he will not withdraw the facility from service without the permission of the Federal Aviation Administration.
.. The owner must bear all costs of meeting the requirements of this section and of any flight or ground inspections made before the facility is commissioned, except that the Federal Aviation Administration may bear certain of these costs subject to budgetary limitations and policy established by the Administrator.
. If the applicant for approval meets the requirements of paragraph (a) of this section, the Federal Aviation Administration commissions the facility as a prerequisite to its approval for use in an IFR procedure. The approval is withdrawn at any time the facility does not continue to meet those requirements.

## § 171.157 - Performance requirements.

[loweralpha]
. The DME must meet the performance requirements set forth in the “International Standards and Recommended Practices. Aeronautical Telecommunications, Part I, Paragraph 3.5” (Annex 10 to the Convention of International Civil Aviation).
. It must be shown during ground inspection of the design features of the equipment that there will not be conditions that will allow unsafe operations because of component failure or deterioration.
. The monitor must be checked periodically, during the in-service test evaluation period, for calibration and stability. These tests and ground tests of the functional and performance characteristics of the DME transponder must be conducted in accordance with the maintenance manual required by § 171.161(b).
. Flight inspection to determine the adequacy of the facility's operational performance and compliance with applicable “Standards and Recommended Practices” must be accomplished in accordance with the “U.S. Standard Flight Inspection Manual.”

## § 171.159 - Installation requirements.

[loweralpha]
. The facility must be installed according to accepted good engineering practices, applicable electric and safety codes, and Federal Communications Commission requirements.
. The facility must have a reliable source of suitable primary power, either from a power distribution system or locally generated, with a supplemental standby system, if needed.
. Dual transmitting equipment with automatic changeover is preferred and may be required to support certain IFR procedures.
. There must be a means for determining from the ground, the performance of the equipment, initially and periodically.
. A facility intended for use as an instrument approach aid for an airport must have or be supplemented by the following ground air or landline communications services:
[arabic]
.. At facilities outside of and not immediately adjacent to controlled airspace, there must be ground-air communications from the airport served by the facility. Separate communications channels are acceptable.
.. At facilities within or immediately adjacent to controlled airspace, there must be the ground-air communications required by paragraph (e)(1) of this section and reliable communications (at least a landline telephone) from the airport to the nearest Federal Aviation Administration air traffic control or communications facility. Separate communications channels are acceptable.
              

## § 171.161 - Maintenance and operations requirements.

[loweralpha]
. The owner of the facility shall establish an adequate maintenance system and provide qualified maintenance personnel to maintain the facility at the level attained at the time it was commissioned. Each person who maintains a facility shall meet at a minimum the Federal Communications Commission's licensing requirements and show that he has the special knowledge and skills needed to maintain the facility, including proficiency in maintenance procedures and the use of specialized test equipment.
. The owner must prepare and obtain Federal Aviation Administration approval of, and each person operating or maintaining the facility shall comply with, an operations and maintenance manual that sets forth procedures for operations, preventive maintenance, and emergency maintenance, including instructions on each of the following:
[arabic]
.. Physical security of the facility.
.. Maintenance and operations by authorized persons only.
.. Federal Communications Commission's requirements and maintenance personnel.
.. Posting of licenses and signs.
.. Relations between the facility and Federal Aviation Administration air traffic control facilities, with a description of the boundaries of controlled airspace over or near the facility, instructions for relaying air traffic control instructions and information (if applicable), and instructions for the operation of an air traffic advisory service if the DME is located outside of controlled airspace.
.. Notice to the Administrator of any suspension of service.
.. Detailed and specific maintenance procedures and servicing guides stating the frequency of servicing.
.. Air-ground communications, if provided, expressly written or incorporating appropriate sections of Federal Aviation Administration manuals by reference.
.. Keeping of station logs and other technical reports, and the submission of reports required by § 171.163.
.. Monitoring of the facility.
.. Inspections by U.S. personnel.
.. Names, addresses, and telephone numbers of persons to be notified in an emergency.
.. Shutdowns for routine maintenance and issue of “Notices to Airmen” for routine or emergency shutdowns, except that private use facilities may omit the “Notices to Airmen.”
.. An explanation of the kinds of activity (such as construction or grading) in the vicinity of the facility that may require shutdown or reapproval of the facility by Federal Aviation Administration flight check.
.. Commissioning of the facility.
.. An acceptable procedure for amending or revising the manual.
.. The following information concerning the facility:
[lowerroman]
... Location by latitude and longitude to the nearest second, and its position with respect to airport layouts.
... The type, make, and model of the basic radio equipment that will provide the service.
... The station power emission and frequency.
... The hours of operation.
... Station identification call letters and methods of station identification, whether by Morse code or recorded voice announcement, and the time spacing of the identification.
... A description of the critical parts that may not be changed, adjusted, or repaired without an FAA flight check to confirm published operations.
. The owner shall make a monthly ground operational check in accordance with procedures approved by the FAA at the time of commissioning, and shall report the results of the checks as provided in § 171.163.
. If the owner desires to modify the facility, he shall submit the proposal to the FAA and may not allow any modifications to be made without specific approval.
. The owner's maintenance personnel shall participate in initial inspections made by the FAA. In the case of subsequent inspections, the owner or his representative shall participate.
. Whenever it is required by the FAA, the owner shall incorporate improvements in DME maintenance.
. The owner shall provide a stock of spare parts of such a quantity to make possible the prompt replacement of components that fail or deteriorate in service.
. The owner shall provide FAA-approved test instruments needed for maintenance of the facility.
[lowerroman]
.. The owner shall shut down the facility (i.e., cease radiation and issue a NOTAM that the facility is out-of-service) upon receiving two successive pilot reports of its malfunctioning.

## § 171.163 - Reports.

The owner of each facility to which this subpart applies shall make the following reports on forms furnished by the FAA, at the time indicated, to the FAA Regional office for the area in which the facility is located:

[loweralpha]
. Record of meter readings and adjustments (Form FAA-198). To be filled out by the owner with the equipment adjustments and meter readings as of the time of commissioning, with one copy to be kept in the permanent records of the facility and two copies to the appropriate Regional office of the FAA. The owner shall revise the form after any major repair, modification, or returning, to reflect an accurate record of facility operation and adjustment.
. Facility maintenance log (FAA Form 6030-1). This form is a permanent record of all equipment malfunctioning met in maintaining the facility, including information on the kind of work and adjustments made, equipment failures, causes (if determined), and corrective action taken. The owner shall keep the original of each report at the facility and send a copy to the appropriate Regional Office of the Federal Aviation Administration at the end of the month in which it is prepared.
. Radio equipment operation record (Form FAA-418), containing a complete record of meter readings, recorded on each scheduled visit to the facility. The owner shall keep the original of each month's record at the facility and send a copy of it to the appropriate Regional Office of the Federal Aviation Administration.

