# Unmanned Free Balloons
:toc:

## § 101.31

### Applicability.

This subpart applies to the operation of unmanned free balloons. However, a person operating an unmanned free balloon within a restricted area must comply only with § 101.33 (d) and (e) and with any additional limitations that are imposed by the using or controlling agency, as appropriate.

## § 101.33

### Operating limitations.

No person may operate an unmanned free balloon—

. Unless otherwise authorized by ATC, below 2,000 feet above the surface within the lateral boundaries of the surface areas of Class B, Class C, Class D, or Class E airspace designated for an airport;
. At any altitude where there are clouds or obscuring phenomena of more than five-tenths coverage;
. At any altitude below 60,000 feet standard pressure altitude where the horizontal visibility is less than five miles;
. During the first 1,000 feet of ascent, over a congested area of a city, town, or settlement or an open-air assembly of persons not associated with the operation; or
. In such a manner that impact of the balloon, or part thereof including its payload, with the surface creates a hazard to persons or property not associated with the operation.

## § 101.35

### Equipment and marking requirements.

. No person may operate an unmanned free balloon unless—
.. It is equipped with at least two payload cut-down systems or devices that operate independently of each other;
.. At least two methods, systems, devices, or combinations thereof, that function independently of each other, are employed for terminating the flight of the balloon envelope; and
.. The balloon envelope is equipped with a radar reflective device(s) or material that will present an echo to surface radar operating in the 200 MHz to 2700 MHz frequency range.
              
. No person may operate an unmanned free balloon below 60,000 feet standard pressure altitude between sunset and sunrise (as corrected to the altitude of operation) unless the balloon and its attachments and payload, whether or not they become separated during the operation, are equipped with lights that are visible for at least 5 miles and have a flash frequency of at least 40, and not more than 100, cycles per minute.
. No person may operate an unmanned free balloon that is equipped with a trailing antenna that requires an impact force of more than 50 pounds to break it at any point, unless the antenna has colored pennants or streamers that are attached at not more than 50 foot intervals and that are visible for at least one mile.
. No person may operate between sunrise and sunset an unmanned free balloon that is equipped with a suspension device (other than a highly conspicuously colored open parachute) more than 50 feet along, unless the suspension device is colored in alternate bands of high conspicuity colors or has colored pennants or streamers attached which are visible for at least one mile.

## § 101.37

### Notice requirements.

. *Prelaunch notice:* Except as provided in paragraph (b) of this section, no person may operate an unmanned free balloon unless, within 6 to 24 hours before beginning the operation, he gives the following information to the FAA ATC facility that is nearest to the place of intended operation:
.. The balloon identification.
.. The estimated date and time of launching, amended as necessary to remain within plus or minus 30 minutes.
.. The location of the launching site.
.. The cruising altitude.
.. The forecast trajectory and estimated time to cruising altitude or 60,000 feet standard pressure altitude, whichever is lower.
.. The length and diameter of the balloon, length of the suspension device, weight of the payload, and length of the trailing antenna.
.. The duration of flight.
.. The forecast time and location of impact with the surface of the earth.
. For solar or cosmic disturbance investigations involving a critical time element, the information in paragraph (a) of this section shall be given within 30 minutes to 24 hours before beginning the operation.
. *Cancellation notice:* If the operation is canceled, the person who intended to conduct the operation shall immediately notify the nearest FAA ATC facility.
. *Launch notice:* Each person operating an unmanned free balloon shall notify the nearest FAA or military ATC facility of the launch time immediately after the balloon is launched.

## § 101.39

### Balloon position reports.

. Each person operating an unmanned free balloon shall:
.. Unless ATC requires otherwise, monitor the course of the balloon and record its position at least every two hours; and
              
.. Forward any balloon position reports requested by ATC.
. One hour before beginning descent, each person operating an unmanned free balloon shall forward to the nearest FAA ATC facility the following information regarding the balloon:
.. The current geographical position.
.. The altitude.
.. The forecast time of penetration of 60,000 feet standard pressure altitude (if applicable).
.. The forecast trajectory for the balance of the flight.
.. The forecast time and location of impact with the surface of the earth.
. If a balloon position report is not recorded for any two-hour period of flight, the person operating an unmanned free balloon shall immediately notify the nearest FAA ATC facility. The notice shall include the last recorded position and any revision of the forecast trajectory. The nearest FAA ATC facility shall be notified immediately when tracking of the balloon is re-established.
. Each person operating an unmanned free balloon shall notify the nearest FAA ATC facility when the operation is ended.

