# Certification Procedures
:toc:

## § 67.401

### Special issuance of medical certificates.

. At the discretion of the Federal Air Surgeon, an Authorization for Special Issuance of a Medical Certificate (Authorization), valid for a specified period, may be granted to a person who does not meet the provisions of subparts B, C, or D of this part if the person shows to the satisfaction of the Federal Air Surgeon that the duties authorized by the class of medical certificate applied for can be performed without endangering public safety during the period in which the Authorization would be in force. The Federal Air Surgeon may authorize a special medical flight test, practical test, or medical evaluation for this purpose. A medical certificate of the appropriate class may be issued to a person who does not meet the provisions of subparts B, C, or D of this part if that person possesses a valid Authorization and is otherwise eligible. An airman medical certificate issued in accordance with this section shall expire no later than the end of the validity period or upon the withdrawal of the Authorization upon which it is based. At the end of its specified validity period, for grant of a new Authorization, the person must again show to the satisfaction of the Federal Air Surgeon that the duties authorized by the class of medical certificate applied for can be performed without endangering public safety during the period in which the Authorization would be in force.
. At the discretion of the Federal Air Surgeon, a Statement of Demonstrated Ability (SODA) may be granted, instead of an Authorization, to a person whose disqualifying condition is static or nonprogressive and who has been found capable of performing airman duties without endangering public safety. A SODA does not expire and authorizes a designated aviation medical examiner to issue a medical certificate of a specified class if the examiner finds that the condition described on its face has not adversely changed.
. In granting an Authorization or SODA, the Federal Air Surgeon may consider the person's operational experience and any medical facts that may affect the ability of the person to perform airman duties including—
.. The combined effect on the person of failure to meet more than one requirement of this part; and
.. The prognosis derived from professional consideration of all available information regarding the person.
. In granting an Authorization or SODA under this section, the Federal Air Surgeon specifies the class of medical certificate authorized to be issued and may do any or all of the following:
.. Limit the duration of an Authorization;
.. Condition the granting of a new Authorization on the results of subsequent medical tests, examinations, or evaluations;
.. State on the Authorization or SODA, and any medical certificate based upon it, any operational limitation needed for safety; or
.. Condition the continued effect of an Authorization or SODA, and any second- or third-class medical certificate based upon it, on compliance with a statement of functional limitations issued to the person in coordination with the Director of Flight Standards or the Director's designee.
. In determining whether an Authorization or SODA should be granted to an applicant for a third-class medical certificate, the Federal Air Surgeon considers the freedom of an airman, exercising the privileges of a private pilot certificate, to accept reasonable risks to his or her person and property that are not acceptable in the exercise of commercial or airline transport pilot privileges, and, at the same time, considers the need to protect the safety of persons and property in other aircraft and on the ground.
. An Authorization or SODA granted under the provisions of this section to a person who does not meet the applicable provisions of subparts B, C, or D of this part may be withdrawn, at the discretion of the Federal Air Surgeon, at any time if—
.. There is adverse change in the holder's medical condition;
.. The holder fails to comply with a statement of functional limitations or operational limitations issued as a condition of certification under this section;
.. Public safety would be endangered by the holder's exercise of airman privileges;
.. The holder fails to provide medical information reasonably needed by the Federal Air Surgeon for certification under this section; or
.. The holder makes or causes to be made a statement or entry that is the basis for withdrawal of an Authorization or SODA under § 67.403.
. A person who has been granted an Authorization or SODA under this section based on a special medical flight or practical test need not take the test again during later physical examinations unless the Federal Air Surgeon determines or has reason to believe that the physical deficiency has or may have degraded to a degree to require another special medical flight test or practical test.
. The authority of the Federal Air Surgeon under this section is also exercised by the Manager, Aeromedical Certification Division, and each Regional Flight Surgeon.
. If an Authorization or SODA is withdrawn under paragraph (f) of this section the following procedures apply:
.. The holder of the Authorization or SODA will be served a letter of withdrawal, stating the reason for the action;
.. By not later than 60 days after the service of the letter of withdrawal, the holder of the Authorization or SODA may request, in writing, that the Federal Air Surgeon provide for review of the decision to withdraw. The request for review may be accompanied by supporting medical evidence;
.. Within 60 days of receipt of a request for review, a written final decision either affirming or reversing the decision to withdraw will be issued; and
.. A medical certificate rendered invalid pursuant to a withdrawal, in accordance with paragraph (a) of this section, shall be surrendered to the Administrator upon request.

## § 67.403

### Applications, certificates, logbooks, reports, and records: Falsification, reproduction, or alteration; incorrect statements.

. No person may make or cause to be made—
.. A fraudulent or intentionally false statement on any application for a medical certificate or on a request for any Authorization for Special Issuance of a Medical Certificate (Authorization) or Statement of Demonstrated Ability (SODA) under this part;
.. A fraudulent or intentionally false entry in any logbook, record, or report that is kept, made, or used, to show compliance with any requirement for any medical certificate or for any Authorization or SODA under this part;
.. A reproduction, for fraudulent purposes, of any medical certificate under this part; or
.. An alteration of any medical certificate under this part.
. The commission by any person of an act prohibited under paragraph (a) of this section is a basis for—
.. Suspending or revoking all airman, ground instructor, and medical certificates and ratings held by that person;
.. Withdrawing all Authorizations or SODA's held by that person; and
.. Denying all applications for medical certification and requests for Authorizations or SODA's.
. The following may serve as a basis for suspending or revoking a medical certificate; withdrawing an Authorization or SODA; or denying an application for a medical certificate or request for an authorization or SODA:
.. An incorrect statement, upon which the FAA relied, made in support of an application for a medical certificate or request for an Authorization or SODA.
.. An incorrect entry, upon which the FAA relied, made in any logbook, record, or report that is kept, made, or used to show compliance with any requirement for a medical certificate or an Authorization or SODA.

## § 67.405

### Medical examinations: Who may perform?

. *First-class.* Any aviation medical examiner who is specifically designated for the purpose may perform examinations for the first-class medical certificate.
. *Second- and third-class.* Any aviation medical examiner may perform examinations for the second-or third-class medical certificate.

## § 67.407

### Delegation of authority.

. The authority of the Administrator under 49 U.S.C. 44703 to issue or deny medical certificates is delegated to the Federal Air Surgeon to the extent necessary to—
.. Examine applicants for and holders of medical certificates to determine whether they meet applicable medical standards; and
.. Issue, renew, and deny medical certificates, and issue, renew, deny, and withdraw Authorizations for Special Issuance of a Medical Certificate and Statements of Demonstrated Ability to a person based upon meeting or failing to meet applicable medical standards.
. Subject to limitations in this chapter, the delegated functions of the Federal Air Surgeon to examine applicants for and holders of medical certificates for compliance with applicable medical standards and to issue, renew, and deny medical certificates are also delegated to aviation medical examiners and to authorized representatives of the Federal Air Surgeon within the FAA.
. The authority of the Administrator under 49 U.S.C. 44702, to reconsider the action of an aviation medical examiner is delegated to the Federal Air Surgeon; the Manager, Aeromedical Certification Division; and each Regional Flight Surgeon. Where the person does not meet the standards of §§ 67.107(b)(3) and (c), 67.109(b), 67.113(b) and (c), 67.207(b)(3) and (c), 67.209(b), 67.213(b) and (c), 67.307(b)(3) and (c), 67.309(b), or 67.313(b) and (c), any action taken under this paragraph other than by the Federal Air Surgeon is subject to reconsideration by the Federal Air Surgeon. A certificate issued by an aviation medical examiner is considered to be affirmed as issued unless an FAA official named in this paragraph (authorized official) reverses that issuance within 60 days after the date of issuance. However, if within 60 days after the date of issuance an authorized official requests the certificate holder to submit additional medical information, an authorized official may reverse the issuance within 60 days after receipt of the requested information.
. The authority of the Administrator under 49 U.S.C. 44709 to re-examine any civil airman to the extent necessary to determine an airman's qualification to continue to hold an airman medical certificate, is delegated to the Federal Air Surgeon and his or her authorized representatives within the FAA.

## § 67.409

### Denial of medical certificate.

. Any person who is denied a medical certificate by an aviation medical examiner may, within 30 days after the date of the denial, apply in writing and in duplicate to the Federal Air Surgeon, Attention: Manager, Aeromedical Certification Division, AAM-300, Federal Aviation Administration, P.O. Box 26080, Oklahoma City, Oklahoma 73126, for reconsideration of that denial. If the person does not ask for reconsideration during the 30-day period after the date of the denial, he or she is considered to have withdrawn the application for a medical certificate.
. The denial of a medical certificate—
.. By an aviation medical examiner is not a denial by the Administrator under 49 U.S.C. 44703.
.. By the Federal Air Surgeon is considered to be a denial by the Administrator under 49 U.S.C. 44703.
.. By the Manager, Aeromedical Certification Division, or a Regional Flight Surgeon is considered to be a denial by the Administrator under 49 U.S.C. 44703 except where the person does not meet the standards of §§ 67.107(b)(3) and (c), 67.109(b), or 67.113(b) and (c); 67.207(b)(3) and (c), 67.209(b), or 67.213(b) and (c); or 67.307(b)(3) and (c), 67.309(b), or 67.313(b) and (c).
              
. Any action taken under § 67.407(c) that wholly or partly reverses the issue of a medical certificate by an aviation medical examiner is the denial of a medical certificate under paragraph (b) of this section.
. If the issue of a medical certificate is wholly or partly reversed by the Federal Air Surgeon; the Manager, Aeromedical Certification Division; or a Regional Flight Surgeon, the person holding that certificate shall surrender it, upon request of the FAA.

## § 67.411

### Reserved

## § 67.413

### Medical records.

. Whenever the Administrator finds that additional medical information or history is necessary to determine whether you meet the medical standards required to hold a medical certificate, you must:
.. Furnish that information to the FAA; or
.. Authorize any clinic, hospital, physician, or other person to release to the FAA all available information or records concerning that history.
. If you fail to provide the requested medical information or history or to authorize its release, the FAA may suspend, modify, or revoke your medical certificate or, in the case of an applicant, deny the application for a medical certificate.
. If your medical certificate is suspended, modified, or revoked under paragraph (b) of this section, that suspension or modification remains in effect until you provide the requested information, history, or authorization to the FAA and until the FAA determines that you meet the medical standards set forth in this part.

## § 67.415

### Return of medical certificate after suspension or revocation.

The holder of any medical certificate issued under this part that is suspended or revoked shall, upon the Administrator's request, return it to the Administrator.

