# Operating Rules
:toc:

## § 103.9

### Hazardous operations.

. No person may operate any ultralight vehicle in a manner that creates a hazard to other persons or property.
. No person may allow an object to be dropped from an ultralight vehicle if such action creates a hazard to other persons or property.

## § 103.11

### Daylight operations.

. No person may operate an ultralight vehicle except between the hours of sunrise and sunset.
. Notwithstanding paragraph (a) of this section, ultralight vehicles may be operated during the twilight periods 30 minutes before official sunrise and 30 minutes after official sunset or, in Alaska, during the period of civil twilight as defined in the Air Almanac, if:
.. The vehicle is equipped with an operating anticollision light visible for at least 3 statute miles; and
.. All operations are conducted in uncontrolled airspace.

## § 103.13

### Operation near aircraft; right-of-way rules.

. Each person operating an ultralight vehicle shall maintain vigilance so as to see and avoid aircraft and shall yield the right-of-way to all aircraft.
. No person may operate an ultralight vehicle in a manner that creates a collision hazard with respect to any aircraft.
. Powered ultralights shall yield the right-of-way to unpowered ultralights.

## § 103.15

### Operations over congested areas.

No person may operate an ultralight vehicle over any congested area of a city, town, or settlement, or over any open air assembly of persons.

## § 103.17

### Operations in certain airspace.

No person may operate an ultralight vehicle within Class A, Class B, Class C, or Class D airspace or within the lateral boundaries of the surface area of Class E airspace designated for an airport unless that person has prior authorization from the ATC facility having jurisdiction over that airspace.

## § 103.19

### Operations in prohibited or restricted areas.

No person may operate an ultralight vehicle in prohibited or restricted areas unless that person has permission from the using or controlling agency, as appropriate.

## § 103.20

### Flight restrictions in the proximity of certain areas designated by notice to airmen.

No person may operate an ultralight vehicle in areas designated in a Notice to Airmen under § 91.137, § 91.138, § 91.141, § 91.143 or § 91.145 of this chapter, unless authorized by:

. Air Traffic Control (ATC); or
. A Flight Standards Certificate of Waiver or Authorization issued for the demonstration or event.

## § 103.21

### Visual reference with the surface.

No person may operate an ultralight vehicle except by visual reference with the surface.

## § 103.23

### Flight visibility and cloud clearance requirements.

No person may operate an ultralight vehicle when the flight visibility or distance from clouds is less than that in the table found below. All operations in Class A, Class B, Class C, and Class D airspace or Class E airspace designated for an airport must receive prior ATC authorization as required in § 103.17 of this part.

