# Airplane Performance Operating Limitations
:toc:

## § 121.171

### Applicability.

. This subpart prescribes airplane performance operating limitations for all certificate holders.
. For purposes of this part, *effective length of the runway* for landing means the distance from the point at which the obstruction clearance plane associated with the approach end of the runway intersects the centerline of the runway to the far end thereof.
. For the purposes of this subpart, *obstruction clearance plane* means a plane sloping upward from the runway at a slope of 1:20 to the horizontal, and tangent to or clearing all obstructions within a specified area surrounding the runway as shown in a profile view of that area. In the plan view, the centerline of the specified area coincides with the centerline of the runway, beginning at the point where the obstruction clearance plane intersects the centerline of the runway and proceeding to a point at least 1,500 feet from the beginning point. Thereafter the centerline coincides with the takeoff path over the ground for the runway (in the case of takeoffs) or with the instrument approach counterpart (for landings), or, where the applicable one of these paths has not been established, it proceeds consistent with turns of at least 4,000 foot radius until a point is reached beyond which the obstruction clearance plane clears all obstructions. This area extends laterally 200 feet on each side of the centerline at the point where the obstruction clearance plane intersects the runway and continues at this width to the end of the runway; then it increases uniformly to 500 feet on each side of the centerline at a point 1,500 feet from the intersection of the obstruction clearance plane with the runway; thereafter it extends laterally 500 feet on each side of the centerline.

## § 121.173

### General.

. Except as provided in paragraph (c) of this section, each certificate holder operating a reciprocating-engine-powered airplane shall comply with §§ 121.175 through 121.187.
. Except as provided in paragraph (c) of this section, each certificate holder operating a turbine-engine-powered airplane shall comply with the applicable provisions of §§ 121.189 through 121.197, except that when it operates—
.. A turbo-propeller-powered airplane type certificated after August 29, 1959, but previously type certificated with the same number of reciprocating engines, the certificate holder may comply with §§ 121.175 through 121.187; or
.. Until December 20, 2010, a turbo-propeller-powered airplane described in § 121.157(f), the certificate holder may comply with the applicable performance requirements of appendix K of this part.
. Each certificate holder operating a large nontransport category airplane type certificated before January 1, 1965, shall comply with §§ 121.199 through 121.205 and any determination of compliance must be based only on approved performance data.
. The performance data in the Airplane Flight Manual applies in determining compliance with §§ 121.175 through 121.197. Where conditions are different from those on which the performance data is based, compliance is determined by interpolation or by computing the effects of changes in the specific variables if the results of the interpolation or computations are substantially as accurate as the results of direct tests.
. Except as provided in paragraph (c) of this section, no person may take off a reciprocating-engine-powered airplane at a weight that is more than the allowable weight for the runway being used (determined under the runway takeoff limitations of the operating rules of 14 CFR part 121, subpart I) after taking into account the temperature operating correction factors in the applicable Airplane Flight Manual.
. The Administrator may authorize in the operations specifications deviations from the requirements in the subpart if special circumstances make a literal observance of a requirement unnecessary for safety.
. The ten-mile width specified in §§ 121.179 through 121.183 may be reduced to five miles, for not more than 20 miles, when operating VFR or where navigation facilities furnish reliable and accurate identification of high ground and obstructions located outside of five miles, but within ten miles, on each side of the intended track.

## § 121.175

### Airplanes: Reciprocating engine-powered: Weight limitations.

. No person may take off a reciprocating engine powered airplane from an airport located at an elevation outside of the range for which maximum takeoff weights have been determined for that airplane.
. No person may take off a reciprocating engine powered airplane for an airport of intended destination that is located at an elevation outside of the range for which maximum landing weights have been determined for that airplane.
. No person may specify, or have specified, an alternate airport that is located at an elevation outside of the range for which maximum landing weights have been determined for the reciprocating engine powered airplane concerned.
. No person may take off a reciprocating engine powered airplane at a weight more than the maximum authorized takeoff weight for the elevation of the airport.
. No person may take off a reciprocating engine powered airplane if its weight on arrival at the airport of destination will be more than the maximum authorized landing weight for the elevation of that airport, allowing for normal consumption of fuel and oil en route.
              
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.177

### Airplanes: Reciprocating engine-powered: Takeoff limitations.

. No person operating a reciprocating engine powered airplane may takeoff that airplane unless it is possible—
.. To stop the airplane safely on the runway, as shown by the accelerate stop distance data, at any time during takeoff until reaching critical-engine failure speed;
.. If the critical engine fails at any time after the airplane reaches critical-engine failure speed *V*
                *1*, to continue the takeoff and reach a height of 50 feet, as indicated by the takeoff path data, before passing over the end of the runway; and
.. To clear all obstacles either by at least 50 feet vertically (as shown by the takeoff path data) or 200 feet horizontally within the airport boundaries and 300 feet horizontally beyond the boundaries, without banking before reaching a height of 50 feet (as shown by the takeoff path data) and thereafter without banking more than 15 degrees.
. In applying this section, corrections must be made for the effective runway gradient. To allow for wind effect, takeoff data based on still air may be corrected by taking into account not more than 50 percent of any reported headwind component and not less than 150 percent of any reported tailwind component.
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.179

### Airplanes: Reciprocating engine-powered: En route limitations: All engines operating.

. No person operating a reciprocating engine powered airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that does not allow a rate of climb (in feet per minute), with all engines operating, of at least 6.90 *V*
                *So* (that is, the number of feet per minute is obtained by multiplying the number of knots by 6.90) at an altitude of at least 1,000 feet above the highest ground or obstruction within ten miles of each side of the intended track.
. This section does not apply to airplanes certificated under part 4a of the Civil Air Regulations.
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.181

### Airplanes: Reciprocating engine-powered: En route limitations: One engine inoperative.

. Except as provided in paragraph (b) of this section, no person operating a reciprocating engine powered airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that does not allow a rate of climb (in feet per minute), with one engine inoperative, of at least
              
. In place of the requirements of paragraph (a) of this section, a person may, under an approved procedure, operate a reciprocating engine powered airplane, at an all-engines-operating altitude that allows the airplane to continue, after an engine failure, to an alternate airport where a landing can be made in accordance with § 121.187, allowing for normal consumption of fuel and oil. After the assumed failure, the flight path must clear the ground and any obstruction within five miles on each side of the intended track by at least 2,000 feet.
. If an approved procedure under paragraph (b) of this section is used, the certificate holder shall comply with the following:
.. The rate of climb (as prescribed in the Airplane Flight Manual for the appropriate weight and altitude) used in calculating the airplane's flight path shall be diminished by an amount, in feet per minute, equal to
              
.. The all-engines-operating altitude shall be sufficient so that in the event the critical engine becomes inoperative at any point along the route, the flight will be able to proceed to a predetermined alternate airport by use of this procedure. In determining the takeoff weight, the airplane is assumed to pass over the critical obstruction following engine failure at a point no closer to the critical obstruction than the nearest approved radio navigational fix, unless the Administrator approves a procedure established on a different basis upon finding that adequate operational safeguards exist.
.. The airplane must meet the provisions of paragraph (a) of this section at 1,000 feet above the airport used as an alternate in this procedure.
.. The procedure must include an approved method of accounting for winds and temperatures that would otherwise adversely affect the flight path.
.. In complying with this procedure fuel jettisoning is allowed if the certificate holder shows that it has an adequate training program, that proper instructions are given to the flight crew, and all other precautions are taken to insure a safe procedure.
.. The certificate holder shall specify in the dispatch or flight release an alternate airport that meets the requirements of § 121.625.
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.183

### Part 25 airplanes with four or more engines: Reciprocating engine powered: En route limitations: Two engines inoperative.

. No person may operate an airplane certificated under part 25 and having four or more engines unless—
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets the requirements of § 121.187; or
.. It is operated at a weight allowing the airplane, with the two critical engines inoperative, to climb at 0.013 V*so*2 feet per minute (that is, the number of feet per minute is obtained by multiplying the number of knots squared by 0.013) at an altitude of 1,000 feet above the highest ground or obstruction within 10 miles on each side of the intended track, or at an altitude of 5,000 feet, whichever is higher.
. For the purposes of paragraph (a)(2) of this section, it is assumed that—
.. The two engines fail at the point that is most critical with respect to the takeoff weight:
.. Consumption of fuel and oil is normal with all engines operating up to the point where the two engines fail and with two engines operating beyond that point;
.. Where the engines are assumed to fail at an altitude above the prescribed minimum altitude, compliance with the prescribed rate of climb at the prescribed minimum altitude need not be shown during the descent from the cruising altitude to the prescribed minimum altitude, if those requirements can be met once the prescribed minimum altitude is reached, and assuming descent to be along a net flight path and the rate of descent to be 0.013 V*so*2 greater than the rate in the approved performance data; and
.. If fuel jettisoning is provided, the airplane's weight at the point where the two engines fail is considered to be not less than that which would include enough fuel to proceed to an airport meeting the requirements of § 121.187 and to arrive at an altitude of at least 1,000 feet directly over that airport.

## § 121.185

### Airplanes: Reciprocating engine-powered: Landing limitations: Destination airport.

. Except as provided in paragraph (b) of this section no person operating a reciprocating engine powered airplane may take off that airplane, unless its weight on arrival, allowing for normal consumption of fuel and oil in flight, would allow a full stop landing at the intended destination within 60 percent of the effective length of each runway described below from a point 50 feet directly above the intersection of the obstruction clearance plane and the runway. For the purposes of determining the allowable landing weight at the destination airport the following is assumed:
.. The airplane is landed on the most favorable runway and in the most favorable direction in still air.
.. The airplane is landed on the most suitable runway considering the probable wind velocity and direction (forecast for the expected time of arrival), the ground handling characteristics of the type of airplane, and other conditions such as landing aids and terrain, and allowing for the effect of the landing path and roll of not more than 50 percent of the headwind component or not less than 150 percent of the tailwind component.
. An airplane that would be prohibited from being taken off because it could not meet the requirements of paragraph (a)(2) of this section may be taken off if an alternate airport is specified that meets all of the requirements of this section except that the airplane can accomplish a full stop landing within 70 percent of the effective length of the runway.
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.187

### Airplanes: Reciprocating engine-powered: Landing limitations: Alternate airport.

. No person may list an airport as an alternate airport in a dispatch or flight release unless the airplane (at the weight anticipated at the time of arrival at the airport), based on the assumptions in § 121.185, can be brought to a full stop landing, within 70 percent of the effective length of the runway.
. This section does not apply to large nontransport category airplanes operated under § 121.173(c).

## § 121.189

### Airplanes: Turbine engine powered: Takeoff limitations.

. No person operating a turbine engine powered airplane may take off that airplane at a weight greater than that listed in the Airplane Flight Manual for the elevation of the airport and for the ambient temperature existing at takeoff.
. No person operating a turbine engine powered airplane certificated after August 26, 1957, but before August 30, 1959 (SR422, 422A), may take off that airplane at a weight greater than that listed in the Airplane Flight Manual for the minimum distances required for takeoff. In the case of an airplane certificated after September 30, 1958 (SR422A, 422B), the takeoff distance may include a clearway distance but the clearway distance included may not be greater than 1/2 of the takeoff run.
. No person operating a turbine engine powered airplane certificated after August 29, 1959 (SR422B), may take off that airplane at a weight greater than that listed in the Airplane Flight Manual at which compliance with the following may be shown:
.. The accelerate-stop distance must not exceed the length of the runway plus the length of any stopway.
.. The takeoff distance must not exceed the length of the runway plus the length of any clearway except that the length of any clearway included must not be greater than one-half the length of the runway.
.. The takeoff run must not be greater than the length of the runway.
. No person operating a turbine engine powered airplane may take off that airplane at a weight greater than that listed in the Airplane Flight Manual—
.. In the case of an airplane certificated after August 26, 1957, but before October 1, 1958 (SR422), that allows a takeoff path that clears all obstacles either by at least (35 + 0.01D) feet vertically (D is the distance along the intended flight path from the end of the runway in feet), or by at least 200 feet horizontally within the airport boundaries and by at least 300 feet horizontally after passing the boundaries; or
.. In the case of an airplane certificated after September 30, 1958 (SR 422A, 422B), that allows a net takeoff flight path that clears all obstacles either by a height of at least 35 feet vertically, or by at least 200 feet horizontally within the airport boundaries and by at least 300 feet horizontally after passing the boundaries.
. In determining maximum weights, minimum distances, and flight paths under paragraphs (a) through (d) of this section, correction must be made for the runway to be used, the elevation of the airport, the effective runway gradient, the ambient temperature and wind component at the time of takeoff, and, if operating limitations exist for the minimum distances required for takeoff from wet runways, the runway surface condition (dry or wet). Wet runway distances associated with grooved or porous friction course runways, if provided in the Airplane Flight Manual, may be used only for runways that are grooved or treated with a porous friction course (PFC) overlay, and that the operator determines are designed, constructed, and maintained in a manner acceptable to the Administrator.
. For the purposes of this section, it is assumed that the airplane is not banked before reaching a height of 50 feet, as shown by the takeoff path or net takeoff flight path data (as appropriate) in the Airplane Flight Manual, and thereafter that the maximum bank is not more than 15 degrees.
. For the purposes of this section the terms, *takeoff distance, takeoff run, net takeoff flight path* and *takeoff path* have the same meanings as set forth in the rules under which the airplane was certificated.

## § 121.191

### Airplanes: Turbine engine powered: En route limitations: One engine inoperative.

. No person operating a turbine engine powered airplane may take off that airplane at a weight, allowing for normal consumption of fuel and oil, that is greater than that which (under the approved, one engine inoperative, en route net flight path data in the Airplane Flight Manual for that airplane) will allow compliance with paragraph (a) (1) or (2) of this section, based on the ambient temperatures expected en route:
.. There is a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within five statute miles on each side of the intended track, and, in addition, if that airplane was certificated after August 29, 1959 (SR 422B) there is a positive slope at 1,500 feet above the airport where the airplane is assumed to land after an engine fails.
.. The net flight path allows the airplane to continue flight from the cruising altitude to an airport where a landing can be made under § 121.197, clearing all terrain and obstructions within five statute miles of the intended track by at least 2,000 feet vertically and with a positive slope at 1,000 feet above the airport where the airplane lands after an engine fails, or, if that airplane was certificated after September 30, 1958 (SR 422A, 422B), with a positive slope at 1,500 feet above the airport where the airplane lands after an engine fails.
. For the purposes of paragraph (a)(2) of this section, it is assumed that—
.. The engine fails at the most critical point en route;
.. The airplane passes over the critical obstruction, after engine failure at a point that is no closer to the obstruction than the nearest approved radio navigation fix, unless the Administrator authorizes a different procedure based on adequate operational safeguards;
.. An approved method is used to allow for adverse winds:
.. Fuel jettisoning will be allowed if the certificate holder shows that the crew is properly instructed, that the training program is adequate, and that all other precautions are taken to insure a safe procedure;
.. The alternate airport is specified in the dispatch or flight release and meets the prescribed weather minimums; and
.. The consumption of fuel and oil after engine failure is the same as the consumption that is allowed for in the approved net flight path data in the Airplane Flight Manual.

## § 121.193

### Airplanes: Turbine engine powered: En route limitations: Two engines inoperative.

. *Airplanes certificated after August 26, 1957, but before October 1, 1958* (SR 422). No person may operate a turbine engine powered airplane along an intended route unless he complies with either of the following:
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets the requirements of § 121.197.
.. Its weight, according to the two-engine-inoperative, en route, net flight path data in the Airplane Flight Manual, allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets the requirements of § 121.197, with a net flight path (considering the ambient temperature anticipated along the track) having a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within five miles on each side of the intended track, or at an altitude of 5,000 feet, whichever is higher.
              
. *Aircraft certificated after September 30, 1958, but before August 30, 1959* (SR 422A). No person may operate a turbine engine powered airplane along an intended route unless he complies with either of the following:
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets the requirements of § 121.197.
.. Its weight, according to the two-engine-inoperative, en route, net flight path data in the Airplane Flight Manual, allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets the requirements of § 121.197, with a net flight path (considering the ambient temperatures anticipated along the track) having a positive slope at an altitude of at least 1,000 feet above all terrain and obstructions within 5 miles on each side of the intended track, or at an altitude of 2,000 feet, whichever is higher.
              
. *Aircraft certificated after August 29, 1959* (SR 422B). No person may operate a turbine engine powered airplane along an intended route unless he complies with either of the following:
.. There is no place along the intended track that is more than 90 minutes (with all engines operating at cruising power) from an airport that meets the requirements of § 121.197.
.. Its weight, according to the two-engine inoperative, en route, net flight path data in the Airplane Flight Manual, allows the airplane to fly from the point where the two engines are assumed to fail simultaneously to an airport that meets the requirements of § 121.197, with the net flight path (considering the ambient temperatures anticipated along the track) clearing vertically by at least 2,000 feet all terrain and obstructions within five statute miles (4.34 nautical miles) on each side of the intended track. For the purposes of this subparagraph, it is assumed that—
... The two engines fail at the most critical point en route;
... The net flight path has a positive slope at 1,500 feet above the airport where the landing is assumed to be made after the engines fail;
... Fuel jettisoning will be approved if the certificate holder shows that the crew is properly instructed, that the training program is adequate, and that all other precautions are taken to ensure a safe procedure;
... The airplane's weight at the point where the two engines are assumed to fail provides enough fuel to continue to the airport, to arrive at an altitude of at least 1,500 feet directly over the airport, and thereafter to fly for 15 minutes at cruise power or thrust, or both; and
... The consumption of fuel and oil after the engine failure is the same as the consumption that is allowed for in the net flight path data in the Airplane Flight Manual.

## § 121.195

### Airplanes: Turbine engine powered: Landing limitations: Destination airports.

. No person operating a turbine engine powered airplane may take off that airplane at such a weight that (allowing for normal consumption of fuel and oil in flight to the destination or alternate airport) the weight of the airplane on arrival would exceed the landing weight set forth in the Airplane Flight Manual for the elevation of the destination or alternate airport and the ambient temperature anticipated at the time of landing.
. Except as provided in paragraph (c), (d), or (e) of this section, no person operating a turbine engine powered airplane may take off that airplane unless its weight on arrival, allowing for normal consumption of fuel and oil in flight (in accordance with the landing distance set forth in the Airplane Flight Manual for the elevation of the destination airport and the wind conditions anticipated there at the time of landing), would allow a full stop landing at the intended destination airport within 60 percent of the effective length of each runway described below from a point 50 feet above the intersection of the obstruction clearance plane and the runway. For the purpose of determining the allowable landing weight at the destination airport the following is assumed:
.. The airplane is landed on the most favorable runway and in the most favorable direction, in still air.
.. The airplane is landed on the most suitable runway considering the probable wind velocity and direction and the ground handling characteristics of the airplane, and considering other conditions such as landing aids and terrain.
. A turbopropeller powered airplane that would be prohibited from being taken off because it could not meet the requirements of paragraph (b)(2) of this section, may be taken off if an alternate airport is specified that meets all the requirements of this section except that the airplane can accomplish a full stop landing within 70 percent of the effective length of the runway.
. Unless, based on a showing of actual operating landing techniques on wet runways, a shorter landing distance (but never less than that required by paragraph (b) of this section) has been approved for a specific type and model airplane and included in the Airplane Flight Manual, no person may takeoff a turbojet powered airplane when the appropriate weather reports and forecasts, or a combination thereof, indicate that the runways at the destination airport may be wet or slippery at the estimated time of arrival unless the effective runway length at the destination airport is at least 115 percent of the runway length required under paragraph (b) of this section.
. A turbojet powered airplane that would be prohibited from being taken off because it could not meet the requirements of paragraph (b)(2) of this section may be taken off if an alternate airport is specified that meets all the requirements of paragraph (b) of this section.

## § 121.197

### Airplanes: Turbine engine powered: Landing limitations: Alternate airports.

No person may list an airport as an alternate airport in a dispatch or flight release for a turbine engine powered airplane unless (based on the assumptions in § 121.195 (b)) that airplane at the weight anticipated at the time of arrival can be brought to a full stop landing within 70 percent of the effective length of the runway for turbopropeller powered airplanes and 60 percent of the effective length of the runway for turbojet powered airplanes, from a point 50 feet above the intersection of the obstruction clearance plane and the runway. In the case of an alternate airport for departure, as provided in § 121.617, allowance may be made for fuel jettisoning in addition to normal consumption of fuel and oil when determining the weight anticipated at the time of arrival.

## § 121.198

### Cargo service airplanes: Increased zero fuel and landing weights.

. Notwithstanding the applicable structural provisions of the airworthiness regulations but subject to paragraphs (b) through (g) of this section, a certificate holder may operate (for cargo service only) any of the following airplanes (certificated under part 4b of the Civil Air Regulations effective before March 13, 1956) at increased zero fuel and landing weights—
.. DC-6A, DC-6B, DC-7B, and DC-7C; and
.. L1049B, C, D, E, F, G, and H, and the L1649A when modified in accordance with supplemental type certificate SA 4-1402.
. The zero fuel weight (maximum weight of the airplane with no disposable fuel and oil) and the structural landing weight may be increased beyond the maximum approved in full compliance with applicable regulations only if the Administrator finds that—
.. The increase is not likely to reduce seriously the structural strength;
.. The probability of sudden fatigue failure is not noticeably increased;
.. The flutter, deformation, and vibration characteristics do not fall below those required by applicable regulations; and
.. All other applicable weight limitations will be met.
. No zero fuel weight may be increased by more than five percent, and the increase in the structural landing weight may not exceed the amount, in pounds, of the increase in zero fuel weight.
. Each airplane must be inspected in accordance with the approved special inspection procedures, for operations at increased weights, established and issued by the manufacturer of the type of airplane.
. Each airplane operated under this section must be operated in accordance with the passenger-carrying performance operating limitations prescribed in this part.
. The Airplane Flight Manual for each airplane operated under this section must be appropriately revised to include the operating limitations and information needed for operation at the increased weights.
. Except as provided for the carrying of persons under § 121.583 each airplane operated at an increased weight under this section must, before it is used in passenger service, be inspected under the special inspection procedures for return to passenger service established and issued by the manufacturer and approved by the Administrator.

## § 121.199

### Nontransport category airplanes: Takeoff limitations.

. No person operating a nontransport category airplane may take off that airplane at a weight greater than the weight that would allow the airplane to be brought to a safe stop within the effective length of the runway, from any point during the takeoff before reaching 105 percent of minimum control speed (the minimum speed at which an airplane can be safely controlled in flight after an engine becomes inoperative) or 115 percent of the power off stalling speed in the takeoff configuration, whichever is greater.
. For the purposes of this section—
.. It may be assumed that takeoff power is used on all engines during the acceleration;
.. Not more than 50 percent of the reported headwind component, or not less than 150 percent of the reported tailwind component, may be taken into account;
.. The average runway gradient (the difference between the elevations of the endpoints of the runway divided by the total length) must be considered if it is more than one-half of 1 percent;
.. It is assumed that the airplane is operating in standard atmosphere; and
.. The *effective length of the runway* for takeoff means the distance from the end of the runway at which the takeoff is started to a point at which the obstruction clearance plane associated with the other end of the runway intersects the runway centerline.

## § 121.201

### Nontransport category airplanes: En route limitations: One engine inoperative.

. Except as provided in paragraph (b) of this section, no person operating a nontransport category airplane may take off that airplane at a weight that does not allow a rate of climb of at least 50 feet a minute, with the critical engine inoperative, at an altitude of at least 1,000 feet above the highest obstruction within five miles on each side of the intended track, or 5,000 feet, whichever is higher.
. Notwithstanding paragraph (a) of this section, if the Administrator finds that safe operations are not impaired, a person may operate the airplane at an altitude that allows the airplane, in case of engine failure, to clear all obstructions within 5 miles on each side of the intended track by 1,000 feet. If this procedure is used, the rate of descent for the appropriate weight and altitude is assumed to be 50 feet a minute greater than the rate in the approved performance data. Before approving such a procedure, the Administrator considers the following for the route, route segment, or area concerned:
.. The reliability of wind and weather forecasting.
.. The location and kinds of navigation aids.
.. The prevailing weather conditions, particularly the frequency and amount of turbulence normally encountered.
.. Terrain features.
.. Air traffic control problems.
.. Any other operational factors that affect the operation.
. For the purposes of this section, it is assumed that—
.. The critical engine is inoperative;
.. The propeller of the inoperative engine is in the minimum drag position;
.. The wing flaps and landing gear are in the most favorable position;
.. The operating engines are operating at the maximum continuous power available;
.. The airplane is operating in standard atmosphere; and
.. The weight of the airplane is progressively reduced by the anticipated consumption of fuel and oil.

## § 121.203

### Nontransport category airplanes: Landing limitations: Destination airport.

. No person operating a nontransport category airplane may take off that airplane at a weight that—
.. Allowing for anticipated consumption of fuel and oil, is greater than the weight that would allow a full stop landing within 60 percent of the effective length of the most suitable runway at the destination airport; and
.. Is greater than the weight allowable if the landing is to be made on the runway—
... With the greatest effective length in still air; and
... Required by the probable wind, taking into account not more than 50 percent of the headwind component or not less than 150 percent of the tailwind component.
. For the purposes of this section, it is assumed that—
.. The airplane passes directly over the intersection of the obstruction clearance plane and the runway at a height of 50 feet in a steady gliding approach at a true indicated airspeed of at least 1.3 *V*
                *S*
                *o*;
.. The landing does not require exceptional pilot skill; and
.. The airplane is operating in standard atmosphere.

## § 121.205

### Nontransport category airplanes: Landing limitations: Alternate airport.

No person may list an airport as an alternate airport in a dispatch or flight release for a nontransport category airplane unless that airplane (at the weight anticipated at the time of arrival) based on the assumptions contained in § 121.203, can be brought to a full stop landing within 70 percent of the effective length of the runway.

## § 121.207

### Provisionally certificated airplanes: Operating limitations.

In addition to the limitations in § 91.317 of this chapter, the following limitations apply to the operation of provisionally certificated airplanes by certificate holders:

. In addition to crewmembers, each certificate holder may carry on such an airplane only those persons who are listed in § 121.547(c) or who are specifically authorized by both the certificate holder and the Administrator.
. Each certificate holder shall keep a log of each flight conducted under this section and shall keep accurate and complete records of each inspection made and all maintenance performed on the airplane. The certificate holder shall make the log and records made under this section available to the manufacturer and the Administrator.

