# Flight Crewmember Requirements
:toc:

## § 135.241 - Applicability.

Except as provided in § 135.3, this subpart prescribes the flight crewmember requirements for operations under this part.

## § 135.243 - Pilot in command qualifications.

[loweralpha]
. No certificate holder may use a person, nor may any person serve, as pilot in command in passenger-carrying operations—
[arabic]
.. Of a turbojet airplane, of an airplane having a passenger-seat configuration, excluding each crewmember seat, of 10 seats or more, or of a multiengine airplane in a commuter operation as defined in part 119 of this chapter, unless that person holds an airline transport pilot certificate with appropriate category and class ratings and, if required, an appropriate type rating for that airplane.
.. Of a helicopter in a scheduled interstate air transportation operation by an air carrier within the 48 contiguous states unless that person holds an airline transport pilot certificate, appropriate type ratings, and an instrument rating.
. Except as provided in paragraph (a) of this section, no certificate holder may use a person, nor may any person serve, as pilot in command of an aircraft under VFR unless that person—
[arabic]
.. Holds at least a commercial pilot certificate with appropriate category and class ratings and, if required, an appropriate type rating for that aircraft; and
.. Has had at least 500 hours time as a pilot, including at least 100 hours of cross-country flight time, at least 25 hours of which were at night; and
.. For an airplane, holds an instrument rating or an airline transport pilot certificate with an airplane category rating; or
.. For helicopter operations conducted VFR over-the-top, holds a helicopter instrument rating, or an airline transport pilot certificate with a category and class rating for that aircraft, not limited to VFR.
. Except as provided in paragraph (a) of this section, no certificate holder may use a person, nor may any person serve, as pilot in command of an aircraft under IFR unless that person—
[arabic]
.. Holds at least a commercial pilot certificate with appropriate category and class ratings and, if required, an appropriate type rating for that aircraft; and
.. Has had at least 1,200 hours of flight time as a pilot, including 500 hours of cross country flight time, 100 hours of night flight time, and 75 hours of actual or simulated instrument time at least 50 hours of which were in actual flight; and
.. For an airplane, holds an instrument rating or an airline transport pilot certificate with an airplane category rating; or
.. For a helicopter, holds a helicopter instrument rating, or an airline transport pilot certificate with a category and class rating for that aircraft, not limited to VFR.
. Paragraph (b)(3) of this section does not apply when—
[arabic]
.. The aircraft used is a single reciprocating-engine-powered airplane;
.. The certificate holder does not conduct any operation pursuant to a published flight schedule which specifies five or more round trips a week between two or more points and places between which the round trips are performed, and does not transport mail by air under a contract or contracts with the United States Postal Service having total amount estimated at the beginning of any semiannual reporting period (January 1-June 30; July 1-December 31) to be in excess of $20,000 over the 12 months commencing with the beginning of the reporting period;
.. The area, as specified in the certificate holder's operations specifications, is an isolated area, as determined by the Flight Standards district office, if it is shown that—
[lowerroman]
... The primary means of navigation in the area is by pilotage, since radio navigational aids are largely ineffective; and
... The primary means of transportation in the area is by air;
.. Each flight is conducted under day VFR with a ceiling of not less than 1,000 feet and visibility not less than 3 statute miles;
.. Weather reports or forecasts, or any combination of them, indicate that for the period commencing with the planned departure and ending 30 minutes after the planned arrival at the destination the flight may be conducted under VFR with a ceiling of not less than 1,000 feet and visibility of not less than 3 statute miles, except that if weather reports and forecasts are not available, the pilot in command may use that pilot's observations or those of other persons competent to supply weather observations if those observations indicate the flight may be conducted under VFR with the ceiling and visibility required in this paragraph;
.. The distance of each flight from the certificate holder's base of operation to destination does not exceed 250 nautical miles for a pilot who holds a commercial pilot certificate with an airplane rating without an instrument rating, provided the pilot's certificate does not contain any limitation to the contrary; and
.. The areas to be flown are approved by the certificate-holding FAA Flight Standards district office and are listed in the certificate holder's operations specifications.

## § 135.244 - Operating experience.

[loweralpha]
. No certificate holder may use any person, nor may any person serve, as a pilot in command of an aircraft operated in a commuter operation, as defined in part 119 of this chapter unless that person has completed, prior to designation as pilot in command, on that make and basic model aircraft and in that crewmember position, the following operating experience in each make and basic model of aircraft to be flown:
[arabic]
.. Aircraft, single engine—10 hours.
.. Aircraft multiengine, reciprocating engine-powered—15 hours.
.. Aircraft multiengine, turbine engine-powered—20 hours.
.. Airplane, turbojet-powered—25 hours.
. In acquiring the operating experience, each person must comply with the following:
[arabic]
.. The operating experience must be acquired after satisfactory completion of the appropriate ground and flight training for the aircraft and crewmember position. Approved provisions for the operating experience must be included in the certificate holder's training program.
.. The experience must be acquired in flight during commuter passenger-carrying operations under this part. However, in the case of an aircraft not previously used by the certificate holder in operations under this part, operating experience acquired in the aircraft during proving flights or ferry flights may be used to meet this requirement.
.. Each person must acquire the operating experience while performing the duties of a pilot in command under the supervision of a qualified check pilot.
.. The hours of operating experience may be reduced to not less than 50 percent of the hours required by this section by the substitution of one additional takeoff and landing for each hour of flight.

## § 135.245 - Second in command qualifications.

[loweralpha]
. Except as provided in paragraph (b), no certificate holder may use any person, nor may any person serve, as second in command of an aircraft unless that person holds at least a commercial pilot certificate with appropriate category and class ratings and an instrument rating. For flight under IFR, that person must meet the recent instrument experience requirements of part 61 of this chapter.
. A second in command of a helicopter operated under VFR, other than over-the-top, must have at least a commercial pilot certificate with an appropriate aircraft category and class rating.

## § 135.247 - Pilot qualifications: Recent experience.

[loweralpha]
. No certificate holder may use any person, nor may any person serve, as pilot in command of an aircraft carrying passengers unless, within the preceding 90 days, that person has—
              
[arabic]
.. Made three takeoffs and three landings as the sole manipulator of the flight controls in an aircraft of the same category and class and, if a type rating is required, of the same type in which that person is to serve; or
.. For operation during the period beginning 1 hour after sunset and ending 1 hour before sunrise (as published in the Air Almanac), made three takeoffs and three landings during that period as the sole manipulator of the flight controls in an aircraft of the same category and class and, if a type rating is required, of the same type in which that person is to serve.
              
.. Paragraph (a)(2) of this section does not apply to a pilot in command of a turbine-powered airplane that is type certificated for more than one pilot crewmember, provided that pilot has complied with the requirements of paragraph (a)(3)(i) or (ii) of this section:
[lowerroman]
... The pilot in command must hold at least a commercial pilot certificate with the appropriate category, class, and type rating for each airplane that is type certificated for more than one pilot crewmember that the pilot seeks to operate under this alternative, and:
[upperalpha]
.... That pilot must have logged at least 1,500 hours of aeronautical experience as a pilot;
.... In each airplane that is type certificated for more than one pilot crewmember that the pilot seeks to operate under this alternative, that pilot must have accomplished and logged the daytime takeoff and landing recent flight experience of paragraph (a) of this section, as the sole manipulator of the flight controls;
.... Within the preceding 90 days prior to the operation of that airplane that is type certificated for more than one pilot crewmember, the pilot must have accomplished and logged at least 15 hours of flight time in the type of airplane that the pilot seeks to operate under this alternative; and
.... That pilot has accomplished and logged at least 3 takeoffs and 3 landings to a full stop, as the sole manipulator of the flight controls, in a turbine-powered airplane that requires more than one pilot crewmember. The pilot must have performed the takeoffs and landings during the period beginning 1 hour after sunset and ending 1 hour before sunrise within the preceding 6 months prior to the month of the flight.
... The pilot in command must hold at least a commercial pilot certificate with the appropriate category, class, and type rating for each airplane that is type certificated for more than one pilot crewmember that the pilot seeks to operate under this alternative, and:
[upperalpha]
.... That pilot must have logged at least 1,500 hours of aeronautical experience as a pilot;
.... In each airplane that is type certificated for more than one pilot crewmember that the pilot seeks to operate under this alternative, that pilot must have accomplished and logged the daytime takeoff and landing recent flight experience of paragraph (a) of this section, as the sole manipulator of the flight controls;
.... Within the preceding 90 days prior to the operation of that airplane that is type certificated for more than one pilot crewmember, the pilot must have accomplished and logged at least 15 hours of flight time in the type of airplane that the pilot seeks to operate under this alternative; and
.... Within the preceding 12 months prior to the month of the flight, the pilot must have completed a training program that is approved under part 142 of this chapter. The approved training program must have required and the pilot must have performed, at least 6 takeoffs and 6 landings to a full stop as the sole manipulator of the controls in a flight simulator that is representative of a turbine-powered airplane that requires more than one pilot crewmember. The flight simulator's visual system must have been adjusted to represent the period beginning 1 hour after sunset and ending 1 hour before sunrise.
. For the purpose of paragraph (a) of this section, if the aircraft is a tailwheel airplane, each takeoff must be made in a tailwheel airplane and each landing must be made to a full stop in a tailwheel airplane.

## §§ 135.249-135.255 - Reserved


Reserved

