# Special Flight Rules in the Vicinity of Luke AFB, AZ
:toc:

## § 93.175

### Applicability.

This subpart prescribes a Special Air Traffic Rule for aircraft conducting VFR operations in the vicinity of Luke Air Force Base, AZ.

## § 93.176

### Description of area.

The Luke Air Force Base, Arizona Terminal Area is designated during official daylight hours Monday through Friday while Luke pilot flight training is underway, as broadcast on the local Automatic Terminal Information Service (ATIS), and other times by Notice to Airmen (NOTAM), as follows:

. East Sector:
.. South section includes airspace extending from 3,000 feet MSL to the base of the overlaying Phoenix Class B airspace bounded by a line beginning at: Lat. 33°23′56″ N; Long. 112°28′37″ W; to Lat. 33°22′32″ N; Long. 112°37′14″ W; to Lat. 33°25′39″ N; Long. 112°37′29″ W; to Lat. 33°31′55″ N; Long. 112°30′32″ W; to Lat. 33°28′00″ N; Long. 112°28′41″ W; to point of beginning.
.. South section lower includes airspace extending from 2,100 feet MSL to the base of the overlaying Phoenix Class B airspace, excluding the Luke Class D airspace area bounded by a line beginning at: Lat. 33°28′00″ N; Long. 112°28′41″ W; to Lat. 33°23′56″ N; Long. 112°28′37″ W; to Lat. 33°27′53″ N; Long. 112°24′12″ W; to point of beginning.
.. Center section includes airspace extending from surface to the base of the overlaying Phoenix Class B airspace, excluding the Luke Class D airspace area bounded by a line beginning at: Lat. 33°42′22″ N; Long. 112°19′16″ W; to Lat. 33°38′40″ N; Long. 112°14′03″ W; to Lat. 33°27′53″ N; Long. 112°24′12″ W; to Lat. 33°28′00″ N; Long. 112°28′41″ W; to Lat. 33°31′55″ N; Long. 112°30′32″ W; to point of beginning.
.. The north section includes that airspace extending upward from 3,000 feet MSL to 4,000 feet MSL, bounded by a line beginning at: Lat. 33°42′22″ N; Long. 112°19′16″ W; to Lat. 33°46′58″ N; Long. 112°16′41″ W; to Lat. 33°44′48″ N; Long. 112°10′59″ W; to Lat. 33°38′40″ N; Long. 112°14′03″ W; to point of beginning.
. West Sector:
.. The north section includes that airspace extending upward from 3,000 feet MSL to 6,000 feet MSL, bounded by a line beginning at: Lat. 33°51′52″ N; Long. 112°37′54″ W; to Lat. 33°49′34″ N; Long. 112°23′34″ W; to Lat. 33°46′58″ N; Long. 112°16′41″ W; to Lat. 33°42′22″ N; Long. 112°19′16″ W; to Lat. 33°39′27″ N; Long. 112°22′27″ W; to point of beginning.
.. The south section includes that airspace extending upward from the surface to 6,000 feet MSL, bounded by a line beginning at: Lat. 33°39′27″ N; Long. 112°22′27″ W; to Lat. 33°38′06″ N; Long. 112°23′51″ W; to Lat. 33°38′07″ N; Long. 112°28′50″ W; to Lat. 33°39′34″ N; Long. 112°31′39″ W; to Lat. 33°39′32″ N; Long. 112°37′36″ W; to Lat. 33°51′52″ N; Long. 112°37′54″ W; to point of beginning.

## § 93.177

### Operations in the Special Air Traffic Rule Area.

. Unless otherwise authorized by Air Traffic Control (ATC), no person may operate an aircraft in flight within the Luke Terminal Area designated in § 93.176 unless—
.. Before operating within the Luke Terminal area, that person establishes radio contact with the Luke RAPCON; and
.. That person maintains two-way radio communication with the Luke RAPCON or an appropriate ATC facility while within the designated area.
. Requests for deviation from the provisions of this section apply only to aircraft not equipped with an operational radio. The request must be submitted at least 24 hours before the proposed operation to Luke RAPCON.

