# Air Traffic Controllers
:toc:

## § 120.17 - Use of prohibited drugs.

[loweralpha]
. Each employer shall provide each employee performing a function listed in subpart E of this part, and his or her supervisor, with the training specified in that subpart. No employer may use any contractor to perform an air traffic control function unless that contractor provides each of its employees performing that function for the employer, and his or her supervisor, with the training specified in subpart E of this part.
. No employer may knowingly use any individual to perform, nor may any individual perform for an employer, either directly or by contract, any air traffic control function while that individual has a prohibited drug, as defined in this part, in his or her system.
. No employer shall knowingly use any individual to perform, nor may any individual perform for an employer, either directly or by contract, any air traffic control function if the individual has a verified positive drug test result on, or has refused to submit to, a drug test required by subpart E of this part and the individual has not met the requirements of subpart E of this part for returning to the performance of safety-sensitive duties.
. Each employer shall test each of its employees who perform any air traffic control function in accordance with subpart E of this part. No employer may use any contractor to perform any air traffic control function unless that contractor tests each employee performing such a function for the employer in accordance with subpart E of this part.

## § 120.19 - Misuse of alcohol.

[loweralpha]
. This section applies to covered employees who perform air traffic control duties directly or by contract for an employer that is an air traffic control facility not operated by the FAA or the US military.
. *Alcohol concentration.* No covered employee shall report for duty or remain on duty requiring the performance of safety-sensitive functions while having an alcohol concentration of 0.04 or greater. No employer having actual knowledge that an employee has an alcohol concentration of 0.04 or greater shall permit the employee to perform or continue to perform safety-sensitive functions.
. *On-duty use.* No covered employee shall use alcohol while performing safety-sensitive functions. No employer having actual knowledge that a covered employee is using alcohol while performing safety-sensitive functions shall permit the employee to perform or continue to perform safety-sensitive functions.
. *Pre-duty use.* No covered employee shall perform air traffic control duties within 8 hours after using alcohol. No employer having actual knowledge that such an employee has used alcohol within 8 hours shall permit the employee to perform or continue to perform air traffic control duties.
. *Use following an accident.* No covered employee who has actual knowledge of an accident involving an aircraft for which he or she performed a safety-sensitive function at or near the time of the accident shall use alcohol for 8 hours following the accident, unless he or she has been given a post-accident test under subpart F of this part or the employer has determined that the employee's performance could not have contributed to the accident.
. *Refusal to submit to a required alcohol test.* A covered employee may not refuse to submit to any alcohol test required under subpart F of this part. An employer may not permit an employee who refuses to submit to such a test to perform or continue to perform safety-sensitive functions.

## § 120.21 - Testing for alcohol.

[loweralpha]
. Each air traffic control facility not operated by the FAA or the U.S. military must establish an alcohol testing program in accordance with the provisions of subpart F of this part.
. No employer shall use any individual who meets the definition of covered employee in subpart A of this part to perform a safety-sensitive function listed in subpart F of this part unless that individual is subject to testing for alcohol misuse in accordance with the provisions of that subpart.

