# Large and Turbine-Powered Multiengine Airplanes and Fractional Ownership Program Aircraft
:toc:

## § 91.501

### Applicability.

. This subpart prescribes operating rules, in addition to those prescribed in other subparts of this part, governing the operation of large airplanes of U.S. registry, turbojet-powered multiengine civil airplanes of U.S. registry, and fractional ownership program aircraft of U.S. registry that are operating under subpart K of this part in operations not involving common carriage. The operating rules in this subpart do not apply to those aircraft when they are required to be operated under parts 121, 125, 129, 135, and 137 of this chapter. (Section 91.409 prescribes an inspection program for large and for turbine-powered (turbojet and turboprop) multiengine airplanes and turbine-powered rotorcraft of U.S. registry when they are operated under this part or part 129 or 137.)
. Operations that may be conducted under the rules in this subpart instead of those in parts 121, 129, 135, and 137 of this chapter when common carriage is not involved, include—
.. Ferry or training flights;
.. Aerial work operations such as aerial photography or survey, or pipeline patrol, but not including fire fighting operations;
.. Flights for the demonstration of an airplane to prospective customers when no charge is made except for those specified in paragraph (d) of this section;
.. Flights conducted by the operator of an airplane for his personal transportation, or the transportation of his guests when no charge, assessment, or fee is made for the transportation;
.. Carriage of officials, employees, guests, and property of a company on an airplane operated by that company, or the parent or a subsidiary of the company or a subsidiary of the parent, when the carriage is within the scope of, and incidental to, the business of the company (other than transportation by air) and no charge, assessment or fee is made for the carriage in excess of the cost of owning, operating, and maintaining the airplane, except that no charge of any kind may be made for the carriage of a guest of a company, when the carriage is not within the scope of, and incidental to, the business of that company;
.. The carriage of company officials, employees, and guests of the company on an airplane operated under a time sharing, interchange, or joint ownership agreement as defined in paragraph (c) of this section;
.. The carriage of property (other than mail) on an airplane operated by a person in the furtherance of a business or employment (other than transportation by air) when the carriage is within the scope of, and incidental to, that business or employment and no charge, assessment, or fee is made for the carriage other than those specified in paragraph (d) of this section;
.. The carriage on an airplane of an athletic team, sports group, choral group, or similar group having a common purpose or objective when there is no charge, assessment, or fee of any kind made by any person for that carriage; and
.. The carriage of persons on an airplane operated by a person in the furtherance of a business other than transportation by air for the purpose of selling them land, goods, or property, including franchises or distributorships, when the carriage is within the scope of, and incidental to, that business and no charge, assessment, or fee is made for that carriage.
.. Any operation identified in paragraphs (b)(1) through (b)(9) of this section when conducted—
... By a fractional ownership program manager, or
... By a fractional owner in a fractional ownership program aircraft operated under subpart K of this part, except that a flight under a joint ownership arrangement under paragraph (b)(6) of this section may not be conducted. For a flight under an interchange agreement under paragraph (b)(6) of this section, the exchange of equal time for the operation must be properly accounted for as part of the total hours associated with the fractional owner's share of ownership.
. As used in this section—
.. A *time sharing agreement* means an arrangement whereby a person leases his airplane with flight crew to another person, and no charge is made for the flights conducted under that arrangement other than those specified in paragraph (d) of this section;
.. An *interchange agreement* means an arrangement whereby a person leases his airplane to another person in exchange for equal time, when needed, on the other person's airplane, and no charge, assessment, or fee is made, except that a charge may be made not to exceed the difference between the cost of owning, operating, and maintaining the two airplanes;
.. A *joint ownership agreement* means an arrangement whereby one of the registered joint owners of an airplane employs and furnishes the flight crew for that airplane and each of the registered joint owners pays a share of the charge specified in the agreement.
. The following may be charged, as expenses of a specific flight, for transportation as authorized by paragraphs (b) (3) and (7) and (c)(1) of this section:
.. Fuel, oil, lubricants, and other additives.
.. Travel expenses of the crew, including food, lodging, and ground transportation.
.. Hangar and tie-down costs away from the aircraft's base of operation.
.. Insurance obtained for the specific flight.
.. Landing fees, airport taxes, and similar assessments.
.. Customs, foreign permit, and similar fees directly related to the flight.
.. In flight food and beverages.
.. Passenger ground transportation.
.. Flight planning and weather contract services.
.. An additional charge equal to 100 percent of the expenses listed in paragraph (d)(1) of this section.

## § 91.503

### Flying equipment and operating information.

. The pilot in command of an airplane shall ensure that the following flying equipment and aeronautical charts and data, in current and appropriate form, are accessible for each flight at the pilot station of the airplane:
.. A flashlight having at least two size “D” cells, or the equivalent, that is in good working order.
.. A cockpit checklist containing the procedures required by paragraph (b) of this section.
.. Pertinent aeronautical charts.
.. For IFR, VFR over-the-top, or night operations, each pertinent navigational en route, terminal area, and approach and letdown chart.
.. In the case of multiengine airplanes, one-engine inoperative climb performance data.
. Each cockpit checklist must contain the following procedures and shall be used by the flight crewmembers when operating the airplane:
.. Before starting engines.
.. Before takeoff.
.. Cruise.
.. Before landing.
.. After landing.
.. Stopping engines.
.. Emergencies.
. Each emergency cockpit checklist procedure required by paragraph (b)(7) of this section must contain the following procedures, as appropriate:
.. Emergency operation of fuel, hydraulic, electrical, and mechanical systems.
.. Emergency operation of instruments and controls.
.. Engine inoperative procedures.
.. Any other procedures necessary for safety.
. The equipment, charts, and data prescribed in this section shall be used by the pilot in command and other members of the flight crew, when pertinent.

## § 91.505

### Familiarity with operating limitations and emergency equipment.

. Each pilot in command of an airplane shall, before beginning a flight, become familiar with the Airplane Flight Manual for that airplane, if one is required, and with any placards, listings, instrument markings, or any combination thereof, containing each operating limitation prescribed for that airplane by the Administrator, including those specified in § 91.9(b).
. Each required member of the crew shall, before beginning a flight, become familiar with the emergency equipment installed on the airplane to which that crewmember is assigned and with the procedures to be followed for the use of that equipment in an emergency situation.

## § 91.507

### Equipment requirements: Over-the-top or night VFR operations.

No person may operate an airplane over-the-top or at night under VFR unless that airplane is equipped with the instruments and equipment required for IFR operations under § 91.205(d) and one electric landing light for night operations. Each required instrument and item of equipment must be in operable condition.

## § 91.509

### Survival equipment for overwater operations.

. No person may take off an airplane for a flight over water more than 50 nautical miles from the nearest shore unless that airplane is equipped with a life preserver or an approved flotation means for each occupant of the airplane.
. Except as provided in paragraph (c) of this section, no person may take off an airplane for flight over water more than 30 minutes flying time or 100 nautical miles from the nearest shore, whichever is less, unless it has on board the following survival equipment:
.. A life preserver, equipped with an approved survivor locator light, for each occupant of the airplane.
.. Enough liferafts (each equipped with an approved survival locator light) of a rated capacity and buoyancy to accommodate the occupants of the airplane.
.. At least one pyrotechnic signaling device for each liferaft.
.. One self-buoyant, water-resistant, portable emergency radio signaling device that is capable of transmission on the appropriate emergency frequency or frequencies and not dependent upon the airplane power supply.
.. A lifeline stored in accordance with § 25.1411(g) of this chapter.
. A fractional ownership program manager under subpart K of this part may apply for a deviation from paragraphs (b)(2) through (5) of this section for a particular over water operation or the Administrator may amend the management specifications to require the carriage of all or any specific items of the equipment listed in paragraphs (b)(2) through (5) of this section.
. The required life rafts, life preservers, and signaling devices must be installed in conspicuously marked locations and easily accessible in the event of a ditching without appreciable time for preparatory procedures.
. A survival kit, appropriately equipped for the route to be flown, must be attached to each required life raft.
. As used in this section, the term shore means that area of the land adjacent to the water that is above the high water mark and excludes land areas that are intermittently under water.

## § 91.511

### Communication and navigation equipment for overwater operations.

. Except as provided in paragraphs (c), (d), and (f) of this section, no person may take off an airplane for a flight over water more than 30 minutes flying time or 100 nautical miles from the nearest shore unless it has at least the following operable equipment:
.. Radio communication equipment appropriate to the facilities to be used and able to transmit to, and receive from, at least one communication facility from any place along the route:
... Two transmitters.
... Two microphones.
... Two headsets or one headset and one speaker.
... Two independent receivers.
.. Appropriate electronic navigational equipment consisting of at least two independent electronic navigation units capable of providing the pilot with the information necessary to navigate the airplane within the airspace assigned by air traffic control. However, a receiver that can receive both communications and required navigational signals may be used in place of a separate communications receiver and a separate navigational signal receiver or unit.
. For the purposes of paragraphs (a)(1)(iv) and (a)(2) of this section, a receiver or electronic navigation unit is independent if the function of any part of it does not depend on the functioning of any part of another receiver or electronic navigation unit.
. Notwithstanding the provisions of paragraph (a) of this section, a person may operate an airplane on which no passengers are carried from a place where repairs or replacement cannot be made to a place where they can be made, if not more than one of each of the dual items of radio communication and navigational equipment specified in paragraphs (a)(1) (i) through (iv) and (a)(2) of this section malfunctions or becomes inoperative.
. Notwithstanding the provisions of paragraph (a) of this section, when both VHF and HF communications equipment are required for the route and the airplane has two VHF transmitters and two VHF receivers for communications, only one HF transmitter and one HF receiver is required for communications.
. As used in this section, the term *shore* means that area of the land adjacent to the water which is above the high-water mark and excludes land areas which are intermittently under water.
. Notwithstanding the requirements in paragraph (a)(2) of this section, a person may operate in the Gulf of Mexico, the Caribbean Sea, and the Atlantic Ocean west of a line which extends from 44°47′00″ N / 67°00′00″ W to 39°00′00″ N / 67°00′00″ W to 38°30′00″ N / 60°00′00″ W south along the 60°00′00″ W longitude line to the point where the line intersects with the northern coast of South America, when:
.. A single long-range navigation system is installed, operational, and appropriate for the route; and
.. Flight conditions and the aircraft's capabilities are such that no more than a 30-minute gap in two-way radio very high frequency communications is expected to exist.

## § 91.513

### Emergency equipment.

. No person may operate an airplane unless it is equipped with the emergency equipment listed in this section.
. Each item of equipment—
.. Must be inspected in accordance with § 91.409 to ensure its continued serviceability and immediate readiness for its intended purposes;
.. Must be readily accessible to the crew;
.. Must clearly indicate its method of operation; and
.. When carried in a compartment or container, must have that compartment or container marked as to contents and date of last inspection.
. Hand fire extinguishers must be provided for use in crew, passenger, and cargo compartments in accordance with the following:
.. The type and quantity of extinguishing agent must be suitable for the kinds of fires likely to occur in the compartment where the extinguisher is intended to be used.
.. At least one hand fire extinguisher must be provided and located on or near the flight deck in a place that is readily accessible to the flight crew.
.. At least one hand fire extinguisher must be conveniently located in the passenger compartment of each airplane accommodating more than six but less than 31 passengers, and at least two hand fire extinguishers must be conveniently located in the passenger compartment of each airplane accommodating more than 30 passengers.
.. Hand fire extinguishers must be installed and secured in such a manner that they will not interfere with the safe operation of the airplane or adversely affect the safety of the crew and passengers. They must be readily accessible and, unless the locations of the fire extinguishers are obvious, their stowage provisions must be properly identified.
              
. First aid kits for treatment of injuries likely to occur in flight or in minor accidents must be provided.
. Each airplane accommodating more than 19 passengers must be equipped with a crash axe.
. Each passenger-carrying airplane must have a portable battery-powered megaphone or megaphones readily accessible to the crewmembers assigned to direct emergency evacuation, installed as follows:
.. One megaphone on each airplane with a seating capacity of more than 60 but less than 100 passengers, at the most rearward location in the passenger cabin where it would be readily accessible to a normal flight attendant seat. However, the Administrator may grant a deviation from the requirements of this subparagraph if the Administrator finds that a different location would be more useful for evacuation of persons during an emergency.
.. On each airplane with a seating capacity of 100 or more passengers, one megaphone installed at the forward end and one installed at the most rearward location where it would be readily accessible to a normal flight attendant seat.

## § 91.515

### Flight altitude rules.

. Notwithstanding § 91.119, and except as provided in paragraph (b) of this section, no person may operate an airplane under VFR at less than—
.. One thousand feet above the surface, or 1,000 feet from any mountain, hill, or other obstruction to flight, for day operations; and
.. The altitudes prescribed in § 91.177, for night operations.
. This section does not apply—
.. During takeoff or landing;
.. When a different altitude is authorized by a waiver to this section under subpart J of this part; or
.. When a flight is conducted under the special VFR weather minimums of § 91.157 with an appropriate clearance from ATC.

## § 91.517

### Passenger information.

. Except as provided in paragraph (b) of this section, no person may operate an airplane carrying passengers unless it is equipped with signs that are visible to passengers and flight attendants to notify them when smoking is prohibited and when safety belts must be fastened. The signs must be so constructed that the crew can turn them on and off. They must be turned on during airplane movement on the surface, for each takeoff, for each landing, and when otherwise considered to be necessary by the pilot in command.
. The pilot in command of an airplane that is not required, in accordance with applicable aircraft and equipment requirements of this chapter, to be equipped as provided in paragraph (a) of this section shall ensure that the passengers are notified orally each time that it is necessary to fasten their safety belts and when smoking is prohibited.
. If passenger information signs are installed, no passenger or crewmember may smoke while any “no smoking” sign is lighted nor may any passenger or crewmember smoke in any lavatory.
. Each passenger required by § 91.107(a)(3) to occupy a seat or berth shall fasten his or her safety belt about him or her and keep it fastened while any “fasten seat belt” sign is lighted.
. Each passenger shall comply with instructions given him or her by crewmembers regarding compliance with paragraphs (b), (c), and (d) of this section.

## § 91.519

### Passenger briefing.

. Before each takeoff the pilot in command of an airplane carrying passengers shall ensure that all passengers have been orally briefed on—
.. *Smoking.* Each passenger shall be briefed on when, where, and under what conditions smoking is prohibited. This briefing shall include a statement, as appropriate, that the Federal Aviation Regulations require passenger compliance with lighted passenger information signs and no smoking placards, prohibit smoking in lavatories, and require compliance with crewmember instructions with regard to these items;
.. *Use of safety belts and shoulder harnesses.* Each passenger shall be briefed on when, where, and under what conditions it is necessary to have his or her safety belt and, if installed, his or her shoulder harness fastened about him or her. This briefing shall include a statement, as appropriate, that Federal Aviation Regulations require passenger compliance with the lighted passenger sign and/or crewmember instructions with regard to these items;
.. Location and means for opening the passenger entry door and emergency exits;
.. Location of survival equipment;
.. Ditching procedures and the use of flotation equipment required under § 91.509 for a flight over water; and
.. The normal and emergency use of oxygen equipment installed on the airplane.
. The oral briefing required by paragraph (a) of this section shall be given by the pilot in command or a member of the crew, but need not be given when the pilot in command determines that the passengers are familiar with the contents of the briefing. It may be supplemented by printed cards for the use of each passenger containing—
.. A diagram of, and methods of operating, the emergency exits; and
.. Other instructions necessary for use of emergency equipment.
. Each card used under paragraph (b) must be carried in convenient locations on the airplane for the use of each passenger and must contain information that is pertinent only to the type and model airplane on which it is used.
. For operations under subpart K of this part, the passenger briefing requirements of § 91.1035 apply, instead of the requirements of paragraphs (a) through (c) of this section.

## § 91.521

### Shoulder harness.

. No person may operate a transport category airplane that was type certificated after January 1, 1958, unless it is equipped at each seat at a flight deck station with a combined safety belt and shoulder harness that meets the applicable requirements specified in § 25.785 of this chapter, except that—
.. Shoulder harnesses and combined safety belt and shoulder harnesses that were approved and installed before March 6, 1980, may continue to be used; and
.. Safety belt and shoulder harness restraint systems may be designed to the inertia load factors established under the certification basis of the airplane.
. No person may operate a transport category airplane unless it is equipped at each required flight attendant seat in the passenger compartment with a combined safety belt and shoulder harness that meets the applicable requirements specified in § 25.785 of this chapter, except that—
.. Shoulder harnesses and combined safety belt and shoulder harnesses that were approved and installed before March 6, 1980, may continue to be used; and
.. Safety belt and shoulder harness restraint systems may be designed to the inertia load factors established under the certification basis of the airplane.

## § 91.523

### Carry-on baggage.

No pilot in command of an airplane having a seating capacity of more than 19 passengers may permit a passenger to stow baggage aboard that airplane except—

. In a suitable baggage or cargo storage compartment, or as provided in § 91.525; or
. Under a passenger seat in such a way that it will not slide forward under crash impacts severe enough to induce the ultimate inertia forces specified in § 25.561(b)(3) of this chapter, or the requirements of the regulations under which the airplane was type certificated. Restraining devices must also limit sideward motion of under-seat baggage and be designed to withstand crash impacts severe enough to induce sideward forces specified in § 25.561(b)(3) of this chapter.

## § 91.525

### Carriage of cargo.

. No pilot in command may permit cargo to be carried in any airplane unless—
.. It is carried in an approved cargo rack, bin, or compartment installed in the airplane;
.. It is secured by means approved by the Administrator; or
              
.. It is carried in accordance with each of the following:
... It is properly secured by a safety belt or other tiedown having enough strength to eliminate the possibility of shifting under all normally anticipated flight and ground conditions.
... It is packaged or covered to avoid possible injury to passengers.
... It does not impose any load on seats or on the floor structure that exceeds the load limitation for those components.
... It is not located in a position that restricts the access to or use of any required emergency or regular exit, or the use of the aisle between the crew and the passenger compartment.
... It is not carried directly above seated passengers.
. When cargo is carried in cargo compartments that are designed to require the physical entry of a crewmember to extinguish any fire that may occur during flight, the cargo must be loaded so as to allow a crewmember to effectively reach all parts of the compartment with the contents of a hand fire extinguisher.

## § 91.527

### Operating in icing conditions.

. No pilot may take off an airplane that has frost, ice, or snow adhering to any propeller, windshield, stabilizing or control surface; to a powerplant installation; or to an airspeed, altimeter, rate of climb, or flight attitude instrument system or wing, except that takeoffs may be made with frost under the wing in the area of the fuel tanks if authorized by the FAA.
. No pilot may fly under IFR into known or forecast light or moderate icing conditions, or under VFR into known light or moderate icing conditions, unless—
.. The aircraft has functioning deicing or anti-icing equipment protecting each rotor blade, propeller, windshield, wing, stabilizing or control surface, and each airspeed, altimeter, rate of climb, or flight attitude instrument system;
.. The airplane has ice protection provisions that meet section 34 of Special Federal Aviation Regulation No. 23; or
.. The airplane meets transport category airplane type certification provisions, including the requirements for certification for flight in icing conditions.
. Except for an airplane that has ice protection provisions that meet the requirements in section 34 of Special Federal Aviation Regulation No. 23, or those for transport category airplane type certification, no pilot may fly an airplane into known or forecast severe icing conditions.
. If current weather reports and briefing information relied upon by the pilot in command indicate that the forecast icing conditions that would otherwise prohibit the flight will not be encountered during the flight because of changed weather conditions since the forecast, the restrictions in paragraphs (b) and (c) of this section based on forecast conditions do not apply.

## § 91.529

### Flight engineer requirements.

. No person may operate the following airplanes without a flight crewmember holding a current flight engineer certificate:
.. An airplane for which a type certificate was issued before January 2, 1964, having a maximum certificated takeoff weight of more than 80,000 pounds.
.. An airplane type certificated after January 1, 1964, for which a flight engineer is required by the type certification requirements.
. No person may serve as a required flight engineer on an airplane unless, within the preceding 6 calendar months, that person has had at least 50 hours of flight time as a flight engineer on that type airplane or has been checked by the Administrator on that type airplane and is found to be familiar and competent with all essential current information and operating procedures.

## § 91.531

### Second in command requirements.

. Except as provided in paragraph (b) and (d) of this section, no person may operate the following airplanes without a pilot who is designated as second in command of that airplane:
              
.. A large airplane, except that a person may operate an airplane certificated under SFAR 41 without a pilot who is designated as second in command if that airplane is certificated for operation with one pilot.
.. A turbojet-powered multiengine airplane for which two pilots are required under the type certification requirements for that airplane.
.. A commuter category airplane, except that a person may operate a commuter category airplane notwithstanding paragraph (a)(1) of this section, that has a passenger seating configuration, excluding pilot seats, of nine or less without a pilot who is designated as second in command if that airplane is type certificated for operations with one pilot.
. The Administrator may issue a letter of authorization for the operation of an airplane without compliance with the requirements of paragraph (a) of this section if that airplane is designed for and type certificated with only one pilot station. The authorization contains any conditions that the Administrator finds necessary for safe operation.
. No person may designate a pilot to serve as second in command, nor may any pilot serve as second in command, of an airplane required under this section to have two pilots unless that pilot meets the qualifications for second in command prescribed in § 61.55 of this chapter.
. No person may operate an aircraft under subpart K of this part without a pilot who is designated as second in command of that aircraft in accordance with § 91.1049(d). The second in command must meet the experience requirements of § 91.1053.

## § 91.533

### Flight attendant requirements.

. No person may operate an airplane unless at least the following number of flight attendants are on board the airplane:
.. For airplanes having more than 19 but less than 51 passengers on board, one flight attendant.
.. For airplanes having more than 50 but less than 101 passengers on board, two flight attendants.
.. For airplanes having more than 100 passengers on board, two flight attendants plus one additional flight attendant for each unit (or part of a unit) of 50 passengers above 100.
. No person may serve as a flight attendant on an airplane when required by paragraph (a) of this section unless that person has demonstrated to the pilot in command familiarity with the necessary functions to be performed in an emergency or a situation requiring emergency evacuation and is capable of using the emergency equipment installed on that airplane.

## § 91.535

### Stowage of food, beverage, and passenger service equipment during aircraft movement on the surface, takeoff, and landing.

. No operator may move an aircraft on the surface, take off, or land when any food, beverage, or tableware furnished by the operator is located at any passenger seat.
. No operator may move an aircraft on the surface, take off, or land unless each food and beverage tray and seat back tray table is secured in its stowed position.
              
. No operator may permit an aircraft to move on the surface, take off, or land unless each passenger serving cart is secured in its stowed position.
. No operator may permit an aircraft to move on the surface, take off, or land unless each movie screen that extends into the aisle is stowed.
. Each passenger shall comply with instructions given by a crewmember with regard to compliance with this section.

## §§ 91.536-91.599

### Reserved

