# Recordkeeping
:toc:

## § 142.71

### Applicability.

This subpart prescribes the training center recordkeeping requirements for trainees enrolled in a course, and instructors and evaluators designated to instruct a course, approved in accordance with subpart B of this part.

## § 142.73

### Recordkeeping requirements.

. A certificate holder must maintain a record for each trainee that contains—
.. The name of the trainee;
.. A copy of the trainee's pilot certificate, if any, and medical certificate;
.. The name of the course and the make and model of flight training equipment used;
.. The trainee's prerequisite experience and course time completed;
.. The trainee's performance on each lesson and the name of the instructor providing instruction;
.. The date and result of each end-of-course practical test and the name of the evaluator conducting the test; and
.. The number of hours of additional training that was accomplished after any unsatisfactory practical test.
. A certificate holder shall maintain a record for each instructor or evaluator designated to instruct a course approved in accordance with subpart B of this part that indicates that the instructor or evaluator has complied with the requirements of §§ 142.13, 142.45, 142.47, 142.49, and 142.53, as applicable.
. The certificate holder shall—
.. Maintain the records required by paragraphs (a) of this section for at least 1 year following the completion of training, testing or checking;
.. Maintain the qualification records required by paragraph (b) of this section while the instructor or evaluator is in the employ of the certificate holder and for 1 year thereafter; and
.. Maintain the recurrent demonstration of proficiency records required by paragraph (b) of this section for at least 1 year.
. The certificate holder must provide the records required by this section to the Administrator, upon request and at a reasonable time, and shall keep the records required by—
              
.. Paragraph (a) of this section at the training center, or satellite training center where the training, testing, or checking, if appropriate, occurred; and
.. Paragraph (b) of this section at the training center or satellite training center where the instructor or evaluator is primarily employed.
. The certificate holder shall provide to a trainee, upon request and at a reasonable time, a copy of his or her training records.

