# General
:toc:

## § 147.1 - Applicability.

This part prescribes the requirements for issuing aviation maintenance technician school certificates and associated ratings and the general operating rules for the holders of those certificates and ratings.

## § 147.3 - Certificate required.

No person may operate as a certificated aviation maintenance technician school without, or in violation of, an aviation maintenance technician school certificate issued under this part.

## § 147.5 - Application and issue.

[loweralpha]
. An application for a certificate and rating, or for an additional rating, under this part is made on a form and in a manner prescribed by the Administrator, and submitted with—
[arabic]
.. A description of the proposed curriculum;
.. A list of the facilities and materials to be used;
.. A list of its instructors, including the kind of certificate and ratings held and the certificate numbers; and
              
.. A statement of the maximum number of students it expects to teach at any one time.
. An applicant who meets the requirements of this part is entitled to an aviation maintenance technician school certificate and associated ratings prescribing such operations specifications and limitations as are necessary in the interests of safety.

## § 147.7 - Duration of certificates.

[loweralpha]
. An aviation maintenance technician school certificate or rating is effective until it is surrendered, suspended, or revoked.
. The holder of a certificate that is surrendered, suspended, or revoked, shall return it to the Administrator.

## § 147.8 - Employment of former FAA employees.

[loweralpha]
. Except as specified in paragraph (c) of this section, no holder of an aviation maintenance technician certificate may knowingly employ or make a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual, in the preceding 2 years—
[arabic]
.. Served as, or was directly responsible for the oversight of, a Flight Standards Service aviation safety inspector; and
.. Had direct responsibility to inspect, or oversee the inspection of, the operations of the certificate holder.
. For the purpose of this section, an individual shall be considered to be acting as an agent or representative of a certificate holder in a matter before the agency if the individual makes any written or oral communication on behalf of the certificate holder to the agency (or any of its officers or employees) in connection with a particular matter, whether or not involving a specific party and without regard to whether the individual has participated in, or had responsibility for, the particular matter while serving as a Flight Standards Service aviation safety inspector.
. The provisions of this section do not prohibit a holder of an aviation maintenance technician school certificate from knowingly employing or making a contractual arrangement which permits an individual to act as an agent or representative of the certificate holder in any matter before the Federal Aviation Administration if the individual was employed by the certificate holder before October 21, 2011.

