# Failure To Comply With This Part
:toc:

## § 161.501 - Scope.

[loweralpha]
. This subpart describes the procedures to terminate eligibility for airport grant funds and authority to impose or collect passenger facility charges for an airport operator's failure to comply with the Airport Noise and Capacity Act of 1990 (49 U.S.C. App. 2151 *et seq.*) or this part. These procedures may be used with or in addition to any judicial proceedings initiated by the FAA to protect the national aviation system and related Federal interests.
. Under no conditions shall any airport operator receive revenues under the provisions of the Airport and Airway Improvement Act of 1982 or impose or collect a passenger facility charge under section 1113(e) of the Federal Aviation Act of 1958 if the FAA determines that the airport is imposing any noise or access restriction not in compliance with the Airport Noise and Capacity Act of 1990 or this part. Recision of, or a commitment in writing signed by an authorized official of the airport operator to rescind or permanently not enforce, a noncomplying restriction will be treated by the FAA as action restoring compliance with the Airport Noise and Capacity Act of 1990 or this part with respect to that restriction.

## § 161.503 - Informal resolution; notice of apparent violation.

Prior to the initiation of formal action to terminate eligibility for airport grant funds or authority to impose or collect passenger facility charges under this subpart, the FAA shall undertake informal resolution with the airport operator to assure compliance with the Airport Noise and Capacity Act of 1990 or this part upon receipt of a complaint or other evidence that an airport operator has taken action to impose a noise or access restriction that appears to be in violation. This shall not preclude a FAA application for expedited judicial action for other than termination of airport grants and passenger facility charges to protect the national aviation system and violated federal interests. If informal resolution is not successful, the FAA will notify the airport operator in writing of the apparent violation. The airport operator shall respond to the notice in writing not later than 20 days after receipt of the notice, and also state whether the airport operator will agree to defer implementation or enforcement of its noise or access restriction until completion of the process under this subpart to determine compliance.

## § 161.505 - Notice of proposed termination of airport grant funds and passenger facility charges.

[loweralpha]
. The FAA begins proceedings under this section to terminate an airport operator's eligibility for airport grant funds and authority to impose or collect passenger facility charges only if the FAA determines that informal resolution is not successful.
. The following procedures shall apply if an airport operator agrees in writing, within 20 days of receipt of the FAA's notice of apparent violation under § 161.503, to defer implementation or enforcement of a noise or access restriction until completion of the process under this subpart to determine compliance.
[arabic]
.. The FAA will issue a notice of proposed termination to the airport operator and publish notice of the proposed action in the *Federal Register.* This notice will state the scope of the proposed termination, the basis for the proposed action, and the date for filing written comments or objections by all interested parties. This notice will also identify any corrective action the airport operator can take to avoid further proceedings. The due date for comments and corrective action by the airport operator shall be specified in the notice of proposed termination and shall not be less than 60 days after publication of the notice.
.. The FAA will review the comments, statements, and data supplied by the airport operator, and any other available information, to determine if the airport operator has provided satisfactory evidence of compliance or has taken satisfactory corrective action. The FAA will consult with the airport operator to attempt resolution and may request additional information from other parties to determine compliance. The review and consultation process shall take not less than 30 days. If the FAA finds satisfactory evidence of compliance, the FAA will notify the airport operator in writing and publish notice of compliance in the *Federal Register.*
              
.. If the FAA determines that the airport operator has taken action to impose a noise or access restriction in violation of the Airport Noise and Capacity Act of 1990 or this part, the FAA will notify the airport operator in writing of such determination. Where appropriate, the FAA may prescribe corrective action, including corrective action the airport operator may still need to take. Within 10 days of receipt of the FAA's determination, the airport operator shall—
[lowerroman]
... Advise the FAA in writing that it will complete any corrective action prescribed by the FAA within 30 days; or
... Provide the FAA with a list of the domestic air carriers and foreign air carriers operating at the airport and all other issuing carriers, as defined in § 158.3 of this chapter, that have remitted passenger facility charge revenue to the airport in the preceding 12 months.
.. If the FAA finds that the airport operator has taken satisfactory corrective action, the FAA will notify the airport operator in writing and publish notice of compliance in the *Federal Register.* If the FAA has determined that the airport operator has imposed a noise or access restriction in violation of the Airport Noise and Capacity Act of 1990 or this part and satisfactory corrective action has not been taken, the FAA will issue an order that—
[lowerroman]
... Terminates eligibility for new airport grant agreements and discontinues payments of airport grant funds, including payments of costs incurred prior to the notice; and
... Terminates authority to impose or collect a passenger facility charge or, if the airport operator has not received approval to impose a passenger facility charge, advises the airport operator that future applications for such approval will be denied in accordance with § 158.29(a)(1)(v) of this chapter.
.. The FAA will publish notice of the order in the *Federal Register* and notify air carriers of the FAA's order and actions to be taken to terminate or modify collection of passenger facility charges in accordance with § 158.85(f) of this chapter.
. The following procedures shall apply if an airport operator does not agree in writing, within 20 days of receipt of the FAA's notice of apparent violation under § 161.503, to defer implementation or enforcement of its noise or access restriction until completion of the process under this subpart to determine compliance.
[arabic]
.. The FAA will issue a notice of proposed termination to the airport operator and publish notice of the proposed action in the *Federal Register.* This notice will state the scope of the proposed termination, the basis for the proposed action, and the date for filing written comments or objections by all interested parties. This notice will also identify any corrective action the airport operator can take to avoid further proceedings. The due date for comments and corrective action by the airport operator shall be specified in the notice of proposed termination and shall not be less than 30 days after publication of the notice.
.. The FAA will review the comments, statements, and data supplied by the airport operator, and any other available information, to determine if the airport operator has provided satisfactory evidence of compliance or has taken satisfactory corrective action. If the FAA finds satisfactory evidence of compliance, the FAA will notify the airport operator in writing and publish notice of compliance in the *Federal Register.*
              
.. If the FAA determines that the airport operator has taken action to impose a noise or access restriction in violation of the Airport Noise and Capacity Act of 1990 or this part, the procedures in paragraphs (b)(3) through (b)(5) of this section will be followed.

