# Termination
:toc:

## § 158.81

### General.

This subpart contains the procedures for termination of PFCs or loss of Federal airport grant funds for violations of this part or 49 U.S.C. 40117. This subpart does not address the circumstances under which the authority to collect PFCs may be terminated for violations of 49 U.S.C. 47523 through 47528.

## § 158.83

### Informal resolution.

The Administrator shall undertake informal resolution with the public agency or any other affected party if, after review under § 158.71, the Administrator cannot determine that PFC revenue is being used for the approved projects in accordance with the terms of the Administrator's approval to impose a PFC for those projects or with 49 U.S.C. 40117.

## § 158.85

### Termination of authority to impose PFC's.

. The FAA begins proceedings to terminate the public agency's authority to impose a PFC only if the Administrator determines that informal resolution is not successful.
. The Administrator publishes a notice of proposed termination in the *Federal Register* and supplies a copy to the public agency. This notice will state the scope of the proposed termination, the basis for the proposed action and the date for filing written comments or objections by all interested parties. This notice will also identify any corrective actions the public agency can take to avoid further proceedings. The due date for comments and corrective action shall be no less than 60 days after publication of the notice.
. If corrective action has not been taken as prescribed by the Administrator, the FAA holds a public hearing, and notice is given to the public agency and published in the *Federal Register* at least 30 days prior to the hearing. The hearing will be in a form determined by the Administrator to be appropriate to the circumstances and to the matters in dispute.
. The Administrator publishes the final decision in the *Federal Register.* Where appropriate, the Administrator may prescribe corrective action, including any corrective action the public agency may yet take. A copy of the notice is also provided to the public agency.
. Within 10 days of the date of publication of the notice of the Administrator's decision, the public agency shall—
.. Advise the FAA in writing that it will complete any corrective action prescribed in the decision within 30 days; or
.. Provide the FAA with a listing of the air carriers and foreign air carriers operating at the airport and all other issuing carriers that have remitted PFC revenue to the public agency in the preceding 12 months.
. When the Administrator's decision does not provide for corrective action or the public agency fails to complete such action, the FAA provides a copy of the *Federal Register* notice to each air carrier and foreign air carrier identified in paragraph (e) of this section. Such carriers are responsible for terminating or modifying PFC collection no later than 30 days after the date of notification by the FAA.

## § 158.87

### Loss of Federal airport grant funds.

. If the Administrator determines that revenue derived from a PFC is excessive or is not being used as approved, the Administrator may reduce the amount of funds otherwise payable to the public agency under 49 U.S.C. 47114. Such a reduction may be made as a corrective action under § 158.83 or § 158.85 of this part.
. The amount of the reduction under paragraph (a) of this section shall equal the excess collected, or the amount not used in accordance with this part.
. A reduction under paragraph (a) of this section shall not constitute a withholding of approval of a grant application or the payment of funds under an approved grant within the meaning of 49 U.S.C. 47111(d).

