# Instrument Landing System (ILS) Facilities
:toc:

## § 171.41 - Scope.

This subpart sets forth minimum requirements for the approval and operation of non-Federal Instrument Landing System (ILS) Facilities that are to be involved in the approval of instrument flight rules and air traffic control procedures related to those facilities.

## § 171.43 - Requests for IFR procedure.

[loweralpha]
. Each person who requests an IFR procedure based on an ILS facility that he owns must submit the following information with that request:
[arabic]
.. A description of the facility and evidence that the equipment meets the performance requirements of § 171.47 and is installed in accordance with § 171.49.
.. A proposed procedure for operating the facility.
.. A proposed maintenance organization and a maintenance manual that meets the requirements of § 171.51.
.. A statement of intent to meet the requirements of this subpart.
.. A showing that the facility has an acceptable level of operational reliability and an acceptable standard of performance. Previous equivalent operational experience with a facility with identical design and operational characteristics will be considered in showing compliance with this subparagraph.
. After the FAA inspects and evaluates the facility, it advises the owner of the results and of any required changes in the facility or the maintenance manual or maintenance organization. The owner must then correct the deficiencies, if any, and operate the facility for an in-service evaluation by the FAA.

## § 171.45 - Minimum requirements for approval.

[loweralpha]
. The following are the minimum requirements that must be met before the FAA will approve an IFR procedure for a non-Federal Instrument Landing System:
[arabic]
.. The facility's performance, as determined by air and ground inspection, must meet the requirements of § 171.47.
.. The installation of the equipment must meet the requirements of § 171.49.
.. The owner must agree to operate and maintain the facility in accord- ance with § 171.51.
.. The owner must agree to furnish periodic reports, as set forth in § 171.53 and agree to allow the FAA to inspect the facility and its operation whenever necessary.
.. The owner must assure the FAA that he will not withdraw the facility from service without the permission of the FAA.
.. The owner must bear all costs of meeting the requirements of this section and of any flight or ground inspections made before the facility is commissioned, except that the Federal Aviation Administration may bear certain of these costs subject to budgetary limitations and policy established by the Administrator.
. If the applicant for approval meets the requirements of paragraph (a) of this section, the FAA commissions the facility as a prerequisite to its approval for use in an IFR procedure. The approval is withdrawn at any time the facility does not continue to meet those requirements. In addition, the facility may be de-commissioned whenever the frequency channel is needed for higher priority common system service.

## § 171.47 - Performance requirements.

[loweralpha]
. The Instrument Landing System must perform in accordance with the “International Standards and Recommended Practices, Aeronautical Telecommunications, Part I, Paragraph 3.1” (Annex 10 to the Convention on International Civil Aviation) except as follows:
[arabic]
.. The first part of paragraph 3.1.3, relating to suppression of radiation wholly or in part in any or all directions outside the 20-degree sector centered on the course line to reduce localizer does not apply.
.. Radiation patterns must conform to limits specified in 3.1.3.3 and 3.1.3.4, but this does not mean that suppression of radiation to the rear of the antenna array to satisfy difficult siting positions (as per 3.1.3.1.4) is not allowed. For example, if a reflector screen for the antenna array is required to overcome a siting problem, the area to the rear of the localizer may be made unusable and should be so advertised.
.. A third marker beacon (inner marker) is not required.
.. The frequency tolerance of the radio frequency carrier must not exceed plus or minus 0.002 percent.
. Ground inspection consists of an examination of the design features of the equipment to determine that there will not be conditions that will allow unsafe operations because of component failure or deterioration.
. The monitor is checked periodically, during the in-service test evaluation period, for calibration and stability. These tests, and ground checks of glide slope and localizer radiation characteristics, are conducted in accordance with FAA Handbooks AF P 6750.1 and AF P 6750.2 “Maintenance Instructions for ILS Localizer Equipment” and “Maintenance Instructions for ILS Glide Slope Equipment”.
. Flight tests to determine the facility's adequacy for operational requirements and compliance with applicable “Standards and Recommended Practices” are conducted in accord- ance with the “U.S. Standard Flight Inspection Manual”, particularly section 217.

## § 171.49 - Installation requirements.

[loweralpha]
. The facility must be of a permanent nature, located, constructed, and installed according to ICAO Standards (Annex 10), accepted good engineering practices, applicable electric and safety codes, and FCC licensing requirements.
. The facility must have a reliable source of suitable primary power, either from a power distribution system or locally generated. A determination by the Administrator as to whether a facility will be required to have stand-by power for the localizer, glide slope and monitor accessories to supplement the primary power, will be made for each airport based upon operational minimums and density of air traffic.
. A determination by the Administrator as to whether a facility will be required to have dual transmitting equipment with automatic changeover for localizer and glide slope components, will be made for each airport based upon operational minimums and density of air traffic.
. There must be a means for determining, from the ground, the perform- ance of the equipment (including antennae), initially and periodically.
. The facility must have, or be supplemented by (depending on the circumstances) the following ground-air or landline communications services:
[arabic]
.. At facilities outside of and not immediately adjacent to controlled airspace, there must be ground-air communications from the airport served by the facility. The utilization of voice on the ILS frequency should be determined by the facility operator on an individual basis.
              
.. At facilities within or immediately adjacent to controlled airspace, there must be the ground-air communications required by paragraph (e)(1) of this section and reliable communications (at least a landline telephone) from the airport to the nearest FAA air traffic control or communications facility.
              

## § 171.51 - Maintenance and operations requirements.

[loweralpha]
. The owner of the facility must establish an adequate maintenance system and provide qualified maintenance personnel to maintain the facility at the level attained at the time it was commissioned. Each person who maintains a facility must meet at least the Federal Communications Commission's licensing requirements and show that he has the special knowledge and skills needed to maintain the facility including proficiency in maintenance procedures and the use of specialized test equipment.
. The owner must prepare, and obtain approval of, an operations and maintenance manual that sets forth mandatory procedures for operations, preventive maintenance, and emergency maintenance, including instructions on each of the following:
[arabic]
.. Physical security of the facility.
.. Maintenance and operations by authorized persons only.
.. FCC licensing requirements for operating and maintenance personnel.
.. Posting of licenses and signs.
.. Relation between the facility and FAA air traffic control facilities, with a description of the boundaries of controlled airspace over or near the facility, instructions for relaying air traffic control instructions and information (if applicable), and instructions for the operations of an air traffic advisory service if the facility is located outside of controlled airspace.
.. Notice to the Administrator of any suspension of service.
.. Detailed and specific maintenance procedures and servicing guides stating the frequency of servicing.
.. Air-ground communications, if provided, expressly written or incorporating appropriate sections of FAA manuals by reference.
.. Keeping of station logs and other technical reports, and the submission of reports required by § 171.53.
.. Monitoring of the facility.
.. Inspections by United States personnel.
.. Names, addresses, and telephone numbers of persons to be notified in an emergency.
.. Shutdowns for routine maintenance and issue of “Notices to Airmen” for routine or emergency shutdowns (private use facilities may omit the “Notices to Airmen”).
.. Commissioning of the facility.
.. An acceptable procedure for amending or revising the manual.
.. An explanation of the kinds of activities (such as construction or grading) in the vicinity of the facility that may require shutdown or recertification of the facility by FAA flight check.
.. Procedures for conducting a ground check or localizer course alignment width, and clearance, and glide slope elevation angle and width.
.. The following information concerning the facility:
[lowerroman]
... Facility component locations with respect to airport layout, instrument runway, and similar areas.
... The type, make, and model of the basic radio equipment that will provide the service.
              
... The station power emission and frequencies of the localizer, glide slope, markers, and associated compass locators, if any.
... The hours of operation.
... Station identification call letters and method of station identification and the time spacing of the identification.
... A description of the critical parts that may not be changed, adjusted, or repaired without an FAA flight check to confirm published operations.
. The owner shall make a ground check of the facility each month in accordance with procedures approved by the FAA at the time of commissioning, and shall report the results of the checks as provided in § 171.53.
. If the owner desires to modify the facility, he must submit the proposal to the FAA and may not allow any modifications to be made without specific approval.
. “The owner's maintenance personnel must participate in initial inspections made by the FAA. In the case of subsequent inspections, the owner or his representative shall participate.”
. Whenever it is required by the FAA, the owner shall incorporate improvements in ILS maintenance brought about by progress in the state of the art. In addition, he shall provide a stock of spare parts, including vacuum tubes, of such a quantity to make possible the prompt replacement of components that fail or deteriorate in service.
. The owner shall provide FAA approved test instruments needed for maintenance of the facility.
. The owner shall close the facility upon receiving two successive pilot reports of its malfunctioning.

## § 171.53 - Reports.

The owner of each facility to which this subpart applies shall make the following reports, at the times indicated, to the FAA Regional Office for the area in which the facility is located:

[loweralpha]
. *Record of meter readings and adjustments* (*Form FAA-198*). To be filled out by the owner or his maintenance representative with the equipment adjustments and meter readings as of the time of commissioning, with one copy to be kept in the permanent records of the facility and two copies to the appropriate Regional Office of the FAA. The owner shall revise the form after any major repair, modernization, or retuning, to reflect an accurate record of facility operation and adjustment.
. *Facility maintenance log* (*FormFAA 6030-1*). This form is a permanent record of all equipment malfunctioning met in maintaining the facility, including information on the kind of work and adjustments made, equipment failures, causes (if determined), and corrective action taken. The owner shall keep the original of each report at the facility and send a copy to the appropriate Regional Office of the FAA at the end of each month in which it is prepared.
. *Radio equipment operation record* (*Form FAA-418*). To contain a complete record of meter readings, recorded on each scheduled visit to the facility. The owner shall keep the original of each month's record at the facility and send a copy of it to the appropriate Regional Office of the FAA.

