# National Air Tour Safety Standards
:toc:

## § 136.1 - Applicability and definitions.

[loweralpha]
. This subpart applies to each person operating or intending to operate a commercial air tour in an airplane or helicopter and, when applicable, to all occupants of the airplane or helicopter engaged in a commercial air tour. When any requirement of this subpart is more stringent than any other requirement of this chapter, the person operating the commercial air tour must comply with the requirement in this subpart.
. As of September 11, 2007, this subpart is applicable to:
[arabic]
.. Part 121 or 135 operators conducting a commercial air tour and holding a part 119 certificate;
.. Part 91 operators conducting flights as described in § 119.1(e)(2); and
.. Part 91 operators conducting flights as described in 14 CFR 91.146
. This subpart is not applicable to operations conducted in balloons, gliders (powered or un-powered), parachutes (powered or un-powered), gyroplanes, or airships.
. For the purposes of this subpart the following definitions apply:

*Commercial Air Tour* means a flight conducted for compensation or hire in an airplane or helicopter where a purpose of the flight is sightseeing. The FAA may consider the following factors in determining whether a flight is a commercial air tour for purposes of this subpart:

[arabic]
. Whether there was a holding out to the public of willingness to conduct a sightseeing flight for compensation or hire;
. Whether the person offering the flight provided a narrative that referred to areas or points of interest on the surface below the route of the flight;
. The area of operation;
. How often the person offering the flight conducts such flights;
. The route of the flight;
. The inclusion of sightseeing flights as part of any travel arrangement package;
. Whether the flight in question would have been canceled based on poor visibility of the surface below the route of the flight; and
. Any other factors that the FAA considers appropriate.

*Commercial Air Tour operator* means any person who conducts a commercial air tour.

*Life preserver* means a flotation device used by an aircraft occupant if the aircraft ditches in water. If an inflatable device, it must be un-inflated and ready for its intended use once inflated. In evaluating whether a non-inflatable life preserver is acceptable to the FAA, the operator must demonstrate to the FAA that such a preserver can be used during an evacuation and will allow all passengers to exit the aircraft without blocking the exit. Each occupant must have the physical capacity to wear and inflate the type of device used once briefed by the commercial air tour operator. Seat cushions do not meet this definition.

*Raw terrain* means any area on the surface, including water, devoid of any person, structure, vehicle, or vessel.

*Shoreline* means that area of the land adjacent to the water of an ocean, sea, lake, pond, river or tidal basin that is above the high water mark and excludes land areas unsuitable for landing such as vertical cliffs or land intermittently under water during the particular flight.
              

*Suitable landing area for helicopters* means an area that provides the operator reasonable capability to land without damage to equipment or injury to persons. Suitable landing areas must be site-specific, designated by the operator, and accepted by the FAA. These site-specific areas would provide an emergency landing area for a single-engine helicopter or a multiengine helicopter that does not have the capability to reach a safe landing area after an engine power loss.

(e) In an in-flight emergency requiring immediate action, the pilot in command may deviate from any rule of this subpart to the extent required to meet that emergency.

## § 136.3 - Letters of Authorization.

Operators subject to this subpart who have Letters of Authorization may use the procedures described in 14 CFR 119.51 to amend or have the FAA reconsider those Letters of Authorization.

## § 136.5 - Additional requirements for Hawaii.

No person may conduct a commercial air tour in the State of Hawaii unless they comply with the additional requirements and restrictions in appendix A to part 136.

## § 136.7 - Passenger briefings.

[loweralpha]
. Before takeoff each pilot in command shall ensure that each passenger has been briefed on the following:
[arabic]
.. Procedures for fastening and unfastening seatbelts;
.. Prohibition on smoking; and
.. Procedures for opening exits and exiting the aircraft.
. For flight segments over water beyond the shoreline, briefings must also include:
[arabic]
.. Procedures for water ditching;
.. Use of required life preservers; and
.. Procedures for emergency exit from the aircraft in the event of a water landing.

## § 136.9 - Life preservers for over water.

[loweralpha]
. Except as provided in paragraphs (b) or (c) of this section, the operator and pilot in command of commercial air tours over water beyond the shoreline must ensure that each occupant is wearing a life preserver from before takeoff until flight is no longer over water.
. The operator and pilot in command of a commercial air tour over water beyond the shoreline must ensure that a life preserver is readily available for its intended use and easily accessible to each occupant if:
[arabic]
.. The aircraft is equipped with floats; or
.. The airplane is within power-off gliding distance to the shoreline for the duration of the time that the flight is over water.
.. The aircraft is a multi engine that can be operated with the critical engine inoperative at a weight that will allow it to climb, at least 50 feet a minute, at an altitude of 1,000 feet above the surface, as provided in the Airplane Flight Manual or the Rotorcraft Flight Manual, as appropriate.
. No life preserver is required if the overwater operation is necessary only for takeoff or landing.

## § 136.11 - Helicopter floats for over water.

[loweralpha]
. A helicopter used in commercial air tours over water beyond the shoreline must be equipped with fixed floats or an inflatable flotation system adequate to accomplish a safe emergency ditching, if—
[arabic]
.. It is a single-engine helicopter; or
.. It is a multi-engine helicopter that cannot be operated with the critical engine inoperative at a weight that will allow it to climb, at least 50 feet a minute, at an altitude of 1,000 feet above the surface, as provided in the Rotorcraft Flight Manual (RFM).
. Each helicopter that is required to be equipped with an inflatable flotation system must have:
[arabic]
.. The activation switch for the flotation system on one of the primary flight controls, and
.. The flotation system armed when the helicopter is over water and is flying at a speed that does not exceed the maximum speed prescribed in the Rotorcraft Flight Manual for flying with the flotation system armed.
. Fixed floats or an inflatable flotation system is not required for a helicopter under this section if:
              
[arabic]
.. The helicopter is over water only during the takeoff or landing portion of the flight, or
.. The helicopter is operated within power-off gliding distance to the shoreline for the duration of the flight and each occupant is wearing a life preserver from before takeoff until the aircraft is no longer over water.
. Air tour operators required to comply with paragraphs (a) and/or (b) of this section must meet these requirements on or before September 5, 2008.

## § 136.13 - Helicopter performance plan and operations.

[loweralpha]
. Each operator must complete a performance plan before each helicopter commercial air tour, or flight operated under 14 CFR 91.146 or 91.147. The pilot in command must review for accuracy and comply with the performance plan on the day the flight is flown. The performance plan must be based on the information in the Rotorcraft Flight Manual (RFM) for that helicopter, taking into consideration the maximum density altitude for which the operation is planned, in order to determine:
[arabic]
.. Maximum gross weight and center of gravity (CG) limitations for hovering in ground effect;
.. Maximum gross weight and CG limitations for hovering out of ground effect; and
.. Maximum combination of weight, altitude, and temperature for which height/velocity information in the RFM is valid.
. Except for the approach to and transition from a hover for the purpose of takeoff and landing, or during takeoff and landing, the pilot in command must make a reasonable plan to operate the helicopter outside of the caution/warning/avoid area of the limiting height/velocity diagram.
. Except for the approach to and transition from a hover for the purpose of takeoff and landing, during takeoff and landing, or when necessary for safety of flight, the pilot in command must operate the helicopter in compliance with the plan described in paragraph (b) of this section.

## §§ 136.15-136.29 - Reserved


Reserved

