# Continued Airworthiness and Safety Improvements
:toc:

## § 125.501

### Purpose and definition.

. This subpart requires operators to support the continued airworthiness of each airplane. These requirements may include, but are not limited to, revising the inspection program, incorporating design changes, and incorporating revisions to Instructions for Continued Airworthiness.
. For purposes of this subpart, the “FAA Oversight Office” is the aircraft certification office or office of the Transport Airplane Directorate with oversight responsibility for the relevant type certificate or supplemental type certificate, as determined by the Administrator.

## § 125.503

### Reserved

## § 125.505

### Repairs assessment for pressurized fuselages.

. No person may operate an Airbus Model A300 (exlcuding the -600 series), British Aerospace Model BAC 1-11, Boeing Model 707, 720, 727, 737 or 747, McDonnell Douglas Model DC-8, DC-9/MD-80 or DC-10, Fokker Model F28, or Lockheed Model L-1011 beyond the applicable flight cycle implementation time specified below, or May 25, 2001, whichever occurs later, unless operations specifications have been issued to reference repair assessment guidelines applicable to the fuselage pressure boundary (fuselage skin, door skin, and bulkhead webs), and those guidelines are incorporated in its maintenance program. The repair assessment guidelines must be approved by the FAA Aircraft Certification Office (ACO), or office of the Transport Airplane Directorate, having cognizance over the type certificate for the affected airplane.
.. For the Airbus Model A300 (excluding the -600 series), the flight cycle implementation time is:
... Model B2: 36,000 flights.
... Model B4-100 (including Model B4-2C): 30,000 flights above the window line, and 36,000 flights below the window line.
... Model B4-200: 25,500 flights above the window line, and 34,000 flights below the window line.
.. For all models of the British Aerospace BAC 1-11, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 707, the flight cycle implementation time is 15,000 flights.
.. For all models of the Boeing 720, the flight cycle implementation time is 23,000 flights.
.. For all models of the Boeing 727, the flight cycle implementation time is 45,000 flights.
.. For all models of the Boeing 737, the flight cycle implementation time is 60,000 flights.
.. For all models of the Boeing 747, the flight cycle implementation time is 15,000 flights.
.. For all models of the McDonnell Douglas DC-8, the flight cycle implementation time is 30,000 flights.
.. For all models of the McDonnell Douglas DC-9/MD-80, the flight cycle implementation time is 60,000 flights.
.. For all models of the McDonnell Douglas DC-10, the flight cycle implementation time is 30,000 flights.
.. For all models of the Lockheed L-1011, the flight cycle implementation time is 27,000 flights.
.. For the Fokker F-28 Mark, 1000, 2000, 3000, and 4000, the flight cycle implementation time is 60,000 flights.
. [Reserved]

## § 125.507

### Fuel tank system inspection program.

. Except as provided in paragraph (g) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity, have—
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7500 pounds or more.
. For each airplane on which an auxiliary fuel tank is installed under a field approval, before June 16, 2008, the certificate holder must submit to the FAA Oversight Office proposed maintenance instructions for the tank that meet the requirements of Special Federal Aviation Regulation No. 88 (SFAR 88) of this chapter.
. After December 16, 2008, no certificate holder may operate an airplane identified in paragraph (a) of this section unless the inspection program for that airplane has been revised to include applicable inspections, procedures, and limitations for fuel tank systems.
. The proposed fuel tank system inspection program revisions must be based on fuel tank system Instructions for Continued Airworthiness (ICA) that have been developed in accordance with the applicable provisions of SFAR 88 of this chapter or § 25.1529 and part 25, Appendix H, of this chapter, in effect on June 6, 2001 (including those developed for auxiliary fuel tanks, if any, installed under supplemental type certificates or other design approval) and that have been approved by the FAA Oversight Office.
. After December 16, 2008, before returning an aircraft to service after any alteration for which fuel tank ICA are developed under SFAR 88, or under § 25.1529 in effect on June 6, 2001, the certificate holder must include in the inspection program for the airplane inspections and procedures for the fuel tank system based on those ICA.
. The fuel tank system inspection program changes identified in paragraphs (d) and (e) of this section and any later fuel tank system revisions must be submitted to the Principal Inspector for review and approval.
. This section does not apply to the following airplane models:
.. Bombardier CL-44
.. Concorde
.. deHavilland D.H. 106 Comet 4C
.. VFW-Vereinigte Flugtechnische Werk VFW-614
.. Illyushin Aviation IL 96T
.. Bristol Aircraft Britannia 305
.. Handley Page Herald Type 300
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C
.. Airbus Caravelle
.. Lockheed L-300

## § 125.509

### Flammability reduction means.

. *Applicability.* Except as provided in paragraph (m) of this section, this section applies to transport category, turbine-powered airplanes with a type certificate issued after January 1, 1958, that, as a result of original type certification or later increase in capacity have:
.. A maximum type-certificated passenger capacity of 30 or more, or
.. A maximum payload capacity of 7,500 pounds or more.
. *New Production Airplanes.* Except in accordance with § 125.201, no person may operate an airplane identified in Table 1 of this section (including all-cargo airplanes) for which the State of Manufacture issued the original certificate of airworthiness or export airworthiness approval after December 27, 2010 unless an Ignition Mitigation Means (IMM) or Flammability Reduction Means (FRM) meeting the requirements of § 26.33 of this chapter is operational.
. *Auxiliary Fuel Tanks.* After the applicable date stated in paragraph (e) of this section, no person may operate any airplane subject to § 26.33 of this chapter that has an Auxiliary Fuel Tank installed pursuant to a field approval, unless the following requirements are met:
.. The person complies with 14 CFR 26.35 by the applicable date stated in that section.
.. The person installs Flammability Impact Mitigation Means (FIMM), if applicable, that is approved by the FAA Oversight Office.
.. Except in accordance with § 125.201, the FIMM, if applicable, are operational.
. *Retrofit.* Except as provided in paragraph (j) of this section, after the dates specified in paragraph (e) of this section, no person may operate an airplane to which this section applies unless the requirements of paragraphs (d)(1) and (d)(2) of this section are met.
.. Ignition Mitigation Means (IMM), Flammability Reduction Means (FRM), or FIMM, if required by §§ 26.33, 26.35, or 26.37 of this chapter, that are approved by the FAA Oversight Office, are installed within the compliance times specified in paragraph (e) of this section.
.. Except in accordance with § 125.201 of this part, the IMM, FRM or FIMM, as applicable, are operational.
. *Compliance Times.* The installations required by paragraph (d) of this section must be accomplished no later than the applicable dates specified in paragraph (e)(1), (e)(2) or (e)(3) of this section.
.. Fifty percent of each person's fleet of airplanes subject to paragraph (d)(1) of this section must be modified no later than December 26, 2014.
.. One hundred percent of each person's fleet of airplanes subject to paragraph (d)(1) of this section must be modified no later than December 26, 2017.
.. For those persons that have only one airplane of a model identified in Table 1 of this section, the airplane must be modified no later than December 26, 2017.
. *Compliance after Installation.* Except in accordance with § 125.201, no person may—
.. Operate an airplane on which IMM or FRM has been installed before the dates specified in paragraph (e) of this section unless the IMM or FRM is operational, or
.. Deactivate or remove an IMM or FRM once installed unless it is replaced by a means that complies with paragraph (d) of this section.
. *Inspection Program Revisions.* No person may operate an airplane for which airworthiness limitations have been approved by the FAA Oversight Office in accordance with §§ 26.33, 26.35, or 26.37 of this chapter after the airplane is modified in accordance with paragraph (d) of this section unless the inspection program for that airplane is revised to include those applicable airworthiness limitations.
. After the inspection program is revised as required by paragraph (g) of this section, before returning an airplane to service after any alteration for which airworthiness limitations are required by §§ 25.981, 26.33, 26.35, or 26.37 of this chapter, the person must revise the inspection program for the airplane to include those airworthiness limitations.
. The inspection program changes identified in paragraphs (g) and (h) of this section must be submitted to the operator's assigned Flight Standards Office responsible for review and approval prior to incorporation.
. The requirements of paragraph (d) of this section do not apply to airplanes operated in all-cargo service, but those airplanes are subject to paragraph (f) of this section.
. After the date by which any person is required by this section to modify 100 percent of the affected fleet, no person may operate in passenger service any airplane model specified in Table 2 of this section unless the airplane has been modified to comply with § 26.33(c) of this chapter.
. No person may operate any airplane on which an auxiliary fuel tank is installed after December 26, 2017 unless the FAA has certified the tank as compliant with § 25.981 of this chapter, in effect on December 26, 2008.
. *Exclusions.* The requirements of this section do not apply to the following airplane models:
.. Convair CV-240, 340, 440, including turbine powered conversions.
.. Lockheed L-188 Electra.
.. Vickers VC-10.
.. Douglas DC-3, including turbine powered conversions.
.. Bombardier CL-44.
.. Mitsubishi YS-11.
.. BAC 1-11.
.. Concorde.
.. deHavilland D.H. 106 Comet 4C.
.. VFW—Vereinigte Flugtechnische VFW-614.
.. Illyushin Aviation IL 96T.
.. Bristol Aircraft Britannia 305.
.. Handley Page Herald Type 300.
.. Avions Marcel Dassault—Breguet Aviation Mercure 100C.
.. Airbus Caravelle.
.. Fokker F-27/Fairchild Hiller FH-227.
.. Lockheed L-300.

