# General
:toc:

## § 91.1

### Applicability.

. Except as provided in paragraphs (b), (c), (e), and (f) of this section and §§ 91.701 and 91.703, this part prescribes rules governing the operation of aircraft within the United States, including the waters within 3 nautical miles of the U.S. coast.
. Each person operating an aircraft in the airspace overlying the waters between 3 and 12 nautical miles from the coast of the United States must comply with §§ 91.1 through 91.21; §§ 91.101 through 91.143; §§ 91.151 through 91.159; §§ 91.167 through 91.193; § 91.203; § 91.205; §§ 91.209 through 91.217; § 91.221, § 91.225; §§ 91.303 through 91.319; §§ 91.323 through 91.327; § 91.605; § 91.609; §§ 91.703 through 91.715; and § 91.903.
. This part applies to each person on board an aircraft being operated under this part, unless otherwise specified.
. This part also establishes requirements for operators to take actions to support the continued airworthiness of each airplane.
. This part does not apply to any aircraft or vehicle governed by part 103 of this chapter, or subparts B, C, or D of part 101 of this chapter.
. Except as provided in §§ 107.13, 107.27, 107.47, 107.57, and 107.59 of this chapter, this part does not apply to any aircraft governed by part 107 of this chapter.

## § 91.3

### Responsibility and authority of the pilot in command.

. The pilot in command of an aircraft is directly responsible for, and is the final authority as to, the operation of that aircraft.
. In an in-flight emergency requiring immediate action, the pilot in command may deviate from any rule of this part to the extent required to meet that emergency.
. Each pilot in command who deviates from a rule under paragraph (b) of this section shall, upon the request of the Administrator, send a written report of that deviation to the Administrator.

## § 91.5

### Pilot in command of aircraft requiring more than one required pilot.

No person may operate an aircraft that is type certificated for more than one required pilot flight crewmember unless the pilot in command meets the requirements of § 61.58 of this chapter.

## § 91.7

### Civil aircraft airworthiness.

. No person may operate a civil aircraft unless it is in an airworthy condition.
. The pilot in command of a civil aircraft is responsible for determining whether that aircraft is in condition for safe flight. The pilot in command shall discontinue the flight when unairworthy mechanical, electrical, or structural conditions occur.

## § 91.9

### Civil aircraft flight manual, marking, and placard requirements.

. Except as provided in paragraph (d) of this section, no person may operate a civil aircraft without complying with the operating limitations specified in the approved Airplane or Rotorcraft Flight Manual, markings, and placards, or as otherwise prescribed by the certificating authority of the country of registry.
. No person may operate a U.S.-registered civil aircraft—
.. For which an Airplane or Rotorcraft Flight Manual is required by § 21.5 of this chapter unless there is available in the aircraft a current, approved Airplane or Rotorcraft Flight Manual or the manual provided for in § 121.141(b); and
.. For which an Airplane or Rotorcraft Flight Manual is not required by § 21.5 of this chapter, unless there is available in the aircraft a current approved Airplane or Rotorcraft Flight Manual, approved manual material, markings, and placards, or any combination thereof.
. No person may operate a U.S.-registered civil aircraft unless that aircraft is identified in accordance with part 45 of this chapter.
. Any person taking off or landing a helicopter certificated under part 29 of this chapter at a heliport constructed over water may make such momentary flight as is necessary for takeoff or landing through the prohibited range of the limiting height-speed envelope established for the helicopter if that flight through the prohibited range takes place over water on which a safe ditching can be accomplished and if the helicopter is amphibious or is equipped with floats or other emergency flotation gear adequate to accomplish a safe emergency ditching on open water.

## § 91.11

### Prohibition on interference with crewmembers.

No person may assault, threaten, intimidate, or interfere with a crewmember in the performance of the crewmember's duties aboard an aircraft being operated.

## § 91.13

### Careless or reckless operation.

. *Aircraft operations for the purpose of air navigation.* No person may operate an aircraft in a careless or reckless manner so as to endanger the life or property of another.
. *Aircraft operations other than for the purpose of air navigation.* No person may operate an aircraft, other than for the purpose of air navigation, on any part of the surface of an airport used by aircraft for air commerce (including areas used by those aircraft for receiving or discharging persons or cargo), in a careless or reckless manner so as to endanger the life or property of another.

## § 91.15

### Dropping objects.

No pilot in command of a civil aircraft may allow any object to be dropped from that aircraft in flight that creates a hazard to persons or property. However, this section does not prohibit the dropping of any object if reasonable precautions are taken to avoid injury or damage to persons or property.

## § 91.17

### Alcohol or drugs.

. No person may act or attempt to act as a crewmember of a civil aircraft—
.. Within 8 hours after the consumption of any alcoholic beverage;
.. While under the influence of alcohol;
.. While using any drug that affects the person's faculties in any way contrary to safety; or
.. While having an alcohol concentration of 0.04 or greater in a blood or breath specimen. Alcohol concentration means grams of alcohol per deciliter of blood or grams of alcohol per 210 liters of breath.
. Except in an emergency, no pilot of a civil aircraft may allow a person who appears to be intoxicated or who demonstrates by manner or physical indications that the individual is under the influence of drugs (except a medical patient under proper care) to be carried in that aircraft.
. A crewmember shall do the following:
.. On request of a law enforcement officer, submit to a test to indicate the alcohol concentration in the blood or breath, when—
... The law enforcement officer is authorized under State or local law to conduct the test or to have the test conducted; and
... The law enforcement officer is requesting submission to the test to investigate a suspected violation of State or local law governing the same or substantially similar conduct prohibited by paragraph (a)(1), (a)(2), or (a)(4) of this section.
.. Whenever the FAA has a reasonable basis to believe that a person may have violated paragraph (a)(1), (a)(2), or (a)(4) of this section, on request of the FAA, that person must furnish to the FAA the results, or authorize any clinic, hospital, or doctor, or other person to release to the FAA, the results of each test taken within 4 hours after acting or attempting to act as a crewmember that indicates an alcohol concentration in the blood or breath specimen.
. Whenever the Administrator has a reasonable basis to believe that a person may have violated paragraph (a)(3) of this section, that person shall, upon request by the Administrator, furnish the Administrator, or authorize any clinic, hospital, doctor, or other person to release to the Administrator, the results of each test taken within 4 hours after acting or attempting to act as a crewmember that indicates the presence of any drugs in the body.
              
. Any test information obtained by the Administrator under paragraph (c) or (d) of this section may be evaluated in determining a person's qualifications for any airman certificate or possible violations of this chapter and may be used as evidence in any legal proceeding under section 602, 609, or 901 of the Federal Aviation Act of 1958.

## § 91.19

### Carriage of narcotic drugs, marihuana, and depressant or stimulant drugs or substances.

. Except as provided in paragraph (b) of this section, no person may operate a civil aircraft within the United States with knowledge that narcotic drugs, marihuana, and depressant or stimulant drugs or substances as defined in Federal or State statutes are carried in the aircraft.
. Paragraph (a) of this section does not apply to any carriage of narcotic drugs, marihuana, and depressant or stimulant drugs or substances authorized by or under any Federal or State statute or by any Federal or State agency.

## § 91.21

### Portable electronic devices.

. Except as provided in paragraph (b) of this section, no person may operate, nor may any operator or pilot in command of an aircraft allow the operation of, any portable electronic device on any of the following U.S.-registered civil aircraft:
.. Aircraft operated by a holder of an air carrier operating certificate or an operating certificate; or
.. Any other aircraft while it is operated under IFR.
. Paragraph (a) of this section does not apply to—
.. Portable voice recorders;
.. Hearing aids;
.. Heart pacemakers;
.. Electric shavers; or
.. Any other portable electronic device that the operator of the aircraft has determined will not cause interference with the navigation or communication system of the aircraft on which it is to be used.
. In the case of an aircraft operated by a holder of an air carrier operating certificate or an operating certificate, the determination required by paragraph (b)(5) of this section shall be made by that operator of the aircraft on which the particular device is to be used. In the case of other aircraft, the determination may be made by the pilot in command or other operator of the aircraft.

## § 91.23

### Truth-in-leasing clause requirement in leases and conditional sales contracts.

. Except as provided in paragraph (b) of this section, the parties to a lease or contract of conditional sale involving a U.S.-registered large civil aircraft and entered into after January 2, 1973, shall execute a written lease or contract and include therein a written truth-in-leasing clause as a concluding paragraph in large print, immediately preceding the space for the signature of the parties, which contains the following with respect to each such aircraft:
.. Identification of the Federal Aviation Regulations under which the aircraft has been maintained and inspected during the 12 months preceding the execution of the lease or contract of conditional sale, and certification by the parties thereto regarding the aircraft's status of compliance with applicable maintenance and inspection requirements in this part for the operation to be conducted under the lease or contract of conditional sale.
.. The name and address (printed or typed) and the signature of the person responsible for operational control of the aircraft under the lease or contract of conditional sale, and certification that each person understands that person's responsibilities for compliance with applicable Federal Aviation Regulations.
.. A statement that an explanation of factors bearing on operational control and pertinent Federal Aviation Regulations can be obtained from the nearest FAA Flight Standards district office.
. The requirements of paragraph (a) of this section do not apply—
.. To a lease or contract of conditional sale when—
              
... The party to whom the aircraft is furnished is a foreign air carrier or certificate holder under part 121, 125, 135, or 141 of this chapter, or
... The party furnishing the aircraft is a foreign air carrier or a person operating under part 121, 125, and 141 of this chapter, or a person operating under part 135 of this chapter having authority to engage in on-demand operations with large aircraft.
.. To a contract of conditional sale, when the aircraft involved has not been registered anywhere prior to the execution of the contract, except as a new aircraft under a dealer's aircraft registration certificate issued in accordance with § 47.61 of this chapter.
. No person may operate a large civil aircraft of U.S. registry that is subject to a lease or contract of conditional sale to which paragraph (a) of this section applies, unless—
.. The lessee or conditional buyer, or the registered owner if the lessee is not a citizen of the United States, has mailed a copy of the lease or contract that complies with the requirements of paragraph (a) of this section, within 24 hours of its execution, to the Aircraft Registration Branch, Attn: Technical Section, P.O. Box 25724, Oklahoma City, OK 73125;
.. A copy of the lease or contract that complies with the requirements of paragraph (a) of this section is carried in the aircraft. The copy of the lease or contract shall be made available for review upon request by the Administrator, and
.. The lessee or conditional buyer, or the registered owner if the lessee is not a citizen of the United States, has notified by telephone or in person the FAA Flight Standards district office nearest the airport where the flight will originate. Unless otherwise authorized by that office, the notification shall be given at least 48 hours before takeoff in the case of the first flight of that aircraft under that lease or contract and inform the FAA of—
... The location of the airport of departure;
... The departure time; and
... The registration number of the aircraft involved.
. The copy of the lease or contract furnished to the FAA under paragraph (c) of this section is commercial or financial information obtained from a person. It is, therefore, privileged and confidential and will not be made available by the FAA for public inspection or copying under 5 U.S.C. 552(b)(4) unless recorded with the FAA under part 49 of this chapter.
. For the purpose of this section, a lease means any agreement by a person to furnish an aircraft to another person for compensation or hire, whether with or without flight crewmembers, other than an agreement for the sale of an aircraft and a contract of conditional sale under section 101 of the Federal Aviation Act of 1958. The person furnishing the aircraft is referred to as the lessor, and the person to whom it is furnished the lessee.

## § 91.25

### Aviation Safety Reporting Program: Prohibition against use of reports for enforcement purposes.

The Administrator of the FAA will not use reports submitted to the National Aeronautics and Space Administration under the Aviation Safety Reporting Program (or information derived therefrom) in any enforcement action except information concerning accidents or criminal offenses which are wholly excluded from the Program.

## §§ 91.27-91.99

### Reserved

